### ISSUE TITLE
Need way to call endpoints as admin, optionally masquerading as a given user

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1009]
**Is your feature request related to a problem? Please describe.**

I need a way to run a script to call endpoints as a user with `admin` role. The purpose of this is to automate the creation of test data in the database.

**Describe the solution you'd like**

I was going to create a new login method that allowed a user to log in as an `admin` if they provided the correct Postgres password to the server. Then they could call any API endpoint as an `admin`.

However, I think a better solution could probably be created. I need to be able to also call any endpoint as an admin, masquerading as any user (i.e. I would have to be logged in already, then I would supply an additional `userId` parameter to any endpoint request, to call that endpoint as that user.

This would be very helpful in unit testing too, by the way...

**Describe alternatives you've considered**

Writing direct to Postgres. However it is much better to go through the endpoints, to avoid duplicating that functionality, and to maximally exercise the endpoints.

**Comment by lukehutch** [comment]
This is what I came up with for calling endpoints within the server. (No auth is performed, I stripped that part out.)

```dart
/// Modified from endpoint_dispatch.dart:
/// Dispatches a call to the [Server] to the correct [Endpoint] method. If
/// successful, it returns the object from the method. If unsuccessful it will
/// return a [Result] object.
Future<Result> callMethod(Serverpod pod, String endpointName, String methodName,
    Map<String, dynamic> paramMap) async {
  // Find correct connector
  var connector = pod.server.endpoints.getConnectorByName(endpointName);
  if (connector == null) {
    return ResultInvalidParams('Endpoint $endpointName does not exist');
  }

  Session session;
  try {
    session = InternalSession(server: pod.server);
  } catch (e) {
    return ResultInvalidParams('Malformed call');
  }

  try {
    var method = connector.methodConnectors[methodName];
    if (method == null) {
      await session.close();
      return ResultInvalidParams('Method $methodName not found');
    }

    var result = await method.call(session, paramMap);

    await session.close();

    return ResultSuccess(
      result,
      sendByteDataAsRaw: connector.endpoint.sendByteDataAsRaw,
    );
  } on SerializableException catch (exception) {
    return ExceptionResult(entity: exception);
  } on Exception catch (e, stackTrace) {
    var sessionLogId = await session.close(error: e, stackTrace: stackTrace);
    return ResultInternalServerError(
        e.toString(), stackTrace, sessionLogId ?? 0);
  } catch (e, stackTrace) {
    // Something did not work out
    var sessionLogId = await session.close(error: e, stackTrace: stackTrace);
    return ResultInternalServerError(
        e.toString(), stackTrace, sessionLogId ?? 0);
  }
}
```

**Comment by lukehutch** [comment]
A quick snippet for calling an endpoint from within another endpoint:

```dart
// result is null if endpoint or method wasn't found
Future<dynamic>? result = await session.server.endpoints
      .getConnectorByName(endpointName)
      ?.methodConnectors[methodName]
      ?.call(session, paramMap);
```

**Comment by vlidholt** [comment]
Yes, this would be a nice to have!

**Comment by lukehutch** [comment]
I'm getting around to creating unit tests for my server, because the complexity now is becoming too great to manually test everything (and in the long run, having unit tests will be critical).

To revise what I was proposing above, I really need to be able to call endpoints on the server in exactly the same way as I call endpoints on the client. This is critical for easily developing unit tests that function the same way as code would function on the client. I would expect to be able to do something like:

```dart
final client = ServersideClient(serverPodInstance: pod, asUserId: testUserId1);
```

And then I would call an endpoint the same was as I do in the app:

```dart
client.myEndpoint.myEndpointMethod(...)
```

The current mechanism I am using to call endpoints, shown in previous comments, is prone to breakage, because no error is shown in the IDE if I rename a parameter of an endpoint method, etc. -- not to mention that it is a lot of complex boilerplate just to make a single API call. I also need to be able to set up a session as an user, by userId, mocking a user of that userId being logged in. Currently I have to set up an `InternalSession` and then manually call `await session.auth.signInUser(userInfo.id!, 'server')`. It would be nice to be able to just pass the `asUserId` param in to the client constructor, as shown above.

Now that I'm getting around to writing unit tests, I would say that supporting this sort of `ServersideClient` should be high priority for Serverpod 2.0, because testing is so important, as you have stated with regards to your own development of Serverpod!

**Comment by SalahAnwer** [comment]
Can I just do this:

```
class FirstEndpoint extends Endpoint {
  Future<String> getExample(Session session, String name) async {
    return 'Hello $name';
  }
}

extension SessionX on Session {
  FirstEndpoint get firstEndpoint {
    final firstEndpoint = (server.endpoints
        .getConnectorByName('FirstEndpoint')
        ?.endpoint as FirstEndpoint?);
    if (firstEndpoint == null) {
      throw Exception('FirstEndpoint not found');
    }
    return firstEndpoint;
  }
}

class SecondEndpoint extends Endpoint {
  Future<String> getExampleFromFirstEndpoint(
      Session session, String name) async {
    return session.firstEndpoint.getExample(session, name);
  }
}
```
