### ISSUE TITLE
 Can't load Kernel binary: Invalid SDK hash.

### ISSUE THREAD

**Issue by egyleader** [serverpod/serverpod#1013]
**Describe the bug**
when running serverpod commands I get the folowwing error : 
```
Can't load Kernel binary: Invalid SDK hash.
```

**Serverpod versions**
Serverpod version: 1.1.1

**Additional context**
I use Fvm to manage my flutter version  with the latest  stable version of  3.10.4 so this may be contributing to the problem .

**Comment by yahu1031** [comment]
Related to [dart-lang pub#2593](https://github.com/dart-lang/pub/issues/2593)

**Comment by egyleader** [comment]
I've restarted everything and now the warning is gone , the new server log : 

```
SERVERPOD version: 1.1.1, dart: 3.0.3 (stable) (Wed May 31 15:35:05 2023 +0000) on "macos_arm64", time: 2023-06-15 10:09:25.411908Z
mode: development, role: monolith, logging: normal, serverId: default
Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082
```
