### ISSUE TITLE
serverpod_cli null check thrown for cmdLanguageServer _printUsage

### ISSUE THREAD

**Issue by tgrushka** [serverpod/serverpod#1016]
**Describe the bug**

The `parser.commands[cmdLanguageServer]` are apparently not defined yet, so line 407 in serverpod_cli.dart throws a null check operator on null value error.

**To Reproduce**
1. Clone the repo.
2. Run `util/pub_get_all`
3. Add `export SERVERPOD_HOME=/path/to/serverpod` to profile and (source the profile or open a new shell).
4. Run `serverpod` with no arguments.
5. Note the following exception thrown:

```
Yikes! It is possible that this error is caused by an internal issue with the
Serverpod tooling. We would appreciate if you filed an issue over at Github.
Please include the stack trace below and describe any steps you did to trigger
the error.
https://github.com/serverpod/serverpod/issues
Null check operator used on a null value
#0      _printUsage (file:///Users/tom/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:407:39)
#1      _main (file:///Users/tom/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:375:3)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/tom/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:42:9)
<asynchronous suspension>
#3      main (file:///Users/tom/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:39:3)
<asynchronous suspension>
```

**Expected behavior**
Running `serverpod` without arguments or with an incomplete argument should generate a help message and not throw.

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ `1.1.0` cloned today from `main`
 - _Library version:_ `1.1.0` cloned today from `main`

**Platform information**
M1 MacBook Pro, macOS Ventura 13.4 (22F66)

**Temporary Fix**
I was able to fix this on my local clone using a null guard, like this:
```dart
  if (parser.commands[cmdLanguageServer] != null) {
    _printCommandUsage(
      cmdLanguageServer,
      'Launches a serverpod language server communicating with JSON-RPC-2 intended to be used with a client integrated in an IDE.',
      parser.commands[cmdLanguageServer]!,
    );
  }
```

And also by removing the bang, like this:
```dart
    _printCommandUsage(
      cmdLanguageServer,
      'Launches a serverpod language server communicating with JSON-RPC-2 intended to be used with a client integrated in an IDE.',
      parser.commands[cmdLanguageServer],
    );
```

**Comment by Isakdl** [comment]
Fixed in [PR](https://github.com/serverpod/serverpod/pull/1020), thanks for the report!

**Comment by Isakdl** [comment]
Fixed on main.
