### ISSUE TITLE
serverpod generate adds dollar sign $ to client URL in flutter main.dart

### ISSUE THREAD

**Issue by tgrushka** [serverpod/serverpod#1018]
Running serverpod generate on latest main adds an extra dollar sign before localhost in main.dart like this, which must be either changed, removed, or $localhost defined:

```dart
var client = Client('http://$localhost:8080/')
  ..connectivityMonitor = FlutterConnectivityMonitor();
```

Are we setting $localhost dynamically so the user can specify the default client URL? (That would be a cool feature!)

Here is the blame:

https://github.com/serverpod/serverpod/blame/837798c8e5a0c948acb97916460d7456fe5ed6c7/templates/serverpod_templates/projectname_flutter/lib/main.dart#L10

**Comment by vlidholt** [comment]
It should work if you have the correct libraries in your project too (not just the CLI), I think. It will dynamically set localhost depending on your device (i.e., it's different on Android).

**Comment by SandPod** [comment]
The localhost variable is imported from the `serverpod_flutter` package that is a generated import in the file.

The conditional import is defined here: https://github.com/serverpod/serverpod/blob/0120e776e1af205233f1276960a1cea6f3ddb81e/packages/serverpod_flutter/lib/serverpod_flutter.dart#L2

This then provides different local host definitions depending on if this is a [web app](https://github.com/serverpod/serverpod/blob/main/packages/serverpod_flutter/lib/src/localhost_web.dart) or [not.](https://github.com/serverpod/serverpod/blob/main/packages/serverpod_flutter/lib/src/localhost_io.dart)
