### ISSUE TITLE
User scopes on UserInfo aren't respected.

### ISSUE THREAD

**Issue by tgrushka** [serverpod/serverpod#1027]
**Describe the bug**
Say I want to assign scopes to a user when the account is created (using Google Auth module). The only way I see to do it (without a future call) is set them in the `onUserCreated` callback.

They do get added to the `serverpod_user_info`. But then, it seems serverpod gets the current scopes from `serverpod_auth_key` instead. (Is there a reason for this?)

Adding them in `onUserCreated` using `updateUserScopes` executes the SQL query to insert them into `serverpod_auth_key`, but apparently that either gets rolled back, or the `serverpod_auth_key` doesn't exist yet.

Anyway, how do we get serverpod to accept the scopes set in the `serverpod_user_info` table when using `requiredScopes` in an Endpoint?

**To Reproduce**
1. Set up serverpod with Google Auth module. Configure like this:
```dart
class Scopes {
  static const Scope admin = Scope.admin;
  static const Scope editor = Scope('editor');
  static const Scope viewer = Scope('viewer');
}
...
  auth.AuthConfig.set(
    auth.AuthConfig(
      /// By default, every new user will have a `viewer` scope.
      onUserCreated: (session, userInfo) async {
        await auth.Users.updateUserScopes(
          session,
          userInfo.id!,
          {Scopes.viewer},
        );
      },
    ),
  );
```
2. Sign in with a Google account. This works fine for me.
3. Go to `psql` console. 
4. Run `select * from serverpod_user_info;` and note the entry for "viewer" is in `scopeNames`.
5. Run `select * from serverpod_auth_key` and note the `scopeNames` field is blank.
6 Try to call an endpoint that has:
```dart
  @override
  Set<Scope> get requiredScopes => {Scopes.viewer};
```
and note that it returns a `ServerpodClientException` with status 403.

**Expected behavior**
I expect one or both of the following:
1. The endpoint works and does not reject the user, because the "viewer" scope is already populated in the `scopeNames` field of the `serverpod_user_info` table, and/or
2. The `scopeNames` field for the user in the `serverpod_auth_key` has the "viewer" scope that I set in `onUserCreated`.
3. It would be nice to have more documentation on how scopes are to be used, and why they are pulled from the `serverpod_auth_key` table instead of the `serverpod_user_info` table.

**Serverpod versions**
 -  _CLI Version:_ 1.1.1
 - _Library version:_ 1.1.1

**Platform information**
macOS
**Might be important**: Building to web / Chrome

**Comment by jblankenship5** [comment]
I'm so confused about this as well... why does `SessionManager.signedInUser.scopeNames` not correspond to the users active scopes? Also, where is the documentation on handling scopes when using google sign in? I saw in another post that you need to set the scopes on sign in... but if it's handled in the background by Serverpod where am I supposed to set those scopes.

**Comment by SandPod** [comment]
Hey @tgrushka!

We had an issue where scopes where not correctly propagated to authentication keys when signing in through all providers.
This PR fixed this issue: https://github.com/serverpod/serverpod/pull/2283

Is this still an issue after that change?

The authentication model for the current authentication module is that UserInfo holds the source of truth for what scopes are assigned to a user. These scopes are then copied from the user to the authentication key when it is created.

When a new user is created you can now correctly modify what scopes are assigned to the user by defining the `onUserCreated` callback.

**Comment by SandPod** [comment]
Closing this issue as complete.
