### ISSUE TITLE
Nit: set _errorMessage = null in example main.dart when client.example.hello returns successfully

### ISSUE THREAD

**Issue by tgrushka** [serverpod/serverpod#1028]
**Describe the bug**

Here I thought something was wrong with my state when testing the Google Auth module. I restricted the example endpoint to a logged in user. The 403 error message would not go away until I reloaded the page. Tried all kinds of troubleshooting, then realized the `_errorMessage` was still set and was overriding the `_resultMessage`.

**To Reproduce**
1. Set up a serverpod with default example and Google auth module.
2. Restrict example endpoint to signed in user:
```dart
  @override
  bool get requireLogin => true;
```
3. Build and run to web/Chrome (should occur on other platforms as well).
4. Without logging in, press the "Send to Server" button on the example page.
5. Note the `ServerpodClientException: , statusCode = 403` error.
6. Sign in with Google.
7. Without reloading, press the "Send to Server" button again.
8. Note the error is still present.
9. Reload the page and submit again.
10. Note the error has cleared.
11. Add a line to clear the error message in main.dart:
```dart
  void _callHello() async {
    try {
      final result = await client.example.hello(_textEditingController.text);
      setState(() {
        _errorMessage = null;
        _resultMessage = result;
      });
...
```
12. Rebuild the app. Note that now, after signing in with Google, the expected Hello message appears without having to reload.

**Expected behavior**
This is a minor issue that led me to believe something was wrong when it was only a view state issue of the error overriding the success message.

**Serverpod versions**
 -  _CLI Version:_ 1.1.1
 - _Library version:_ 1.1.1

**Platform information**
Web/Chrome

**Comment by bradintheusa** [comment]
I came here to say that. It just bit me too.

**Comment by vlidholt** [comment]
We'll make sure this gets fixed for the next version!
