### ISSUE TITLE
Need to generate no-args constructor for `protocol` yaml files

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1050]
**Is your feature request related to a problem? Please describe.**

Currently the constructor for client classes created from a `protocol` yaml file in the server project require each field to be specified.

**Describe the solution you'd like**

I really need the Serverpod codegen to generate a factory constructor for each protocol file, e.g. `MyClass.newDefault()`, with all fields set to a reasonable default, e.g. `''` set as the default value for string fields, `false` set as the default for `bool` fields, etc.

Alternatively (and probably better), protocol object constructor arguments could be made optional, utilizing the default value for each parameter if the corresponding argument is not given.

This would then allow me to set only the fields that are necessary, and not have to specify a value for every field, every time I construct an instance of this class. (My data type is sparse in the columns.)

The default value to use should be able to be overridden by adding a `default <value>` suffix to the field description in the YAML file.

**Describe alternatives you've considered**

I have a class with dozens of fields that is constantly changing as I develop the data model. I need to be able to create blank instances of this class.

Currently I have my own factory method that constructs an instance of this protocol object, passing empty values into each parameter. But every time I add a field to the yaml file, my code breaks, in spite of codegen, because all constructor arguments are currently required.

**Comment by lukehutch** [comment]
Incidentally, allowing a default value to be specified for a given field will help with the database upgrade/migration feature that you are currently working on for Serverpod.

**Comment by lukehutch** [comment]
By the way using nullable types is not a good solution: nullable columns slow down queries in Postgres:

https://www.postgresql.org/message-id/CAKFQuwZP8KUnLLukbfnxp7uqE5q-8vkOZcZGDhdXxZ0u1eOHpg%40mail.gmail.com

**Comment by Isakdl** [comment]
Yeah! This is planed, there is a longer discussion on different features for the protocol here: https://github.com/serverpod/serverpod/discussions/1005. Feel free to append any comments / suggestion there as well! :)

**Comment by SandPod** [comment]
I think this is mostly covered by default values now using the keyword `defaultModel=....`.
Then it just becomes a matter of supporting default values for all the different data types that a model can define.

@lukehutch OK if I close this or would you like to specialize it for the use-case that is not covered?

**Comment by lukehutch** [comment]
@SandPod Yes, I think this is pretty much covered given that #1005 is nearly completed. Thanks!
