### ISSUE TITLE
`ParsedYamlException: Mapping values are not allowed here`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1072]
**Describe the bug**

I updated my Serverpod project to depend upon the latest `main` commit.

When I run `serverpod generate`, for some reason the templates in the `serverpod` project are being compiled, rather than just the yaml files in my own project.

The templates are not formatted to be parsed the usual way. The result is:

```console
$ dart ../vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart generate --watch
Development mode. Using templates from: ../vendor/serverpod/templates/serverpod_templates
SERVERPOD_HOME is set to ../vendor/serverpod
Exception: Error while parsing pubspec file: ../vendor/serverpod/templates/pubspecs/templates/serverpod_templates/pubspec.yaml: ParsedYamlException: line 4, column 5: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
4 │ name: serverpod_templates
  │     ^
  ╵
```

This never happened before the update.

**Serverpod versions**
 -  _CLI Version:_ 1.1.1 (git main)
 - _Library version:_ 1.1.1 (git main)

**Platform information**

Linux

**Comment by Isakdl** [comment]
Thank you! Looking at it now.

**Comment by lukehutch** [comment]
Thanks!
