### ISSUE TITLE
Please don't check in generated files to git

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1076]
**Describe the bug**

I am working from my own fork of Serverpod, because I have several PRs that have not been merged upstream yet.

Whenever I need to sync my fork with the latest upstream fork, I have to rerun `util/generate_all` to regenerate the generated files based on the latest changes.

However, that produces many differences between the files generated on my end, and the files generated on the server.

Probably this is because you don't check in changes to the generated files often, however those files are now out of sync with the latest code-generator, for example:

**In git:**
```dart
/// {@category Endpoint}
class EndpointAdmin extends _i1.EndpointRef {
  EndpointAdmin(_i1.EndpointCaller caller) : super(caller);
```

**Generated on my machine:** (note the missing comment and extra underscore)
```dart
class _EndpointAdmin extends _i1.EndpointRef {
  _EndpointAdmin(_i1.EndpointCaller caller) : super(caller);
```

The issue is that it's easy for changes in generated files to accidentally slip into changesets, which pollutes the changesets.

The alternative is to carefully manually cherrypick changes, but I want to be able to just go `git add . ; git commit -am "..." ; git push`, and not have to worry about whether there are changes in files that I didn't personally make.

Please either keep checking in the generated files every time the code generation code is changed, or please do not check in generated files.

Thank you!

**Comment by Isakdl** [comment]
Right now we kind of use the generated code as a snapshot test for the code generator. I.E. we validate that the generator does not change any of the files when running the command in our workflows. It would of course be possible to substitute this with some other solution that does the same thing, but not as simple as just removing the generated code and be done with it.

With that said I find it odd that you have a different output locally compared to main? Did you change the code or is the source for the generator still the same?

**Comment by lukehutch** [comment]
I agree, that sort of codegen output check should be in unit tests, not part of the project itself.

No, I'm using `serverpod_cli` from git main. I didn't change anything in the output.

Take a look at the example I gave -- that may tell you what's going on, since these codegen changes were fairly recent.

**Comment by lukehutch** [comment]
@Isakdl Look at PR #1080 -- I accidentally checked in generated files into this PR (again). This my give you an idea of why my `serverpod generate` doesn't generate the same files as yours.

**Comment by lukehutch** [comment]
OK, I think I figured out why this was happening. I was using a git checkout of `serverpod`, but I didn't have `SERVERPOD_HOME` set. I erroneously assumed that if I ran scripts within the `serverpod` git repo, the generator code from the git repo would be used. But instead, `generate_all` just uses the currently-activated `serverpod_cli` version. `SERVERPOD_HOME` seems to override this -- it should be set to the git repo's root directory. (This is not documented anywhere though...)

**Comment by lukehutch** [comment]
I updated `generate_all` to use the git version of `serverpod_cli` in #1188.

**Comment by lukehutch** [comment]
@Isakdl a much better idea than checking in generated files is to add `generated/` to `.gitignore`, then have a script that copies all `**/generated/*` to have a suffix `.snapshot`. Then a second script would compare each snapshot to the current version of the file.

**Comment by Isakdl** [comment]
Hmm yeah! Could work, but we would still have to keep the .snapshot files in version control for this to work right? So we wouldn't get around the problem with polluting the git diff I think.

**Comment by lukehutch** [comment]
No, the .snapshot files would be in "generated" directories, so they wouldn't be checked in either. When you start developing from a got clone, you run the script to generate the snapshot files, then you periodically run the other script to compare current generated files to the snapshot.

Actually that second script could be part of the "generate" CLI command, comparing output to .snapshot files of the snapshot version exist.

**Comment by Isakdl** [comment]
The problem with that is that we do not get any check in our CI pipeline, and we lose the main real test, it is simply not enough to hope people run this correctly locally. I suppose it would be possible to clone main generate the files, save them, clone the new PR, copy all the previously generated files and then re generate and do a check between them. 

However quite a lot of work to setup this to work both in CI and locally I think, but it is doable.

**Comment by lukehutch** [comment]
You can check in the snapshots in a separate repository, if you prefer that... There are hooks for this!

Almost every time I try to prep a PR, I run into issues with these confounded generated files making their way into my changesets. Maybe I'm using git wrongly, but it's really really annoying.

**Comment by lukehutch** [comment]
@Isakdl I am pulling out my hair -- having generated files checked in to git causes me grief almost every single day.

The fundamental problem is that I am maintaining numerous feature branches against serverpod upstream -- and then I have a single branch `all-merged` that has all these feature branches merged together, which I am using to develop my client and server code. Every time I make a change, or create a new feature branch (which is branched off of upstream `main`), and then I have to merge into `all-merged`, the generated files are incompatible, because several of my feature branches affect code generation.

Some of my code generation changes conflict with each other, so several of my feature branches conflict with each other in the generated code, so every time I merge, *I have to go through all the merge conflicts in the generated code, and manually fix the conflicts.

It's extremely annoying, and it should be unnecessary. **Generated code should NEVER be checked into a source code repository!** This has been standard practice for decades. I remember dealing with this issue 30 years ago in a different context.

If you need your own snapshot of generated code, then please make your own snapshot with a script, and you can have a test that compares the current generated code with that. But **PLEASE** add your generated code to `.gitignore`.

**Comment by lukehutch** [comment]
I just ran into another major reason that generated code should not be checked in. It causes enormous bit-rot when you are trying to rebase PRs on the latest git main version. Not all of these can be fixed by `generate_all`, and in fact when model code is broken, `generate_all` often fails in a way that is very difficult to fix.

I just tried updating my Facebook login code to git main, and got these merge conflicts (mostly in generated code):

```console
$ git merge main
Auto-merging examples/chat/chat_client/lib/src/protocol/client.dart
Auto-merging examples/chat/chat_server/lib/src/generated/channel.dart
CONFLICT (content): Merge conflict in examples/chat/chat_server/lib/src/generated/channel.dart
Auto-merging modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/authentication_fail_reason.dart
Auto-merging modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/client.dart
Auto-merging modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/protocol.dart
CONFLICT (modify/delete): modules/serverpod_auth/serverpod_auth_server/generated/tables.pgsql deleted in main and modified in HEAD.  Version HEAD of modules/serverpod_auth/serverpod_auth_server/generated/tables.pgsql left in tree.
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/authentication_fail_reason.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_auth.dart
CONFLICT (content): Merge conflict in modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_auth.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_create_account_request.dart
CONFLICT (content): Merge conflict in modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_create_account_request.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_failed_sign_in.dart
CONFLICT (content): Merge conflict in modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_failed_sign_in.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_reset.dart
CONFLICT (content): Merge conflict in modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_reset.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/endpoints.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/google_refresh_token.dart
CONFLICT (content): Merge conflict in modules/serverpod_auth/serverpod_auth_server/lib/src/generated/google_refresh_token.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/protocol.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/protocol.yaml
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/user_image.dart
CONFLICT (content): Merge conflict in modules/serverpod_auth/serverpod_auth_server/lib/src/generated/user_image.dart
Auto-merging modules/serverpod_auth/serverpod_auth_server/lib/src/generated/user_info.dart
CONFLICT (content): Merge conflict in modules/serverpod_auth/serverpod_auth_server/lib/src/generated/user_info.dart
CONFLICT (file location): modules/serverpod_auth/serverpod_auth_server/lib/src/protocol/facebook_long_lived_token.yaml added in HEAD inside a directory that was renamed in main, suggesting it should perhaps be moved to modules/serverpod_auth/serverpod_auth_server/lib/src/models/facebook_long_lived_token.yaml.
Auto-merging modules/serverpod_chat/serverpod_chat_server/lib/src/generated/chat_message.dart
CONFLICT (content): Merge conflict in modules/serverpod_chat/serverpod_chat_server/lib/src/generated/chat_message.dart
Auto-merging modules/serverpod_chat/serverpod_chat_server/lib/src/generated/chat_read_message.dart
CONFLICT (content): Merge conflict in modules/serverpod_chat/serverpod_chat_server/lib/src/generated/chat_read_message.dart
Auto-merging packages/serverpod/lib/src/generated/auth_key.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/auth_key.dart
Auto-merging packages/serverpod/lib/src/generated/cloud_storage.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/cloud_storage.dart
Auto-merging packages/serverpod/lib/src/generated/cloud_storage_direct_upload.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/cloud_storage_direct_upload.dart
Auto-merging packages/serverpod/lib/src/generated/future_call_entry.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/future_call_entry.dart
Auto-merging packages/serverpod/lib/src/generated/log_entry.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/log_entry.dart
Auto-merging packages/serverpod/lib/src/generated/message_log_entry.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/message_log_entry.dart
Auto-merging packages/serverpod/lib/src/generated/method_info.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/method_info.dart
Auto-merging packages/serverpod/lib/src/generated/query_log_entry.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/query_log_entry.dart
Auto-merging packages/serverpod/lib/src/generated/readwrite_test.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/readwrite_test.dart
Auto-merging packages/serverpod/lib/src/generated/runtime_settings.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/runtime_settings.dart
Auto-merging packages/serverpod/lib/src/generated/server_health_connection_info.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/server_health_connection_info.dart
Auto-merging packages/serverpod/lib/src/generated/server_health_metric.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/server_health_metric.dart
Auto-merging packages/serverpod/lib/src/generated/session_log_entry.dart
CONFLICT (content): Merge conflict in packages/serverpod/lib/src/generated/session_log_entry.dart
Auto-merging packages/serverpod_service_client/lib/src/protocol/client.dart
Auto-merging templates/serverpod_templates/projectname_client/lib/src/protocol/client.dart
Auto-merging tests/serverpod_test_client/lib/src/protocol/client.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_field_scopes.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_field_scopes.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_bytedata.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_bytedata.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_duration.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_duration.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_enum.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_enum.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_index.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_index.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_object.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_object.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_parent.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_parent.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_self_parent.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_self_parent.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/object_with_uuid.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/object_with_uuid.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/simple_data.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/simple_data.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/simple_date_time.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/simple_date_time.dart
Auto-merging tests/serverpod_test_server/lib/src/generated/types.dart
CONFLICT (content): Merge conflict in tests/serverpod_test_server/lib/src/generated/types.dart
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by lukehutch** [comment]
> The problem with that is that we do not get any check in our CI pipeline, and we lose the main real test, it is simply not enough to hope people run this correctly locally. I suppose it would be possible to clone main generate the files, save them, clone the new PR, copy all the previously generated files and then re generate and do a check between them.

What if you put generated files into `.gitignore`, but then had a script that copied all the generated files into a directory that was connected to a different git repo that could be diff'd against?

**Comment by SandPod** [comment]
Closing this as a won't fix to make our intent clear.

We will continue to check in generated files in the Serverpod repository as these are used for both snapshot testing for the generated code but also utilized by external tools (that use the serverpod_service_client for example).

We are aware this is going to cause issues for developers maintaining a fork of our repo.

**Comment by lukehutch** [comment]
Can't you just check the generated files into a separate repo, or something?

**Comment by SandPod** [comment]
There are several potential approaches to address this issue. However, the primary challenges would involve building pipelines for released packages and ensuring a continued good developer experience for the Serverpod framework maintainers.

Given the effort required to tackle these challenges, we believe it would be more beneficial to focus on enhancing the framework itself and improving the overall digital infrastructure that supports Serverpod servers.

As a result, this issue will not be prioritized or worked on by the Serverpod team in the foreseeable future.
