### ISSUE TITLE
serverpod_cli, Windows 11 installation issue.

### ISSUE THREAD

**Issue by saiful00000** [serverpod/serverpod#108]
First of all I activated serverpod_cli

`C:\Users\saifu>flutter pub global activate serverpod_cli
Package serverpod_cli is currently active at version 0.9.5.
Resolving dependencies...
The package serverpod_cli is already activated at newest available version.
To recompile executables, first run `flutter pub global deactivate serverpod_cli`.
Installed executable serverpod.
Warning: Executable "serverpod" runs "bin\serverpod_cli.dart", which was not found in serverpod_cli.
Activated serverpod_cli 0.9.5.`

And after that I was checking whether serverpod_cli activated or not so I ran this command

`C:\Users\saifu>serverpod
WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: which dart
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      CommandLineTools.existsCommand (file:///C:/Users/saifu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.5/bin/create/command_line_tools.dart:22:32)
#5      main (file:///C:/Users/saifu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.5/bin/serverpod_cli.dart:43:31)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: which dart
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      CommandLineTools.existsCommand (file:///C:/Users/saifu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.5/bin/create/command_line_tools.dart:22:32)
#5      main (file:///C:/Users/saifu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/serverpod_cli-0.9.5/bin/serverpod_cli.dart:43:31)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
C:\Users\saifu>`

**Comment by vlidholt** [comment]
Windows is not yet supported. There is a pull request that should add Windows support, I'll look that over in the next few days!

**Comment by anandsubbu007** [comment]
any update? facing issue in windows 10.
may I know when will windows support be available?

**Comment by yahu1031** [comment]
@saiful00000 Can you please reinstall and check? The current version is 0.9.6. Please check this and update the ticket.
