### ISSUE TITLE
error when trying to deploy with docker

### ISSUE THREAD

**Issue by aragornz325** [serverpod/serverpod#1101]
I am trying to deploy the server with docker. I tried to do it in railway.app but it returned errors:

![image](https://github.com/serverpod/serverpod/assets/70964354/108785b4-52ba-43ab-b6c4-2bcbd3bfd5e2)

 so I tried to build it locally and this is the error I get.

![image](https://github.com/serverpod/serverpod/assets/70964354/14eb7b27-e073-4d64-b6dc-b6a6080dc1bd)

![image](https://github.com/serverpod/serverpod/assets/70964354/28df652d-33c6-454b-bd65-94eb1057bfba)

The dockerfile is exactly as it is autogenerated by serverpod, except for the first line that I changed to the latest stable version to see if that corrected the problem, but I can't get it to work.
If I comment out the line that gives the error, the image is built, but when trying to run it, it returns this error

![image](https://github.com/serverpod/serverpod/assets/70964354/f05875ea-683f-4c04-b552-6f719d19b3a2)

any ideas?

**Comment by Kstev239** [comment]
This is probably the same as in #882 .
His workaround was to replace
`COPY --from=build /runtime/ /`
with
```
COPY --from=build /runtime/etc /etc
COPY --from=build /runtime/lib /lib
COPY --from=build /runtime/lib64 /lib64
COPY --from=build /runtime/usr /usr
```

**Comment by aragornz325** [comment]
replace the line with the suggested ones


FROM dart:2.19.0 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM busybox

ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/etc /etc
COPY --from=build /runtime/lib /lib
COPY --from=build /runtime/lib64 /lib64
COPY --from=build /runtime/usr /usr
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/generated/ generated/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role

and got it to display in railway.app, but after a few moments it crashed
these are the railway log

![image](https://github.com/serverpod/serverpod/assets/70964354/3730168e-d223-4cd2-a24f-86e259d68d0f)

**Comment by Kstev239** [comment]
@aragornz325 Yeah, it seems like this is happening a lot lately. ( See #1054 )

**Comment by aragornz325** [comment]
> Did you create a new project with the same name of an old project?
> It is better to not repeat same name...

no, "gestion" is a new

**Comment by aragornz325** [comment]
Well, after trying a lot I managed to come up with a configuration that works to deploy serverpod on any host that supports docker

>FROM dart:stable AS build
>
>WORKDIR /app
>COPY . .
>
>RUN dart pub get
>RUN dart compile exe bin/main.dart -o bin/main
>
>FROM jenkins/jenkins:lts
>USER root
>RUN apt-get update && \
>    apt-get -y install apt-transport-https \
>         ca-certificates curl gnupg2 \
>         software-properties-common && \
>    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && >\
>    add-apt-repository \
>      "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
>      $(lsb_release -cs) \
>      stable" && \
>    apt-get update && \
>    apt-get -y install docker-ce
>USER jenkins
>
>
>ENV runmode=development
>ENV serverid=default
>ENV logging=normal
>ENV role=monolith
>
>COPY --from=build /runtime/etc /etc
>COPY --from=build /runtime/lib /lib
>COPY --from=build /runtime/lib64 /lib64
>COPY --from=build /runtime/usr /usr
>COPY --from=build /app/bin/main /app/bin/main
>COPY --from=build /app/config/ config/
>COPY --from=build /app/generated/ generated/
>COPY --from=build /app/web/ web/
>
>EXPOSE 8080
>EXPOSE 8081
>EXPOSE 8082
>
>CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role


**I hope that those who were having problems with the deployment can solve it with this guide**

**Comment by vlidholt** [comment]
We should look into why the default container doesn't work everywhere. I'm adding it to our roadmap.

**Comment by aragornz325** [comment]
@vlidholt  I found this easiest way to make the container be generated correctly

`FROM dart:stable AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM debian:buster-slim AS runtime

ENV runmode=staging
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/etc /etc
COPY --from=build /runtime/lib /lib
COPY --from=build /runtime/lib64 /lib64
COPY --from=build /runtime/usr /usr
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/generated/ generated/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
`

but I can't connect with the app in any way, neither with the previous dockerfile nor with this one.
consult with the railway people and this is what they tell me

**please have your app listen on host 0.0.0.0 and the environment variable PORT, this PORT variable is auto assigned to your service, and without your app listening on it, railway won't know how to forward traffic to your app, thus you get that error page**

**Comment by juanjosegarcia98** [comment]
I've managed to connect with my container deployed in Railway by rewriting in runtime the YAML config file in the `config/` folder, before the server starts listening with ```pod.start()```. By doing this, i was able to insert dynamically the PORT variable provided by platform. 

"Graphical" example:

```dart
/// Start function for Serverpod.
void run(List<String> args) async {
  rewriteConfigYaml(); // A function that creates a new YAML file to replace the original needed (depending on runmode) in config/ folder.
  
  // Rest of the code placed in this function.
  
  // Start the server.
  await pod.start();
}
```

I understand that doing this might not be an optimal solution according to the idea of the framework, but it has allowed me to get out of the way. @vlidholt @aragornz325

**Comment by darko-bacic** [comment]
After spending the whole day yesterday trying to build a Docker image of my server to go first time live, I was pretty disappointed to see that "out of the box" solution doesn't work. In the evening I watched couple of Docker courses to comprehend what could be the problem.

And after sleeping on it, this morning I managed to resolve the issue 🎉  (I must say that I'm not a fan of leaving dependencies the possibility to update themselves when a new version comes out that is not tested if it works with the current setup @vlidholt ).

Basically the issue is with the busybox Docker image and some changed in the newer versions, if you select to use `FROM busybox:1.34.1` it works just fine (I tried newer versions but it didn't work).

Here's the final Dockerfile (that was tested on MacBook Air Apple M1 chip and Docker Desktop 4.21.1 (114176)):

```
FROM dart:2.19.0 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM busybox:1.34.1

ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/ /
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/generated/ generated/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
```

**Comment by rodjordan** [comment]
The above solution (to replace one line `FROM busybox:1.34.1` ) worked for me.  Previous attempts to replace the COPY --from=build /runtime/ / with multiple lines always failed on the copy of lib64. Well done to @darko-bacic for finding this solution and I agree, this needs to work out of the box.

**Comment by aragornz325** [comment]
> After spending the whole day yesterday trying to build a Docker image of my server to go first time live, I was pretty disappointed to see that "out of the box" solution doesn't work. In the evening I watched couple of Docker courses to comprehend what could be the problem.
> 
> And after sleeping on it, this morning I managed to resolve the issue 🎉 (I must say that I'm not a fan of leaving dependencies the possibility to update themselves when a new version comes out that is not tested if it works with the current setup @vlidholt ).
> 
> Basically the issue is with the busybox Docker image and some changed in the newer versions, if you select to use `FROM busybox:1.34.1` it works just fine (I tried newer versions but it didn't work).
> 
> Here's the final Dockerfile (that was tested on MacBook Air Apple M1 chip and Docker Desktop 4.21.1 (114176)):
> 
> ```
> FROM dart:2.19.0 AS build
> 
> WORKDIR /app
> COPY . .
> 
> RUN dart pub get
> RUN dart compile exe bin/main.dart -o bin/main
> 
> FROM busybox:1.34.1
> 
> ENV runmode=development
> ENV serverid=default
> ENV logging=normal
> ENV role=monolith
> 
> COPY --from=build /runtime/ /
> COPY --from=build /app/bin/main /app/bin/main
> COPY --from=build /app/config/ config/
> COPY --from=build /app/generated/ generated/
> COPY --from=build /app/web/ web/
> 
> EXPOSE 8080
> EXPOSE 8081
> EXPOSE 8082
> 
> CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
> ```

I did not try to change the version of busy box, but if I changed to debian... and it worked there.
Thanks for sharing your solution, it's nice to have one more alternative.
where did you deploy it?

**Comment by aragornz325** [comment]
@darko-bacic 
 I did not try to change the version of busy box, but if I changed to debian... and it worked there.
Thanks for sharing your solution, it's nice to have one more alternative.
where did you deploy it?

**Comment by darko-bacic** [comment]
I deployed to GCP, that was also a wild story.. in the end since I use Cloud Run and Cloud SQL I needed to connect using unix socket.. to spare you the headache, in your config file add under database `isUnixSocket: true` and to the unix socket connection string at the end append  `/.s.PGSQL.5432` 😆 

@aragornz325

**Comment by aragornz325** [comment]
we deployed in railway.app... it was quite difficult, the solution that comes by default doesn't work, we had to rewrite the .yaml file at the moment the image is being generated. kind of crazy... but it worked
@darko-bacic

**Comment by rodjordan** [comment]
Regarding the `isUnixSocket: true` and the `/.s.PGSQL.5432` this is all covered in the ServerPod documentation so maybe you missed it :-)
[https://docs.serverpod.dev/next/deployments/deploying-to-gcr-console](url)

```
database:
  **isUnixSocket: true**
  host: /cloudsql/my-project:us-central1:database-name**/.s.PGSQL.5432**
  port: 5432
  name: serverpod
  user: postgres
```

**Comment by darko-bacic** [comment]
Indeed I missed that part somehow, well that's the price you pay for not reeding the documentation 😅

**Comment by SandPod** [comment]
@darko-bacic Sorry for the late reply on this one.

You where completely correct in your analysis above and we have a PR up to pin the busy box and dart image version so that they are compatible with each other.

**Comment by Kiwi-KiwiCorp** [comment]
This is still an issue with the current "out of the box" dockerfile when trying to deploy to GCP, unsure why this has been closed
