### ISSUE TITLE
Extended tests for new database migrations

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#1117]
Improve test coverage for new database migrations.

This should include tests for:

- [ ] `generateDatabaseMigration` in `tools/serverpod_cli/lib/src/database/migration.dart`
- [ ] `createDatabaseDefinitionFromEntities` in `tools/serverpod_cli/lib/src/database/create_definition.dart`

**Comment by SandPod** [comment]
We now have a comprehensive test suite for the [definition creation](https://github.com/serverpod/serverpod/tree/main/tools/serverpod_cli/test/database/create_definition) and the [migrations](https://github.com/serverpod/serverpod/tree/main/tools/serverpod_cli/test/database/migration).
