### ISSUE TITLE
Issues to relate methods of example project to rest equivalent

### ISSUE THREAD

**Issue by remonh87** [serverpod/serverpod#114]
First of all impressive work! Setting up the backend was super easy to set everything up. I only struggle after starting up the server how to access the `hello` endpoint using Postman or curl.  How can I do this?

Also tip for documentation I am used to annotation frameworks like KTOR or Spring boot that are closely tied to REST terminology. At the moment I really find the Endpoint class a bit overwhelming and miss a bridge between "old fashioned" API development.

**Comment by MarkOSullivan94** [comment]
Hey @remonh87 I've just shared within Discussions how to access the `ExampleEndpoint` with cURL command which you should be able to import into Postman

https://github.com/serverpod/serverpod/discussions/100#discussioncomment-2447775

**Comment by remonh87** [comment]
ah wow totally missed that discussion thanks for sharing. Will close the issue
