### ISSUE TITLE
Default value support in protocol / generated code / database

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1140]
**Feature: default values.**

Allow the programmer to define a default value for a field in the protocol. The default value should propagate to the SQL table and the generated dart class. These defaults are in most cases constant and does not give a dynamic value.

```yaml
class: Example
table: example
fields:
  toggle: boolean, default=true
  score: int, default=0
```

The default "default" value should be null if field is nullable, if not it is required to be set. In case of List and Map I think it makes sense to initialize them as empty List/Map in the field is not nullable.

We should at least support the following types for default values

- boolean
- int
- double
- String
- DateTime
- Uuid
- Duration

__DateTime__, the default value has to be an ISO8001 string OR `now()` where it would map to the same function in postgresql.
__Uuid__, the default value has to follow the uuid syntax such as the nil uuid `00000000-0000-0000-0000-000000000000`.

For other types we should not support default values (such as custom objects). We should allow defaults for any database type we have implemented.

**Keywords**
Configuring the default value could be done using the following keywords:
- **defualt** - Sets the default value for both the Model and the storage.
- **defaultModel**. - Sets the default value for only the Model.
- **defaultPersist** - Sets the default value for only the storage.

**Comment by MarkOSullivan94** [comment]
Agree with all of this and for me this is one feature I'll be very excited to see added in the 1.2 release

**Comment by lukehutch** [comment]
I definitely need this. I have a method that creates a default instance of a large protocol class, setting fields to `''`, `0`, or `false`. Every time I modify the protocol file, this class breaks, and I have to go edit it.

**Comment by alguintu** [comment]
Curious how you classify default values as a "nice to have" feature instead of an essential functionality in a migration/orm package? Most if not all ORMs I have encountered have this feature to ensure data consistency and simplify api calls for new entitities.

**Comment by Isakdl** [comment]
@alguintu it is classified as nice to have for the 1.2 update. This feature is something we want to build but we have to make a cut somewhere to get the release out. I agree that this is an important feature.

**Comment by lukehutch** [comment]
Hopefully when default values are added, this migration issue can be avoided:

> One or more columns are added to table "social_post" which cannot be added in a table migration. The complete table will be deleted and recreated.

Columns should always be able to be added, without deleting the database, but I assume the reason this is not possible right now is because default values are not supported. The error message should actually explain that, even when default value support is added.

**Comment by lukehutch** [comment]
Other issues that would be fixed if we had default values:

* #2000 -- new columns with non-nullable values could be added without dropping the whole table if a default value could be assigned to the column.
* #1815 could be revised so that no error is given for non-nullable `serverOnly` fields that also have a default value.
