### ISSUE TITLE
Support quering nested objects 

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1151]
**Is your feature request related to a problem? Please describe.**
Add support to query relations in the database by specifying which objects you want to include. See related issue (https://github.com/serverpod/serverpod/issues/1150) for how the definition side looks.

Based on the object relation generate the necessary dart code to customize what we want to include. All querying functions need to take a new typed optional object.

Example of querying methods:
```dart
class Employee extends TableRow {
  
  ...

  static Future<List<Employee>> find(
    Session session, {
    NoteExpressionBuilder? where,
    int? limit,
    int? offset,
    Column? orderBy,
    List<_i1.Order>? orderByList,
    bool orderDescending = false,
    bool useCache = true,
    Transaction? transaction,
    EmployeeInclude? include,
  })

  static Future<Employee?> findById(
      _i1.Session session,
      int id,
      EmployeeInclude? include,
   ) { ... }

  static EmployeeInclude include(EmployeeInclude param) {
    ...
    return param;
  }
  ...
}
```

The `EmployeeInclude` object also needs to be generated but is fairly simple, it could look like this:

```dart
class EmployeeInclude {
  CompanyInclude? company;

  EmployeeInclude({this.company});
}
```

If the company table has no references the `CompanyInclude` would be an empty object. Each class that has a table also need this companion object even if it is just empty. 

It should be possible to nest these n levels deep if you wish.

```dart
Employee.find(
  session,
  include: Employee.include({
    company: Company.include({
      address: Address.include(),
    }),
  }),
);
```

The query methods needs to have the generated code to manage these relations when querying the data. In this issue we only deal with the case of a single object, we leave the list implementation to a subsequent issue.

**Comment by lukehutch** [comment]
It looks like what you're proposing is a halfway step towards joins? If so, what about something like this:

```dart
Employee.find(
  session,
  include: [
    Employee.joinOn(Employee.id),
    Company.joinOn(Company.employeeId),
    Address.joinOn(Address.emloyeeId),
  ],
);
```

**Comment by Isakdl** [comment]
Indeed it is :)! Interesting take, what do you think the benefit of this approach is? The one I proposed above this information would instead live inside the protocol and you can simply toggle on or off the join.

My initial though was to limit the knowledge need on the query side, makes it easier to work with the data. Requires more understanding on the protocol side but I think you would have to define the nested object in the protocol anyway to be able to join it. 

Minimal example:
```yaml
class Employee
table: employee
fields:
  address: Address?, scope=api
```

Employee would now be able to hold the address object but could not add any other, unless you add them too.

**Comment by lukehutch** [comment]
Well, I was just proposing something closer to SQL syntax, since people with RDBMS backgrounds will have an easier time with the API that way.
