### ISSUE TITLE
On Fedora, `docker compose` is `docker-compose`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1152]
**Describe the bug**

When running `serverpod generate` on Fedora:

```console
Setting up Docker and default database tables in /home/luke/Work/click/vendor/testproj/testproj_server
If you run serverpod create for the first time, this can take a few minutes as Docker is downloading the images for Postgres. If you get stuck at this step, make sure that you have the latest version of Docker Desktop and that it is currently running.

Starting docker
unknown flag: --build
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND
```

The problem is that the command is `docker-compose`, not `docker compose` as on (I assume) Ubuntu or some other Linux flavor.

**Comment by vlidholt** [comment]
If I remember correctly, the `docker-compose` command is being deprecated. Are you using the latest version of Docker?

**Comment by lukehutch** [comment]
Oops, you're right, I thought it was the other way around.

docker and docker-compose (v1) are deprecated by Docker (but not yet by Fedora) in favor of docker-ce and the docker compose plugin.

For the record (in case anybody needs this info in future), you can replace the Fedora version of docker with docker-ce and the docker compose plugin by following these instructions:

https://docs.docker.com/engine/install/fedora/#uninstall-old-versions
