### ISSUE TITLE
LSP failed to start in the vscode extension

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#1192]
**Describe the bug**
Failed to spawn serverpod LSP in vs code extension code. The available code has been utilized in the [VSCode extension code](https://github.com/yahu1031/serverpod_ext/blob/f0a801b8d2e9507fad1025b86c4e15a609da85ee/src/base/classes/serverpod.class.ts#L66).

**To Reproduce**
1. Clone the code
2. Head into `tools/serverpod_vscode_extension`
3. Open it in a new vs code.
4. Run `npm i`
5. Now hit `F5`.

**Expected behavior**
The Serverpod's LSP should run without any issues.

**Screenshots**
![Screenshot 2023-07-19 at 11 13 38 PM](https://github.com/serverpod/serverpod/assets/35523357/322938dd-cc3f-48da-b120-38fcdb7f21a8)

**Serverpod versions**
 -  _CLI Version:_ 1.1.0 (Github - main branch)

**Platform information**
```console
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A5286i
```

**Comment by yahu1031** [comment]
Some issue with the system, but A restart fixed it. But got something new.

```console
[Error - 01:23:43] Request textDocument/documentColor failed.
  Message: File is not being analyzed
  Code: -32007 
/Users/mr.minnu/Documents/testpod/testpod_server/bin/main.dart
[Error - 01:23:43] Request textDocument/inlayHint failed.
  Message: File is not being analyzed
  Code: -32007 
/Users/mr.minnu/Documents/testpod/testpod_server/bin/main.dart
[Error - 01:23:43] Request textDocument/inlayHint failed.
  Message: File is not being analyzed
  Code: -32007 
/Users/mr.minnu/Documents/testpod/testpod_server/bin/main.dart
[Error - 01:23:43] Request textDocument/documentSymbol failed.
  Message: File is not being analyzed
  Code: -32007 
/Users/mr.minnu/Documents/testpod/testpod_server/bin/main.dart
```

Was this expected?

**Comment by Isakdl** [comment]
I'm not able to replicate, are you running the serverpod cli from main as well? The language server is built into the CLI and you will also have to use the latest CLI for this to work.

After you switch to the main branch and pulled all the latest changes, make sure you run `dart pub global activate --source path .` from the serverpod_cli folder, to ensure you are running the latest version.

Please let me know if this didn't fix the issue.

**Comment by Isakdl** [comment]
Oh I just saw your linked code. the main branch has changed the implementation here!

You have to  change this 
```
args: ['language-server', '--no-development-print'],
```

To this
```
args: ['language-server', '--quiet'],
```
