### ISSUE TITLE
chat module's intl dependency confict with flutter_localizations

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1204]
### Discussed in https://github.com/serverpod/serverpod/discussions/1203

<div type='discussions-op-text'>

<sup>Originally posted by **Frank1016** July 25, 2023</sup>
I was trying to add serverpod_chat_flutter package to my serverpod project's flutter folder, but got this intl dependency conflict error:

```
Resolving dependencies...
Because every version of flutter_localizations from sdk depends on intl 0.18.0 and serverpod_chat_flutter >=1.1.0 depends on intl ^0.18.1, flutter_localizations from sdk is incompatible with serverpod_chat_flutter >=1.1.0.
So, because sbm2025_flutter depends on both flutter_localizations from sdk and serverpod_chat_flutter ^1.1.1, version solving failed.
exit code 1
```

I found a way to override intl dependency in the pubspec.yaml file to resolve the issue, but don't think this is a proper way. So I'm suggesting that maybe it's a good idea to make the intl dependency version of serverpod_chat_flutter package the same with flutter_localizations in the future? Thanks!</div>

**Comment by SandPod** [comment]
This has been resolved now.
