### ISSUE TITLE
`serverpod generate` not generating protocol relative tables data in tables.pgsql

### ISSUE THREAD

**Issue by b14cknc0d3** [serverpod/serverpod#1225]
**Describe the bug**
`serverpod generate` not generating protocol relative table in tables.pgsql

**To Reproduce**
1.  create new project `serverpod create myfirstgame`
2.  add player `player.yaml`
3.  run serverpod generate
**Expected behavior**
player relative data should generate in tables.pgsql 

**Screenshots**

![Screenshot 2023-07-30 at 1 26 47 PM](https://github.com/serverpod/serverpod/assets/40236753/8d4f4dc7-8bea-4996-b1e5-c3136782d8ed)

**Serverpod versions**
 -  _CLI Version: 1.1.1
 - _Library version:1.1.1

**Platform information**
mac
**Additional context**
I updated serverpod via git

**Comment by Isakdl** [comment]
You have to define a table in the protocol or you will not get any SQL code.

Your protocol file should look like this:

```yaml
class: Player
table: player
fields:
  dx: double
  dy: double
  createdAt: DateTime
  updatedAt: DateTime
