### ISSUE TITLE
Stopping & starting doesn't seem to work

### ISSUE THREAD

**Issue by atreeon** [serverpod/serverpod#123]
Hi, serverpod looks interesting, thanks for starting the project!
I did a `serverpod run`, I then ctrl + c ended the terminal window (also stopped my docker container), I ran it again  and it seems like it is stuck running in the background.  What service does it run under and how do I stop it please?
```
There are some issues with your setup that will prevent your Serverpod project from launching.
The public api port (8180) is occupied by another application or you are running another instance of Serverpod.
The service insights port (8181) is occupied by another application or you are running another instance of Serverpod.
```

**Comment by vlidholt** [comment]
This needs some further investigation. There should be no services started that doesn't end when pressing ctrl-c. Are you on Linux?

You may potentially want to run serverpod with `dart bin/main.dart` if you keep having this issue.

**Comment by atreeon** [comment]
thanks, I'm on mac.  Yes, thank you, I've been running dart bin\main.dart actually now and it is fine.  I'll run it again tomorrow and update you.

**Comment by yahu1031** [comment]
We can write a script for this. that will check for ports listening(we already have it). Will get user input whether (s)he wants to kill the port and restart again. I think I can write it.

**Comment by atreeon** [comment]
I tried this again & ctrl+c doesn't always seem to stop the service.  However closing the terminal window does seem to stop the service ok.  I'm happy with this but I'll let you close the issue just in case.  Thank you.

**Comment by vlidholt** [comment]
Automatically killing process doesn't seem like a great solution. But it might be smart to list the processes that are using the ports so that the user easily can kill them if needed.

**Comment by vlidholt** [comment]
Also, I haven't been able to reproduce this issue. It would be interesting to see if more people are affected and what the root cause is.

**Comment by yahu1031** [comment]
I have a solution. I have dropped the solution on your LinkedIn. Please check it and verify it. If that is okie, I will start implementing it. @vlidholt
