### ISSUE TITLE
Transaction objects as function argument inside Endpoints

### ISSUE THREAD

**Issue by starklord** [serverpod/serverpod#1246]
Hi i tried to pass the transaction object from one function endpoint to another function in another endpoint.
The problem as i can understand is that when you run "serverpod generate" the client cant resolve the package database_connection and that is great i think. BUT...
what is the correct way to reuse some endpoint functions inside another endpoint functions if you always need to pass the Session object, and if you are in a transaction block, also the Transaction object.

**Comment by SandPod** [comment]
Hey 👋 
I'm not sure I understand what you are trying to achieve. Could you provide a code example that illustrates how you have structured your code and the issue you are encountering?

If you are trying to reuse logic between two server endpoints I would suggest defining that logic in separate class that can be shared between the endpoints.

**Comment by SandPod** [comment]
Closing as this seems to be resolved by the comment.
