### ISSUE TITLE
flexible search

### ISSUE THREAD

**Issue by dongri727** [serverpod/serverpod#1254]
What Can I do with searching operation like this ?   Thank you

SELECT A.*
FROM tableA A
INNER JOIN tableC C ON A.id = C.tableA_id
INNER JOIN tableB B ON C.tableB_id = B.id
WHERE B.column_name = 'your_value'

**Comment by SandPod** [comment]
Hey 👋
We currently don't support joins operations. We are working on adding that support right now and the work is tracked here https://github.com/serverpod/serverpod/issues/1145.

Right now, you could either solve your issue by performing multiple queries, https://docs.serverpod.dev/concepts/database-communication#joining-tables-and-nesting-objects,  or you could define your own sql query https://docs.serverpod.dev/concepts/database-communication#executing-raw-queries.
