### ISSUE TITLE
Please report more info when `not like the target database` errors are given

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1262]
When errors like the following are shown:

```console
WARNING: The database does not match the target database:
 - Table "account" is not like the target database.
```

it would be good to be told at least one way in which the database schema doesn't match the expected schema.

**Comment by SandPod** [comment]
Hey 👋 
Makes sense to me, good catch!

**Comment by ChaStPierre** [comment]
Same here, just don't have much to go on and the proposed fix are not really helping. thanks
