### ISSUE TITLE
Serverpod CLI generate in watch mode only generates once

### ISSUE THREAD

**Issue by itsparth** [serverpod/serverpod#1274]
**Describe the bug**
When in server directory, after running serverpod generate -w -v, the protocol and endpoints are generated, but if I make any changes to example_endpoint.dart file (e.g adding a new endpoint) and saving, there are no updates to the generated files.

**To Reproduce**
1. Go to mypod_server
2. Run serverpod generate -w -v
3. Go to mypod_server/lib/src/endpoints/example_endpoint.dart
4. Make any changes to the file (adding / updating endpoints)

**Expected behavior**
Changes to example_endpoint.dart should regenerate files in mypod_server/lib/src/generated and mypod_client

**Logs of serverpod generate -w -v**
Analyzing serializable entities in the protocol directory.
  - processing file: lib/src/protocol/example.yaml
Generating files for serializable entities.
Generating lib/src/generated/protocol.dart.
Generating lib/src/generated/example.dart.
Generating ../mypod_client/lib/src/protocol/example.dart.
Generating generated/tables.pgsql.
Analyzing the endpoints.
Generating the protocol.
Generating lib/src/generated/protocol.dart.
Generating lib/src/generated/endpoints.dart.
Generating ../mypod_client/lib/src/protocol/protocol.dart.
Generating ../mypod_client/lib/src/protocol/client.dart.
Cleaning old files.
Cleaning up old files.
Remove old files from Directory: 'lib/src/generated'
Remove old files from Directory: '../mypod_client/lib/src/protocol'
Initial code generation complete. Listening for changes.
Starting up continuous generator
File changed: modify lib/src/endpoints/example_endpoint.dart
Analyzing serializable entities in the protocol directory.
  - processing file: lib/src/protocol/example.yaml
Generating files for serializable entities.
Generating lib/src/generated/protocol.dart.
Generating lib/src/generated/example.dart.
Generating ../mypod_client/lib/src/protocol/example.dart.
Generating generated/tables.pgsql.
Analyzing the endpoints.
Generating the protocol.
Generating lib/src/generated/protocol.dart.
Generating lib/src/generated/endpoints.dart.
Generating ../mypod_client/lib/src/protocol/protocol.dart.
Generating ../mypod_client/lib/src/protocol/client.dart.
Cleaning old files.
Cleaning up old files.
Remove old files from Directory: 'lib/src/generated'
Remove old files from Directory: '../mypod_client/lib/src/protocol'
Incremental code generation complete.

File changed: modify lib/src/endpoints/example_endpoint.dart
Analyzing serializable entities in the protocol directory.
  - processing file: lib/src/protocol/example.yaml
Generating files for serializable entities.
Generating lib/src/generated/protocol.dart.
Generating lib/src/generated/example.dart.
Generating ../mypod_client/lib/src/protocol/example.dart.
Generating generated/tables.pgsql.
Analyzing the endpoints.
Generating the protocol.
Generating lib/src/generated/protocol.dart.
Generating lib/src/generated/endpoints.dart.
Generating ../mypod_client/lib/src/protocol/protocol.dart.
Generating ../mypod_client/lib/src/protocol/client.dart.
Cleaning old files.
Cleaning up old files.
Remove old files from Directory: 'lib/src/generated'
Remove old files from Directory: '../mypod_client/lib/src/protocol'
Incremental code generation complete.

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling. 1.1.1
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using. 1.1.1

**Platform information**
WSL2 Windows 11

**Comment by vlidholt** [comment]
We are doing a lot of work on the code generation in version 1.2, so this will be fixed in the next release!
