### ISSUE TITLE
StateError (Bad state: Stream has already been listened to.)

### ISSUE THREAD

**Issue by IttaiBarkai** [serverpod/serverpod#1279]
First, just want to say that I have really been enjoying working with Serverpod, so thanks for all the hard work put into this. 

I am creating and disposing this cubit (view code snippet below) every time I enter a screen. When the cubit is created the first time I encounter no issues. However, when I navigate back and then return to the same screen I get the error " StateError (Bad state: Stream has already been listened to.) ". I checked the previous closed [issue](https://github.com/serverpod/serverpod/issues/900#issue-1703673144) on this github repository and I have made sure to close the connectionHandler when the cubit is closed. I also double checked that this method is actually being called. The _listenToServer(); function is the one causing the issue for me. I also made sure this function is not being called twice on cubit creation. 

If this isn't a bug then any explanation as to what I am doing wrong would be great. 

```
class GameCubit extends Cubit<GameState> {
  late final StreamingConnectionHandler connectionHandler;

  GameCubit() : super(const GameState.initial()) {
    connectionHandler = StreamingConnectionHandler(
      client: client,
      listener: (connectionState) {},
    );
 
     _listenToServer();
       connectionHandler.connect();
  }

  Future<void> _listenToServer() async {
    await for (var update in client.gameLobby.stream) {}
  }

  @override
  Future<void> close() async {
    connectionHandler.close();
    return super.close();
  }
}
```

**Comment by vlidholt** [comment]
There is a method for resetting the stream, you may want to have a look at that. Pixorama https://pixorama.live and Bacterial Boom https://github.com/serverpod/bacterialboom show different approaches to handling reconnections to the server.

**Comment by IttaiBarkai** [comment]
Hi @vlidholt, thanks for the two references I will make sure to check them out in the coming days and update this thread if I manage to solve my issue :)

**Comment by IttaiBarkai** [comment]
Adding `client.gameLobby.resetStream();` to the start of the _listenToServer function solved the issue. @vlidholt Thanks for the bacterialboom example which highlighted what I was missing.
