### ISSUE TITLE
Future calls test

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#13]
Add tests for future calls

**Comment by wilsonsilva** [comment]
Which files need such tests?

**Comment by vlidholt** [comment]
This may actually have been added already, but I will double check!

**Comment by SandPod** [comment]
Some smoke tests for future calls now exists: https://github.com/serverpod/serverpod/blob/2865fdcce43dfcdd2ef0eeb40b982608bb1033bb/tests/serverpod_test_server/test_e2e/service_protocol_test.dart#L231C67-L231C75
