### ISSUE TITLE
Can `Column.equals` and `Column.notEquals` be replaced with `==` and `!=`?

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1302]
Why does `Column` use `.equals` and `.notEquals` rather than overriding `==` and `!=` ? The inequality operators are overridden...

**Comment by SandPod** [comment]
The difference is that the `.equals` and `.notEquals` are typed compared to the other operators that just take in any expression.

But I don't see any good reason for not supporting `==` and `!=` as well as the typed `.equals` and `.notEquals` methods.

**Comment by lukehutch** [comment]
I don't think having both types of operators would make sense, it would just confuse users as to what the differences are. For consistency, if you have overridden inequality operators, then you should probably use `==` and `!=`, and deprecate `.equals` and `.notEquals`. It took me a while to figure out that I had to use `.equals` and `.notEquals` rather than `==` and `!=` (and I had to read the source for `Column` to figure it out).

Another thing that confused me was the function of `.equals`, given that I'm coming from a Java world. It's not very Dart-y to have to use `.equals` rather than `==`, and it comes with certain expectations.

Can the symbolic operators not be typed? I don't understand the issue.

**Comment by SandPod** [comment]
I think I understand your concern and the source of confusion.
The interface isn't as clear as it could be here and I think there is some discrepancy between this and the implementation of the other operator overloads (`<=`, `>=`, `<`, `>`).

As I see it the purpose of `.equals` and `.notEquals` are to help developers perform a compare operation on all columns towards a specific value. We then guarantee (by our typing and possible escaping) that the value is compatible with the column values stored in the database.

We don't provide that guarantee for the other operator overloads. The reason being that we also want to support operations between two expressions, this especially comes into play once we think about nested relations.

For example we would like to support this expression where homeTown and location both are instances of a fictional Town table entity.
``` dart
Expression whereSameHomeAsCompanyTown = Citizen.t.homeTown.name == Citizen.t.company.location.name;
```

Therefore I jumped to the conclusion that we probably need to support both, but possible with some other syntax to make it more clear?

**Comment by lukehutch** [comment]
> And both will probably need to be there since `.equals` helps you do operations on the value of the column while the Expression operators helps you do comparisons between expressions

You are wrapping values in expressions already in several places in your recent changes. So maybe that should be applied to all values used anywhere. Values just become the leaf nodes of an expression tree. Then you don't need special treatment of values vs. expressions -- everything becomes an expression.

**Comment by SandPod** [comment]
That is true, but that would place the responsibility of understanding what values need to be escaped in the hands of the developer.

That might not be the wrong thing to do, but it is a different approach than the current one.

I think the code in place might need some cleanups to communicate the intent more clearly as well. But the internal usage shouldn't stand in the way of providing helpful methods for developers.

**Comment by lukehutch** [comment]
@SandPod OK, what about making expressions typed, then? `Expression<T>`. Then you can constrain expression operands by type, for example to ensure that both sides of an inequality are scalar types, or that both sides of a Boolean test are Boolean types.

**Comment by lukehutch** [comment]
@SandPod great -- and sure, I'd be more than happy to take a look. This is maybe the most important part of the server API to get right (at least, the part I find myself using the most!).

**Comment by SandPod** [comment]
Follow up here - Haven't gotten to any improvements to the typing yet.

I'm just going to type out the problem a bit to create a shared understanding.
Please give any feedback if something is missing or this doesn't represent the full picture.

### Problem
The key problem is that there are two ways to compare a columns value.

1. Compare it to a known value before hand.
2. Compare it to another column as part of the query.

### Examples
Given the entity:

``` yaml
class: Citizen
table: citizen
fields:
    friends: int
    wantedNumberOfFriends: int
```

Example 1: Asking for all citizens that have exactly 5 friends - Displays Comparison 1.
``` dart
Citizen.find(
    session,
    where: (t) => t.friends.equals(5),
);
```

Example 2: Asking how many citizens have exactly their wanted number of friends. (Syntax currently not supported) - Displays Comparison 2.
``` dart
Citizen.find(
    session,
    where: (t) => t.friends == t.wantedNumberOfFriends,
);
```

### Wanted behavior.
When performing Comparison 1, We want typed support for the column value. It should not be possible to pass any other type than an `Int` in Example 1.

When performing Comparison 2. We want typed support for only columns or expressions that evaluate to a value of the column type. Only `ColumnInt` or an `Expression<int>` should be supported for Example 2.

**Comment by lukehutch** [comment]
This might be a good chance to express your support for Union types in Dart, since this is a very interesting usecase. I have already done so for other applications.

https://github.com/dart-lang/language/issues/1222

I'm wondering, what is the contract for the equality types in Dart? I assume `==` and `!=` can take any type on either side of the operator, but they are expected to return false if the types on each side are not null? Can that even validly be constrained to specific subtypes, and/or can the left and right operand be of different types?

I would be OK with using `equalsColumn` and `notEqualsColumn` for the column case.

**Comment by SandPod** [comment]
Aah, nice to see there is an issue on that. I come from a C++ background and really miss parameter overloading.

We would need to investigate the implications or even the possibility of overloading `==` and `!=`. Since they have such a general use and are probably important for other features (such as placing multiple `Expressions` in a Set), I'm not sure that it would be wise to overload them even it if was possible.

**Comment by lukehutch** [comment]
What about even defining `===` and `!==` ?

Although, because Dart doesn't yet have Union types, there probably needs to be two types of equality: column-vs-value (`.equalsValue`), and column-vs-expression (`.equalsExpression`). Maybe even column-vs-column (`.equalsColumn`), for joins.

**Comment by vlidholt** [comment]
I don't think this is possible unfortunately. You cannot define `===` to be an operator in Dart and you can only override `==` to return a `bool`.

Shall we close this issue?

**Comment by lukehutch** [comment]
Yes, OK -- although first, what is your reaction to my last comment about needing different equals functions, for type safety, given that Dart doesn't support multiple dispatch or union types?

**Comment by SandPod** [comment]
Closing this issue as it seems we reached a consensus that this was not possible to support in a nice way.

@lukehutch - Please reopen if that analysis was wrong and clarify what the definition of done would be in that case.
