### ISSUE TITLE
Protocol files can't contain spaces

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1328]
**Describe the bug**

I created a protocol file for an enum, and I accidentally put a space in the protocol file filename. Even though `serverpod generate` worked, and the client code seemed to compile (with `%20` in place of the space in the import name), my Flutter code couldn't find the enum.

I didn't dig far to figure out what went wrong. But probably protocol file filenames should not be allowed to have spaces in them.

**Comment by SandPod** [comment]
Good catch! Thanks for the report! 🙏

**Comment by hampuslavin** [comment]
Hi @lukehutch!
I had a look at this one and tried to reproduce by doing the following on MacOS:
- Created an enum like this:
```yaml
enum: HampusEnum
values:
  - cat
  - dog
```
- Named the file `hampus_  enum.spy.yaml`
- Ran `serverpod generate`

It generates the enum and correctly builds the client package. When importing it into the Flutter code it works and I can run the app.

I'm wondering if it could  perhaps be platform dependent. What OS are you running on?

Thanks!

**Comment by lukehutch** [comment]
Hi @hampuslavin,

I am on Linux. I just tried this again, and it seems to be fixed now (presumably via some other change), so I'll go ahead and close this. Thanks!
