### ISSUE TITLE
Allow updating of multiple rows using Postgres `update...from`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1329]
**Is your feature request related to a problem? Please describe.**

Sometimes I need to update a batch of rows. For efficiency and atomicity reasons, I would like to make all these updates in a single query.

PostgreSQL has a way to do this:

https://stackoverflow.com/a/18799497/3950982

**Describe the solution you'd like**

I would love to see this supported in Serverpod as `T.updateMultiple(Session session, List<T> rows)`, where `T extends TableRow`.

**Describe alternatives you've considered**

Right now I just launch a bunch of async updates in parallel, and then await all the results.

**Comment by SandPod** [comment]
This feature request makes total sense. It would be very useful to have a way to update multiple rows in one query.

**Comment by lukehutch** [comment]
We probably need a `T.insertMultiple` too.

Then I wonder if `T.upsertMultiple` also makes sense (#232 is the upsert issue)... (maybe not? I think Postgres `update...from` only works for existing records)

**Comment by Isakdl** [comment]
Im almost done with the implementation of this for insert, update and delete. Needs some more tests but hopefully can get it merged within a few days.

**Comment by lukehutch** [comment]
Thanks for your work on this, @Isakdl!
