### ISSUE TITLE
relation on createing tables in db not exist 

### ISSUE THREAD

**Issue by ElsimatAmir** [serverpod/serverpod#1351]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling.
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**

**Comment by ElsimatAmir** [comment]
![image](https://github.com/serverpod/serverpod/assets/123176613/138c94cb-3b02-4e90-bc1d-f814b9e113a0)

**Comment by ElsimatAmir** [comment]
am  still learning and testing serverpod so, i created a small table  to save notes iin it but when am trying to read or write to it am getting this error with status code 500 what am doing wrong

**Comment by ElsimatAmir** [comment]
![image](https://github.com/serverpod/serverpod/assets/123176613/5a1c7f59-2b83-47e8-aef8-1c3283a4aedd)

thats the endpoint am useing

**Comment by SandPod** [comment]
Hey @ElsimatAmir! 👋 

Have you run the sql script after you generated your `Note` entity? That error can show if the table `Note` does not exist in the database.

Try this solution to create the table: https://stackoverflow.com/questions/76180598/serverpod-sql-error-when-starting-a-clean-project.

We are working on migrations for serverpod that will make this process much simpler.

**Comment by ElsimatAmir** [comment]
@SandPod yes i have runed the setup tables script and generated the serverpod

**Comment by SandPod** [comment]
Is the table present if you connect to the database using some form of database viewer?

**Comment by SandPod** [comment]
Closing because the issues seems to be solved.
