### ISSUE TITLE
[Proposal] Universal models

### ISSUE THREAD

**Issue by Rodsevich** [serverpod/serverpod#1360]
**Is your feature request related to a problem? Please describe.**
Yes, the models generated ATM by serverpod aren't usable everywhere because of the extension of TableRow (which depends at last on dart:ffi). We need to manipulate them properly on the backend side for providing appropiate performance tools like DTOs, INNER JOINS, etc

**Describe the solution you'd like**
We need a solution that allows you to make your own models (however you want) and then those models are translated to what Serverpod wants (in a future, that could be simplified, but ATM is out of scope for us)

**Describe alternatives you've considered**
Write a lot of code for circunventing the limitations of TableRow with ffi

## Proposal
We need an adapter of our used-everywhere enhanced models to Serverpod internals models. For this we needed to do this changes on our project:  
 - A common location for the models, preferable on an independent package with as minimum dependencies as you want to have them working, like explained here:  
```
├─generated_project_with_serverpod
│   ├── project_client
│   ├── project_flutter
│   ├── project_server
│   ├── project_models  <--- This was a nice location
│   ├── docker-compose.yaml - because we needed to have them included on the Docker container
│   ├── Dockerfile <--- so we also had to take these files outside of project_server too
```
- A builder for those models that creates the logic for conversion between those models and the model inputs that Serverpod needed.
- An adapter for the client and the server built-in CRUD operations

**Comment by Isakdl** [comment]
Just to clarify, do you want a shared base model that is used by both the client and the server? Like discussed in this issue: https://github.com/serverpod/serverpod/issues/1256. 

That is indeed something we want to support at some point and a topic that seems to come up every now and then.

**Comment by Rodsevich** [comment]
indeed, sth like that would do the trick. I close the issue for continuing there in #1256 . Thanks, @Isakdl
