### ISSUE TITLE
How to call another api endpoint  

### ISSUE THREAD

**Issue by GeorgePagounis** [serverpod/serverpod#1361]
Hi, this may be a stupid question but I haven't found easily any info regarding on how to call another api endpoint from a custom endpoint. E.g. my custom todo endpoint

```class TodoEndpoint extends Endpoint {
  Future<List<Todo>> getTodos(Session session) async {
    // make request to https://jsonplaceholder.typicode.com/todos to get todos
   //maybe save them in my db (then in the future I could check when they were created in my db and either fetch from db or 
   //endpoint if not stale
   
    return todos;
  }
  ```

**Comment by Isakdl** [comment]
Unfortunately not supported yet, The issue tracking this: https://github.com/serverpod/serverpod/issues/1009.

**Comment by GeorgePagounis** [comment]
@Isakdl I am sorry, but [#1009](https://github.com/serverpod/serverpod/issues/1009) is not what I am looking for. Serverpod seems to be really well made, as it has support for dockers, redis, a shareable library so both backend and frontend can use the same class and is suggested by many for a backend dart framework, maybe my question was confusing.

Is there no way to call another service from inside an endpoint of my server? Like make an http call to get the json response from another service on the web?

**Comment by vlidholt** [comment]
@GeorgePagounis you can most certainly do this. Just use the http or dart:io package. :)

**Comment by GeorgePagounis** [comment]
@vlidholt Thank you very much! Apologies if it sounds stupid, but there were no tutorials or info regarding serverpod and this.

**Comment by vlidholt** [comment]
No problem at all, happy to help! :)
