### ISSUE TITLE
Internal server error. Call log id: 74, statusCode = 500

### ISSUE THREAD

**Issue by dongri727** [serverpod/serverpod#1373]
I have set up functions on multiple endpoints and the others are working fine, but only this getPrincipal is an error.
Please let me know how to deal with this.
I have confirmed that I am getting the keywords for get correctly.

The message that appears in Run
```bash
flutter: Current Country where it happened
flutter: {listPays: [France, Japan]}
flutter: [France, Japan]
flutter: fetch Principal
flutter: Failed call: principal.getPrincipal
flutter: ServerpodClientException: Internal server error. Call log id: 75, statusCode = 500
flutter: ServerpodClientException: Internal server error. Call log id: 75, statusCode = 500
```

Message that appears in terminal
```bash
METHOD CALL: principal.getPrincipal duration: 20ms numQueries: 0 authenticatedUser: null
type 'String' is not a subtype of type 'num?' in type cast
#0 SerializationManager.deserialize (package:serverpod_serialization/src/serialization.dart:57:20)
#1 Protocol.deserialize (package:acorn_server/src/generated/protocol.dart:1397:18)
#2 new Principal.fromJson (package:acorn_server/src/generated/principal.dart:32:32)
#3 Protocol.deserialize (package:acorn_server/src/generated/protocol.dart:1183:29)
#4 DatabaseConnection._formatTableRow (package:serverpod/src/database/database_connection.dart:239:45)
#5 DatabaseConnection.find (package:serverpod/src/database/database_connection.dart:178:18)
#6 Database.find (package:serverpod/src/database/database_connection.dart:60:12)
#7 PrincipalEndpoint.getPrincipal (package:acorn_server/src/endpoints/principal_endpoint.dart:29:12)

#8 EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)

#9 Server._handleRequest (package:serverpod/src/server/server.dart:243:18)
#10
```
Configure endpoints
```dart
Future> getPrincipal(Session session,
  {List? keywords}) async {
  print("Getting principal with keywords: $keywords");

  var whereClause;
  if (keywords != null && keywords.isNotEmpty) {
    for (var keyword in keywords) {
      if (whereClause == null) {
        whereClause = Principal.t.pays.like('%$keyword%'); 
      } else {
        whereClause = whereClause | Principal.t.pays.like('%$keyword%'); 
      }
    }
  
  } else {
    whereClause = Constant(true); 
  }
  

  return await Principal.find(
    session,
    where: whereClause, whereClause, whereClause (_) => whereClause, where
    orderBy: Principal.t.point,
  );
}
```

Setting up a table
```yaml
class: Principal Principal
table: principal
fields: principal
  period: String
  annee: double
  month: int
  day: int
  point: int
  affair: String String
  pays: String String
```

Setting flutter
```dart
Future<void>fetchPrincipal({List<String>? countries}) async {
  try {
    print(countries);
    _principal = await client.principal.getPrincipal(keywords: countries);
    print("Getting principal with keywords: $countries");
    notifyListeners();
  } on Exception catch (e) {
    debugPrint('$e');
  }
}
```

**Comment by Isakdl** [comment]
Hello @dongri727 !

First a little tip, you can create code blocks in github (markdown) by using triple backticks like this to get formatting: 

Example:
\```dart 
var name = 'Dongri';
\```

I have added this to your post already to make it easier to see what is going on :). 

So I can see two issues here, first the yaml seems to be formatted wrong, maybe you accidentally added the extra types in this post? 

 But from what I gather it should look like this:

```yaml
class: Principal
table: principal
fields: principal
  period: String
  annee: double
  month: int
  day: int
  point: int
  affair: String
  pays: String
```

The other issue that I believe is the cause of the error is in your endpoint definition the params keywords are typed as a List like so: `{List? keywords}`. If you change this to a list of strings instead, `{List<String>? keywords}` the serialization should understand what type you are expecting.

**Comment by dongri727** [comment]
We apologize for taking the time to look at this carefully. It was really stupid of me to put the code into the translation, and even more stupid of me not to check it.

I rechecked and redid the two places, but the result remained the same.
Please let me know what to do next, thank you.


```dart
class: Principal
table: principal
fields:
  period: String
  annee: double
  month: int
  day: int
  point: int
  affair: String
  pays: String
```

```dart
  Future<List<Principal>> getPrincipal(Session session,
      {List<String>? keywords}) async {
    print("Getting principal with keywords: $keywords");

    var whereClause;
    if (keywords != null && keywords.isNotEmpty) {
      for (var keyword in keywords) {
        if (whereClause == null) {
          whereClause = Principal.t.pays.like('%$keyword%');
        } else {
          whereClause = whereClause | Principal.t.pays.like('%$keyword%');
        }
      }
    } else {
      whereClause = Constant(true);
    }

    return await Principal.find(
      session,
      where: (_) => whereClause,
      orderBy: Principal.t.point, 
    );
  }
```

```dart
Future<void>fetchPrincipal({List<String>? countries}) async {
  try {
    print(countries);
    _principal = await client.principal.getPrincipal(keywords: countries);
    print("Getting principal with keywords: $countries");
    notifyListeners();
  } on Exception catch (e) {
    debugPrint('$e');
  }
}
```

flutter: {listPays: [France, Japan]}
flutter: [France, Japan]
flutter: fetch Principal
flutter: Failed call: principal.getPrincipal
flutter: ServerpodClientException: Internal server error. Call log id: 76, statusCode = 500

SERVERPOD version: 1.1.1, dart: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_arm64", time: 2023-09-17 22:21:52.854462Z
mode: development, role: monolith, logging: normal, serverId: default
Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082
METHOD CALL: pays.getPays duration: 11ms numQueries: 0 authenticatedUser: null
Getting principal with keywords: [France, Japan]
METHOD CALL: principal.getPrincipal duration: 14ms numQueries: 0 authenticatedUser: null
type 'String' is not a subtype of type 'num?' in type cast
#0      SerializationManager.deserialize (package:serverpod_serialization/src/serialization.dart:57:20)
#1      Protocol.deserialize (package:acorn_server/src/generated/protocol.dart:1397:18)
#2      new Principal.fromJson (package:acorn_server/src/generated/principal.dart:32:32)
#3      Protocol.deserialize (package:acorn_server/src/generated/protocol.dart:1183:29)
#4      DatabaseConnection._formatTableRow (package:serverpod/src/database/database_connection.dart:239:45)
#5      DatabaseConnection.find (package:serverpod/src/database/database_connection.dart:178:18)
<asynchronous suspension>
#6      Database.find (package:serverpod/src/database/database.dart:60:12)
<asynchronous suspension>
#7      PrincipalEndpoint.getPrincipal (package:acorn_server/src/endpoints/principal_endpoint.dart:29:12)
<asynchronous suspension>
#8      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)
<asynchronous suspension>
#9      Server._handleRequest (package:serverpod/src/server/server.dart:243:18)
<asynchronous suspension>

**Comment by dongri727** [comment]
Is it possible to delete the auto-generated file you pointed out and regenerate it?

**Comment by dongri727** [comment]
The following line is pointed out in #2: 

 annee:
          serializationManager.deserialize<double>(jsonSerialization['annee']),


annee is double in protocol, numerics in PostgreSQL, is there a problem?

**Comment by dongri727** [comment]
Where can I find "Call log id: 79 " ?

**Comment by dongri727** [comment]
I found the problem. front, the server side is double, while it was numeric in Database, I changed it to real and it is fixed. Thank you very much.
