### ISSUE TITLE
Optimise analyzer dependency resolver

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1377]
**Is your feature request related to a problem? Please describe.**
The analyzer uses an O(n^2)  algorithm to resolve dependencies in the protocol files, this is not a problem for smaller projects but could prove to be an issue for larger projects. 

We should refactor this to a more efficient solution that scales better.

**Comment by SandPod** [comment]
This was resolved as part of this PR: https://github.com/serverpod/serverpod/pull/3007
