### ISSUE TITLE
Code generator crashes on unknown types used in an Endpoint

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#1390]
**Describe the bug**
If you use some datatypes that are unknown to our parser the entire code generator crashes. 

Related issues: 
https://github.com/serverpod/serverpod/issues/1275
https://github.com/serverpod/serverpod/issues/1169

**Expected behavior**
Should give a clear error message for any times we don't happen to support.

**Comment by lukehutch** [comment]
This happens all the time, and it's very annoying, because it doesn't tell you what exactly the problem is.

I hope this can please be fixed soon!

**Comment by SandPod** [comment]
related: https://github.com/serverpod/serverpod/issues/1299
