### ISSUE TITLE
Better deserialization features for raw SQL queries

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1410]
**Is your feature request related to a problem? Please describe.**

The docs say you can execute raw SQL queries as follows:

> ### Executing raw queries
> Sometimes more advanced tasks need to be performed on the database. For those occasions, it's possible to run raw SQL queries on the database. Use the query method. A List<List<dynamic>> will be returned with rows and columns.
> 
> `var result = await session.db.query('SELECT * FROM mytable WHERE ...');`

I need to use this while I wait for all the new database query stuff to land.

However, by the looks of it, you end up with a 2D array (a list of lists of values). This has two issues:

1. The columns are not named, which makes the query brittle, since columns could become reordered, or a column inserted/deleted.
2. There is no way to deserialize a protocol object from these results.

**Describe the solution you'd like**

I would like to be able to get result values by table name and then column name, meaning the results should be in the form

```dart
List<Map<String, Map<String, dynamic>>>
```

The list has one entry per result row, then the middle map maps from table name to result row (for cases where you perform a join), then the innermost map maps from column name to value.

There would need to then be a `.fromMap` constructor on every protocol object, to construct an object instance from a `Map<String, dynamic>`.

Even better, the database connector could automatically deserialize objects from each table involved in a join, and simply map from the table name to the deserialized protocol object representing the row.

**Comment by Isakdl** [comment]
This is more or less how this works internally, when we are returning values but this method is not exposed currently. The .fromMap is basically the fromJson method on each protocol file. But I suppose making the mappedQuery public could make sense.

**Comment by lukehutch** [comment]
@Isakdl It does get more complicated with joins though. The whole reason I want to use this method is because I need some complex joins, and I want the protocol objects from the result row of each table in the join. It would be nice if the deserialization of all the relevant objects could be done automatically, either by parsing the join to figure out the order of result columns (might be a bit complex), or by ensuring the query fully specifies `table_name.column_name` for each column. This would require some work beyond just exposing `.fromMap`.

**Comment by Isakdl** [comment]
Well actually we have a generated method that does exactly this inside the `Protocol.dart` file. If you use it like this:

```dart
Protocol().deserialize(jsonMap);
```

But! the result from the mapped query method we have returns `Map<String, Map<String, dynamic>>` where the first `Map` represents the tables queried (the key is the table name), The second `Map` is the row. Here you would first have to stitch together a valid jsonMap for the protocol then send it to the method above.

**Comment by lukehutch** [comment]
@Isakdl thanks for exposing the mapped results. What do you mean by the following?

> Here you would first have to stitch together a valid jsonMap for the protocol then send it to the method above.

Since this functionality is likely to be needed by other Serverpod users, is there any chance you could please write the code for this too?

**Comment by lukehutch** [comment]
Also, converting the result of `mappedResultsQueryDangerously` into JSON just so that `Protocol().deserialize` can be called seems unnecessarily wasteful. Why not add a `Protocol().deserializeFromMap`?

Then a `reconstitutedResultsQueryDangerously` could be added, which calls `deserializeFromMap` for each table, and returns a simple `Map<String, dynamic>` that maps the table name to the object that is reconstituted from the map of column name to value.

**Comment by Isakdl** [comment]
This I think would be pretty hard to implement for any generic query. As the result will contain the same name as you are casting your columns too in your queries. You may omit columns we need to instantiate the classes etc. And in the end all this functionality is something we have (or are working on) for the generated ORM api. If you use the find method it will do all of this work for you already.

Hence I don't think we will add much value with this and it would be hard to get a reasonable solution in place.

I would say the goal is to have a good enough interface in the ORM that you do not need to make your own queries unless it is some very special thing. And if you have that special edge case you probably want more control anyway.

What you need here I would say should / will be implemented in the normal api.

**Comment by lukehutch** [comment]
OK. Do you have an idea of how long the new orm work will take, assuming no further unseen issues? I am blocked right now.
