### ISSUE TITLE
Chat example needs updating

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1419]
**Describe the bug**

I ran into several problems getting the chat example to work.

1. In `serverpod/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml`, the version of `intl` is 0.17.0, which is incompatible with latest `flutter_localizations`.
2. Even after installing the three tables required on [this page](https://github.com/serverpod/serverpod/blob/main/examples/chat/README.md), I got the error:
  ```
     WARNING: The database does not match the target database:
        - Table "serverpod_chat_message" is missing.
        - Table "serverpod_chat_read_message" is missing.
  ```
  I tried installing the tables using one of the SQL files in `migrations`, but then I got a warning that the table structure doesn't match the live database. The app runs now though, at least.
3. The documentation says the database password is `database_password`, but it's actually `postgres_password`.

Also, I'd like to add push notification support to the chat server, for clients that are offline. Does Serverpod have a push notification strategy planned?

**Comment by Isakdl** [comment]
1. Now fixed thank you @lukehutch !
2. Using the latest definition.sql or simply launching the server with the flag --apply-migrations will solve this.
3. Fixed in pr: https://github.com/serverpod/serverpod/pull/1639

Push notifications tracked here: https://github.com/serverpod/serverpod/issues/439

**Comment by lukehutch** [comment]
OK, so `tables.pgsql` is in fact gone.

How do I pull in all the database table definitions I need, from my own code (after `serverpod generate`), from Serverpod, and from any Serverpod modules?

**Comment by lukehutch** [comment]
I think you're saying `generated/migrations/<datetime>/definition.sql` takes the place of `tables.pgsql`, and that `definition.sql` is not incremental at all (it's not a migration), it's a snapshot of the table definition? I don't know how to select the highest datetime value in Bash. Can you please include a softlink in `migrations` called `latest` that points to the latest migration?

**Comment by Isakdl** [comment]
Yes correct, we have updated all the database stuff with the new migration system. The new documentation is deployed under next, the page on migration is here: https://docs.serverpod.dev/next/concepts/database/migrations

Project migration guide here: https://docs.serverpod.dev/next/upgrading/upgrade-to-one-point-two

Note that the new SQL file now also include all module and serverpod tables as well!

`definition.sql` is indeed a snapshot of the entire database structure at that point in time, while `migration.sql` describes the changes from the previous version to this one.

`generated/migration/migrations/serverpod/20*/definition.sql` is not the correct path anymore. The first implementation had all modules split but we opted to combine them into a single SQL file now. Meaning `generated/migration/migrations/<datetime>/definition.sql` is the correct path. 

You can add the flag `--apply-migrations` to run all migrations when starting the server. This will roll you forward from the previous applied migration to the latest, OR if the database has no previous migration will use the latest snapshot. 

In the project migration guide linked above we have instructions for how to move from a project that didn't use the migration system.

**Comment by lukehutch** [comment]
@Isakdl Thanks, I will respond over at #1645, since this issue is closed...
