### ISSUE TITLE
Add `columns` parameter to database `update` methods

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1422]
Since there is no `upsert` support yet (#232), perhaps a halfway-step could be added? It would be nice to be able to specify which specific fields need to be updated, without specifying a complete object:

**(1) `copyWith`:**

```dart
    await Account.update(session, account.copyWith(
      lastPing: DateTime.now().toUtc(),
    ));
```

**(2) `updateWith`:**

```dart
    await Account.updateWith(session, account,
      lastPing: DateTime.now().toUtc(),
    );
```

or maybe

```dart
    await Account.updateWith(session,
      where: (t) => t.id == account.id,
      lastPing: DateTime.now().toUtc(),
    );
```

**Comment by Isakdl** [comment]
`copyWith` also exists on all generated protocols if you use the main branch.

**Comment by lukehutch** [comment]
OK, great. I must have forked the main branch before you added support for `copyWith` (it's an enormous amount of work to rebase on new releases of main, because of the issue with generated files being checked in to git, so I'm stuck on an old version now...)

Should I leave this issue open, with the suggestion that `columns:` be added to the type-specific `update` methods?

**Comment by lukehutch** [comment]
@Isakdl In addition to my last question about whether `columns:` should be added to regular `update` methods, I have another idea: could this style of column specification be used to atomically decrement/increment a value in a row? For example:

```dart
await MyTable.incrementRowValue(userRow, column: Account.t.numLogins);
```

This would translate to

```
UPDATE MyTable SET numLogins = numLogins + 1 WHERE id = ${userRow.id};
```

There could be additional parameters for adding/subtracting more than 1, for example to adjust an account balance by a number of credits, and there could be a fixed minimum or maximum value (e.g. so that the balance doesn't go negative).

**Comment by Isakdl** [comment]
@lukehutch I think adding this to the generated update method makes sense too!

It's an interesting idea, but I think it is specific enough to be a standalone feature. Perhaps some thought is needed on the min/max values, it would be interesting if this could be added to the yaml file. Then we could also enforce these as restrictions in the database.

**Comment by lukehutch** [comment]
> @lukehutch I think adding this to the generated update method makes sense too!

OK, I updated the title of this issue to reflect this.

I opened #1464 for the new suggestion. Thanks!
