### ISSUE TITLE
Windows/Docker Get started sequence not clear in the official site, missing info

### ISSUE THREAD

**Issue by Am3rikA** [serverpod/serverpod#1424]
Hi, I'm a new user, I've struggled almost 3 days trying to figure why I cannot start the server on my windows machine with docker.
At the end the problem was, that on the official documentation page: https://docs.serverpod.dev/get-started ,it is missing a vital step to start the server and the docker container.
Official doc say:
  -cd mypod/mypod_server
  -docker compose up --build --detach
  -dart bin/main.dart
But correct sequence (windows host) is:
  -cd mypod/mypod_server
  - .\setup-tables.cmd (missing)
  -docker compose up --build --detach
  -dart bin/main.dart

**Comment by Isakdl** [comment]
Fixed in next documentation and with the new migration flow.
