### ISSUE TITLE
Code generation issue with subclassing of `Endpoint` class

### ISSUE THREAD

**Issue by b14cknc0d3** [serverpod/serverpod#1437]
**Describe the bug**
The code generation for Endpoints is not functioning as expected when I create a subclass of the Endpoint class.

**To Reproduce**

1.  create generic.dart
```
class GenericEndpoint<T extends TableRow> extends Endpoint {
  Future<T> create(Session s, T row) async {
    return await s.dbNext.insertRow<T>(row);
  }
}

```
2. create a `test_endpoint.dart` in `endpoints` folder
```
class TestGeneric extends GenericEndpoint<Product> {

}

```
3. run `serverpod generate`

**Expected behavior**
The Endpoint code generation should generate code for the `TestGeneric ` endpoint

**Comment by lukehutch** [comment]
See #912

**Comment by SandPod** [comment]
Closing as duplicate of: https://github.com/serverpod/serverpod/issues/912
