### ISSUE TITLE
VS Code instructions for Serverpod

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1459]
VS Code is by far the most popular way to edit Dart code (because the tooling is excellent).

I discovered that working with a Serverpod `_flutter` sub-project is kind of annoying when you're constantly changing and regenerating protocol files in the server, because VS Code only picks up changes to source files that are in the workspace, and the `_client` project is not in the same workspace as `_flutter` by default.

The trick is to create a multi-root workspace, with both the `_flutter` and `_client` subprojects included in a single workspace. Then the analysis server will cover both projects, and respond instantly to code changes in both.

https://code.visualstudio.com/docs/editor/multi-root-workspaces

The Serverpod docs should document this. Having stale files, and having to manually refresh the window or close/open Code, was an endless source of frustration before I came across the solution.

**Comment by vlidholt** [comment]
This would indeed be good to document. It usually works if I open the root project directory, rather than the `_flutter` directory. Also, if it happens, no need to restart VS Code, you can just restart the analyzer.

Cmd-Shift-P > "Dart: Restart Analysis Server"

**Comment by vlidholt** [comment]
This seems to work for me if I open the complete project. So I'm closing this issue.
