### ISSUE TITLE
Authentication should encrypt password before posting to server to not expose the raw password in the network request.

### ISSUE THREAD

**Issue by PhilipNell-258** [serverpod/serverpod#1463]
**Describe the bug**
Authentication should encrypt the password before posting to the server to avoid exposing the raw password in the network request.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Flutter app in Browser
2. Open the network tab on the console
3. Submit the username and password
4. The unencrypted password is sent as raw text over the network request

**Expected behaviour**
Password should be encrypted before posting and decrypted by the server for comparison

**Screenshots**
The screenshot is attached with the network request. I have masked the username and password used for my application.

**Serverpod versions**
 -  _CLI Version:_ 1.1.1
 - _Library version:_ 1.1.1

**Platform information**
Windows 11 Version 22H2
Chrome Browser

**Additional context**
![Screenshot 2023-10-18 092018](https://github.com/serverpod/serverpod/assets/83400730/54c3afea-e5b0-4e90-96ce-a227732994af)

**Comment by vlidholt** [comment]
When you deploy Serverpod using our Terraform scripts, all traffic (including keys) are encrypted over SSL. That being said, we are likely moving to pass authentication keys in the headers soon.

**Comment by PhilipNell-258** [comment]
Awesome, thanks for the quick response @vlidholt. This is excellent news to me.
