### ISSUE TITLE
Development of the client and server separately, is it possible?

### ISSUE THREAD

**Issue by habr** [serverpod/serverpod#1465]
Is it possible to develop the server part separately, and the client part separately? And then connect them, or are they inextricably linked and generated together? I have a ready-made client part developed earlier, can I connect it to the server part by simply linking it to the server part? I'm just afraid that due to automatic generation, I won't be able to combine my client part and the server

**Comment by Isakdl** [comment]
It depends on what you mean by `client`. If by `client` you mean a flutter app then yes you can absolutely develop them separately and even use an already existing app and connect it to a Serverpod backend.

`client` in the Serverpod world does not refer to the flutter app however but the generated client library. This package is 100% auto generated and you wouldn't normally write this by hand. This package creates functions and classes to help you make requests to the server and serialize / deserialize the data.

In your existing flutter app you would import this generated client and use that to make calls to the server.
