### ISSUE TITLE
Deserialization inefficiency

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1469]
**Describe the bug**

In `serialization.dart`, there is the following function:

```dart
  /// Deserialize the provided json [data] to an object of type [t] or [T].
  T deserialize<T>(dynamic data, [Type? t]) {
    t ??= T;

    //TODO: all the "dart native" types should be listed here
    if (t == int || t == getType<int?>()) {
      return data;
    } else if (t == double || t == getType<double?>()) {
      return (data as num?)?.toDouble() as T;
    } else if (t == String || t == getType<String?>()) {
      return data;
    } else if (t == bool || t == getType<bool?>()) {
      return data;
    } else if (t == DateTime) {
      return DateTime.parse(data).toUtc() as T;  // (*)
    } else if (t == getType<DateTime?>()) {
      return DateTime.tryParse(data ?? '')?.toUtc() as T;
    } else if (t == ByteData) {
      return (data as String).base64DecodedByteData()! as T;
    } else if (t == getType<ByteData?>()) {
      return (data as String?)?.base64DecodedByteData() as T;
    } else if (t == Duration) {
      return Duration(milliseconds: (data as int)) as T;
    } else if (t == getType<Duration?>()) {
      return data == null ? data : Duration(milliseconds: (data as int)) as T;
    } else if (t == UuidValue) {
      return UuidValue(data as String) as T;
    } else if (t == getType<UuidValue?>()) {
      return (data == null ? null : UuidValue(data as String)) as T;
    }
    throw FormatException('No deserialization found for type $t');
  }
```

If I enable the debugger to stop on all exceptions, then when deserializing a `null` value into a `DateTime?`-typed field, the debugger stops on the line marked `// (*)`, with `FormatException (FormatException: Invalid date format)`, because it tries to parse the empty string as a `DateTime`, and the empty string is never a valid `DateTime` string representation. `tryParse` throws the exception internally.

This is a time-consuming way to handle null values! Serialization efficiency affects everything in Serverpod, so this needs to be optimized.

The multi-`if`-statement needs a separate initial check, for efficiency:

```dart
    if (data == null) {
      return null;
    } else ...
```

**Comment by lukehutch** [comment]
@Isakdl thanks for the fix, but I just noticed there are other potentially nullable types in there too...

For example, for `Duration`, I imagine `(data as int)` could throw an exception if `data` is `null`...

Can you please check all the other clauses?

**Comment by Isakdl** [comment]
This could be an issue if you change a yaml file field from nullable to none-nullable, but still have nullable data in the database (that you didn't migrate), but in this situation, you will get a warning on startup. It could also become an issue if you make a manual rest request to your endpoint and set a non-nullable field to null. But this should/is guarded for in the API layer. 

You use the generated methods and your data in the database follows the restrictions in the model this parsing should never be an issue. 

We would have to throw here anyway if you get null for a non-nullable type. Ultimately, I don't think this is a problem and you should be safe.

**Comment by lukehutch** [comment]
Thanks for the clarification, that makes sense. The rest looks fine then. Thanks!
