### ISSUE TITLE
It is necessary to be able to send a raw string as a response from Serverpod

### ISSUE THREAD

**Issue by habr** [serverpod/serverpod#1474]
Hello!

I ran into a problem when I tried to send a raw string (to standard JSON) in response to a request in Serverpod. For example, I want to send a response in the form of {Hello 1}, but now Serverpod automatically adds double quotes, turning it into 
"{Hello 1}".

Can you provide a solution or the ability to send raw strings as a response without additional serialization?

Here is an example of my code:
```
import 'package:serverpod/serverpod.dart';

class ExampleEndpoint extends Endpoint {
  Future<String> hello(Session session, String name) async {
    return "Hello $name";
  }
}
```

I would appreciate any help or recommendations on this matter. Thanks!

**Comment by Isakdl** [comment]
I'm not sure I understand your problem, what is your use case?

**Comment by habr** [comment]
Thank you for your response.

I'm working on an integration where the external system expects a specific non-standard format of the JSON response. Instead of the typical serialized JSON with double quotes like "{Hello 1}", the system expects the response to be {Hello 1} without the surrounding quotes. This format is crucial for the integration to work correctly.

Using Serverpod, I haven't found a way to send a raw string response without it being automatically serialized with additional quotes. I was hoping there might be a way or a workaround to achieve this raw response format.

Any suggestions or guidance would be greatly appreciated.

**Comment by Isakdl** [comment]
I see! Okay in that case you should not use the `Endpoint` feature but the [web server](https://docs.serverpod.dev/concepts/webserver).

For your use-case you can extend the abstract `AbstractWidget` class and create your own class that can format the response in what ever way you need.

```dart
// lib/src/web/widgets/string_widget.dart
import 'package:serverpod/serverpod.dart';

class StringWidget extends AbstractWidget {
  @override
   toString() {
     return "{hello 1}";
  }
}
```

```dart
// lib/src/web/routes/my_route.dart
class MyRoute extends WidgetRoute {
  @override
  Future<Widget> build(Session session, HttpRequest request) async {
    return StringWidget();
  }
}
```

```dart
// lib/src/server.dart

void run(List<String> args) async {

  ...
  pod.webServer.addRoute(MyRoute(), '/'); // change the / to what ever path you like: /my/custom/response/path
  ...

}
```

Hope this helps!

**Comment by habr** [comment]
I thank the creators for their help and support!
