### ISSUE TITLE
GraphQL Spec Support

### ISSUE THREAD

**Issue by Edorin9** [serverpod/serverpod#1497]
**Is your feature request related to a problem? Please describe.**
I just started looking for dart backend frameworks to create a GraphQL web service and serverpod looks like a promising framework already.

**Describe the solution you'd like**
I'm thinking of the same implementation [angel3](https://github.com/dukefirehawk/angel) or [leto](https://github.com/juancastillo0/leto) has.

**Describe alternatives you've considered**
Can you suggest ways I could implement GQL in your current framework?

Edit: I'm not well-versed with GraphQL, I have only consumed such services and never made the services myself. I'm just creating this feature request as a suggestion specifically to your framework because I'm liking what I see in your work, and I would love to create a GraphQL service with it.

**Comment by vlidholt** [comment]
I'm closing this as it is tracked here: #14 

There seem to be a GraphQL library available on Pub. I haven't tried it out, but that could be a great starting point. At some time we are likely to natively support this natively in Serverpod.
