### ISSUE TITLE
Easy deployments with terraforming on Google Cloud

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#151]
Make it easy to deploy your Serverpod with terraforming on AWS.

- [x] Script for minimal setup.
- [x] Full-fledged setup.

**Comment by loic-hamdi** [comment]
Is this something that will be available anytime soon? (linked with [https://github.com/serverpod/serverpod/issues/156](https://github.com/serverpod/serverpod/issues/156))

**Comment by vlidholt** [comment]
Hi! We currently only support AWS, cannot give a date for when we can support GCP too yet.

**Comment by ajay-k07** [comment]
Draft requirements 


@vlidholt please add the requirements if anything is missed 

Terraform scripts for

- [ ]      1. Creating CloudSQL Instance (Postgres SQL)

- [ ]       2. Cloud Storage

- [ ]       3. Redis instance 

- [ ]       4. Load balancer

**Comment by vlidholt** [comment]
Completed, will be part of 1.1.
