### ISSUE TITLE
CI tests are being run twice

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1519]
**Describe the bug**

Some (or maybe all?) tests are being run twice in the CI config. I noticed this because the same tests were failing twice when they failed.

**Comment by SandPod** [comment]
Hey, are you sure? Could you provide a print screen?

The unit tests are run separate for each project in the monorepo, and the GitHub interface doesn't show the full filename path so might it just be the same configuration running for different projects?

<img width="374" alt="Screenshot 2023-11-02 at 08 26 59" src="https://github.com/serverpod/serverpod/assets/137198655/92e5d983-67a3-42cf-9e61-c4ab477e4ac4">
<img width="424" alt="Screenshot 2023-11-02 at 08 27 12" src="https://github.com/serverpod/serverpod/assets/137198655/2dd6b791-1ae2-438a-8098-7f6f17983e8a">

**Comment by lukehutch** [comment]
It looks like duplication to me -- these two screenshots are in the same run:

![image](https://github.com/serverpod/serverpod/assets/811305/4db13589-7d04-4be0-953e-28e52b8a2418)

![image](https://github.com/serverpod/serverpod/assets/811305/ae34f530-afdb-41b5-b232-fdde3f6bdfa1)

Job: https://github.com/serverpod/serverpod/actions/runs/6729403461/job/18290230136#step:4:1305

**Comment by SandPod** [comment]
Sorry, I misunderstood the issue.

But the tests in your image are actually different.
The first image tests the `client` and the second test tests the `server`. 

This is visible in the path of the test.

**Comment by lukehutch** [comment]
Apparently I can't read :-D  Sorry about that!
