### ISSUE TITLE
Authentication with phone number and password

### ISSUE THREAD

**Issue by Errechydy** [serverpod/serverpod#1520]
**Describe the solution you'd like**
We want to start using Serverpod where i work, but the auth system that we're using is phone number and password, I hope you consider adding that to the supported auth

I think adding phone number and password will not be that hard to implement, because it will be similar to email and password auth

**Describe alternatives you've considered**
I tried to use email and password auth as  a work around and send the phone number instead of the email and disable email verification but didn't work out

**Comment by Isakdl** [comment]
There is a PR from the community on this here: https://github.com/serverpod/serverpod/pull/1362. I haven't had the chance to deal with it yet but I agree, this is a nice feature to add!

**Comment by SandPod** [comment]
Issue created for this here: https://github.com/serverpod/serverpod/issues/2050

Closing this issue as it will be tracked there.
