### ISSUE TITLE
Can't use bool column as an expression

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1530]
Boolean column names can be specified directly as expression terms in SQL, but `ColumnBool` references can't be used in the Serverpod API without `.equals`.

This doesn't work:

```dart
    final endorsementsFuture = Endorsement.db.find(session,
        where: (t) =>
            t.otherUserId.equals(requestedUserId) &
            (Constant.bool(requestingOwnProfile) |
                t.approved |                                       // Runtime error
                t.userId.equals(requestingUserId)));
```

This is required:

```dart
    final endorsementsFuture = Endorsement.db.find(session,
        where: (t) =>
            t.otherUserId.equals(requestedUserId) &
            (Constant.bool(requestingOwnProfile) |
                t.approved.equals(true) |                           // Fixed
                t.userId.equals(requestingUserId)));
```

**Comment by Isakdl** [comment]
Cool idea! There are some problems getting this to work in practice as we have two different types that shouldn't be allowed to be used together, that is, `Columns` and `Expression`. Perhaps we can find a nice solution but it is not as straightforward as it might appear. 

With that said you have discovered a type issue here, the first example _should_ give a compile time error not just a runtime error. Having only a runtime error here is indeed not good.

**Comment by SandPod** [comment]
We now no longer accept dynamic as input to the `&` and `|`. Now we catch this as a compile time error instead of just a runtime error.
