### ISSUE TITLE
Need `.isDistinctFrom` / `.isNotDistinctFrom` query expression operators

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1552]
**Is your feature request related to a problem? Please describe.**

The SQL operator `"column" <> 'value'` fails to match any `NULL` value, even though `NULL` is not equal to `'value'`. You need to use `IS DISTINCT FROM` to cause not-equals matching to succeed against `NULL` values.

This is not supported in the query expression syntax right now. We need a `.isDistinctFrom` query operator. (The opposite is `.isNotDistinctFrom`, and this should be supported too.)

I guess the alternative is to automatically use `IS NOT DISTINCT FROM` for nullable types when calling `.equals`, and use `IS DISTINCT FROM` for nullable types when calling `.notEquals`...

**Comment by SandPod** [comment]
We actually already use your suggested solution. When calling `.notEquals` on a nullable column with a not `NULL` value we create an `IS DISTINCT FROM ` expression that also ensures that `NULL` values are matched.

Link to code: https://github.com/serverpod/serverpod/blob/534a76241c4349780b8cb39b86914e67784d4803/packages/serverpod/lib/src/database/columns.dart#L274C4-L274C4

Did you run into an issue while using the `.notEquals(..)` operator?

**Comment by lukehutch** [comment]
Oops, sorry, I missed that...

No, I was trying to write queries by hand in SQL and then translate them to the Serverpod API, and I needed `IS DISTINCT FROM` at one point. I wrongly assumed that `.equals` would just be the standard equals operator (and same for not equals). This should be clearly documented if it's not already.
