### ISSUE TITLE
Connection time out when using real device

### ISSUE THREAD

**Issue by Errechydy** [serverpod/serverpod#1568]
**Describe the bug**
Using a real device is not working, i edited the `ipAddress` of the `Client` to my computer IP but it didn't work. 
I tested `http://10.x.x.36:8080` on my device browser and it was reachable.
```
I/flutter (22341): Failed call: serverpod_auth.email.authenticate
I/flutter (22341): SocketException: HTTP connection timed out after 0:00:20.000000, host: 10.x.x.36, port: 8080
```

**To Reproduce**
1. I'm using Mac M1
2. Android real device
3. I got my computer IP address `ipconfig getifaddr en0`
5. Run start debugging
 
**Expected behavior**
The request should work without throwing time out exception (SocketException)

**Serverpod versions** - _Library version: 1.1.1 

**Platform information**
Macbook pro M1

**Additional context**
Debugging on MacOs desktop is working fine, so there are no problem with the code

**Comment by Isakdl** [comment]
Just to be sure. Have you have verified that you are on the same local network on both devices? Are you sure the network is not using some type of sandboxing for each device? 

A simple test is to use the network-sharing feature on your phone as this should not have any sandboxing between devices.

**Comment by Errechydy** [comment]
@Isakdl  That's why i tested the ipAddress on the browser, if that was the case then my computer ip address will not be accessible on my phone's browser too.

**Comment by Errechydy** [comment]
@Isakdl  You were right using network-sharing on my phone worked
