### ISSUE TITLE
`serverpod generate --watch` is not robust to even parameter name changes

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1576]
**Describe the bug**

Numerous kinds of changes are not picked up when running `serverpod generate --watch`. You have to kill `serverpod_cli` and then restart it.

One example of this is when you change the name of a parameter in an endpoint. The `endpoints.dart` that is generated does not pick up the new parameter name, and so it has a compile error.

Other examples are more extreme, for example adding or removing an endpoint function, renaming an endpoint, or even renaming a file.

**Comment by SandPod** [comment]
Thanks for reporting this!

This is clearly a bug so we will take a look at it.

**Comment by lukehutch** [comment]
Here's an example:

Endpoint code before the change:

![image](https://github.com/serverpod/serverpod/assets/811305/e360c63f-a2eb-45ef-9644-6fc5fc4edce8)

Generated code before the change:

![image](https://github.com/serverpod/serverpod/assets/811305/575d6756-16f1-4321-ae9f-144f3ff7b23a)

Endpoint code after the change: (`profileUserId` is changed to `targetUserId`):

![image](https://github.com/serverpod/serverpod/assets/811305/77dc1763-b69e-4e9f-bee9-b39d86f284d3)

Generated code after the change:

![image](https://github.com/serverpod/serverpod/assets/811305/aad69449-d392-42ae-90c6-55360c6ad0ea)

**Comment by lukehutch** [comment]
This is off-topic for this bug, but I just want to also add the general observation that the `serverpod generate --watch` capability needs to be made much more robust in general -- e.g. if an exception is thrown during generation, the generator (or the watch process) shouldn't just crash and die. `serverpod generate` is currently brittle in all sorts of ways (there are several other bugs I know have been reported already about exceptions being thrown during generation).

**Comment by vlidholt** [comment]
We should definitely do a better attempt at not crashing when using `--watch`. I feel like this would be reasonably easy to implement.

**Comment by SandPod** [comment]
This should be fixed now by these three PRs:
- https://github.com/serverpod/serverpod/pull/1634 - We no longer crash in generate watch mode. 
- https://github.com/serverpod/serverpod/pull/1655 - We now detect changes that influence endpoint files correctly.
- https://github.com/serverpod/serverpod/pull/1672 - We now don't try to create endpoints from invalid dart syntax.
