### ISSUE TITLE
Why is `serverpod generate` so slow?

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1586]
```
$ util/generate_all

✓ Generating code (5.1s)
✅ Done.

examples/chat/chat_server
✓ Generating code (4.3s)
✅ Done.

examples/auth_example/auth_example_server
✓ Generating code (4.3s)
✅ Done.

\nmodulename_server
✓ Generating code (4.2s)
✅ Done.

\nprojectname_server
✓ Generating code (4.2s)
✅ Done.

\nserverpod_auth_server
✓ Generating code (8.6s)
✅ Done.

\nserverpod_chat_server
✓ Generating code (8.3s)
✅ Done.

\ntests/serverpod_test_server
✓ Generating code (9.7s)
✅ Done.

\ntests/serverpod_test_module/serverpod_test_module_server
✓ Generating code (4.2s)
✅ Done.
```

That's 44.4 seconds total, or 155.5 billion cycles on my 3.5GHz processor. This seems like a ludicrous amount of work to do to generate a handful of files.

Is Dart really that slow? Or is there a hotspot somewhere in generation, where algorithmic complexity needs to be reduced by means of a hash lookup or similar?

**Comment by flutterindiadev** [comment]
That's a lot. I don't think dart is this slow, I am assuming some internal functions have some complex algorithms that are taking time. Surely we can have a look to reduce the complexity.

**Comment by Isakdl** [comment]
> Or is there a hotspot somewhere in generation, where algorithmic complexity needs to be reduced by means of a hash lookup or similar?

Yes you are right, we have some O(n<sup>2</sup>) algorithms that can be optimized in the resolver on our todo.

**Comment by lukehutch** [comment]
The Dart profiler's flame chart might help:

```console
dart run --pause-isolates-on-start --observe ../vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart generate --watch
```

![image](https://github.com/serverpod/serverpod/assets/811305/ebd2a4b2-08b7-445f-baed-e78a1e724e04)

**Comment by SandPod** [comment]
When working on the endpoint analyzer I noticed that a major part the generate command execute time is spent initializing the AnalysisContextCollection.

The reason the class is used is because we utilized darts analyzer to get information about imports that are used in the endpoint file. One option to speed this up could be to only use an AST tree for analyzing the endpoint, but then we need a different way to resolve the imports.

This is the explanation why when running `generate --watch` the first generate is always much slower than the subsequent ones.

**Comment by lukehutch** [comment]
Is this being done more than once? `serverpod generate` still shouldn't take 9 seconds for one project. The Dart compiler can initialize and compile thousands of classes much faster than that.

Is there a way to detect if VS Code's analyzer server is running, to then use that instead?

**Comment by SandPod** [comment]
The slow initial initialization is only done once for each invokation of  `serverpod generate` regardless of if `--watch` is applied or not.

Interesting idea, that might be worth exploring as well.

**Comment by vlidholt** [comment]
It's correct that it's the Dart analyzer that is slow. It's pretty much the same as when you are opening up a project in VS Code, it will take a few seconds until you get the syntax checks going. The solution is to use the `--watch` flag, as it will have all analyzer data loaded.

It's an unusual case to run generate on many packages at the same time. I'm guessing it's really only a problem for us, when running the tests. Typically you work on a single server (or module) at a time. Then `--watch` will be quick.

**Comment by lukehutch** [comment]
@vlidholt OK. I hope you can get `--watch` to work better then. It breaks all the time, and I have to kill it and restart it.
