### ISSUE TITLE
"Planning failed" during terraform apply

### ISSUE THREAD

**Issue by studioaugustus** [serverpod/serverpod#1614]
Any idea what's causing this issue? I've been following the documentation for deployment and also went along with the video to check for mistakes. Let me know if there's any extra information I can apply - I'm sure I missed something obvious.
Thanks!

---terminal output---

Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 14, in provider "aws":
│   14: provider "aws" {

**Comment by jason-downs** [comment]
@studioaugustus It would be helpful if you posted a quick follow-up on how you fixed this, assuming that it was fixed and that's why you closed the issue. I'm getting the same error now.

**Comment by studioaugustus** [comment]
@jason-downs this was a while ago, but this error happened to be something very basic with the correct access id and password being setup in the cli / terminal.
