### ISSUE TITLE
502 Bad Gateway Issue

### ISSUE THREAD

**Issue by studioaugustus** [serverpod/serverpod#1617]
Can't get past 502 bad gateway.
Followed all the steps outlined here: https://github.com/serverpod/serverpod/discussions/445

I have server and client using min of 2.19.6 sdk. Changed the two deployment scripts to use 2.19.6. EC2 instance is updated to 2.19.6. 
Git action is passing successfully (with 2 warnings) :

Git hub annotations (warnings):
[Deploy to AWS](https://github.com/studioaugustus/rpglms/actions/runs/7050554834/job/19192317692)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, aws-actions/configure-aws-credentials@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[Deploy to AWS](https://github.com/studioaugustus/rpglms/actions/runs/7050554834/job/19192317692#step:4:41)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Any ideas of what to try? Should I run terraform destroy and try again? Let me know what additional info I can provide. 
Thank you!

**Comment by jason-downs** [comment]
@studioaugustus How did you fix this?

**Comment by spaghettigus** [comment]
> @studioaugustus How did you fix this? 

My edit describes that some basic resets fixed this issue for me, but I've since moved onto my own terraform setup. Sorry I can't be of more help!
