### ISSUE TITLE
Serverpod CLI can leave Zombie processes if runtime is interrupted.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#1671]
**Describe the bug**
The Serverpod CLI utilized asynchronous processed when creating a new project for setting up docker containers and applying the initial database migration.

If the user (or as in our case, the test environment) aborts CLI command when a process has been started, they are left as zombie processes and are not cleaned up.

**To Reproduce**
1. Create a new project with verbose logging enabled. `serverpod create my_pod --verbose`
2. Kill the CLI process after the debug message `Applying migrations.` is displayed.
3. Observer that the Server output for applying migrations continues and that the docker containers is left running.

**Expected behavior**
The Serverpod CLI never leaves any running zombie processes.

**Serverpod versions**
 -  _CLI Version:_ latest main.

**Platform information**
macOS.

**Comment by yahu1031** [comment]
@SandPod Can you cross-check this one? I tried this, but the threads and processes are about to exit. They stay in activity only for 2–3 seconds and are dead or killed.

**Comment by SandPod** [comment]
This case it actually resolved since we have now removed applying migrations as part of the creation process with this PR: https://github.com/serverpod/serverpod/pull/1724.

I don't think there are any other processes that are started and left during the creation process.

Thanks for the ping on this @yahu1031
