### ISSUE TITLE
enable snake_case for table columns in serverpod 1.2

### ISSUE THREAD

**Issue by starklord** [serverpod/serverpod#1682]
Hi after updating from 1.1 to 1.2 seems like snake_case is not supported anymore for naming column tables in yaml files.
Is this now mandatory? or how can i reference columns that are named with snake_case format?

**Comment by SandPod** [comment]
Hey @starklord 👋 

Happy to read that you are trying out 1.2.

We added a restriction on this since the generated dart code gives an `info` message for snake_case formated fields.
We should match this so that we give an `info` message from our side to match Darts log level.
