### ISSUE TITLE
 dart bin/main.dart shows error

### ISSUE THREAD

**Issue by Bil0000** [serverpod/serverpod#1686]
**Describe the bug**
when I run  dart bin/main.dart it shows these errors:
 dart bin/main.dart
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/serverpod.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
library serverpod;
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/server.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
library server;
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/relic.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
export 'src/relic/web_server.dart';
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/database.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
library database;
^
../../../.pub-cache/hosted/pub.dev/serverpod_serialization-1.1.1/lib/serverpod_serialization.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
library serverpod_serialization;
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/src/util/http_request_extension.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
import 'dart:io';
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/src/generated/log_level.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/src/cloud_storage/cloud_storage.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
import 'dart:io';
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/src/cloud_storage/database_cloud_storage.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
import 'dart:math';
^
../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1/lib/protocol.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.17.
export 'src/generated/protocol.dart';
^
when I checked this path ../../../.pub-cache/hosted/pub.dev/serverpod-1.1.1 I saw that the version specfied in pubspe.yaml is environment:
  sdk: '>=2.19.0 <4.0.0'
I used the command serverpod create myprojectname

note: my flutter version:
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (10 days ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4

hope you change it as fast as possible

**Comment by Isakdl** [comment]
Hey @Bil0000 

This seems a little strange, your flutter version should work. In the next version of Serverpod we bumped the min required version to 3.0 perhaps this fixes the problem, you can try it out by changing the version too: `1.2.0-rc.1`.

**Comment by Bil0000** [comment]
Thanks @Isakdl 

i actually manged to make it work i found out that the problem was with my port thanks again.

**Comment by Isakdl** [comment]
I assume this is no an issue then? If I'm wrong please reopen.

**Comment by Bil0000** [comment]
the issue was with the port but then I figured out another problem that was related to serverpod_runtime_settings i had to initialize them manually for them to work which should be managed automatically, so hopefully serverpod will solve this in the next version coming out on 15/1/2024 which is after 10 from the time i posted this comment.
