### ISSUE TITLE
`Zoned exception` when receiving rogue requests with a blank URL

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1689]
**Describe the bug**

If you leave a Serverpod server up long enough, you'll get hit by a rogue request from someone scanning the Internet for open ports. Often these requests have a blank URL. This causes the following exception to be thrown:

```console
2023-12-21 02:40:39.200632Z Internal server error. Zoned exception.
RangeError (start): Invalid value: Only valid value is 0: 1
#0      RangeError.checkValidRange (dart:core/errors.dart:360:7)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:413:27)
#2      Server._handleUriCall (package:serverpod/src/server/server.dart:340:25)
#3      Server._handleRequest (package:serverpod/src/server/server.dart:269:24)
<asynchronous suspension>
```

The code in question is:

```dart
  Future<Result> _handleUriCall(
      Uri uri, String body, HttpRequest request) async {
    var path = uri.path.substring(1);            // ** Exception here **
    return endpoints.handleUriCall(this, path, uri, body, request);
  }
```

Before calling `uri.path`, if the path is empty, an exception result should be returned.

Or, alternatively, the problematic line could read

```dart
var path = uri.path;
while (path.startsWith('/')) {
  path = path.substring(1);
}
```

and then `endpoints.handleUriCall` should fail if no endpoint is specified (I haven't checked that code).

**Comment by SandPod** [comment]
Fixed by: https://github.com/serverpod/serverpod/pull/1780
