### ISSUE TITLE
Incorrect code in chat example server.dart

### ISSUE THREAD

**Issue by Disregard-Therest** [serverpod/serverpod#1690]
**Describe the bug**

**To Reproduce**
1. Go to chat example
2. Execute dart bin/main.dart --apply-migrations -r maintenance
3. See error

![image](https://github.com/serverpod/serverpod/assets/98102396/a4891ed8-85f3-405e-baa6-379aa9fbbabc)

To fix this just put populate database after pod.start()

![image](https://github.com/serverpod/serverpod/assets/98102396/e07fb02d-5e26-4043-a9a1-de4fda3f271a)

**Comment by Isakdl** [comment]
Are you getting this from a clean clone of the project?

**Comment by vlidholt** [comment]
I'll try this out later this week!
