### ISSUE TITLE
Please upgrade to latest version of firebase and  image_cropper for serverpod 1.2.0-rc.3 due to conflicts

### ISSUE THREAD

**Issue by rodjordan** [serverpod/serverpod#1693]
**Problem** 
When using firebase authentication in my flutter app (because I wanted to use the firebase_ui_auth SignInScreen() )
I get conflicts because of image_cropper and firebase 

**Solution**
Please update the following versions in serverpod because of package conflicts when using firebase authentication in my flutter app.
To work around this I am using a local version of "main branch" serverpod (but would prefer to use the hosted beta version instead)
Upgrading the image_cropper in serverpod_auth_shared_flutter (pub spec.yaml)  from 3.0.2 to 5.0.1 solves the problem.
Also upgrading the firebase core, auth, ui_auth solves an issue whereby I get AuthProvider conflicts.

 - serverpod_auth_shared_flutter  -  image_cropper 3.02 to 5.0.1 (needs a major version update, see conflict below)
 - serverpod_auth_firebase_flutter  - firebase - (needs a dart pub upgrade, causes conflicts in AuthProvider) 

**Details re image_cropper**
Because every version of serverpod_auth_shared_flutter from path depends on image_cropper ^3.0.2 which depends on
  image_cropper_platform_interface ^3.0.3, every version of serverpod_auth_shared_flutter from path requires
  image_cropper_platform_interface ^3.0.3.
And because image_cropper_platform_interface >=2.0.0-beta.1 <5.0.0 depends on http ^0.13.4, every version of
  serverpod_auth_shared_flutter from path requires http ^0.13.4.
And because desktop_webview_auth 0.0.14 depends on http ^1.0.0 and no versions of desktop_webview_auth match >0.0.14 <0.1.0,
  serverpod_auth_shared_flutter from path is incompatible with desktop_webview_auth ^0.0.14.
And because firebase_ui_oauth 1.4.15 depends on desktop_webview_auth ^0.0.14 and no versions of firebase_ui_oauth match >1.4.15
  <2.0.0, serverpod_auth_shared_flutter from path is incompatible with firebase_ui_oauth ^1.4.15.
And because firebase_ui_auth 1.11.0 depends on firebase_ui_oauth ^1.4.15 and no versions of firebase_ui_auth match >1.11.0 <2.0.0,
  serverpod_auth_shared_flutter from path is incompatible with firebase_ui_auth ^1.11.0.
So, because denver depends on both firebase_ui_auth ^1.11.0 and serverpod_auth_shared_flutter from path, version solving failed.

**Details Re AuthProvider issue**
This issue is the result of a naming collision caused by the recent update to the firebase_auth package, specifically version 4.13.0, which now exports an AuthProvider class  and is mentioned in the release notes https://pub.dev/packages/firebase_auth/changelog) dated November 9, 2023.
Exports AuthProvider from firebase_auth_interface ([#11470](https://github.com/firebase/flutterfire/issues/11470)). ([39881e7e](https://github.com/firebase/flutterfire/commit/39881e7e4671faa94b274d980aad81829e6e0bfc)

**Workaround**
Upgrade image_cropper in serverpod_auth_shared_flutter pubspec.yaml from 3.02 to 5.0.1
Upgrade firebase in  serverpod_auth_firebase_flutter  -to latest versions (needs a dart pub upgrade, causes conflicts in AuthProvider) 

Thanks for making serverpod great

**Comment by rodjordan** [comment]
I managed to resolve this by updating my pubspec.yaml as follows
This avoids the conflicts above related to AuthProvider.
Now I can use the hosted 1.2.0-rc.1 

 firebase_auth: '>=4.4.2 <4.13.0'

**Comment by rodjordan** [comment]
Resolved, sorry for the newbie Package dependency issue.
I hope it helps others who want to use firebase auth without package conflicts.

**Comment by rodjordan** [comment]
Because I want to use the latest version of Firebase (which I believe requires the latest version of image_cropper) I have currently the following overrides in place. I hope serverpod updates their pubspec.yaml files to the latest firebase and image_cropper soon.

Flutter app subspec.yaml file includes:

dependency_overrides:
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_ui_auth: ^1.12.0
  firebase_ui_oauth_google: ^1.2.16
  image_cropper: ^5.0.1

**Comment by SandPod** [comment]
This will be included in Serverpod 1.2.0. Thank for tor the repport!

**Comment by rodjordan** [comment]
And thank you for solving it.
I will close this issue when the 1.2.0 becomes visible in pub.dev later today.
Great response, team-Serverpod👍

**Comment by SandPod** [comment]
We usually close the issue as completed as soon as it is merged into main, but you can expect 1.2.0 to become visible later today.

**Comment by rodjordan** [comment]
Thanks
I have already tested the change in RC.4 and it's perfect. Many thanks for
your help.
Serverpod is awesome.
