### ISSUE TITLE
Query on JWT Support and Blacklisting Refresh Tokens in Serverpod

### ISSUE THREAD

**Issue by dhirajnikam** [serverpod/serverpod#1698]
I'm currently implementing authentication in my Serverpod application and am unsure about the support for JWT, specifically how to manage and blacklist refresh tokens.

I am looking for information or guidance on whether Serverpod has built-in support for JWT, including best practices for managing refresh tokens, particularly how to blacklist them effectively.

As an alternative, I've considered implementing a custom solution for JWT handling, but I would prefer to use native Serverpod features if they exist.

I am using Serverpod 1.1.1 . Any insights or documentation links regarding JWT implementation in this version would be highly appreciated.

**Comment by Isakdl** [comment]
Hey @dhirajnikam currently Serverpod does not use JWT tokens for authentication. But we have the authentication module that is quite convenient to get auth into your app.

See: 
https://docs.serverpod.dev/concepts/authentication/setup
https://docs.serverpod.dev/tutorials/authentication

**Comment by SandPod** [comment]
Closing this issue in favour of https://github.com/serverpod/serverpod/issues/1720 and https://github.com/serverpod/serverpod/issues/2113
