### ISSUE TITLE
Tried to signup with Email Auth ('serverpod_email_auth') Table not generated

### ISSUE THREAD

**Issue by anandsubbu007** [serverpod/serverpod#170]
```
SERVERPOD version: 0.9.7 mode: development
Insights listening on port 8281
Server id 0 listening on port 8280
METHOD CALL: serverpod_auth.email.createAccountRequest duration: 70ms numQueries: 1 authenticatedUser: null
METHOD CALL: serverpod_auth.status.getUserInfo duration: 3ms numQueries: 0 authenticatedUser: null
METHOD CALL: serverpod_auth.email.authenticate duration: 10ms numQueries: 1 authenticatedUser: null
PostgreSQLSeverity.error 42P01: relation "serverpod_email_auth" does not exist 
package:postgres/src/connection.dart 453:18                            _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 427:7                             _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart 482:22                            _PostgreSQLExecutionContextMixin.mappedResultsQuery
package:serverpod_postgres_pool/postgres_pool.dart 750:23              _PgExecutionContextWrapper.mappedResultsQuery.<fn> 
package:serverpod_postgres_pool/postgres_pool.dart 678:27              _PgExecutionContextWrapper._run
package:serverpod_postgres_pool/postgres_pool.dart 749:12              _PgExecutionContextWrapper.mappedResultsQuery      
package:serverpod_postgres_pool/postgres_pool.dart 614:16              PgPool.mappedResultsQuery.<fn>
package:serverpod_postgres_pool/postgres_pool.dart 319:22              PgPool.run.<fn>.<fn>
package:serverpod_postgres_pool/postgres_pool.dart 418:27              PgPool._useOrCreate
package:serverpod_postgres_pool/postgres_pool.dart 390:14              PgPool._withConnection.<fn>
package:executor/src/executor_impl.dart 61:19                          _Executor.scheduleTask
package:serverpod_postgres_pool/postgres_pool.dart 318:18              PgPool.run.<fn>
package:retry/retry.dart 131:16                                        RetryOptions.retry
package:serverpod_postgres_pool/postgres_pool.dart 316:14              PgPool.run
package:serverpod/src/database/database_connection.dart 171:20         DatabaseConnection.find
package:serverpod/src/database/database_connection.dart 199:18         DatabaseConnection.findSingleRow
package:serverpod/src/database/database.dart 86:12                     Database.findSingleRow
package:serverpod_auth_server/src/endpoints/email_endpoint.dart 25:17  EmailEndpoint.authenticate
package:serverpod/src/server/endpoint_dispatch.dart 115:20             EndpointDispatch.handleUriCall
package:serverpod/src/server/server.dart 220:18                        Server._handleRequest
===== asynchronous gap ===========================
package:serverpod_postgres_pool/postgres_pool.dart 318:18              PgPool.run.<fn>
package:retry/retry.dart 131:16                                        RetryOptions.retry
package:serverpod_postgres_pool/postgres_pool.dart 316:14              PgPool.run
package:serverpod/src/database/database_connection.dart 171:20         DatabaseConnection.find
package:serverpod/src/database/database_connection.dart 199:18         DatabaseConnection.findSingleRow
package:serverpod/src/database/database.dart 86:12                     Database.findSingleRow
package:serverpod_auth_server/src/endpoints/email_endpoint.dart 25:17  EmailEndpoint.authenticate
package:serverpod/src/server/endpoint_dispatch.dart 115:20             EndpointDispatch.handleUriCall
package:serverpod/src/server/server.dart 220:18                        Server._handleRequest

DEBUG: authenticate anandsubbu7@gmail.com / 123456777
METHOD CALL: serverpod_auth.status.getUserInfo duration: 0ms numQueries: 0 authenticatedUser: null
```

**Comment by TechDockDev** [comment]
I am also getting same Issue 
2022-05-11 20:09:35.232 UTC [103] ERROR:  relation "example" does not exist at character 13

2022-05-11 20:09:35.232 UTC [103] STATEMENT:  INSERT INTO example ("name", "data") VALUES ('Serverpod corp.', 90) RETURNING id

**Comment by vlidholt** [comment]
This should be added to the documentation.

When you add a module, you manually need to add its database tables to your database. The queries you need to run are located here for the authentication module:

https://github.com/serverpod/serverpod/blob/main/modules/serverpod_auth/serverpod_auth_server/generated/tables.pgsql

**Comment by anandsubbu007** [comment]
> This should be added to the documentation.
> 
> When you add a module, you manually need to add its database tables to your database. The queries you need to run are located here for the authentication module:
> 
> https://github.com/serverpod/serverpod/blob/main/modules/serverpod_auth/serverpod_auth_server/generated/tables.pgsql

also please mention to use only lowercase string for table name

**Comment by SriRam-Macha** [comment]
Hey even after flowing the above steps. The response from the server is always failed when I try to login after create an account.

**Comment by vlidholt** [comment]
@SriRam-Macha, can you describe a bit more in detail where you get stuck or what sort of error message you are getting? It's very hard to help otherwise. :)

**Comment by SriRam-Macha** [comment]
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/53489400/202795224-799c4fc1-c5c9-4efb-a658-1d2c5bc8683e.png">
the above picture has the response i get after trying to login to the user account i just created.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/53489400/202795394-44d40093-73ef-48e6-a547-88d339caab88.png">
the above picture is from postico I have add the tables as described in the above mentions

<img width="405" alt="image" src="https://user-images.githubusercontent.com/53489400/202795613-1a8aa29c-ae18-4a97-bff1-fed7f5df6fb1.png">
I am using the button widget provided with the pacakge
<img width="359" alt="image" src="https://user-images.githubusercontent.com/53489400/202795737-0507da40-cc02-4e79-b412-a661272b5feb.png">

If there is any more information needed please let me know.

**Comment by vlidholt** [comment]
I'll be going through the whole email authentication flow and updating the documentation in the next few days.

**Comment by SriRam-Macha** [comment]
Ok will be waiting and wanted to ask one more thing
- will Serverpod 1.0 be released in this year?

**Comment by vlidholt** [comment]
@SriRam-Macha, yes, it will be released in the next few weeks most likely. The next version will be a release candidate. So I'm going over all documentation, examples, etc to make sure that everything is up to date and working.

**Comment by SriRam-Macha** [comment]
That's really great. Looking forward towards it.

**Comment by yahu1031** [comment]
@vlidholt can you open up this ticket if this isn't fixed yet.

**Comment by vlidholt** [comment]
I tried this in the example, and it works for me as far as I can tell:
https://github.com/serverpod/serverpod/tree/main/examples/chat
