### ISSUE TITLE
Database Migration Issue: Long Class Names with Object Relations

### ISSUE THREAD

**Issue by freppps** [serverpod/serverpod#1708]
**Describe the bug**
I am currently evaluating Serverpod as a potential backend solution for my project, but I've encountered a potential bug.

When generating migrations for classes with long class names using object relations, the resultant column name seems to exceed PostgreSQL's maximum length limit, leading to its truncation.

Due to this mismatch in column names, a warning is issued: '- Table 'user_note_with_a_long_name' is not like the target database.' Furthermore, this discrepancy results in the inability to perform read operations on the affected tables. Im still figuring out how to create/update/delete rows with one-to-many implicit object relation, therefore the manual db modification.

**To Reproduce**
1. Create a fresh project `serverpod create notes`
2. Add the below protocol definitions
3. Run `serverpod generate` and `serverpod create-migration`
4. Start docker containers `docker compose up --build --detach`
5. Apply migration `dart run bin/main.dart --role maintenance --apply-migrations`
6. Manually add UserNoteCollectionWithALongName to the db
7. Manually add UserNoteWithALongName to the db with using the id from step 6
8. Start server `dart bin/main.dart`
9. Call the ExampleEndpoint.getCollections - Throws `type 'Null' is not a subtype of type 'int'`

**Expected behavior**
Not sure about the desired behaviour but a suggestions would be an error to be produced when running `serverpod generate` or `serverpod create-migration`, that column exceeds the maximum length pointing the user to set the column name explicitly (when its been implemented https://github.com/serverpod/serverpod/issues/1238)

**Serverpod versions**
 -  _CLI Version: Serverpod version: 1.2.0-rc.1
 - _Library version: serverpod: 1.2.0-rc.1

**Platform information**
MacOS

**Protocol definitions**
```
class: UserNoteCollectionWithALongName
table: user_note_collection_with_a_long_name
fields:
  name: String
  notes: List<UserNoteWithALongName>?, relation
```

```
class: UserNoteWithALongName
table: user_note_with_a_long_name
fields:
  name: String
```

**Endpoint**

```
class ExampleEndpoint extends Endpoint {
  Future<List<UserNoteCollectionWithALongName>> getCollections(
      Session session) {
    return UserNoteCollectionWithALongName.db.find(session,
        include: UserNoteCollectionWithALongName.include(
            notes: UserNoteWithALongName.includeList()));
  }
}
```

**Comment by SandPod** [comment]
Hey @freppps 👋 

Thanks for reporting and providing a repro for this. We will look into it.

Also, happy to hear you are evaluating Serverpod as a potential backend for your projekt.

**Comment by freppps** [comment]
Added some additional details to my initial post, I realised that my testing only covered read operations, and I have not yet explored create, update, or delete functionalities.
Not sure about the correct procedure for performing those that would establish the necessary relations. I guess i'm waiting for https://github.com/serverpod/serverpod/issues/1343

Also great work everyone involved in Serverpod, ive been following for a while and i like what im seeing :)

**Comment by freppps** [comment]
Performed additional tests using shorter class names, and a similar problem arises with properties intended for relationships when include relational data. Create a simple example below for demonstration.

Accessing the below endpoint results in the error type 'Null' is not a subtype of type 'int' at UserNoteCollection.db.findById. 

It appears that the returned column name is cut short and therefore omitted in the _queryIncludedLists function before JSON parsing. The column name in the database appears correct to me.
![image](https://github.com/serverpod/serverpod/assets/41991003/f637cd8d-7172-4449-a7b4-840341a37084)

Changing userNotesPropertyName to a shorter name, such as userNotes, makes the code function correctly.

Error message:
```
METHOD CALL: example.createCollection duration: 110758ms numQueries: 0 authenticatedUser: null
type 'Null' is not a subtype of type 'int'
#0      mapListToQueryById.<anonymous closure> (package:serverpod/src/database/database_result.dart:68:9)
#1      ListBase.fold (dart:collection/list.dart:202:22)
#2      mapListToQueryById (package:serverpod/src/database/database_result.dart:62:34)
#3      DatabaseConnection._queryIncludedLists (package:serverpod/src/database/database_connection.dart:576:38)
<asynchronous suspension>
#4      DatabaseConnection._deserializedMappedQuery (package:serverpod/src/database/database_connection.dart:429:33)
<asynchronous suspension>
#5      DatabaseConnection.findFirstRow (package:serverpod/src/database/database_connection.dart:92:16)
<asynchronous suspension>
#6      DatabaseConnection.findById (package:serverpod/src/database/database_connection.dart:117:12)
<asynchronous suspension>
#7      ExampleEndpoint.createCollection (package:notes_server/src/endpoints/example_endpoint.dart:42:30)
<asynchronous suspension>
#8      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:120:20)
<asynchronous suspension>
#9      Server._handleRequest (package:serverpod/src/server/server.dart:269:18)
<asynchronous suspension>
```


**Protocol definitions**

```
class: UserNoteCollection
table: user_note_collections
fields:
  name: String
  userNotesPropertyName: List<UserNote>?, relation
```

```
class: UserNote
table: user_note
fields:
  name: String
```

**Endpoint**

```
  Future<UserNoteCollection> createCollection(Session session, UserNoteCollection collection) async {
    final insertedCollection = await UserNoteCollection.db.insertRow(session, collection);

    final notes = collection.userNotesPropertyName;
    var insertedNotes = <UserNote>[];
    if (notes != null && notes.isNotEmpty) {
      insertedNotes = await UserNote.db.insert(session, notes);
      await UserNoteCollection.db.attach.userNotesPropertyName(session, insertedCollection, insertedNotes);
    }

    final returnCollection = await UserNoteCollection.db.findById(
      session,
      insertedCollection.id!,
      include: UserNoteCollection.include(
        userNotesPropertyName: UserNote.includeList(),
      ),
    );

    return returnCollection!;
  }
```

**Comment by SandPod** [comment]
We now truncate all aliases generated by the framework when performing queries.

@freppps thanks for the great bug report and repro steps.

Please feel free to reach out if you encounter any issues with this again.

**Comment by freppps** [comment]
Great news, thank you for the update! I'll be sure to give it a try as soon as rc4 is available.
