### ISSUE TITLE
Error when trying to generate table

### ISSUE THREAD

**Issue by anandsubbu007** [serverpod/serverpod#171]
when run

Get-Content .\generated\tables.pgsql | docker-compose run -T postgres env PGPASSWORD="aaaaaaaaaaaaaaaaaaaaaaaaaaaa" psql -h postgres -U postgres -d subbu_shop

```
ERROR:  data type json has no default operator class for access method "btree"
HINT:  You must specify an operator class for the index or define a default operator class for the data type.
```

**Comment by vlidholt** [comment]
Can you please describe in more detail the issue that you are facing and what the steps are to reproduce this issue?

**Comment by anandsubbu007** [comment]
when i define tableclassmodel in index this error throws. 
then only understand that data will stored as json. 
after removed that classmodel name from index. there is no issue.
 
i think that defining classmodel in table will create link to that id. 

> error in defining in yaml file

**Comment by anandsubbu007** [comment]
IN MAC

when i try to run
```
docker-compose run postgres env PGPASSWORD="aaaaaaaaaaaaaaaaaa" psql -h postgres -U postgres -d subbu_pod > generated/tables.pgsql
```

Errror:
> the input device is not a TTY


How to generate table?

is there way to view postgres table?

**Comment by anandsubbu007** [comment]
After added "-T" after run Table generated.

```
docker-compose run -T postgres env PGPASSWORD="aaaaaaaaaaaaaaaaaa" psql -h postgres -U postgres -d subbu_pod > generated/tables.pgsql
```
