### ISSUE TITLE
Relation link between tables (primary & foreign key).

### ISSUE THREAD

**Issue by anandsubbu007** [serverpod/serverpod#172]
is it possible to create relation between two tables?
i tried to define other tableclass inside yaml file but i think it is stored as json. not creating link. am i right?

if wrong...!

how to define link between tables in yaml file.

**Comment by vlidholt** [comment]
Currently not possible, but this is on the todo-list

**Comment by vlidholt** [comment]
The pattern right now is to declare the relation in the yaml file and add the `api` flag. When you fetch the table from the database you can then make an extra database request and attach it to the object.

```yaml
class: MyData
fields:
  objects: List<OtherObject>?, api
```
