### ISSUE TITLE
Copying Dart runtime in Dockerfile results in "cannot copy to non-directory" error

### ISSUE THREAD

**Issue by adityapandeyz** [serverpod/serverpod#1729]
### Discussed in https://github.com/serverpod/serverpod/discussions/1712

<div type='discussions-op-text'>

<sup>Originally posted by **adityapandeyz** January  5, 2024</sup>
Issue Description:

When building the Docker image using the provided Dockerfile, an error occurs during the COPY operation from the build stage to the final stage. The error message indicates that there is an attempt to copy to a non-directory.

Steps to Reproduce:

1. Clone the repository.
2. Navigate to the directory containing the Dockerfile.
3. Run the docker build -t serverpod-app . command.

Expected Behavior:

The Docker image should be built successfully without any errors.

Actual Behavior:

The build process fails with the following error message:

`ERROR: failed to solve: cannot copy to non-directory: /var/lib/docker/overlay2/qeimp06mtt16u6pl5hph5zvdw/merged/lib64`

Dockerfile Section Causing the Issue:

`COPY --from=build /runtime/ /app/`

![image](https://github.com/serverpod/serverpod/assets/40023090/23da50f3-3af2-4b15-b17b-fa80e03934f9)

Complete dockerfile:

```
FROM dart:stable AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM busybox

ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

# COPY --from=build /runtime/ /

COPY --from=build /runtime/ /app/
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/generated/ generated/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
```

</div>

**Comment by ewann** [comment]
I also just ran into this issue when using github actions, though interestingly I wasn't experiencing the issue locally.

In my case I appear to have been able to stay a bit closer to the original multi stage approach, using:

```
FROM dart:3.0 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM busybox

ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

# COPY --from=build /runtime/ /
COPY --from=build /runtime/ /etc/ /etc
COPY --from=build /runtime/ /lib/ /lib
COPY --from=build /runtime/ /usr/ /usr
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
```

**Comment by ewann** [comment]
similar issue in: https://github.com/serverpod/serverpod/discussions/1785

**Comment by ewann** [comment]
Seems also:
https://github.com/serverpod/serverpod/issues/1101
https://github.com/serverpod/serverpod/issues/882
related, both having a (same in both) slightly different proposed solution.

**Comment by Isakdl** [comment]
> I also just ran into this issue when using github actions, though interestingly I wasn't experiencing the issue locally.
> 
> In my case I appear to have been able to stay a bit closer to the original multi stage approach, using:
> 
> ```
> FROM dart:3.0 AS build
> 
> WORKDIR /app
> COPY . .
> 
> RUN dart pub get
> RUN dart compile exe bin/main.dart -o bin/main
> 
> FROM busybox
> 
> ENV runmode=development
> ENV serverid=default
> ENV logging=normal
> ENV role=monolith
> 
> # COPY --from=build /runtime/ /
> COPY --from=build /runtime/ /etc/ /etc
> COPY --from=build /runtime/ /lib/ /lib
> COPY --from=build /runtime/ /usr/ /usr
> COPY --from=build /app/bin/main /app/bin/main
> COPY --from=build /app/config/ config/
> COPY --from=build /app/web/ web/
> 
> EXPOSE 8080
> EXPOSE 8081
> EXPOSE 8082
> 
> CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
> ```

@ewann FYI we recently made a fix in the docker file as sometimes the dart version and the busybox version are not compatible, so we pinned the versions in the file.

Here is the current checked in docker file and it should work:

```docker
# If you update the dart version, make sure the image is
# compatible with the busybox image.
FROM dart:3.2.5 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

# If you update the busybox version, make sure the image is
# compatible with the dart image.
FROM busybox:1.36.1-glibc

ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/ /
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
```

**Comment by ewann** [comment]
@Isakdl thanks for sharing that, though I had found the other commit about dart/busybox versions :)

this issue appears to have been opened for a different dockerfile issue though, specifically:

```
# COPY --from=build /runtime/ /
COPY --from=build /runtime/ /etc/ /etc
COPY --from=build /runtime/ /lib/ /lib
COPY --from=build /runtime/ /usr/ /usr
```

and it appears the current checked in version doesn't appear to address it - at least for some environments / images (including github actions) the build fails here as shown in the screenshot from OP

I linked the additional issues as I see at least two approaches using multistage builds, and I'm not 100% sure the exact set of source locations that should be included if `/runtime/ /` cannot be used

**Comment by vlidholt** [comment]
@Isakdl fixed?

**Comment by Isakdl** [comment]
@theindieduo I would recommend against your solution as you are not ahead of time compiling the server. This means your performance will be worse. You are also copying over and storing all the source code and all other files in your project which means the container will be much larger than necessary, (slower download speeds, more storage space needed).

**Comment by theindieduo** [comment]
@Isakdl  Thanks for the info 

I tried the dockerfile you mentioned in [comment above](https://github.com/serverpod/serverpod/issues/1729#issuecomment-1918811717) and getting the following error:



`***14 [stage-1 2/5] COPY --from=build /runtime/ /
***14 ERROR: cannot copy to non-directory: /var/lib/docker/overlay2/xw26gux15z981ys04ls1jqlvv/merged/lib64
------
 > [stage-1 2/5] COPY --from=build /runtime/ /:
------
Dockerfile:20
--------------------
  18 |     ENV role=monolith
  19 |     
  20 | >>> COPY --from=build /runtime/ /
  21 |     COPY --from=build /app/bin/main /app/bin/main
  22 |     COPY --from=build /app/config/ config/ 
--------------------
ERROR: failed to solve: cannot copy to non-directory: /var/lib/docker/overlay2/xw26gux15z981ys04ls1jqlvv/merged/lib64
Error: ***[error]Process completed with exit code 1.`


is it ok to try the approach @ewann  has mentioned? link [here](https://github.com/serverpod/serverpod/issues/1729#issuecomment-1918827610)

Some background: I am a pure front end dev and have very little exposure to docker/gcp things. I rely on issues/discussion on serverpod. I am trying to use serverpod for the first time, discoverd it a week back and its integration with flutter was so compelling that I had to try it.

**Comment by Isakdl** [comment]
@theindieduo I took some time and dived into this problem.

Turns out the issue here is when building on x86 architecture, (worked fine on ARM). There was a conflict when copying some files that caused the build to fail.

Anyway I have a PR up for the template that will get merged soon.

You can use this Dockerfile:
```Dockerfile
FROM dart:3.2.5 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/server

FROM scratch

COPY --from=build /runtime/ /
COPY --from=build /app/bin/server server
COPY --from=build /app/config/ config/
COPY --from=build /app/web/ web/


EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

# The default flags used when starting the server, can be manually overridden by passing flags to the docker run command
ENTRYPOINT ["./server", "--mode=production", "--server-id=default", "--logging=normal", "--role=monolith"]

```
