### ISSUE TITLE
Deps need updating

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1749]
`serverpod_auth_shared_flutter` 1.2.0-rc.1 depends upon `image_cropper` 3.0.3 (latest version is 5.0.1), which depends upon `http` version 0.13.4 (latest version is 1.1.2).

This is an old version of `http`, which is a very commonly used package, so it can be difficult to use Serverpod with other packages because of this transitive dependency.

The latest version of `http` depended upon by `image_cropper` is `^1.0.0`. Can you please upgrade `serverpod_auth_shared_flutter` to be compatible with this?

In general, it would be worth checking for upgraded dependencies every month or so, in all the Serverpod packages and modules, because I keep running into issues like this of old dependencies being used. (I think this is the third time I have submitted a bug report because a dependency is old, and that blocks me from using another package that I need.)

**Comment by SandPod** [comment]
Upgrade for these packages will be included in 1.2.

We will aim to have more steadily releases going forward which should help us keep dependencies up to date.

**Comment by lukehutch** [comment]
Thanks. Maybe `generate_all` should do a `pub upgrade`, not just `pub get`?

**Comment by SandPod** [comment]
Yeah, good suggestion. We can explore that.

I think it would also be neat if we could get dependabot. That way we get the information about updates pushed to us.
