### ISSUE TITLE
The "--mode" parameter is only available for "create-repair-migration" and not for "create-migration"  documentation issue?

### ISSUE THREAD

**Issue by rodjordan** [serverpod/serverpod#1762]
When running  `serverpod create-migration --mode production` the following error is produced:
Example above taken from 1.2.0 documentation .

Could not find an option named "mode".

Usage: serverpod create-migration [arguments]
-h, --help     Print this usage information.
-f, --force    Creates the migration even if there are warnings or information that may be destroyed.
-t, --tag      Add a tag to the revision to easier identify it.

CLI Version 1.2.0
Platform: macOS

**Comment by Isakdl** [comment]
Yeah this needs better documentation I think. the `create-migration` command will never look at the real database and therefor needs no mode flag. It creates the migration based on the previous migrations and the changes in the model yaml files.

**Comment by rodjordan** [comment]
You just need to correct the docs in the repair-migration section then you can close this.

- From:  $ serverpod create-migration --mode production
- To:  $ serverpod create-**repair**-migration --mode production
