### ISSUE TITLE
 failed to calculate checksum: 1.2 docker file not working

### ISSUE THREAD

**Issue by zezo357** [serverpod/serverpod#1763]
**Describe the bug**
running the docker file after creating the project gives me this error 
```
failed to solve: failed to compute cache key: failed to calculate checksum of ref f5d893ad-7e0d-4953-8244-c7673ad60a38::0gg7a3am9ephd0n3e69hv85wh: "/app/generated": not found
```
**To Reproduce**
1. Create project using `serverpod create test`
2. CD to server directory 
3. Run docker compose up

**Expected behavior**
it should run server pod in docker 

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling.
 - Serverpod version: 1.2.0
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

**Platform information**
i am running this on macos

**Additional context**
commenting this line `COPY --from=build /app/generated/ generated/` builds the container but i dont know what i am missing by commenting the line

**Comment by SandPod** [comment]
@zezo357 Thanks for the report, we will fix this ASAP.

As a workaround it is fine to just comment out that line. It shouldn't make a difference for the final container. The fix will be to remove it.

**Comment by armanhadifatah** [comment]
Also I faced same problem then after commenting that line then i got this 

```
wane_serverpod_server-app-1       | /bin/sh: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /bin/sh)
wane_serverpod_server-app-1 exited with code 1
```

**Comment by armanhadifatah** [comment]
I change the busybox to debian:bullseye-slim that error solved but i got new error 

```
wane_serverpod_server-postgres-1  | 2024-01-19 18:52:04.224 UTC [71] STATEMENT:  INSERT INTO "serverpod_runtime_settings" ("logSettings", "logSettingsOverrides", "logServiceCalls", "logMalformedCalls") VALUES ('{"logLevel":1,"logAllSessions":false,"logAllQueries":false,"logSlowSessions":true,"logStreamingSessionsContinuously":true,"logSlowQueries":true,"logFailedSessions":true,"logFailedQueries":true,"slowSessionDuration":1.0,"slowQueryDuration":1.0}', '[]', FALSE, FALSE) RETURNING *
wane_serverpod_server-app-1       | Failed to store runtime settings. PostgreSQLSeverity.error 42P01: relation "serverpod_runtime_settings" does not exist 
wane_serverpod_server-app-1       | 2024-01-19 18:52:04.224811Z Internal server error. Zoned exception.
wane_serverpod_server-app-1       | Null check operator used on a null value
wane_serverpod_server-app-1       | #0      Serverpod.start.<anonymous closure> (package:serverpod/src/server/serverpod.dart:440)
wane_serverpod_server-app-1       | <asynchronous suspension>
wane_serverpod_server-app-1       | #1      Serverpod.start (package:serverpod/src/server/serverpod.dart:341)
wane_serverpod_server-app-1       | <asynchronous suspension>
wane_serverpod_server-app-1       | #2      run (package:wane_serverpod_server/server.dart:33)
wane_serverpod_server-app-1       | <asynchronous suspension>
```

**Comment by zezo357** [comment]
> I change the busybox to debian:bullseye-slim that error solved but i got new error
> 
> ```
> wane_serverpod_server-postgres-1  | 2024-01-19 18:52:04.224 UTC [71] STATEMENT:  INSERT INTO "serverpod_runtime_settings" ("logSettings", "logSettingsOverrides", "logServiceCalls", "logMalformedCalls") VALUES ('{"logLevel":1,"logAllSessions":false,"logAllQueries":false,"logSlowSessions":true,"logStreamingSessionsContinuously":true,"logSlowQueries":true,"logFailedSessions":true,"logFailedQueries":true,"slowSessionDuration":1.0,"slowQueryDuration":1.0}', '[]', FALSE, FALSE) RETURNING *
> wane_serverpod_server-app-1       | Failed to store runtime settings. PostgreSQLSeverity.error 42P01: relation "serverpod_runtime_settings" does not exist 
> wane_serverpod_server-app-1       | 2024-01-19 18:52:04.224811Z Internal server error. Zoned exception.
> wane_serverpod_server-app-1       | Null check operator used on a null value
> wane_serverpod_server-app-1       | #0      Serverpod.start.<anonymous closure> (package:serverpod/src/server/serverpod.dart:440)
> wane_serverpod_server-app-1       | <asynchronous suspension>
> wane_serverpod_server-app-1       | #1      Serverpod.start (package:serverpod/src/server/serverpod.dart:341)
> wane_serverpod_server-app-1       | <asynchronous suspension>
> wane_serverpod_server-app-1       | #2      run (package:wane_serverpod_server/server.dart:33)
> wane_serverpod_server-app-1       | <asynchronous suspension>
> ```

i think the migration is not being ran? i am not sure

**Comment by armanhadifatah** [comment]
> > I change the busybox to debian:bullseye-slim that error solved but i got new error
> > ```
> > wane_serverpod_server-postgres-1  | 2024-01-19 18:52:04.224 UTC [71] STATEMENT:  INSERT INTO "serverpod_runtime_settings" ("logSettings", "logSettingsOverrides", "logServiceCalls", "logMalformedCalls") VALUES ('{"logLevel":1,"logAllSessions":false,"logAllQueries":false,"logSlowSessions":true,"logStreamingSessionsContinuously":true,"logSlowQueries":true,"logFailedSessions":true,"logFailedQueries":true,"slowSessionDuration":1.0,"slowQueryDuration":1.0}', '[]', FALSE, FALSE) RETURNING *
> > wane_serverpod_server-app-1       | Failed to store runtime settings. PostgreSQLSeverity.error 42P01: relation "serverpod_runtime_settings" does not exist 
> > wane_serverpod_server-app-1       | 2024-01-19 18:52:04.224811Z Internal server error. Zoned exception.
> > wane_serverpod_server-app-1       | Null check operator used on a null value
> > wane_serverpod_server-app-1       | #0      Serverpod.start.<anonymous closure> (package:serverpod/src/server/serverpod.dart:440)
> > wane_serverpod_server-app-1       | <asynchronous suspension>
> > wane_serverpod_server-app-1       | #1      Serverpod.start (package:serverpod/src/server/serverpod.dart:341)
> > wane_serverpod_server-app-1       | <asynchronous suspension>
> > wane_serverpod_server-app-1       | #2      run (package:wane_serverpod_server/server.dart:33)
> > wane_serverpod_server-app-1       | <asynchronous suspension>
> > ```
> 
> i think the migration is not being ran? i am not sure

how to run the migration ?

this is the base dockerfile 

```
FROM dart:3.0 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM debian:bullseye-slim

ENV runmode=production
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/ /
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main  --mode $runmode --server-id $serverid --logging $logging --role $role
```

even I added  `--apply-migrations ` `after  CMD app/bin/main  --mode $runmode --server-id $serverid --logging $logging --role $role`
like this  :
`CMD app/bin/main  --mode $runmode --server-id $serverid --logging $logging --role $role --apply-migrations`

but didn't help , I thought out of the box these things works but I got tired after 2 hours not figuring out how to run it on server

**Comment by zezo357** [comment]
i made a custom one 
```
# Use the official Dart image
FROM dart:3.0 AS build

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Get all the dependencies
RUN dart pub get

RUN dart pub global activate serverpod_cli

# Compile to native code for faster startup and performance
RUN dart compile exe bin/main.dart -o bin/main

# Set environment variables
ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

# # Copy the necessary files from the build stage
# COPY --from=build /runtime/ /
# COPY --from=build /app/bin/main /app/bin/main
# COPY --from=build /app/config/ config/
# # COPY --from=build /app/generated/ generated/
# COPY --from=build /app/web/ web/

# Expose the necessary ports
EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

# Command to run the application
CMD dart bin/main.dart --apply-migrations && bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
```


try it

**Comment by zezo357** [comment]
thank you for the note
