### ISSUE TITLE
Bump vm_service package

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#1767]
Serverpods pub.dev score is reduced because the vm_service package is outdated: https://pub.dev/packages/serverpod/score

"_The constraint `^13.0.0` on vm_service does not support the stable version `14.0.0`._"

**Comment by yahu1031** [comment]
@SandPod A small heads up, There will be a possible issue coming if we use `vm_service: 14.0.0` version. Ref: https://github.com/dart-lang/sdk/issues/54483

**Comment by SandPod** [comment]
Thanks for the heads up! Will check it out before merging out bump 🙏

**Comment by SandPod** [comment]
@yahu1031 - From my understanding is seems like the issues you encountered in the thread you linked is related to using an older version of dart and flutter together with the latest version of vm_service.

If I understand the replies correctly this should be resolved when using any version of Dart 3. And since Serverpod now requires version  ^3.0.0 of Dart and ^3.10.0 of Flutter we should be good.

Have I understood this correctly @yahu1031?

**Comment by yahu1031** [comment]
_Originally posted by @bkonyi in https://github.com/dart-lang/sdk/issues/54483#issuecomment-1883521374_

As of this comment the fix for http profile wasn't deployed yet.
