### ISSUE TITLE
orderBy on find is broken

### ISSUE THREAD

**Issue by kieran-novarca** [serverpod/serverpod#1772]
**Describe the bug**
orderBy on find documentation is incorrect and causes an error in the code as it does not appear to accept that type. 

**Screenshots**
![image](https://github.com/serverpod/serverpod/assets/120369588/4b039315-a4f3-4893-bd17-00ea3fc20379)
![image](https://github.com/serverpod/serverpod/assets/120369588/f89fde4b-857c-4d7a-bd37-67d8176b9b70)

**To Reproduce**
1. Try adding an order by to any find as documented 

**Expected behavior**
A clear and concise description of what you expected to happen:
For it not to error and order correctly 

**Serverpod versions**
 -  _CLI Version: 1.2.0
 - _Library version: 1.2.0
 -

**Comment by Isakdl** [comment]
In the new api under `OpNoteField.db` the `orderBy` param is now a callback that gives you the table, exactly like the `where` param.

You need to change the code to the following:

```dart
var fields = await OpNoteField.db.find(
  session,
  where: (t) => t.opNoteSectionId.equals(section.first.id),
  orderBy: (t) => t.order,
);
```
)

**Comment by kieran-novarca** [comment]
In that case the documentation is wrong

**Comment by Isakdl** [comment]
Alright! Will take a look at that, thank you!
