### ISSUE TITLE
Migrate to Serverpod 1.2 on Windows

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#1773]
### Discussed in https://github.com/serverpod/serverpod/discussions/1765

<div type='discussions-op-text'>

<sup>Originally posted by **PhilipNell-258** January 16, 2024</sup>
Hi

I have followed the migration process on the wiki page to preserve data.
I am running Serverpod on a Windows machine with Docker

Commands ```serverpod generate``` and ```serverpod create-migration``` is working 100%

When running the 3rd command: ```serverpod create-repair-migration``` the following error is received.

```console
⠧ Creating repair migration... (2.1s)Failed call: insights.getLiveDatabaseDefinition
SocketException: The remote computer refused the network connection.
 (OS Error: The remote computer refused the network connection.
, errno = 1225), address = localhost, port = 56650

Unable to fetch live database schema from server. Make sure the server is running and is connected to the database.
SocketException: The remote computer refused the network connection.
 (OS Error: The remote computer refused the network connection.
, errno = 1225), address = localhost, port = 56650
✗ Creating repair migration (2.1s)
```

How do I solve this, because running the server normally using ```dart run bin/main.dart``` gives the following error:

```console
SERVERPOD version: 1.2.0, dart: 3.2.4 (stable) (Thu Dec 21 19:13:53 2023 +0000) on "windows_x64", time: 2024-01-16 14:21:03.210838Z
mode: development, role: monolith, logging: normal, serverId: default
Failed to apply database migrations. PostgreSQLSeverity.error 42P01: relation "serverpod_migrations" does not exist 
Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082
CPU and memory usage metrics are not supported on this platform.
```

Thanks
</div>

**Comment by rodjordan** [comment]
Perhaps you could create the missing table manually:

--
-- Class DatabaseMigrationVersion as table serverpod_migrations
--
CREATE TABLE "serverpod_migrations" (
    "id" serial PRIMARY KEY,
    "module" text NOT NULL,
    "version" text NOT NULL,
    "timestamp" timestamp without time zone
);

-- Indexes
CREATE UNIQUE INDEX "serverpod_migrations_ids" ON "serverpod_migrations" USING btree ("module");

**Comment by PhilipNell-258** [comment]
Creating the table manually did the trick, thanks @rodjordan. When running the ```serverpod create-repair-migration``` command gives the following warning which then aborts

```console
 serverpod create-repair-migration
⠸ Creating repair migration... (0.2s)
Migration Warnings:
 • Unique index "serverpod_google_refresh_token_userId_idx" is added to table "serverpod_google_refresh_token". If
there are existing rows with duplicate values, this migration will fail.
Migration aborted. Use --force to ignore warnings.
```

I am going to force it since I am not using google auth.
