### ISSUE TITLE
Healthcheck Timeout on GCP Instance Groups during Serverpod Project Deployment using Terraform

### ISSUE THREAD

**Issue by miraieyes** [serverpod/serverpod#1781]
**Bug Description:**
When deploying my Serverpod project using Terraform on Google Cloud Platform (GCP), the Healthcheck for the Instance Groups times out consistently. Despite attempting various troubleshooting steps such as restarting the compute engine and deploying the project in a new GCP project, the issue persists. I also came across a similar problem documented in issue #1060, but modifying the Dockerfile as suggested did not resolve the problem in my case.

**Steps to Reproduce:**
Deploy Serverpod project using Terraform on GCP.
Observe the Healthcheck status for the Instance Groups.
Expected Behavior:
The Healthcheck for the Instance Groups should succeed without timing out during the Serverpod project deployment.

**Actual Behavior:**
The Healthcheck for the Instance Groups times out consistently, leading to deployment issues.

**Environment:**
Serverpod version: 1.2.0
Terraform version: 1.6.6

**Zone**
europe-west4
europe-west4-c

Dockerfile 
```dockerfile
FROM dart:3.0 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM busybox

ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/etc /etc
COPY --from=build /runtime/lib /lib
COPY --from=build /runtime/lib64 /lib64
COPY --from=build /runtime/usr /usr
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
#COPY --from=build /app/generated/ generated/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role

``` 
Additional Information:
Mentioned issue #1060 did not provide a resolution in my case.
Restarting the compute engine and deploying the project in a new GCP project did not resolve the issue.

Your prompt attention to this matter is highly appreciated, and please let me know if any further information is required to diagnose and resolve this issue.

**Comment by SandPod** [comment]
Hey @miraieyes!

Could you please also provide any logs emitted from the instance?

**Comment by miraieyes** [comment]
Hi @SandPod  

Appreciate the swift response! Here are the logs.
[log-vm-instancegroup.json](https://github.com/serverpod/serverpod/files/13978528/log-vm-instancegroup.json)
[log-instancegroupmanager.json](https://github.com/serverpod/serverpod/files/13978529/log-instancegroupmanager.json)
[log-vm-instance.json](https://github.com/serverpod/serverpod/files/13978530/log-vm-instance.json)

**Comment by SandPod** [comment]
We will start looking into it.

Did you also see this thread and try out the solutions suggested there? https://github.com/serverpod/serverpod/issues/1101

**Comment by miraieyes** [comment]
Thank you @SandPod  

I've experimented with a few potential fixes and plan to try a couple more tomorrow. If any of these prove successful, I'll keep you posted.

**Comment by miraieyes** [comment]
@SandPod I attempted to modify the Dockerfile using various configurations as described in issue #1101. However, I encountered an error stating "/app/generated" not found. While exploring the issues section, I noticed someone with a similar problem and the suggestion was to comment out that line. Consequently, my modified Dockerfile now looks like this based on #1101:
```dockerfile
FROM dart:3.0 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM busybox:1.34.1

ENV runmode=development
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/etc /etc
COPY --from=build /runtime/lib /lib
COPY --from=build /runtime/lib64 /lib64
COPY --from=build /runtime/usr /usr
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
#COPY --from=build /app/generated/ generated/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role
``` 

This adjustment enables my action to succeed and allows my container to be built. However, the previously mentioned issue persists.

It might be helpful to note that I purchased a Google Cloud domain, as specified in the documentation, and followed the outlined steps for setting up the Google Cloud domain.

**Comment by SandPod** [comment]
Thank you for the additional information.

As mentioned in [#1763](https://github.com/serverpod/serverpod/issues/1763), removing that line is completely fine.

Just to clarify, the issue that remains is a repeated failing health check?

**Comment by miraieyes** [comment]
@SandPod Yes unfortunately, the health check is still failing, and the instance group continues to experience timeouts.
<img width="1732" alt="Scherm­afbeelding 2024-01-19 om 09 19 59" src="https://github.com/serverpod/serverpod/assets/82806264/d26b3bcb-79ca-46ba-a14a-c697c549b95c">
<img width="1705" alt="Scherm­afbeelding 2024-01-19 om 09 20 07" src="https://github.com/serverpod/serverpod/assets/82806264/715e892a-741d-402c-bb85-19fc4b600f57">

**Comment by SandPod** [comment]
An additional piece of information that would be helpful is if you could turn on verbose logging for the instance you are attempting to deploy, and then paste the loggs produced by that instance during boot and the health check process here.

You can turn on verbose logging by setting the environment variable `logging` to 'verbose' or modify the docker file and change the `$logging` variable to a set value `verbose`.

**Comment by miraieyes** [comment]
Thank you for your assistance. I've incorporated the 'verbose' setting into the Dockerfile. I hope that these enhanced logs will provide valuable insights to aid in troubleshooting.
[instancegrouplog.json](https://github.com/serverpod/serverpod/files/13986976/instancegrouplog.json)
[instancegroupmanager-log.json](https://github.com/serverpod/serverpod/files/13986977/instancegroupmanager-log.json)
[vminstance-log.json](https://github.com/serverpod/serverpod/files/13986978/vminstance-log.json)

**Comment by miraieyes** [comment]
@SandPod I want to express my sincere gratitude for the invaluable assistance you provided. The issue has been resolved, and it turns out the problem stemmed from an error on my part during the database table setup, which was causing the health-related issues. Thank you once again for your support.

**Comment by SandPod** [comment]
@miraieyes 🎉 I'm happy it resolved itself! Please continue reaching out in the future! :)
