### ISSUE TITLE
pod 1.2 just quits

### ISSUE THREAD

**Issue by mike-novarca** [serverpod/serverpod#1795]
**Describe the bug**
run Serverpod it shows some text then quits

**To Reproduce**
1. Go to server directory
2. type dart bin/main.dart  
3. server quits with error message

**Expected behavior**
server not quitting 

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_1.2
 - _Library version:1.2
![Screenshot 2024-01-22 at 14 18 34](https://github.com/serverpod/serverpod/assets/120393194/a175bc6e-1ea6-487a-98ea-21b0efc36c60)

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**

**Comment by SandPod** [comment]
Hey @mike-novarca! 👋 

Could you try starting the server with `dart run bin/main.dart --logging=verbose` and paste the output here.

**Comment by mike-novarca** [comment]
mdb@Mikes-MBP-2 myopnotes_server % dart run bin/main.dart --logging=verbose
SERVERPOD version: 1.2.0, dart: 3.2.5 (stable) (Tue Jan 16 15:02:13 2024 +0000) on "macos_x64", time: 2024-01-22 14:25:25.032153Z
mode: development, role: monolith, logging: verbose, serverId: default
Config loaded from: config/development.yaml
api port: 8080
api public host: localhost
api public port: 8080
api public scheme: http
insights port: 8081
insights public host: localhost
insights public port: 8081
insights public scheme: http
web port: 8082
web public host: localhost
web public port: 8082
web public scheme: http
database host: localhost
database port: 8090
database name: myopnotes
database user: postgres
database require SSL: false
database unix socket: false
database pass: ********
redis host: localhost
redis port: 8091
redis pass: ********

**Comment by SandPod** [comment]
Hmm, it seems like the server is reading the configuration but not starting.

If you check in `myopnotes_server/lib/server.dart` do you call `start()` on the server in the run method?

This is what the run method looks like for a newly generated project:
```
void run(List<String> args) async {
  // Initialize Serverpod and connect it with your generated code.
  final pod = Serverpod(
    args,
    Protocol(),
    Endpoints(),
  );

  // If you are using any future calls, they need to be registered here.
  // pod.registerFutureCall(ExampleFutureCall(), 'exampleFutureCall');

  // Setup a default page at the web root.
  pod.webServer.addRoute(RouteRoot(), '/');
  pod.webServer.addRoute(RouteRoot(), '/index.html');
  // Serve all files in the /static directory.
  pod.webServer.addRoute(
    RouteStaticDirectory(serverDirectory: 'static', basePath: '/'),
    '/*',
  );

  // Start the server.
  await pod.start();
}
```

Notice the last line of the method.

**Comment by mike-novarca** [comment]
My bad. fixed. Thanks
