### ISSUE TITLE
Show error in `generator.yaml` if the included modules are not in dependencies.

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#1801]
## Is your feature request related to a problem? Please describe. ##
When we include modules in generator.yaml on the server without adding them to pubspec.yaml, it should throw an error during compile time or during build (generate) time.

## Describe the solution you'd like ##
1. The expected solution is to show an error or warning during compile time with the help of LSP. (Better solution).
2. Or throw errors when we call `serverpod generate`(Alternative solution).

Solution 1 is a better idea because this will avoid a new span of serverpod and getting errors in the console while getting benefits from LSP.

**Comment by Isakdl** [comment]
Sub task of: https://github.com/serverpod/serverpod/issues/1660
