### ISSUE TITLE
crashes with empty Map, causes type cast error

### ISSUE THREAD

**Issue by jason-downs** [serverpod/serverpod#1806]
**Describe the bug**

According to the discussion here: https://github.com/serverpod/serverpod/pull/1799 having Map types with int keys is already supported even though the documentation has not yet been updated to reflect this.

However, hen using a serverpod-serializable class as defined in the yaml files, if a field is type Map with int keys (or enum keys whether they are serialized by name or by number) and then use it in any situation where this Map contains no entries and it needs to be deserialized, it triggers an exception.

The offending code appears to be in the `src/generated/protocol.dart` file where during deserialization, the Map data attempts to be type-cast from a Map to a List, as seen in this screenshot (note the "data as List"):

<img width="674" alt="Screenshot 2024-01-23 at 2 16 21 PM" src="https://github.com/serverpod/serverpod/assets/31083702/e2674085-1910-4298-8394-c041134c8214">

...which produces the error:

`type '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast`

Looking into things, it seems that map data is being stored behind the scenes in a format that is a List of map entries, with format:
`[{"k": somekey, "v":somevalue}, {"k": anotherkey, "v": anothervalue}]. So it would seem that since it's actually a list in that case, the type cast in question works when data exists and has been converted into that format, but when there is no data in the map, it remains a Map type and the type cast fails.

In one case, this was a database table class and I was able to see in my database viewer that the empy Map field was written to the database as {} whereas the non-empty ones were written as the list format described above. Changing these empty brackets from {} to [] (map to list) and then re-running caused the app to run without this error. In another case, adding some placeholder value in the Map on startup also avoided the error. However, these are hacky workarounds and there are many cases where you might want some Map data type that is initially empty and then filled in by various user actions, for example.

This was tested in two different projects with various types of Maps with the same result.

**To Reproduce**

1) Define a class with one or more Map fields with int keys:

<img width="316" alt="Screenshot 2024-01-23 at 2 33 40 PM" src="https://github.com/serverpod/serverpod/assets/31083702/92fdaae6-679d-4ccc-8bb8-458918272047">

2) Write an endpoint function that handles this data in some way:

<img width="666" alt="Screenshot 2024-01-23 at 2 34 05 PM" src="https://github.com/serverpod/serverpod/assets/31083702/98a14186-cdf5-4d98-b34f-48a91e54dac9">

3) Call this endpoint when the Map field is empty:

<img width="489" alt="Screenshot 2024-01-23 at 2 34 49 PM" src="https://github.com/serverpod/serverpod/assets/31083702/848eb402-4a58-4344-81a7-52ce4a5a5c69">

4) Error:

<img width="388" alt="Screenshot 2024-01-23 at 2 35 02 PM" src="https://github.com/serverpod/serverpod/assets/31083702/c12f60ce-61a1-46fc-b482-23f905cb2b25">

**Serverpod versions**

All serverpod components are 1.2.1

**Platform information**

Flutter 3.16.8, Dart 3.2.5, MacOS Sonoma 14.2.1, serverpod server running on localhost

**Comment by Isakdl** [comment]
Thank you for the detailed issue! I will cover this case in the PR you linked!

**Comment by jason-downs** [comment]
Unfortunately the problems with empty Map types haven't been fully fixed even with this PR merged; see #1908
