### ISSUE TITLE
 http://localhost:8081 and  http://localhost:8080 return same thing and no dashboard

### ISSUE THREAD

**Issue by SEED-Foundation** [serverpod/serverpod#1808]
I just created Serverpod project and just start running it 

this port 8080 and 8081 just give me same thing in the browser something like this `OK 2024-01-24 08:50:25.112825Z`

`http://localhost:8080`
`http://localhost:8081`

I think one should give me a dashboard something like that 

`http://localhost:8081/dashboard/`
`http://localhost:8080/dashboard/`

from those two i get 'This page isn't working' in the browser

**Comment by Isakdl** [comment]
There is no dashboard bundled with the server. We do have the insights app though, but it is a standalone application: https://docs.serverpod.dev/insights

**Comment by SandPod** [comment]
Hey @SEED-Foundation 👋 

The two ports listed are by default assigned to serve the RPC endpoints for the flutter app(8080) that you are developing and the insights tool(8081) that is a standalone tool that can be used to connect to your server.

Then on port 8082 you have the port where the web server is hosted, that is the page that is best to visit in your browser.

We don't natively server a `dashboard` page. Is this something that you have build yourself or did you read about it somewhere?

**Comment by SEED-Foundation** [comment]
maybe i'm wrong but the first time run serverpod I got a dashboard for seeing the request and things like that I didn't take screenshot at that time that's why was confused now that both 8080 and 8081 give me same thing

**Comment by SandPod** [comment]
That sounds like the insights functionality. The app is available on Mac and Windows if you would like to try it out.
