### ISSUE TITLE
`database` model flag is mis-named

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1819]
There are three places a model can be used: client, server, and serialized to the database.

A model field should always be visible to the server. However, it may not be allowed to be sent to the client (`database` flag is set if not allowed), and it may not be meant for storing in the database (`!persist` is set if field is not part of database schema).

The `database` flag is a bit weirdly named, because if you create a model that is for client and server communication only, but it is never stored in the database (it doesn't have a `table:` value set in the model yaml), then `database` actually means "create field in the server version of the class only, don't create it in the client, and don't send it over the wire". This has nothing to do with the database.

I need to use one of these fields to store sorting information, so that I can run a custom sort in Dart code on the server for a certain query type, but that info should not be sent to the client. I'm using `database` to do it, but I think a better term could be used here.

I would prefer 3 values: `excludeFromDatabase`, `excludeFromClient`, and the default `clientServer`.

**Comment by Isakdl** [comment]
Yes tghis

**Comment by Isakdl** [comment]
Yes, this is why we have deprecated the `database` keyword! You should get a "info" message on this if you use it when generating your code or if you have the vscode plugin. 

Both `api` and `database` have been replaced with the keywords `scope` and `persist` where `!persist` means do not store in the database, and scope has 3 values `all`, `serverOnly` and a special `none` (this is mostly used internally).

So your `excludeFromDatabase` is `!persist` and `excludeFromClient` is `scope=serverOnly`.

**Comment by lukehutch** [comment]
@Isakdl OK, thanks, I missed this because it's only described in the release notes, not in the core docs! (#1818 is still an issue, even though you closed it just now...). This issue should have been closed, not the other one :-)

**Comment by lukehutch** [comment]
Also, I have the Serverpod extension, but it doesn't seem to work. Mind you my models are in `lib/src/model`, not `lib/src/models` -- but the extension should presumably be backwards-compatible.

**Comment by Isakdl** [comment]
the extension is not backward compatible with the `model` folder as that was an in-between state. It is however backwards compatible with the `protocol` folder. Either `protocol` or `models` will work!

**Comment by lukehutch** [comment]
Got it. Thanks!
