### ISSUE TITLE
serverpod linter still showing error in 1.2.2 for non-lowerCamelCase enums

### ISSUE THREAD

**Issue by jason-downs** [serverpod/serverpod#1841]
Despite merging #1820 being included in the new Serverpod version 1.2.2, I'm still getting a linter error (not info or warning) in the vscode extension for not naming my enums in lowerCamelCase in the serverpod protocol yaml files.

`serverpod generate` runs fine without any error messages now, but the linter warning persists, which is pretty annoying and should at least be configurable if turning off this linter error by default is not the desired behavior. Maybe the vscode extension just needs to be updated to conform with the latest serverpod version - it seems the most recent extension update was 2 weeks ago.

The vscode linter error is coming from serverpod not from dart, as it says so in the error message.

**Comment by Isakdl** [comment]
@jason-downs did you update the CLI? The vscode plugin will run the CLI in the background to get the linting information.

**Comment by jason-downs** [comment]
Yes the CLI was updated to the latest version.

What fixed it for me just now was closing and reopening vscode. 🤦🤦🤦

**Comment by jason-downs** [comment]
Gonna close this now if that's ok, just one of many silly things I've done lately!
