### ISSUE TITLE
Serverpod docs for creating a session for test db access are very poor

### ISSUE THREAD

**Issue by mike-novarca** [serverpod/serverpod#1855]
**Describe the bug**
I is not documented how to create a session for database access for tests. There is also no default test folder included with Serverpod. Testing is essential for enterprise level deployments.

**To Reproduce**
Read the create session documentation. 

**Expected behavior**
A clear and concise description of how to create a session with with example code and parameters explained.

**Comment by vlidholt** [comment]
This will be a part of our new testing framework. I'm closing this as it is better covered here:
https://github.com/serverpod/serverpod/issues/2494
