### ISSUE TITLE
error when migrating from 1.1.1 to 1.2.2

### ISSUE THREAD

**Issue by aragornz325** [serverpod/serverpod#1859]
Hello, I am migrating from version 1.1.1 to version 1.2.2. I have updated the pubspec.yaml files, updated dart and changed the models according to the new syntax, but when I run serverpod generate... I get this error

" Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the
stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

type 'YamlMap' is not a subtype of type 'String'

#0      Restrictions.validateParentName (package:serverpod_cli/src/analyzer/models/validation/restrictions.dart:651:49)
#1      _collectValueRestrictionErrors (package:serverpod_cli/src/analyzer/models/validation/model_validator.dart:263:32)
#2      validateYamlModel (package:serverpod_cli/src/analyzer/models/validation/model_validator.dart:76:5)
#3      _collectNodesWithNestedNodesErrors (package:serverpod_cli/src/analyzer/models/validation/model_validator.dart:311:26)
#4      validateYamlModel (package:serverpod_cli/src/analyzer/models/validation/model_validator.dart:107:5)
#5      _collectNodesWithNestedNodesErrors (package:serverpod_cli/src/analyzer/models/validation/model_validator.dart:311:26)
#6      validateYamlModel (package:serverpod_cli/src/analyzer/models/validation/model_validator.dart:107:5)
#7      SerializableModelAnalyzer.validateYamlDefinition (package:serverpod_cli/src/analyzer/models/model_analyzer.dart:162:5)
#8      StatefulAnalyzer._validateAllModels (package:serverpod_cli/src/analyzer/models/stateful_analyzer.dart:133:33)
#9      StatefulAnalyzer.validateAll (package:serverpod_cli/src/analyzer/models/stateful_analyzer.dart:70:5)
#10     performGenerate (package:serverpod_cli/src/generator/generator.dart:29:25)
<asynchronous suspension>
#11     StdOutLogger.progress (package:serverpod_cli/src/logger/loggers/std_out_logger.dart:131:20)
<asynchronous suspension>
#12     GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:67:17)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     ServerpodCommandRunner.runCommand (package:serverpod_cli/src/runner/serverpod_command_runner.dart:140:7)
<asynchronous suspension>
#15     _main (file:///home/rodrigo/.pub-cache/hosted/pub.dev/serverpod_cli-1.2.2/bin/serverpod_cli.dart:52:3)
<asynchronous suspension>
#16     main.<anonymous closure> (file:///home/rodrigo/.pub-cache/hosted/pub.dev/serverpod_cli-1.2.2/bin/serverpod_cli.dart:26:9)
<asynchronous suspension>
#17     main (file:///home/rodrigo/.pub-cache/hosted/pub.dev/serverpod_cli-1.2.2/bin/serverpod_cli.dart:23:3)
<asynchronous suspension>

**Comment by vlidholt** [comment]
It looks like some of the configuration files is not using correct syntax. Any more information there can help us debug this issue. Would you mind posting a copy of your config files (obviously not the passwords or any private data).
