### ISSUE TITLE
Google auth ApiException: 10 error

### ISSUE THREAD

**Issue by armanhadifatah** [serverpod/serverpod#1876]
I'm getting this error when i try to implement login with google 

steps I took

created google cloud app 
created credentials for Web application and android 

copy Web application client id to serverClientId
copy android client id to clientId

add sha1 debug key to android credential 

this is my singin button 

```
SignInWithGoogleButton(
              onFailure: () {
                print('Failed to sign in with Google');
              },
              onSignedIn: () {
                print('Signed in with Google');
              },
              debug: true,
              caller: client.modules.auth,
              redirectUri: Uri.parse('http://localhost:5053'),
              serverClientId: '812722303014-6c1uv6e4ovpqf8jeb0e7pdmtmfqphmnk.apps.googleusercontent.com',
              clientId: '812722303014-vh1drc6lgfom3b9g0kagksh5modhjnbu.apps.googleusercontent.com',
            ),
```

and this is the error i get 

```
I/flutter (14856): serverpod_auth_google: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
I/flutter (14856): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
I/flutter (14856): <asynchronous suspension>
I/flutter (14856): #1      GoogleSignInAndroid._signInUserDataFromChannelData (package:google_sign_in_android/google_sign_in_android.dart:111:3)
I/flutter (14856): <asynchronous suspension>
I/flutter (14856): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
I/flutter (14856): <asynchronous suspension>
I/flutter (14856): #3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
I/flutter (14856): <asynchronous suspension>
```

**Comment by armanhadifatah** [comment]
> I had the same issue and it took me a very long time to figure out how to solve it. I can't remember exactly what fixed it, but I know part of solving this is ensuring you have the right SHA1 key in the app.
> 
> https://stackoverflow.com/a/49450870/3950982

The documentation is so bad that i tried different things for four hours and I couldn't figure it out .
I tried flutter web just to test so I would not need SHA1 but then when I do the signin it show a new page to login with my gmail and when I do it it will just open my wesbite page again in this new tab without any thing to happen.

**Comment by Isakdl** [comment]
If you are trying this on web have you setup the redirect URI properly? Do you have a page extracting the auth code?

See this tutorial for a full example: https://medium.com/serverpod/integrating-google-sign-in-with-serverpod-authentication-part-2-6fade3099baf

**Comment by SandPod** [comment]
@armanhadifatah - Closing this issue, Please feel free to reopen it if @Isakdl answer was not sufficient,

**Comment by babelomranedev-cell** [comment]
📌 عنوان المشكلة:
حل مشكلة فشل تسجيل الدخول بجوجل ApiException: 10 (DEVELOPER_ERROR) في تطبيقات Flutter عند نشرها على متجر Google Play.

🔍 التشخيص (Diagnosis):
عند إعداد تسجيل الدخول عبر Google مع Firebase في Flutter، يتطلب كائن GoogleSignIn تمرير خيار serverClientId.
يحدث الخطأ رقم 10 حصرياً عند وجود أحد الأسباب التالية:

وجود معرف قديم أو غير مطابق مکتوب يدوياً (Hardcoded) داخل الكود (مثل اختلاف serverClientId بين ملفات الـ Auth المختلفة في المشروع).

تمرير Android Client ID بدلاً من Web Client ID.

🛠️ الحل النهائي (Solution):

افتح مشروعك في Firebase Console -> Authentication -> Sign-in method -> Google.

انسخ معرف عميل الويب (Web Client ID) الحقيقي والنشط.

ابحث في مشروع Flutter كاملاً عن أي نص ينتهي بـ apps.googleusercontent.com.

تأكد من أن كل ملفات الخدمات (مثل auth_service.dart و google_sign_in_provider.dart) تستخدم نفس المعرف تماماً دون أي اختلاف في الحروف.

يفضل دائماً قراءة المعرف ديناميكياً من ملف google-services.json أو توحيده في ملف ثوابت موحد (Constants) لمنع تكراره وتحديثه في مكان دون آخر.
