### ISSUE TITLE
Typo in `UserAuthetication`

### ISSUE THREAD

**Issue by timnew** [serverpod/serverpod#1887]
**Describe the bug**

class `UserAuthetication` in `server/session.dart` has a typo

**To Reproduce**
1. Goto https://github.com/serverpod/serverpod/blob/main/packages/serverpod/lib/src/server/session.dart
2. Search `UserAuthetication`

**Expected behavior**
`UserAuthetication` should be `UserAuthentication`

**Screenshots**
![CleanShot 2024-02-08 at 18 06 35@2x](https://github.com/serverpod/serverpod/assets/1287238/fa706874-2c27-4c51-9552-d52dd46fb14b)

**Serverpod versions**
 -  _CLI Version:_  1.2.3
 - _Library version:_  1.2.3

**Platform information**
N/A

**Additional context**
N/A

**Comment by vlidholt** [comment]
Well spotted! We are working on Serverpod 2.0 now, so smaller breaking changes like this is ok. If you submit a PR, make sure to create a dummy class with the old (incorrect) name and add a deprecated annotation, so it's easier to find the correct class when upgrading.

**Comment by kaljitism** [comment]
@vlidholt @timnew I have fixed this typo and created a dummy class of incorrect name with Deprecated decorator and relevant message.
