### ISSUE TITLE
!!! Serverpod Generate Does Not Work with Custom Serializable Objects

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#1932]
**Describe the bug**
Serverpod Generate Does Not Work with Custom Serializable Objects, retrieving:
```
⠙ Generating code... (1ms)

Found 1 issue.
Error on line 6, column 12 of lib\src\models\utente_dto.yaml: The field has an invalid datatype "Negozio".
  ╷
1 │ Negozio
  │ ^^^^^^^
  ╵
✗ Generating code (0.3s)
```

**To Reproduce**
1. Create:
import 'package:serverpod_serialization/serverpod_serialization.dart';
```
class Negozio {
  const Negozio({
    required this.codice,
    required this.nome,
    required this.zonaNegozioId,
  });

  factory Negozio.fromJson(Map<String, dynamic> json, SerializationManager serializationManager) {
    return Negozio(
      codice: json['codice']!,
      nome: json['nome']!,
      zonaNegozioId: json['zonaNegozioId']!,
    );
  }

  final String codice;

  final String nome;

  final String zonaNegozioId;

  @override
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> map = <String, dynamic>{};
    map['codice'] = codice;
    map['nome'] = nome;
    map['zonaNegozioId'] = zonaNegozioId;
    return map;
  }
}
```
2. Add to extraClasses:
```
extraClasses:
  - package:ewocrm_shared/src/negozio.dart:Negozio
```

3. Run Serverpod Generate

**Expected behavior**
Before the upgrade to > 1.1, it correctly generated the protocols with custom serializable objects

**Serverpod versions**
1.2.3

**Platform information**
Windows and Mac

**Comment by Isakdl** [comment]
This should work:

```yaml
class: Example
fields:
  negozio: package:ewocrm_shared/src/negozio.dart:Negozio
```

Keep in mind that the class `Negozio` needs to implement `toJson`, `allToJson`, `copyWith` and the factory constructor `fromJson` to function as a field in a generated class.

**Comment by AndryHTC** [comment]
> This should work:
> 
> ```yaml
> class: Example
> fields:
>   negozio: package:ewocrm_shared/src/negozio.dart:Negozio
> ```
> 
> Keep in mind that the class `Negozio` needs to implement `toJson`, `allToJson`, `copyWith` and the factory constructor `fromJson` to function as a field in a generated class.

Thank you @Isakdl. Can you kindly send me the link where this is explained in the documentation?

**Comment by Isakdl** [comment]
I think the documentation is spare on this tbh, we will add this!

**Comment by Isakdl** [comment]
I also think we can improve the validation of custom classes too, it is cleaner to only have to write the class name in the model files. And it would be nice to validate the implementation too.

**Comment by AndryHTC** [comment]
Before the 1.2 it was already working like this. This is the model using it:
```
class: UtenteDto
fields:
  uuid: String
  nomeVisualizzato: String
  photoUrl: String?
  negozio: Negozio?
  ruolo: String
  email: String
  firebaseUid: String?
```

**Comment by AndryHTC** [comment]
> I also think we can improve the validation of custom classes too, it is cleaner to only have to write the class name in the model files. And it would be nice to validate the implementation too.

So is this a regression?

**Comment by AndryHTC** [comment]
Hi @Isakdl, we're having some trouble at the moment. The way you suggested, for array fields isn't working for us. We have about 100 YAML protocols that use custom objects, and changing all of them to a the new way is already a big task. It really doesn't make sense to go through all this effort and still face problems with arrays.

**We're stuck**

**Comment by Isakdl** [comment]
Yes it looks like a regression indeed. I will take a look at this now.

**Comment by AndryHTC** [comment]
What is the difference between **toJson** and **allToJson**? No documentation, no explanations.

So sorry to say this, but this should be the most stable Serverpod version ever, and instead I've been stuck for 2 days without even being able to migrate to it

**Comment by Isakdl** [comment]
We should definitely add that to the docs. 

The difference is probably none for your custom classes, I presume you want to transfer the entire object to the client, in that case you can map `allToJson` to the same method as `toJson`. 

Internally we use `allToJson` to serialize all fields including `serverOnly` fields. Where as `toJson` will only convert fields that should be sent between the server and client.
