### ISSUE TITLE
inSet produces malformed sql if set is empty

### ISSUE THREAD

**Issue by mike-novarca** [serverpod/serverpod#1968]
**Describe the bug**
inSet produces malformed sql if set is empty.
Error produced
PostgreSQLSeverity.error 42601: syntax error at or near ")" 
package:postgres/src/connection.dart 520:18                             _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 481:7                              _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart 549:22                             _PostgreSQLExecutionContextMixin.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 820:23                         _PgExecutionContextWrapper.mappedResultsQuery.<fn>
package:postgres_pool/postgres_pool.dart 746:27                         _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 819:12                         _PgExecutionContextWrapper.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 661:16                         PgPool.mappedResultsQuery.<fn>
package:postgres_pool/postgres_pool.dart 352:22                         PgPool.run.<fn>.<fn>
package:postgres_pool/postgres_pool.dart 451:27                         PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 423:14                         PgPool._withConnection.<fn>
package:executor/src/executor_impl.dart 61:19                           _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 351:18                         PgPool.run.<fn>
package:retry/retry.dart 131:16                                         RetryOptions.retry
package:postgres_pool/postgres_pool.dart 349:14                         PgPool.run
package:serverpod/src/database/database_connection.dart 395:20          DatabaseConnection.mappedResultsQuery
package:serverpod/src/database/database_connection.dart 423:18          DatabaseConnection._deserializedMappedQuery
**To Reproduce**

**Expected behavior**
A valid query.

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ 1.2.4
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**

**Comment by mike-novarca** [comment]
SELECT "actions"."id" AS "actions.id", "actions"."actionTargetType" AS "actions.actionTargetType", "actions"."actionCategory" AS "actions.actionCategory", "actions"."componentType" AS "actions.componentType", "actions"."actionType" AS "actions.actionType", "actions"."automationId" AS "actions.automationId", "actions"."itemIds" AS "actions.itemIds", "actions"."order" AS "actions.order", "actions"."createdAt" AS "actions.createdAt", "actions"."createdById" AS "actions.createdById", "actions"."editedAt" AS "actions.editedAt", "actions"."editedById" AS "actions.editedById", "actions"."deletedAt" AS "actions.deletedAt", "actions"."deletedById" AS "actions.deletedById" FROM "actions" WHERE "actions"."automationId" IN ()

**Comment by kieran-novarca** [comment]
A simple fix for this issue is that there just needs to be a null check on the inSet function that does not produce any output if the input is null rather than producing empty brackets "()" which are what seem to be causing the error

**Comment by SandPod** [comment]
The SQL query should never be malformed and will be fixed, but I'm not sure what the expected behavior is here.


From the API perspective, if I require something to be in a set and then pass in an empty set, I would expect no matching results.

I see it as we have a couple of possible ways to go here:
1. We throw and inform the user of the interface that an empty set is not a valid argument (with added documentation).
2. We produce SQL that won't match anything.
3. We just remove the inSet filter producing an unexpected result - I personally don't like this option.

Null is not a valid argument for the `inSet(...)` method so we shouldn't need to worry about that.

**Comment by SandPod** [comment]
After discussions we will replicate this behavior to solve this issue (option 2):

```dart
  test('filter with empty set', () {
    var mySet = <int>{};
    var arr = [1, 2, 3, 4, 5, 6];
    var result = arr.where((element) => mySet.contains(element));

    expect(result, isEmpty);
  });
```

**Comment by SandPod** [comment]
Fixed by: https://github.com/serverpod/serverpod/pull/2073
