### ISSUE TITLE
Failed to create server socket

### ISSUE THREAD

**Issue by rammesaran** [serverpod/serverpod#1970]
When i run this 'dart bin/main.dart --apply-migrations' I am getting this error.

![image](https://github.com/serverpod/serverpod/assets/45402258/99ea4a62-5ebe-4275-ac97-a779a5953253)

**Comment by Isakdl** [comment]
You are using Serverpod version 1.1.1, migrations are only supported in version 1.2.x.

**Comment by rammesaran** [comment]
After updating to 1.2. Iam getting this error 
![Screenshot2024_02_27_225027](https://github.com/serverpod/serverpod/assets/45402258/ce212df4-637f-444f-b76d-94b3f478542a)

**Comment by rammesaran** [comment]
my password was different - so i have updated the password in password.yamal - it works

![Screenshot2024_02_27_235536](https://github.com/serverpod/serverpod/assets/45402258/b0a16e0f-a0a4-4557-aebb-aaab97ac87ff)

![Screenshot2024_02_27_235552](https://github.com/serverpod/serverpod/assets/45402258/b0734006-1eec-4c99-a8d7-133c983f7ee5)
