### ISSUE TITLE
dart run warning

### ISSUE THREAD

**Issue by xxzj990** [serverpod/serverpod#1973]
**Describe the bug**
```
../../../.pub-cache/hosted/pub.flutter-io.cn/postgres-2.6.4/lib/src/substituter.dart:24:52: Warning: Operand of null-aware operation '!' has type 'Map<String, dynamic>' which excludes null.
 - 'Map' is from 'dart:core'.
    replace ??= (spec, index) => converter.convert(values![spec.name]);
                                                   ^
```

**To Reproduce**

`dart run bin/main.dart`

**Expected behavior**
No warning.

**Screenshots**
None.

**Serverpod versions**
 -  _CLI Version:_ 1.2.5
 - _Library version:_ 1.2.5

**Platform information**
SERVERPOD version: 1.2.5, dart: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64", time: 2024-02-28 09:55:10.949692Z
mode: development, role: monolith, logging: normal, serverId: default

**Additional context**
None.

**Comment by SandPod** [comment]
This is an issue in the underlying postgres library: https://github.com/isoos/postgresql-dart/issues/306.

Your server should functional normally, this is just a compile warning.
