### ISSUE TITLE
`DatabaseResultRow.toColumnMap()` does not always include table names

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1990]
`DatabaseResultRow.toColumnMap()` uses the full aliased column names `<tableName>.<columName>` for joined tables, but it uses just `<columnName>` for the base table. It would be better to always add the `<tableName>` (or specifically, the `queryPrefix`) for consistency.

**Comment by SandPod** [comment]
What database method are you using that returns the DatabaseResultRow?
Could you provide an example query where the result column name does not match your expected result?

If I remember correctly, we only return `DatabaseResultRow` from the `unsafeQuery` method where the developer is required to build the query manually. The column names in the result are the aliases used in the query, therefore it should be possible to fully control this from the input side.

**Comment by lukehutch** [comment]
Yes, that is the method I am using, and I didnt realize aliases were used directly, including for the "FROM" table in the query. Thanks, I think that resolves this.
