### ISSUE TITLE
Modify the entitlements for the MacOS project on `serverpod create`

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#2013]
When creating a new project, the MacOS target is missing an entitlement to connect to the server. It would be nice to add the entitlement automatically when running `serverpod create`.

The process could look something like:
- Check if the `mypod_flutter/macos/Runner/DebugProfile.entitlements` and/or the `mypod_flutter/macos/Runner/Release.entitlements` files exist.
- If they exist, overwrite them with new files with the `com.apple.security.network.client` entitlement added.

Example of release file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
</dict>
</plist>
```

Example of debug profile:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
</dict>
</plist>
```

**Comment by abdelaziz-mahdy** [comment]
since GitHub didn't add the mention i think due to this not being an issue, i opened a pr https://github.com/serverpod/serverpod/pull/2209
