### ISSUE TITLE
Documentation is incorrect for adding the auth module

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#2014]
Four issues with the auth module documentation [here](https://docs.serverpod.dev/concepts/authentication/setup):

- There is a `serverpod generate` missing after adding the module to the pubspec file.
- It says to add configuration to the `generate.yaml` (this is not wrong, but no longer needed).
- The 'Authentication' menu item is misspelled.
- It would be nice to add references at the bottom of the page to the different providers as they may otherwise be hard to find.

**Comment by bfemmer** [comment]
I'll pick this one up next. Analyzing the current documentation page against the four issues highlighted above, I will:

- add the `serverpod generate` step into the flow
- if you're referring to the section referencing nickname configuration in generator.yaml, I can either remove it or add text indicating that this is an _optional_ step ... any preference here, @vlidholt?
- not fix ... appears that the misspelling has already been fixed (unless I'm looking at the wrong thing)
- add references at the bottom of the page to the different providers

In addition, I'll update the typo in the following line:

- _Then apply the migration by starting the server with the apply-migration flag._

**Comment by bfemmer** [comment]
Ok, I see the third issue originally highlighted (misspelling in menu). It's in v1.1.1...

![image](https://github.com/serverpod/serverpod/assets/19608410/e03360e2-c079-4d12-8ae8-4de316261cda)

**Comment by bfemmer** [comment]
Made updates as described in items 1-3 in the original comment. I held off on implementing item 4 (references to providers) as there's already easy access to them via the navigation menu (shown below).

![image](https://github.com/serverpod/serverpod/assets/19608410/1cbc6f87-6468-4542-bfd6-7d5d448a9d30)

Easy enough to implement the references, so they can be added at any time. Looking for any feedback.

**Comment by bfemmer** [comment]
Updated menu item in 1.1.1 ...

![image](https://github.com/serverpod/serverpod/assets/19608410/ec301418-d0e9-4d1e-b191-a3d99f2c9a5b)
