### ISSUE TITLE
Add documentation for connecting directly to Postgres without using Docker

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#2015]
We should have some documentation on the steps required to set up Serverpod with Postgres without using Docker.

**Comment by chrisnorman7** [comment]
I was wondering about this myself for running on a server, so I would be very grateful for such documentation.

Thanks for an awesome project! I love it! 🥰

**Comment by darko-bacic** [comment]
I'll take this doc request 👨‍💻

**Comment by SandPod** [comment]
We now have documentation regarding how to connect to any Postgres instance: https://docs.serverpod.dev/concepts/database/connection
