### ISSUE TITLE
The UserAuthetication class is spelt incorrectly

### ISSUE THREAD

**Issue by staginghub** [serverpod/serverpod#2018]
The spelling of the UserAuthetication class is incorrect.  Its missing an 'n' : UserAuthe**N**tication

https://pub.dev/documentation/serverpod/latest/serverpod/UserAuthetication-class.html

**Comment by SandPod** [comment]
Hey @staginghub!

Thanks for taking the time to report this issue.

I'm closing this issue as it seems to duplicate #1887.
