### ISSUE TITLE
Inline fromJson deserialization for classes and remove serialization manager as parameter.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2027]
**Is your feature request related to a problem? Please describe.**
Currently all generated classes do roundtrips through the serialization manager to complete their deserialization in the `fromJson` method. This also makes the `fromJson` methods interface break convention by requiring an additional `SerializationManager` parameter to function correctly.

A recent change proved it possible to inline the full class serialization into the `toJson` method without the need of the `SerializationManager`, [example code here](https://github.com/serverpod/serverpod/blob/db5df4b21b06bf9ef34af5fcaf216906027ec307/tests/serverpod_test_server/lib/src/generated/models_with_relations/one_to_one/company.dart#L63-L70), the same change should be applied to the `fromJson` method.

**Describe the solution you'd like**
Inline deserialization for models in the `fromJson` method. The operation of the method should only rely on a single parameter which is the object map that represents the json data.

To achieve this extensions will need to be added for supported dart types providing a `fromJson` method that is used inline to deserialize the fields of a class.

Deserialization for the test `Company` class before change:

```dart
  factory Company.fromJson(
    Map<String, dynamic> jsonSerialization,
    _i1.SerializationManager serializationManager,
  ) {
    return Company(
      id: serializationManager.deserialize<int?>(jsonSerialization['id']),
      name: serializationManager.deserialize<String>(jsonSerialization['name']),
      townId:
          serializationManager.deserialize<int>(jsonSerialization['townId']),
      town: serializationManager
          .deserialize<_i2.Town?>(jsonSerialization['town']),
    );
  }
```

And a naive example of how it could look after the change:

```dart
  factory Company.fromJson(
    Map<String, dynamic> jsonSerialization,
  ) {
    return Company(
      id: jsonSerialization.containsKey('id')
          ? int.fromJson(jsonSerialization['id'])
          : null,
      name: String.fromJson(jsonSerialization['name']),
      townId: int.fromJson(jsonSerialization['townId']),
      town: jsonSerialization.containsKey('town')
          ? _i2.Town.fromJson(jsonSerialization['town'])
          : null,
    );
  }
```

**Serverpod version additions**
There should be 2 PRs created, one that targets the `1.2 stable` branch and one targeting `main`.

The PR targeting `1.2 stable` should preserve the `SerializationManager` as input parameter to the `fromJson` method but add a comment marking it as deprecated and that it will be removed in Serverpod 2.0. 

The PR targeting `main` should have the `SerializationManager` parameter removed from the `fromJson` method. The PR should therefore be marked as breaking `fix!: ....`.

**Additional context**

Some considerations when implementing:
- Even if the key of the field is present the data part could be null.
- If the serialization manager is removed from the `fromJson` interface we should be compatible with freezed generated classes: https://github.com/serverpod/serverpod/issues/873
- By inlining the deserialization we should be able to prove a helpful message when the data doesn't match the type: https://github.com/serverpod/serverpod/issues/1522

**Comment by SandPod** [comment]
This PR could be used as source of inspiration for improving incorrect serialization messages: https://github.com/serverpod/serverpod/pull/1528

**Comment by dkbast** [comment]
I ran into the same issue with freezed, I would like to add that it is important to be able to work with freezed both directions: Using a freezed class in a serverpod class and using a serverpod generated class in a freezed class.
