### ISSUE TITLE
Email/Password input validation for email auth endpoint

### ISSUE THREAD

**Issue by ordru** [serverpod/serverpod#204]
1. Add email validation for email auth endpoint
2. Add password validation for email auth endpoint

**Comment by ordru** [comment]
I see that some of the below is already available, however, I suggest to move what's available around, add what's not there and make it consistent across all paths to ensure that expensive operations (like db lookups) are not performed before validation occurs (first layer validation, second layer ...) . This isn't just about performance :) 

On endpoint:

- [ ] Validate that the email input is formatted properly (rule)
- [ ] Validate that the email is not bigger than a certain limit (rule)
- [ ] Validate that the password contains only the allowed characters (rule)
- [ ] Validate that the password is not smaller or bigger than a certain limit (rule)
- [ ] Optional/Extended: Validate that the password matches a certain level of "strength"
- [ ] Do the above before any other processing  (e.g. database lookups) 
- [ ] Log any auth calls that are not matching the rules defined (make it consistent across all auth paths)

**Comment by vlidholt** [comment]
Emails are already being validated both server and client side.
Added a length check for passwords on both client and server.
I think that should be sufficient for now, but a strength validator would be nice in the future.

**Comment by mikepyts** [comment]
@vlidholt sorry, but seems like email endpoint for authentication doesn't have validation, am I missing something?
![image](https://user-images.githubusercontent.com/26088845/221366897-f9bf504e-91b0-4ee3-b902-b55cda7f26da.png)

**Comment by vlidholt** [comment]
@mikepyts The validation is only needed when you create the account and insert the email in the database. In this case, if you have an invalid email address it will not be found and the user is not signed in.
