### ISSUE TITLE
SECURITY ISSUE: Client SDK always accepts all server certificates! [CWE-16]

### ISSUE THREAD

**Issue by Skycoder42** [serverpod/serverpod#2040]
In Version 1.2.5 of `serverpod_client`, one can find the following code in `serverpod_client_io.dart`:

```dart
    // TODO: Generate working certificates
    _httpClient.badCertificateCallback =
        ((X509Certificate cert, String host, int port) {
//      print('Failed to verify server certificate');
//      print('pem: ${cert.pem}');
//      print('subject: ${cert.subject}');
//      print('issuer: ${cert.issuer}');
//      print('valid from: ${cert.startValidity}');
//      print('valid to: ${cert.endValidity}');
//      print('host: $host');
//      print('port: $port');
//      return false;
      return true;
    });
```

This is a **serious** security misconfiguration, as this allows easy man in the middle attacks on **any** serverpod client application. You must remove this code ASAP and should propably file a security advisory on pub.dev for older serverpod versions.

FYI: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/creating-a-repository-security-advisory

**Comment by Isakdl** [comment]
Thank you for the report! Will push a fix for this to pub.dev asap, PR pending.
