### ISSUE TITLE
Disable/Enable user authentication per user on the auth endpoints

### ISSUE THREAD

**Issue by ordru** [serverpod/serverpod#205]
Allow authentication to be enabled or disabled per user

**Comment by vlidholt** [comment]
This should definitely be added as a method in the authentication module.

**Comment by vlidholt** [comment]
I looked into this a bit further. It's currently possible to use the `AuthConfig` when setting up the authentication module to configure the behaviour when authenticating. Set the `onUserWillBeCreated` parameter to block certain users from signing in. For instance, this can be used to only allow users from a certain domain to create an account.

In addition, you can sign out a specific user from the `Session` object. E.g. `session.auth.signOutUser(userId: aUserId)`.

Please reopen this issue if there is any additional functionality you need here and add a more detailed description.
