### ISSUE TITLE
Improved Email authentication error messages.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2051]
**Is your feature request related to a problem? Please describe.**
Serverpod receives multiple questions and issues regarding the email authentication module.

In many cases, most of the issues are simple problems that the developers could solve if the authentication module provided sufficient feedback.

Currently, when checks fail in the authentication module on the server or if a configuration step is missing, no information about what went wrong is logged.

For example, In the Flutter app, we always display `Email already in use` if any account creation step fails.

**Describe the solution you'd like**
Improve logging on the server side so developers can understand why validation fails.

If possible, improve client-side communication when account creation fails without changing the communication protocol.

**Additional context**
The solution needs to be made backward compatible with all existing clients and should target both `main` and `1.2 stable`.

Reported issues with the email authentication module:
- https://github.com/serverpod/serverpod/issues/1969

**Comment by sisyfus** [comment]
I'm encountering this problem with Serverpod 2.3.1 - is that expected? I received an "email already in use" error, despite the fact that the actual problem was due to the password minimum length not meeting the policy set on the server. (it met the client side policy, but not the server side)

**Comment by SandPod** [comment]
@sisyfus Unfortuntately, there was no way to add additional information in the response to the client. The new logs on the server side was the only interverntion we could do without this becoming a breaking change.

We are currently working on an improved authentication module with migration steps from the old one. There we will ensure these types of issues no longer happen.
