### ISSUE TITLE
What's the right naming for model and serializable classes

### ISSUE THREAD

**Issue by ebitogu** [serverpod/serverpod#2055]
When a new project is bootstrapped with `serverpod create mypod` the model classes are usually in the format:

`example.spy.yaml`

However, on the documentation site, I noticed that the .yaml extention is omitted and I keep seeing just `example.spy`

What is the correct naming convention?

And also what is `spy`?

Please note that I am developing on Android Studio IDE.

**Comment by SandPod** [comment]
Thanks for pointing to an answer @BenAuerDev 🌟 

We should add some clarification around this documentation.
