### ISSUE TITLE
Firebase Admin SDK breaks with some service account keys

### ISSUE THREAD

**Issue by dkbast** [serverpod/serverpod#2056]
**Describe the bug**
Apparently the Firebase SDK used by serverpod_auth_firebase_flutter has an issue where some service account keys cannot be read. This bug https://github.com/appsup-dart/firebase_admin/issues/7 and this here https://github.com/appsup-dart/firebase_admin/issues/21 probably describe what is going on. 
Finding this solutions was difficult, because it was not clear where the issue was coming from (in this case the admin SDK) - maybe there needs to be a way to prefix log output of dependencies to properly trace issues. This might be possible with Zones. 

For me generating the key 3 times did the trick because I came across these issues when diving into the dependencies of the auth package. 

**To Reproduce**
Follow the steps in https://docs.serverpod.dev/concepts/authentication/providers/firebase and create a service account key `firebase_service_account_key.json` -  since this is a flaky bug, you might need to generate a couple of files until you encounter the issue :)

**Expected behavior**
An error message which tells me that my keyfile could not be read (or an error message which suggests that this could be the case).

**Screenshots**
<img width="626" alt="image" src="https://github.com/serverpod/serverpod/assets/13539680/55714901-35a2-4e93-8f49-540e89e1d319">

**Serverpod versions**
 -  _CLI Version:_ 1.2.5
 - _Library version:_ 1.2.5

**Platform information**
Macos arm64

**Additional context**
An alternative implementation for the firebase admin sdk could be the implementation by Invertase https://github.com/invertase/dart_firebase_admin

**Comment by SandPod** [comment]
Thanks for the report @dkbast!

If I understand the issue correctly, we can't really fix the issue from our side. But what we can do is to improve our documentation so that users are aware of this issue.

Does that sound like an acceptable action based on the bug report?

**Comment by dkbast** [comment]
Yes - I think mentioning it in the tutorial should be enough, maybe add a reminder in the future to reinvestigate this once either of the firebase SDKs leaves alpha?

**Comment by SandPod** [comment]
We no longer depend on the `firebase_admin` package. We never got around to updating the documentation but my question is if this could be closed now instead?

**Comment by dkbast** [comment]
If you no longer depend upon the this package this can probably be closed, as it was mostly an upstream issue :)
