### ISSUE TITLE
notInSet fails if the set is empty

### ISSUE THREAD

**Issue by dkbast** [serverpod/serverpod#2070]
**Describe the bug**
I have a set of ids and want to exclude them from a query using "notInSet", for a new user the set can potentially be empty this results in an invalid query from the ORM, since it seems to be unable to work with an empty set:

This query
```Dart
    final newMasters = Master.db.find(session,
         where: (t) => t.id.notInSet(existingMasterIds),
        limit: n);
```
Results in
```SQL
SELECT "master_definitions"."id" AS "master_definitions.id", "master_definitions"."uniqueId" AS "master_definitions.uniqueId", "master_definitions"."fields" AS "master_definitions.fields", "master_definitions"."combinations" AS "master_definitions.combinations" FROM "master_definitions" WHERE ("master_definitions"."id" NOT IN () OR "master_definitions"."id" IS NULL) LIMIT 5
```

Possible workaround:
```Dart
    final newMasters = Master.db.find(session,
        where: existingMasterIds.isEmpty
            ? null
            : (t) => t.id.notInSet(existingMasterIds),
        limit: n);
```

![image](https://github.com/serverpod/serverpod/assets/13539680/9e61db16-b02a-47c8-8b3c-211bd4bcdb8c)

**Serverpod versions**
 -  _CLI Version:_ 1.2.5
 - _Library version:_ 1.2.5

**Platform information**
MacosArm 64
Postgres running in Docker Desktop with default docker compose file

**Comment by SandPod** [comment]
This issue is connected to https://github.com/serverpod/serverpod/issues/1968.

It should be solved using the same pattern, following the expected dart behavior:

```dart
  test('filter with empty set', () {
    var mySet = <int>{};
    var arr = [1, 2, 3, 4, 5, 6];
    var result = arr.where((element) => !mySet.contains(element));

    expect(result, arr);
  });
```

**Comment by SandPod** [comment]
Fixed by: https://github.com/serverpod/serverpod/pull/2073
