### ISSUE TITLE
Authentification custom providers   `await session.scopes empty`

### ISSUE THREAD

**Issue by ihebmeftah** [serverpod/serverpod#2082]
I use custom providers in authentification : when i want access to scopes in the server using session  `await session.scopes` i recieve empty list (In the past after i migrate to custom providers i use email auth work fine )

<img width="332" alt="Capture d’écran 2024-03-29 à 6 51 39 PM" src="https://github.com/serverpod/serverpod/assets/78818443/f0f94080-96af-47a6-bfed-438d68fd42dd">
<img width="332" alt="Capture d’écran 2024-03-29 à 6 51 52 PM" src="https://github.com/serverpod/serverpod/assets/78818443/46fd6d0d-7fe1-4935-8a57-eb540ce15406">
<img width="1000" alt="Capture d’écran 2024-03-29 à 6 52 31 PM" src="https://github.com/serverpod/serverpod/assets/78818443/3843ecdb-8fb7-4078-9194-274c518846f8">

**Comment by SalahAnwer** [comment]
I got this issue too

**Comment by ihebmeftah** [comment]
> I got this issue too

@SalahAnwer try pass this param in siginin methode  `.signInUser(userInfo.id!, 'myAuthMethod', scopes: userInfo.scopes)` this is my example
