### ISSUE TITLE
Don't crash when web/templates/ directory doesn't exist.

### ISSUE THREAD

**Issue by schultek** [serverpod/serverpod#2101]
**Is your feature request related to a problem? Please describe.**

I would like to be able to remove the `web/templates/` folder when not using templates (and e.g. jaspr for rendering).
Currently the server crashes with: 
`[ERROR] PathNotFoundException: Directory listing failed, path = 'web/templates/' (OS Error: No such file or directory, errno = 2)`

**Describe the solution you'd like**
Make the directory optional.

**Describe alternatives you've considered**
Currently it requires me to have an empty directory.

**Comment by SandPod** [comment]
This should be fixed 👍
Thanks for reporting the issue.

**Comment by schultek** [comment]
Thanks. Do you know which version this lands in?

**Comment by SandPod** [comment]
We should be able to add this to a 1.2.x version.
