### ISSUE TITLE
UserInfo type not imported by libs on flutter side.

### ISSUE THREAD

**Issue by dufguix** [serverpod/serverpod#2122]
Hi,
In the flutter project, I get a UserInfo object thanks to `sessionManager.signedInUser;`

But the type UserInfo isn't imported by libs.

I have tried to import serverpod_flutter, serverpod_auth_email_flutter, serverpod_auth_shared_flutter.

**Comment by Isakdl** [comment]
It is located in the package `serverpod_auth_client`.

**Comment by dufguix** [comment]
thanks !

**Comment by etegan** [comment]
Should this not be exported by serverpod_auth_shared_flutter since that is the lib used in the flutter directory?
