### ISSUE TITLE
Make `toJson` and `fromJson` always compatible.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2149]
**Is your feature request related to a problem? Please describe.**
This issue assumes that the serialization manager is removed from the `fromJson` interface (Issue tracked here:  https://github.com/serverpod/serverpod/issues/2027).

Serverpod models expose two methods to create JSON from a model, `toJson` and `allToJson`.

Currently, `toJson` is used to create the JSON that is serialized for the client, and `allToJson` is used to create the "real" JSON representation of the object (used as base for serializing to the database).

If a class is scoped as serverOnly, or if a field is scoped as `serverOnly` or `none` the field will be removed from the `toJson` serialization.

This makes the `fromJson` and `toJson` behave unexpectedly.

For example, given a model definition that looks like this:
```yaml
class: MyClass
serverOnly: true
fields:
  serverOnlyScope: String
```

The following code would result in a throw:

```dart
var a = MyClass();
var b = MyClass.fromJson(instance.toJson()); // Throws because it is missing the required serverOnlyScope field
```

While this works:
```dart
var a = MyClass();
var b = MyClass.fromJson(allToJson());
```

**Describe the solution you'd like**
- Rename the current `toJson` method to `toJsonForClient`.
- Rename the current `allToJson` method to `toJson` and keep the existing behavior.

**Additional context**
- [ ] This is a breaking change so it will need to be implemented in a major version upgrade (target only main)
- [ ] This changes the behavior of the methods so we should add upgrade instructions and documentation on how these two methods work after this change.

**Comment by klkucaj** [comment]
We agreed to rename "toJsonForClient" to "toConstraintJson".
