### ISSUE TITLE
How to create production DB tables, 1.2 docs outdated?

### ISSUE THREAD

**Issue by jblankenship5** [serverpod/serverpod#2151]
I have been using serverpod locally for a while and am now ready to deploy. I followed this guide https://docs.serverpod.dev/deployments/deploying-to-gce-terraform, and I'm stuck on the last step of creating the production tables. It mentions to 

> Once connected, run the database queries found in generated/tables-serverpod.pgsql and in generated/tables.pgsql. When you have added the tables for the database, Serverpod should be able to start. However, it could take an hour before the correct SSL certificates are created and validated.

I don't have a generated/tables-serverpod.pgsql file and generated/tables.pgsql mentions that it's deprecated and shouldn't be used. How should I create the production tables and finish my deployment. Also, are there any docs on setting up a staging environment?

**Comment by SandPod** [comment]
Hey @jblankenship5 👋 

Sorry, updating that documentation was missed; the database query you should apply is called `definition.sql` and can be found in your latest migration directory `migrations/<LATEST_MIGRATION>/definition. SQL`.

I have a PR updating the docs on the way now.

We don't provide any official docs for setting up a staging environment yet. Using the same steps but in a different environment should yield the wanted results though.
