### ISSUE TITLE
Missed/Typo single colon (:) in documentation

### ISSUE THREAD

**Issue by hussainxgit** [serverpod/serverpod#2158]
[Finding multiple rows
To find multiple rows, use the same principle as for finding a single row.](https://docs.serverpod.dev/concepts/database/crud)

```
var companies = await Company.db.find(
  session,
  where: (t) => t.id < 100,
  limit 50, <<<<<<<<<<<<<<<<<<<
);
```

**it should be (limit:50,)**
thanks to u guys for the great efforts <3

**Comment by SandPod** [comment]
Hey @hussainxgit!

Thanks for finding these issues!

Feel free to create a PR towards our documentation repo directly to fix these.
You can find our documentation repo here: https://github.com/serverpod/serverpod_docs

**Comment by bfemmer** [comment]
PR submitted ... https://github.com/serverpod/serverpod_docs/pull/96.
