### ISSUE TITLE
Where are the application logs on aws?

### ISSUE THREAD

**Issue by jblankenship5** [serverpod/serverpod#2161]
I'm trying to run my serverpod on AWS with terraform. So far I've made the following modifications to get terraform apply and the github action to work. So far the production database is running and I have connected to it locally and modified it with the definition.sql queries.

- modified engine version in database.tf to 16.1 from 14.2 to avoid "Cannot find version 14.2 for postgres" error.
- modified aws buckets config according to this post to avoid ACL error - https://github.com/serverpod/serverpod/issues/925#issue-1718549192
- modified dart sdk version to 3.0.0 in init-script.sh and github action according to this post https://github.com/serverpod/serverpod/discussions/445#discussioncomment-4333113
- changed prod database links to remove the 'private-production' part

I'm still getting a 502 and have found no additional help among the other problems posted from others. I simply want to see the application logs for serverpod so I can debug further, but I'm unfamiliar with AWS or where serverpod is logging.

EDIT: found them /home/ec2user/serverpod.log and serverpod.err, closing.

**Comment by eripoll** [comment]
@jblankenship5 Do you have a working copy of your tf files somewhere? I have been fighting for over two days trying to deploy on aws and hitting wall after wall.
The last one being a connection issue between the EC2 and the database...
I am this close to giving up
