### ISSUE TITLE
Server does not always report when streaming connections fail

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2188]
In `server.dart`, method `_handleWebSocket`, if an un-serializable type is passed in, this line will fail:

https://github.com/serverpod/serverpod/blob/35878d0e8b35469b9357e8b0d63318ef5d628369/packages/serverpod/lib/src/server/server.dart#L435

(In my case, I accidentally put an extra comma after an expression in a `where:` clause, which meant that an `Expression` was wrapped in a Dart `Record` object, so JSON serialization to Postgres failed.)

Assuming that you're using the streaming connection for Serverpod Chat, what happens after that is that the exception is caught, and then a `MessageLogEntry` is logged. However, the chat contoller's `joinFailed` field is not set to `true`, and the controller's `ConnectionStatusListener` is not called. Therefore, the client is not notified that the attempt to join a channel failed.

Also, the exception may be logged to the Serverpod log, but it should also be printed to the debug console. Right now there is no indication on either the server console or the client that the join attempt failed.

**Comment by SandPod** [comment]
We will have to take a closer look at this one.

> (In my case, I accidentally put an extra comma after an expression in a where: clause, which meant that an Expression was wrapped in a Dart Record object, so JSON serialization to Postgres failed.)

Is it possible to provide an example input that would trigger this issue? That helps us faster pintpoint what needs to be done to fix the issue.

**Comment by lukehutch** [comment]
OK, here is the statement with the problematic comma:

```dart
    final likeActions = await UserAction.db.find(session,
        where: (t) =>
            ((t.fromUserId.equals(userId1) & t.toUserId.equals(userId2)) |
                (t.fromUserId.equals(userId2) & t.toUserId.equals(userId1))) &
            (t.likeActionType.equals(LikeActionType.like),));  // <---
```

And here is the stacktrace of the exception:

![image](https://github.com/serverpod/serverpod/assets/811305/4c5527ee-a0a3-4483-979e-13ab9f83d952)

The problem is that the type of `&` is `Expression<dynamic> &(dynamic other)`, and the type of `other` is not checked. In this case, it ends up being `Record`, and that is passed all the way down to the Postgres serializer, because other serialization attempts fail.

I suggest checking the type of `other` for this and all similar operators, but before you do that, the exception handling should be fixed to actually report this to the console, rather than failing silently.

Thanks!

**Comment by lukehutch** [comment]
I have another similar silent failure: my code is failing here with `DatabaseException: relation <X> does not exist`, and this failure is never reported to the console.

![image](https://github.com/serverpod/serverpod/assets/811305/1a284431-f2a3-468d-a95f-aa866e9b4194)
