### ISSUE TITLE
VS Code can't find `DateTimeJsonExtension` extension

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2206]
Client-side code cannot find the `DateTimeJsonExtension` extension in the most recent git version of Serverpod:

![image](https://github.com/serverpod/serverpod/assets/811305/56e8a562-ce51-49b3-bc45-1066de247345)

Note that the client project is added to the same workspace as the flutter and server projects.

**Comment by lukehutch** [comment]
Weirdly, the code builds and runs fine -- it is only broken in the editor.

**Comment by bfemmer** [comment]
This is kinda interesting. I had an "anomaly" with `DateTimeJsonExtension` occur in my project when I was working on a PR in main (2.0.0-alpha.2 version) last week. 

![image](https://github.com/serverpod/serverpod/assets/19608410/f644a80b-c040-4204-a099-b63cc456fa8e)

In my case, I inadvertently omitted the dependency override for the `serverpod_serialization` package in the server project. I didn't look into it any further and went on with my work after adding the dependency.

![image](https://github.com/serverpod/serverpod/assets/19608410/880aa57b-f57b-45a4-9bbe-b317ccce36b4)

Do you have any other observations you might be able to share?

**Comment by lukehutch** [comment]
I already checked for that dep, and I do require that deep in my project.

**Comment by lukehutch** [comment]
OK, the problem was that the flutter project (the only place I was using the client library) had the `serverpod_serialization` dep, but the client project did not (which is why VS Code couldn't find it). Thanks!
