### ISSUE TITLE
Making the Email Verification Validation Code length Configurable in Serverpod Auth Module

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2247]
### Discussed in https://github.com/serverpod/serverpod/discussions/2221

> 
> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **adiltirur** May  8, 2024</sup>
> Hello everyone,
> 
> I've been working with the Serverpod auth module and I've noticed that the validationCode for email verification is currently set to 8 digits. For the purpose of enhancing user experience in mobile apps, I'm interested in making this length configurable, allowing for either 4 or 6 digit codes.
> 
> I'm wondering if there's already a way to configure the length of the validationCode that I might have missed. If not, could anyone provide guidance on how I might implement this feature?
> 
> Any suggestions or insights would be greatly appreciated. Thank you in advance for your help.</div>
> 

### Feature
Make it possible to configure the email verification validation code length to make it possible to improve mobile UI.

**Comment by BenAuerDev** [comment]
@SandPod can I have a look at that?
