### ISSUE TITLE
Documentation still uses "findRow" instead of "findFirstRow" 

### ISSUE THREAD

**Issue by kieran-myopnotes** [serverpod/serverpod#2260]
**Describe the bug**
The documentation still uses findRow instead of findFirstRow in a bunch of the examples.

**Comment by kieran-myopnotes** [comment]
I have submitted a PR for this here: https://github.com/serverpod/serverpod_docs/pull/104

**Comment by Isakdl** [comment]
Thank you for the issue and the PR! Much appreciated :)
