### ISSUE TITLE
Trying to dispose a StreamingConnectionHandler

### ISSUE THREAD

**Issue by Katekko** [serverpod/serverpod#2261]
**Describe the bug**
Trying to dispose a StreamingConnectionHandler, line 55 its adding another _onConnectionStatusChanged, I don't think this is right.
I was trying to dipose all the elements in my controller but it keep duplicating my streams and I found out why. 

Lemme know if this is the expected, if is not, I will create a PR to fix this (changing to removeStreamingConnection)

![image](https://github.com/serverpod/serverpod/assets/13632735/12cda4ee-d92e-4a15-a5f3-ea1a14cb4ac2)

**To Reproduce**
1. Just try to use the dispose method on StreamingConnectionHandler

**Expected behavior**
Maybe remove the stream from client? 
![image](https://github.com/serverpod/serverpod/assets/13632735/5839de73-e61e-4f4c-b321-ae262f30a77e)

**Serverpod versions**
 -  _CLI Version: 1.2.7
 - _Library version: 1.2.7

**Platform information**
I'm running in windows

**Comment by Katekko** [comment]
@Isakdl can you confirm for me?

**Comment by BenAuerDev** [comment]
@Katekko is it duplicating the stream itself or the items within the stream?

**Comment by Katekko** [comment]
> @Katekko is it duplicating the stream itself or the items within the stream?

The stream. Instead removing the stream in the client, its adding the same listener in the dispose method. I guess this need to be the remove instead the add

**Comment by Katekko** [comment]
Let me clarify what I meant earlier. The issue isn't with the stream itself but with the duplication of the listener. Specifically, another listener is being added in the dispose method, even though a listener is already added when the StreamingConnectionHandler is created. If the listener wasn't added in the constructor, then the dispose method shouldn't be responsible for adding it either.
