### ISSUE TITLE
File upload doc needs more details

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2273]
This page

https://docs.serverpod.dev/next/concepts/file-uploads

says

> You may also want to add the bucket as a backend for your load balancer to give it a custom domain name.

I have no idea what this means or if it's needed, but "may" makes it sound optional.

However then I don't know if I need a custom domain name for the server config, for `publicHost`:

```dart
  pod.addCloudStorage(gcp.GoogleCloudStorage(
    serverpod: pod,
    storageId: 'public',
    public: true,
    region: 'auto',
    bucket: 'my-bucket-name',
    publicHost: 'storage.myapp.com',
  ));
```

Also it's not clear to me whether `bucket` and `publicHost` are supposed to be the same name -- the bucket name for my app is `storage.clicksocial.app`, so are my `bucket` and `publicHost` supposed to be the same?

Please expand these docs...

**Comment by vlidholt** [comment]
Fixed in the upcoming 2.1 documentation.
