### ISSUE TITLE
Found almost all typos

### ISSUE THREAD

**Issue by BenAuerDev** [serverpod/serverpod#2276]
## Description

While looking at some source code I found a typo. I didn't want to make a PR for a single typo so I played around with a cli-tool and tried to find as much as possible.

##### There are very few! And around 95% of them are not in operational code. Like in:

- comments
- doc-comments
- test-descriptions
- assert() in "rainy day test"

##### But there are some that concern operational code and maybe require changes across multiple files.

- `/packages/serverpod_serialization/lib/src/copy_with.dart` :    `clonableTypeNames` instead of `cloneableTypeNames`

- `/tools/serverpod_cli/lib/scr/database/exptensions.dart`:  `var refColumsFmt` instead of `var refColumnsFmt`

- multiple `init-script.sh`:  `ehco "Installing wget"` instead of `echo "Installing wget"`

One where I'm not sure if it matters:
`/templates/serverpod_templates/projectname_server_upgrade/deploy/aws/terraform/variables.tf`:  deployning => deploying

And a generated file imports:
`import 'long_identifiers/models_with_relations/relation_to_mutiple_max_field_name.dart'`, (should this be ..._multiple_max_... ?)

## Details on tool / How to reproduce

I used [cspell](https://cspell.org/) and ignored:

- non english words (`Skinnskatteberg` and `lorem`, `ipsum` ...)
- names (of people, frameworks etc.)
- words like: `tablename`, `testuuid` (that were flagged but are correct)
- tech terms (`relname`, `relnamespace`)

**Comment by craiglabenz** [comment]
Are you planning to open a PR with these typo changes?

**Comment by BenAuerDev** [comment]
Hi Craig,

Yes I just wanted to get feedback from the serverpod team first. 
And also ask if it would be wise to do the non operational code separate from the rest or even split it further. 

Of course if you have suggestions I'm all ears (eyes) 😊

**Comment by craiglabenz** [comment]
My hunch is that you should open a PR - it may be hard for them to offer much feedback without seeing your changes.

**Comment by SalahAnwer-dev** [comment]
Also add a typo in `templates/serverpod_templates/projectname_server_upgrade/deploy/aws/terraform/init-script.sh` line 8.
`ehco` instead of `echo`

**Comment by BenAuerDev** [comment]
Ok 😊 will do. Thanks 👍

**Comment by BenAuerDev** [comment]
@SalahAnwer-dev got it 😊👍
