### ISSUE TITLE
Double Values Encoded as Integers in Flutter Web Causing Type Mismatch

### ISSUE THREAD

**Issue by freppps** [serverpod/serverpod#2295]
**Describe the bug**
Double values are encoded as integers in the Web version of the app, leading to a type mismatch error. Specifically, double values such as 1.0 are being decoded as int, causing a runtime error. This issue does not occur in the iOS version of the app, as far as tested.

**To Reproduce**
1. Create a fresh project serverpod create mypod
1. Modify model, endpoint and main according to the below
1. Run serverpod generate and serverpod create-migration
1. Start docker containers docker compose up --build --detach
1. Run and apply migration dart run bin/main.dart --role maintenance --apply-migrations
1. Run the flutter app in iOS and click "Send to Server" (Working)
1. Run the flutter app in Web and click "Send to Server" (Not working)
Exception from log:
```
METHOD CALL: example.helloExample duration: 4ms numQueries: 0 authenticatedUser: null
type 'int' is not a subtype of type 'double' in type cast
#0      new Example.fromJson (package:mypod_server/src/generated/example.dart:31:51)
#1      Protocol.deserialize (package:mypod_server/src/generated/protocol.dart:40:26)
#2      EndpointDispatch._formatArg (package:serverpod/src/server/endpoint_dispatch.dart:175:33)
#3      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:115:25)
<asynchronous suspension>
#4      Server._handleRequest (package:serverpod/src/server/server.dart:290:18)
<asynchronous suspension>
```

**Expected behavior**
Explicitly parse double values using .toDouble() or ?.toDouble() for nullable values to prevent this type mismatch as mentioned in [Serverpod Discussions #110](https://github.com/serverpod/serverpod/discussions/110).

**Screenshots**
![image](https://github.com/serverpod/serverpod/assets/41991003/de3858c6-2dd4-45dd-a9da-f66c8651a564)

**Serverpod versions**
 -  _CLI Version: Serverpod version: 2.0.0-alpha.3
 - _Library version: serverpod: 2.0.0-alpha.3

**Platform information**
MacOS
App running in Flutter iOS (Working)
App running in Flutter Web (Not working)

**Additional context**
N/A

**Models**
Replace the content in existing `example.spy.yaml` under the "mypod_server" folder with:
```
class: Example
fields:
  name: String
  data: int
  dataDouble: double
```

**Endpoints**
Replace the content in existing `example_endpoint.dart` under the "mypod_server" folder with:
```
import 'package:mypod_server/src/generated/protocol.dart';
import 'package:serverpod/serverpod.dart';

class ExampleEndpoint extends Endpoint {
  Future<String> hello(Session session, String name) async {
    return 'Hello $name';
  }

  Future<String> helloExample(Session session, Example example) async {
    return 'Hello $example';
  }
}

```

**Endpoints**
Replace the line in existing `main.dart` under the "mypod_flutter" folder from:
```
final result = await client.example.hello(_textEditingController.text);
```
With:
```
final result = await client.example.helloExample(Example(name: 'name', data: 1, dataDouble: 1));
```

**Comment by SandPod** [comment]
Hey @freppps!

Thanks for the detailed report, it looks like we are not correctly parsing our serialized doubles and are falling into this trap: https://github.com/dart-lang/sdk/issues/45160

We will fix this.
