### ISSUE TITLE
Generated client.dart-code has errors (Target of URI doesn't exist - database_connection.dart)

### ISSUE THREAD

**Issue by hoeverma** [serverpod/serverpod#2303]
**Describe the bug**
Recently, I used transaction for the first time in my serverpod app. I used it in the implementation of endpoints. Now, the file protocol/client.dart, produced by the command 'serverpod generate' contains the line

import 'package:serverpod/src/database/database_connection.dart' as _i4;

This produces the error:

Target of URI doesn't exist: 'package:serverpod/src/database/database_connection.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.

**To Reproduce**
In my case, the following endpoint implementation caused the error:

import 'package:eventer_server/src/generated/event_location.dart';
import 'package:serverpod/serverpod.dart';

class EventLocationEndpoint extends Endpoint {
  Future<EventLocation> create(Session session, EventLocation eventLocation,
      Transaction? transaction) async {
    return await EventLocation.db
        .insertRow(session, eventLocation, transaction: transaction);
  }

  Future<int> delete(Session session, EventLocation eventLocation,
      Transaction? transaction) async {
    return await EventLocation.db
        .deleteRow(session, eventLocation, transaction: transaction);
  }
}

**Expected behavior**
The generated code should be correct.

**Serverpod versions**
 -  _CLI Version:_ 1.2.7
 - _Library version:_ 1.2.7

**Platform information**
I use viscose on Mac.

**Comment by SandPod** [comment]
Hello @hoeverma!

The reason you are getting this error is that you have a transaction as an input parameter to an endpoint. This makes it generate on the client side as well.

Transactions are a server-only concept since they only make sense in the scope of an open database connection. Once your endpoint has returned the connection for that request to the database will be closed and the transaction would not be based in anything.

If you remove `transaction` from your endpoints parameters the error should go away.

**Comment by hoeverma** [comment]
Thank you very much, I got it!

**Comment by SalahAnwer-dev** [comment]
@SandPod But if I wanted to run a transaction within the current endpoint and also call a method from another endpoint as part of the same transaction, I would have to pass the transaction object as a parameter to that other endpoint, right?

**Comment by SandPod** [comment]
> @SandPod But if I wanted to run a transaction within the current endpoint and also call a method from another endpoint as part of the same transaction, I would have to pass the transaction object as a parameter to that other endpoint, right?

We don't recommend calling endpoints within endpoints. In that case, I would suggest you extract the shared logic from the endpoint and just make it a regular function. Then the transaction could be a parameter to that shared function.

**Comment by SalahAnwer-dev** [comment]
@SandPod But if I had to, is this a bad approach to do it ?

```dart
extension SessionX on Session {
  UsersEndpoint get usersEndpoint {
    final usersEndpoint = (server.endpoints
        .getConnectorByName(UsersEndpoint.endpointConnectorName)
        ?.endpoint as UsersEndpoint?);
    if (usersEndpoint == null) {
      throw Exception(
          'Endpoint connector "${UsersEndpoint.endpointConnectorName}" not found');
    }
    return usersEndpoint;
  }

  ConfigsEndpoint get configsEndpoint { ... }

  ...
}
```
And then in any other endpoint I can do this:
```dart 
final users = await session.usersEndpoint.getAll(session);
```

**Comment by SandPod** [comment]
@SalahAnwer-dev  I'm sorry, but I don't think I understand the motivation behind forcing the business logic to be defined inside of the endpoint. Could you elaborate a bit on what you see the as benefits and at the same time highligt the drawbacks of moving it out?

The main benefit that endpoint bring are:
1. They define the API layer of your server (serialization and endpoints definition).
2. Generated client code to make calling the server simple.
3. Authentication is handled by the framework.

From the example code you have presented, I don't understand how this is helpful.

From my perspective, it seems that you have two, or more, entry points into your server that rely on the same business logic.  
This should be the perfect opportunity to encapsulate that business logic with a clear interface. It also adds the benefit that if your endpoints evolve in a different direction, the unit of your buisiness logic would still stay the same.
