### ISSUE TITLE
Failed to download templates

### ISSUE THREAD

**Issue by jzllovecat** [serverpod/serverpod#2342]
command: serverpod
hint: Downloading templates for version 2.0.0
error: Failed to download templates.

so i commanded dart pub global activate serverpod_templates,
now,serverpod_cli and serverpod_templates in the global_packages,
retry severpod still report the error.

**Comment by SandPod** [comment]
Hello @jzllovecat.

> so i commanded dart pub global activate serverpod_templates,

It looks like you are trying to activate the templates package which is not required.
You should run `dart pub global activate serverpod_cli`.

You can read more on how to get started on this page: https://docs.serverpod.dev

Do you still have an issue if you follow the instructions there?

If so, what system are you running on? And what is the log output if you add the verbose flag.

**Comment by jzllovecat** [comment]
@SandPod serverpod_cli is already active

**Comment by SandPod** [comment]
Thanks for the additional information.

Unfortunatelly our logging is lacking there a bit.
But there are a couple of steps we can try to figure out what is going wrong.

Does the cli have sufficient privileges to create a folder in your home directory?
The CLI will create a folder named `.serverpod` in your home directory root. Does this folder exist?

Can you access `https://pub.dev/packages/serverpod_templates/versions/2.0.0.tar.gz`?
You could download the templates manually using that link and then unpack it under `.serverpod/2.0.0/serverpod_template/`.

**Comment by jzllovecat** [comment]
Thank you!
.serverpod is exist.
serverpod_templates-2.0.0 already in the pub_cache\hosted\pub.dev.
I copied the content to .serverpod/2.0.0/serverpod_template/.
Now it's working normally!
