### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by lastmeta** [serverpod/serverpod#236]
in the yaml file can I specify a default value for the field?

```
class: Address
table: address

fields:  
  address: String
  used: bool
    #default: true  #something like this?
```

**Comment by fischerscode** [comment]
@vlidholt do you envision any special way how this should be implemented? Sounds like a nice PR...

**Comment by ramyak-mehra** [comment]
we can handle the default value on the sql side or dart side

**Comment by vlidholt** [comment]
It would be a cool addition, but I think the implementation needs to be thought through. Handling the default value on the Dart side is probably best, but it may only be possible to do primitive types (other serializable objects would be tricky). Also, what should the syntax look like. Needs to feel clean and be backwards compatible.

**Comment by fischerscode** [comment]
I think it would be best to provide the serialized version of the data in the yaml file. This could be used to set the default in the database, and a dart default could be constructed, too, by using the `SerializationManager`.

I'm currently working on a package that helps specify and parse yaml based configuration files. I think it'd be the perfect fit for specifying the class definitions. (Had this as a usecase in mind)

**Comment by SandPod** [comment]
Closing this as duplicate for the more specified issue here https://github.com/serverpod/serverpod/issues/1140.

PS. This is being implemend right now 🙌
