### ISSUE TITLE
Password reset code still valid after successful password reset

### ISSUE THREAD

**Issue by Thanados** [serverpod/serverpod#2360]
**Describe the bug**

Hello, I have just implemented the password reset flow with serverpod. I noticed that if the user has successfully changed his password, the reset validation password code is still valid.  Therefore, the password can be changed multiple times with the same validation password code. 

In my opinion, this poses a security risk, as attackers could obtain the validation password code and change the password again even after a user has changed it. 

**To Reproduce**
1. Start Password reset flow with client.modules.auth.email.initiatePasswordReset(email)
2. Verify password reset code with client.modules.auth.email.verifyEmailPasswordReset(verificationCode)
3. Change password with client.modules.auth.email.resetPassword(verificationCode, password)
4. Change again the password with the same verification code client.modules.auth.email.resetPassword(verificationCode, password)

**Expected behavior**

The validation code should be invaild after successful password change.

**Screenshots**

not needed.

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling.
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

Serverpod version: 2.0.0

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

Developing on Mac for web.

**Additional context**

**Comment by Isakdl** [comment]
Thank you for the report! Agreed the code should be invalidated after use.
