### ISSUE TITLE
Issue with postgres version when deploying to AWS

### ISSUE THREAD

**Issue by edzzn** [serverpod/serverpod#2375]
**Describe the bug**
There is an issue when deploying the application using Terraform where the build process fails due to an invalid PostgreSQL version specified in the Terraform configuration file.

**To Reproduce**
1. Follow the deployment tutorial: https://docs.serverpod.dev/deployments/deploying-to-aws
2. Ryb `terraform apply`

**Expected behavior**
I expect the build to succed.

**Actual Result**
I get the following error
```
 Error: creating RDS DB Instance (inmueble): InvalidParameterCombination: Cannot find version 14.2 for postgres
│ 	status code: 400, request id: 1ac11bf9-3098-471a-aedf-0dc7d78fe46e
│
│   with aws_db_instance.postgres,
│   on database.tf line 1, in resource "aws_db_instance" "postgres":
│    1: resource "aws_db_instance" "postgres" {
│
```

If I run `aws rds describe-db-engine-versions --engine postgres --query "DBEngineVersions[].EngineVersion"` to list the available versions I can see that `4.2` is not one of them.

```
[
    "11.22",
    "11.22-rds.20240418",
    "11.22-rds.20240509",
    "12.15",
    "12.16",
    "12.17",
    "12.18",
    "12.19",
    "13.11",
    "13.12",
    "13.13",
    "13.14",
    "13.15",
    "14.9",
    "14.10",
    "14.11",
    "14.12",
    "15.4",
    "15.5",
    "15.6",
    "15.7",
    "16.1",
    "16.2",
    "16.3"
]
```

## Resolution
To fix the issue I need to change the version to: a valid one. The update needs to be updated on: 

`inmueble_server/deploy/aws/terraform/database.tf`
```
# Staging
resource "aws_db_instance" "postgres_staging" {
  count = var.enable_staging_server ? 1 : 0

  identifier          = "${var.project_name}-staging"
  allocated_storage   = 10
  engine              = "postgres"
  engine_version      = "14.10" // change here
  instance_class      = "db.t3.micro"
  db_name             = "serverpod"
  username            = "postgres"
  password            = var.DATABASE_PASSWORD_STAGING
  skip_final_snapshot = true
  vpc_security_group_ids = [
    aws_security_group.database.id
  ]
  publicly_accessible  = true
  db_subnet_group_name = module.vpc.database_subnet_group_name
}
```

**Serverpod versions**
 -  _CLI Version: 2.0.1
 - _Library version: 2.0.0

**Comment by SandPod** [comment]
Hey @edzzn!

Thank you for that detailed report.
It appears that Amazon RDS 14.3 is now deprecated, source https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-versions.html#postgresql-versions-version143.

We will update the terraform scripts to a new supported version.
