### ISSUE TITLE
sql querying for in list

### ISSUE THREAD

**Issue by lastmeta** [serverpod/serverpod#238]
I'm not sure if this would work because I didn't test it yet, but I noticed serverpod has `.equals()` and `.notEquals()` on like all `Column` objects. I would suspect that the next most useful thing to says is, "is this value in a list" so I made this little extension following your pattern:

```
/// TODO: needs testing
extension IsInExtension on ColumnInt {
  /// Creates an [Expression] checking if the value in the column is in a list
  /// of specified values.
  Expression isIn(List<int>? values) {
    if (values == null) {
      return Expression('"$columnName" IS NOT NULL');
    } else {
      return Expression('"$columnName" IN (${values.join(',')})');
    }
  }
}
```

and I'm planning on using it like this:

```
await Table.find(session, where: (table) => table.id.isIn(selected));
```

Do you think that would work? If so, maybe you want to include it by default?

**Comment by vlidholt** [comment]
Great addition, will add this. Thank you!

**Comment by Kstev239** [comment]
Would then like to suggest a notIn method:

```
extension NotInExtension on ColumnInt {
  Expression notIn(List<int?>? value) {
    if (value == null) {
      return Expression('"$columnName" IS NULL');
    } else {
      return Expression('"$columnName" NOT IN (${value.join(",")})');
    }
  }
}
```

**Comment by SandPod** [comment]
This should be available now using the `inSet` expression. Check out https://github.com/serverpod/serverpod/blob/7186d782beed2b0bdd961a3283612e4aac5acd1b/packages/serverpod/test/database/columns/column_int_test.dart#L77C43-L77C48 for the syntax or https://github.com/serverpod/serverpod/blob/7186d782beed2b0bdd961a3283612e4aac5acd1b/tests/serverpod_test_server/lib/src/endpoints/column_operations/column_int.dart#L39 for its use in an endpoint.
