### ISSUE TITLE
WASM support, dart:html package is deprecated and should be replaced by package:web

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#2380]
The package `dart:html` does not support wasm compilation target. This package is in use in a limited number of places in the code but currently blocks support for wasm in a flutter app.

To fix this, the `dart:html` package should be replaced with `package:web`

source: https://dart.dev/libraries/dart-html

**Comment by SandPod** [comment]
It's being worked on by @abdelaziz-mahdy.
