### ISSUE TITLE
serverpod create mypod - Waiting for Postgres..

### ISSUE THREAD

**Issue by adoniaspp** [serverpod/serverpod#239]
When creating the first project in linux environment:

...
starting docker
Recreating mypod_server_postgres_1 ... done
Recreating mypod_server_redis_1 ... done
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
...

Indefinitely showing "Waiting for Postgres..." in the terminal.

**Comment by yahu1031** [comment]
@adoniaspp As of the Script written, this is because your `8090` port is already taken(busy). So it was waiting to let the port get freed.

**Comment by vlidholt** [comment]
Automated tests on Linux will be added.
