### ISSUE TITLE
Keep the base library clean

### ISSUE THREAD

**Issue by BlockRen** [serverpod/serverpod#2392]
**The problem considered:**

serverpod_auth_shared_flutter introduces too many third-party libraries.
For example, cached_network_image, image_cropper, image_picker, sqflite, file_picker, like low-level libraries should be clean, not too many third-party libraries, and unimportant functions should be placed in other libraries, or use interface.
The Auth library should handle Auth-related functions.

The Serverpod is outstanding, expect better.

**Comment by SandPod** [comment]
Hey @BlockRen!

We try to stay as strict as possible when it comes to the base Serverpod package. But it is also something we would like to improve in the future for modules. When it comes to our auth module, it will likely be manifested in a new module with a more clear thinking around modularity and user-desired functionality.

**Comment by BlockRen** [comment]
Thank you for your prompt and thoughtful response.  I appreciate the commitment to maintaining strict standards for the base Serverpod package.  It's encouraging to hear that there are plans to improve modularity and focus on user-desired functionality in future modules.

Thanks again for your hard work and dedication to improving Serverpod!
