### ISSUE TITLE
generated code does not await database functions?

### ISSUE THREAD

**Issue by lastmeta** [serverpod/serverpod#241]
Here's a generated code snippet from one of our generated classes, they all look like this. Notice the `.delete`, `.update`, `.insert`, `.findById`, all the database functions are not awaited. Is this by design?

```
  static Future<WalletAddress?> findById(Session session, int id) async {
    return session.db.findById<WalletAddress>(id);
  }

  static Future<int> delete(
    Session session, {
    required WalletAddressExpressionBuilder where,
    Transaction? transaction,
  }) async {
    return session.db.delete<WalletAddress>(
      where: where(WalletAddress.t),
      transaction: transaction,
    );
  }

  static Future<bool> deleteRow(
    Session session,
    WalletAddress row, {
    Transaction? transaction,
  }) async {
    return session.db.deleteRow(
      row,
      transaction: transaction,
    );
  }

  static Future<bool> update(
    Session session,
    WalletAddress row, {
    Transaction? transaction,
  }) async {
    return session.db.update(
      row,
      transaction: transaction,
    );
  }
```

**Comment by Levi-Lesches** [comment]
I don't know much about the internals of Serverpod but in general, you don't need a `await` a `Future` that you're returning -- you can just pass it back to the caller and they can await it. In other words, if someone does `await deleteRow(...)`, they're not awaiting a new Future created by `async`, it's the future from `session.db.deleteRow`
