### ISSUE TITLE
Improve error handling in SignInWithGoogle by rethrowing exceptions

### ISSUE THREAD

**Issue by Arnooodles** [serverpod/serverpod#2417]
**Is your feature request related to a problem? Please describe.**
When a user cancels the sign-in process, the current method simply returns `null`. However, an exception occurs indicating that the sign-in was aborted. It would be more useful to rethrow the exception, allowing us to differentiate between the types of exceptions that occur, including distinguishing between an actual error and a user cancellation.

**Describe the solution you'd like**
In the try-catch block, instead of returning `null`, `rethrow` the exception. 

**Additional context**
https://github.com/serverpod/serverpod/blob/03edf7f1ffcf7fa0c45cccc075193c5647b74dfa/modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart#L102-L106

**Comment by SandPod** [comment]
Suggested a temporary solution in the PR so that this could be implemented without cause a breaking change to the interface.
