### ISSUE TITLE
Improve ServerPod Documentation so new developer can better under

### ISSUE THREAD

**Issue by alihassan143** [serverpod/serverpod#244]
kindly improve the documentation with good explanation so new developers can easily understand the underlying apis

**Comment by vlidholt** [comment]
Have you checked out https://docs.serverpod.dev ? It's reasonable comprehensive, but we will be adding tutorials and videos for the final 1.0 release too.

**Comment by alihassan143** [comment]
@vlidholt  but its very little we cannot work into to app if we did not know the complete reference of the all apis and proper documentation and tutorials 
I hope the all documentation is totally  revamped in the final 1.0 release

**Comment by vlidholt** [comment]
The APIs themselves are documented here: https://pub.dev/documentation/serverpod/latest/

**Comment by abcnow** [comment]
videos tutorials are the key.. specially practical ones where they do real projects like chat apps (simple ones of course) but where you get to see how to use serverpod..

**Comment by alihassan143** [comment]
> videos tutorials are the key.. specially practical ones where they do real projects like chat apps, news api (simple one of course) but where you get to see how to use serverpod..most people learn better by doing things and most docs fail to do this.. here is an idea for a potential interactive serverpod interactive docs -the way docs should be: https://www.figma.com/file/dnK4kzmKGIpb7CsavXQAA2/docs_serverpod?node-id=1%3A2

@vlidholt  kindly looks into this 
this help all the new developers to understand all the serverpod api
and they can easily understand the serverpod

**Comment by vlidholt** [comment]
We are very much working on this. CodeX is also creating a set of video tutorials around Serverpod. Check out this playlist: https://www.youtube.com/watch?v=3Q2vKGacfh0&list=PL3wGb9_yWsvLPOvTRl39HQ6Qp0XJwi9dB

**Comment by abcnow** [comment]
thanks for sharing the link.. I had already gone through the 3-video series from CodeX.. pretty good but basic.. I sent him a message to see if he could do another series on more complex projects.. crossing my fingers..

**Comment by vlidholt** [comment]
Another good place to start is the Pixorama app. You can find it here, it has complete source code too: https://pixorama.live/

**Comment by abcnow** [comment]
thanks a lot Viktor! This is promising! The app is what we need.. Keep it up :)
