### ISSUE TITLE
Allow AuthConfig to take hashing password callback

### ISSUE THREAD

**Issue by Kiruel** [serverpod/serverpod#2440]
**Is your feature request related to a problem? Please describe.**
In case of a migration of a database to serverpod, my users in the old database use  bcrypt to hash the password and validate it.

**Describe the solution you'd like**
I propose to add 2 new arguments to AuthConfig:

`GeneratePasswordHashCallback` and `ValidatePasswordHashCallback`

**Comment by SandPod** [comment]
I can understand the need for this. Placed a review on the PR now.
