### ISSUE TITLE
Serverpod Membership without user authentication

### ISSUE THREAD

**Issue by hidayet-poscu** [serverpod/serverpod#2445]
I want to perform membership without user authentication, but I could not find such a setting.

**Comment by SandPod** [comment]
Hey @hidayet-poscu 👋 

Could you elaborate a bit on the feature? I'm not sure I fully understand the request here.

**Comment by lukehutch** [comment]
I set up something like this as a way to manually make API calls, separate from the users created in my app. Here's how to create a user, and manually sign in from your own code:

```dart
Future<void> createTestUser(Serverpod pod) async {
  Session session = InternalSession(server: pod.server);

  // Create user
  final emailAddr = '<redacted>';
  final password = '<redacted>';

  final userInfo =
      await auth.Emails.createUser(session, 'Test user', emailAddr, password);

  if (userInfo?.id == null) {
    throw 'Failed to create test user';
  }

  // Try logging in as user
  await auth.UserAuthentication.signInUser(session, userInfo!.id!, 'server');
  assert(await session.authenticated != null);

  await session.close();
}
```

**Comment by hidayet-poscu** [comment]
> Hey@hidayet-poscu👋
> 
> Özellik hakkında biraz daha ayrıntı verebilir misiniz? Buradaki isteği tam olarak anladığımdan emin değilim.

want to use the user registration and login panel you have prepared. My user base cannot verify their accounts with a code sent via email. Therefore, I want the registration to be completed without the verification code step when using the API.

**Comment by hidayet-poscu** [comment]
Future<void> createTestUser(Session session, async { 
I changed it and created the endpoint. It worked. The topic is closed.
Thank you [lukehutch]
