### ISSUE TITLE
authenticationHandler not called when doing custom auth

### ISSUE THREAD

**Issue by jhntrifork** [serverpod/serverpod#2453]
I'm trying to make a simple access validation following the description here:
https://docs.serverpod.dev/concepts/authentication/custom-overrides

To my understanding the `authenticationHandler` function should be called when serverpod receives an incoming request. But it never gets called. I'm not including `serverpod_auth`, as I want to make a custom authentication.

It does not matter whether I set `requireLogin` or not on my endpoint. I'm calling my endpoint from Postman and tried with Authorization set to the "valid" as well as "Bearer valid".

I'm using Serverpod 2.0.1 mini.

**Comment by Isakdl** [comment]
Hey @jhntrifork 

Could you provide a sample of the request you are making?

**Comment by jhntrifork** [comment]
Certainly. I've used both Postman and curl. Here is the curl requests:
`curl -v http://localhost:8080/example/rss -H "Authorization: Bearer valid"`
`curl -v http://localhost:8080/example/rss -H "Authorization: valid"`

My endpoint gets called (when requireLogin is not set), but the authenticationHandler function is not.

**Comment by Isakdl** [comment]
I see, the current implementation of endpoints requires the auth key to be set in the request's body, under the key `auth`.

e.g.

```json
{
   "auth": "token"
}
```

The authenticationHandler is only called if you try to access the authentication information or if auth is required for the endpoint. 

We have plans to change this implementation to align with REST standard headers.

**Comment by jhntrifork** [comment]
That helped 🙂

Thank you for your quick reply.
