### ISSUE TITLE
Allow model classes with no fields (for use as events, sent via streaming message)

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2454]
Currently it's impossible to create a model `.spy.yaml` with no fields. (`serverpod generate` and the `Serverpod` VS Code plugin both disallow this.)

I need to be able to send events from the server to my app, and some of these events don't have any associated data -- they just cause the app to take some action (such as calling back to the server to refreshing a given database query, when the server knows that those query results will have changed).

Currently I have to create a `placeholder: String?` field in an otherwise empty model `.spy.yaml` just to keep Serverpod happy. 

I know that normally there would be no need to create empty model classes, but being able to send any `SerializableModel` object over the websocket makes it make sense to be able to have empty classes.

**Comment by lukehutch** [comment]
Yes, I could use an enum, but I would have to wrap it in a class to use it as a message anyway. And some of my events have extra fields, while a few just need to trigger a specific view to be refreshed in the app.

This is a pretty low-priority request, since it's easy to work around, but to me it makes sense, if serializable objects can be seen as events when sent via websocket.

**Comment by Isakdl** [comment]
> Yes, I could use an enum, but I would have to wrap it in a class to use it as a message anyway.

Why? At least from the Serverpod perspective you should be able to send the enum as a standalone entity. 

 > And some of my events have extra fields, while a few just need to trigger a specific view to be refreshed in the app.

Fair, but there shouldn't be anything stopping you from sending both the enum and the classes.

**Comment by lukehutch** [comment]
> Why? At least from the Serverpod perspective you should be able to send the enum as a standalone entity.

Ah, I didn't realize individual enum values could be serialized as a `SerializableModel`, but that makes sense. Thanks! I'll close this.
