### ISSUE TITLE
Another malformed URL exception

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2465]
**Describe the bug**

This exception is thrown on malformed file URL:

```
type 'Null' is not a subtype of type 'String'
#0      CloudStoragePublicEndpoint.register.<anonymous closure> (package:serverpod/src/cloud_storage/public_endpoint.dart:119:61)
public_endpoint.dart:119
#1      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:128:37)
endpoint_dispatch.dart:128
<asynchronous suspension>
#2      Server._handleRequest (package:serverpod/src/server/server.dart:303:18)
server.dart:303
<asynchronous suspension>
```

The problematic line uses a `dynamic` value (which is `Null` in a malformed URL) and passes it as an arg to a `String`-typed parameter:

```dart
            return file(session as MethodCallSession, params['path']);
```

I'll copy here the comment I made in #2398:

> There is a more general pattern here though: this is about the third issue I have filed for the handling of malformed HTTP requests. One of them was for URLs that were not formatted correctly to be interpreted as an endpoint call (also triggered by rogue crawler requests). This one and one other (IIRC) is about malformed UTF8 in the request.
> 
> You really need to stress-test your API server, webserver, and web socket upgrade handler by fuzzing them, so that unexpected exceptions are not thrown. This sort of issue does not instill confidence in Serverpod (even though Dart is a pretty safe language in general).

Basically, you need to assume that every part of every request could be wrong or invalid. There aren't enough validity checks being run right now.

**Comment by klkucaj** [comment]
This issue was fixed here: #2676
Specifically this is the code that now validates all parameters passed to endpoints:
https://github.com/serverpod/serverpod/blob/aeba3a8d126a2f4eb814bbb772ae71f9a36fa237/packages/serverpod/lib/src/server/endpoint_parameter_helper.dart#L8-L32
