### ISSUE TITLE
Create Database rules (Soft Delete)

### ISSUE THREAD

**Issue by MrFahrenheit-55** [serverpod/serverpod#2492]
**Is your feature request related to a problem? Please describe.**
I want to incorporate soft delete in the database. This will enable the end-user to roll back changes if he/she accidentally deletes a record from the DB. If the records are deleted longer than a specified amount of time, then the record will be removed from the database.

**Describe the solution you'd like**

- A user deletes a record from the database.
- The record is flagged as isDeleted with a timestamp.
- After a pre-defined period (i.e. 7 days), the record is removed from the DB.
- If the user decides to recover the record, the isDeleted flag is cleared and the timestamp is removed.

**Describe alternatives you've considered**
Currently, I use transactions to set the timestamp for entries within a database. I call the update database function to write the timestamp to the record. The transaction is necessary because of the nesting of tables: Categories => Sub-Categories => Items. All the levels below are flagged for deletion if the top level is deleted.

**Comment by SandPod** [comment]
Just to put an alternative solution out there, this should already be achievable by utilizing a recurring future call, as described in the cronjob issue: https://github.com/serverpod/serverpod/issues/899.

Simply put, you could set up a recurring future call that removes entries flagged as "deleted" with their due date passed.

**Comment by MrFahrenheit-55** [comment]
Awesome! Thanks @SandPod
