### ISSUE TITLE
Can't serve `index.html` from `/` in production

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2522]
I'm trying to serve `index.html` from `/`.

What I am currently doing is

```dart
  pod.webServer.addRoute(RouteRoot(), '/');
  pod.webServer.addRoute(RouteRoot(), '/index.html');
```

then I have

```
class RouteRoot extends WidgetRoute {
  @override
  Future<Widget> build(Session session, HttpRequest request) async =>
      Widget(name: 'index');
}
```

then I moved `index.html` into `web/templates`.

On my development server, `index.html` is being correctly served from both `/` and `/index.html`. However, on GCP, `/` returns a `404` error.

I tried the following, but it didn't fix the problem:

```dart
  pod.webServer.addRoute(RouteRedirectRoot(), '/');
```

```dart
class RouteRedirectRoot extends WidgetRoute {
  @override
  Future<AbstractWidget> build(Session session, HttpRequest request) async =>
      WidgetRedirect(url: '/index.html');
}
```

**Comment by SandPod** [comment]
Is the 404 served from the Serverpod Server on GCP? Just want to root out that the request is actually hitting the instance and is not intercepted by a load balancer or proxy.

**Comment by lukehutch** [comment]
@SandPod It is highly likely being intercepted, given that `/` is serving `index.html` correctly if I start the server locally.

I have no idea how to track down what might be intercepting this on GCP, or how, however.

**Comment by SandPod** [comment]
Unfortunately, it seems like something is intercepting the request on GCP. If your server can handle the request locally, there is nothing in the framework routing rules that are connected to the runtime mode.

Just to be on the safe side you could run the server locally in "production" mode but with the development configuration but I expect this to yield the same result.

The load balancer on GCP will return with a 404 if the backend instance can't be found. So double check that the root is correctly routed.

There are some instructions here on how to access the load balancer logs that could be helpful: https://cloud.google.com/load-balancing/docs/https/https-logs-monitor-overview

I don't know if you have any additional helpful information @vlidholt?

**Comment by lukehutch** [comment]
@SandPod 

I can't see anything that looks out of place in the load balancer settings, but I may have missed something...

What do you mean by "double-check that the root is correctly routed"?

**Comment by SandPod** [comment]
My hunch tells me that there might be something funky going on with the `root` routing. That is, `/` for your domain. There might be some configuration that informs root request to take a specific route compared to requests with any type of path.

There is a section in the documentation that explains how to add tests to the URL map deployed here: https://cloud.google.com/load-balancing/docs/url-map#test-url-map

That could help us root out if the load balancing is configured correctly.

**Comment by vlidholt** [comment]
This looks like the correct way of doing things:

```dart
  pod.webServer.addRoute(RouteRoot(), '/');
  pod.webServer.addRoute(RouteRoot(), '/index.html');
```

If your local server is serving things correctly, it's most likely an issue with your load balancer setup. The Terraform script should work pretty much out of the box for this use case, e.g., Pixorama runs on this setup and is serving from the root:
https://pixorama.live/

Did you change any of the load balancer's rules?

**Comment by lukehutch** [comment]
No, I haven't changed any of the rules of load balancer. I looked in the load balancer settings, and I couldn't find anything relating to the URL path `/`. Where am I supposed to find the setting you are alluding to?

**Comment by lukehutch** [comment]
@vlidholt I found the problem, after days of trying to fix this... the load balancer was set up as an HTTP load balancer, not an HTTPS load balancer. This has to be an error in the Terraform config, because I never touched this. With this fixed, the web server delivers `/` again.

**Comment by SandPod** [comment]
I am thrilled that you found the issue here.

**Comment by lukehutch** [comment]
@SandPod Actually a few hours after this everything broke because of this change, and I was getting 502 errors on every service. So this wasn't the correct change. But when I changed back from HTTPS to HTTP, somehow magically the original problem was fixed. So weird. Anyway I will close this now that everything is working.
