### ISSUE TITLE
Default `Dockerfile` template should use `pub upgrade`, not `pub get`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2541]
**Describe the bug**

I was trying to figure out why my production server was not picking up changes in a dependency (specifically, my GitHub fork of Serverpod).

It turns out my `Dockerfile` was using `pub get`, and should have been using `pub upgrade`:

https://github.com/lukehutch/click/blob/85a6b6f619e470a9ec768ebb53a8539b983e6810/click_server/Dockerfile#L6

The template should really be adjusted to use `pub upgrade`.

**Comment by SandPod** [comment]
I think we wrongly triaged this as an `enhancement`.

The intention of the `Dockerfile` is to be run in a production environment.
In a production environment, the version of the project's dependencies should be deterministic, enabling testing to validate that everything works as expected. This is enforced by providing a `pubspec.lock` file. 

When `pub upgrade` is used, any `pubspec.lock` file is ignored, potentially running the production environment with an unknown configuration.

Following best practices https://dart.dev/tools/pub/cmd/pub-upgrade:
> For [application packages](https://dart.dev/tools/pub/glossary#application-package), check in the lockfile to source control; this ensures the application has the exact same versions of all dependencies for all developers and when deployed to production.

Closing this as a won't fix.
