### ISSUE TITLE
serverpod generate  creates error and, doesnt create Protocol and Endpoints class 

### ISSUE THREAD

**Issue by xyzbilal** [serverpod/serverpod#2557]
**Describe the bug**

I m running serverpod generate command after modifying my endpoinst and I start to get the error below. I tried to figure it out which can cause this problem but could not success. Maybe its not a bug but I m not sure what is the problem and what cause the problem. 

I upgraded to 2.0.2  but no luck.

Any idea will be appriciated. thanks 

here is the error what I get 

```
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you
filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

RangeError (start): Invalid value: Only valid value is 0: 1

#0      RangeError.checkValidRange (dart:core/errors.dart:359:7)
#1      List.sublist (dart:core-patch/growable_array.dart:84:38)
#2      EndpointMethodAnalyzer.parse
(package:serverpod_cli/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart:30:39)
#3      EndpointsAnalyzer._parseLibrary (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:141:47)
#4      EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:83:27)
<asynchronous suspension>
#5      performGenerate (package:serverpod_cli/src/generator/generator.dart:53:19)
<asynchronous suspension>
#6      StdOutLogger.progress (package:cli_tools/src/logger/loggers/std_out_logger.dart:141:20)
<asynchronous suspension>
#7      GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:67:17)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      BetterCommandRunner.runCommand (package:cli_tools/src/better_command_runner/better_command_runner.dart:140:7)
<asynchronous suspension>
#10     _main (file:///Users/bilalsimsek/.pub-cache/hosted/pub.dev/serverpod_cli-2.0.2/bin/serverpod_cli.dart:59:3)
<asynchronous suspension>
#11     main.<anonymous closure>
(file:///Users/bilalsimsek/.pub-cache/hosted/pub.dev/serverpod_cli-2.0.2/bin/serverpod_cli.dart:33:9)
<asynchronous suspension>
#12     main (file:///Users/bilalsimsek/.pub-cache/hosted/pub.dev/serverpod_cli-2.0.2/bin/serverpod_cli.dart:30:3)
<asynchronous suspension>
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ Run `serverpod version` to determine the version of installed tooling.
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**

**Comment by Isakdl** [comment]
Hey @xyzbilal 

This looks like a bug, there seems to be some endpoint method that is causing this would you mind figuring out which and pasting the method declaration code here? 

The easiest way I think is to comment out all methods and run the generator and then enable more and more methods until you run into the crash. This way you should be able to find which method is the culprit.

**Comment by xyzbilal** [comment]
Thanks for quick answer. I was creating my endpoint  to save files local folders, referencing the methods defined in 
 link of https://github.com/serverpod/serverpod/blob/e1ad802bcb99ea1de0293dd5f6fa5b51eef7d571/packages/serverpod/lib/src/cloud_storage/database_cloud_storage.dart#L13 ,
because Session parameter in methods are defined named like ```
Future<bool> fileExists(
      {required Session session, required String path})
``` instead of ```
Future<bool> fileExists(Session session,
      {  required String path})
``` 
making session parameter named causes the problem. changing them accordingly solves the problem. 
Thanks.

**Comment by Isakdl** [comment]
Perfect thank you very much! :) 

@SandPod Take a look if you can reproduce this with the analyzer!
