### ISSUE TITLE
Serverpod 2.0.1: notInSet() not working - flutter: Converting object to an encodable object failed: _Set len:10

### ISSUE THREAD

**Issue by KelvinTK** [serverpod/serverpod#2572]
Environment Info:
VS Code, Flutter, Serverpod 2.0.1, on Windows 11
Debugging on a windows VM

Full Error:
flutter: Failed call: visits.updateVisits
flutter: Converting object to an encodable object failed: _Set len:10

Error info:
Trying to exclude some table IDs using serverpods .notInSet(), server-side code is being generated without issues but the calls to the server are failing with the conversion error mentioned above.

Code highlight:
Future<List<Visit>?> updateVisits(Session session, int personnelId,  Set<int> visIds) async {
    int cnt = await Visit.db.count( session,  where: (v) =>v.personnelId.equals(personnelId) );
    if (cnt > visIds.length) {
      return await Visit.db.find(session,  where: (v) => v.id.notInSet(visIds) & v.personnelId.equals(personnelId) );
   }
return null;
}

**Comment by KelvinTK** [comment]
Sorry, typo on Code highlight:
the method is a nullable Future list of type Visit

**Comment by SandPod** [comment]
Hey @KelvinTK 👋 

If I understand your example correctly, the error appear on the flutter side of the code.

Could you include the code for where you call the server method in your example?
Do you see any errors in the Server logs?
