### ISSUE TITLE
serverpod_auth_google: PlatformException(missing-config, GoogleService-Info.plist file not found and clientId was not provided programmatically., null, null)

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#258]
## Description
I'm trying the `serverpod_auth_google_flutter` package and I have followed every step from docs. But I still get config missing error from google_sign_in package, Where `clientId` is missing from the dart code.

## Logs
```console
Launching lib/main.dart on iPhone 13 in debug mode...
Xcode build done.                                           23.2s
Connecting to VM Service at ws://127.0.0.1:64027/GTrB-EFUVhw=/ws
flutter: serverpod_auth_google: GoogleSignIn
flutter: serverpod_auth_google: PlatformException(missing-config, GoogleService-Info.plist file not found and clientId was not provided programmatically., null, null)
flutter: #0      StandardMethodCodec.decodeEnvelope
#1      MethodChannel._invokeMethod
<asynchronous suspension>
#2      GoogleSignIn._callMethod
<asynchronous suspension>
#3      GoogleSignIn.signIn.isCanceled
<asynchronous suspension>
[log] Failed to signin
```

I have deep-dived into the `serverpod_auth_google_flutter` code. There I found There is [no clientId is being passed](https://github.com/serverpod/serverpod/blob/main/modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart#L22-L24) to the `GoogleSignIn` object. We have to pass an argument to the [`signInWithGoogle` method](https://github.com/serverpod/serverpod/blob/main/modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart#L8) and also to the [`SignInWithGoogleButton` constructor](https://github.com/serverpod/serverpod/blob/main/modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/signin_button.dart#L33).

I will take this up and resolve it.

**Comment by vlidholt** [comment]
The fix here is to provide the GoogleService-Info.plist that you install in your iOS project. Then authentication should work correctly.

**Comment by yahu1031** [comment]
I have followed exactly what they said, But when I added `GoogleSignIn`, it works for me.

**Comment by yahu1031** [comment]
@vlidholt This ticket must be opened. I found something that isn't working. Firstly I have been using the docs and following them. And then I found that `clientID` must be passed to `GoogleSignIn` explicitly. Even their docs show that. I have `GoogleService-Info.plist` in Runner but when I give the `clientId` in the code, Then it worked for me and returns the user data. And also the Serverpod auth has some issue with another thing where it gives 400 Errors (I gonna raise a new ticket for that.) and no error message. May be need to look deeper.

> INFO: NEED UPDATE IN CODE https://github.com/serverpod/serverpod/blob/70473726427c4989ef0506473c08412a97cff80e/modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart#L127

```json
{
  "iss": "https://accounts.google.com",
  ...
  "given_name": "Minnu",
  "locale": "en-GB",
  "iat": 1669663640,
  "exp": 1669667240
}
```

> `iss` includes `https://`. I'm gussing that condition will fail.

Hope you are aware of this.

**Comment by vlidholt** [comment]
I will test this before the 1.0 release.
