### ISSUE TITLE
DatabaseException: not caught in a try-catch block

### ISSUE THREAD

**Issue by Sandyhi5** [serverpod/serverpod#2589]
**Describe the bug**
I have a situation where a record is not able to be inserted as it violates the unique idx as it would cause a duplicate. Fair enough I get a DatabaseException.
But I expect, given that the INSERT is within a try-catch block the exception should be caught smoothly. Instead I have no control over the flow.
How do I catch such exceptions?

**To Reproduce**
Any insert into a table with unique index

**Expected behavior**
I expect that the exception is caught by the catch block allowing me to plan next steps

**Screenshots**
See info below

**Serverpod versions**
 serverpod - 2.0.0
Dart - 3.3.0

**Platform information**
Windows 11 on Acer [Test / Dev env]

**Additional context**
2024-08-12 03:04:35.513110Z Internal server error. Zoned exception.
DatabaseException: duplicate key value violates unique constraint "sp_lg_mt_pl_yr_2idx"
#0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:416:9)
<asynchronous suspension>
#1      DatabaseConnection._mappedResultsQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:470:1
8)
<asynchronous suspension>
#2      DatabaseConnection.insert (package:serverpod/src/database/adapters/postgres/database_connection.dart:155:9)
<asynchronous suspension>

**Comment by SandPod** [comment]
Hey @Sandyhi5!

The intention is that you should always be able to catch the exception.
Could you provide the sample code for the try-catch block that you have written?

**Comment by vlidholt** [comment]
@Sandyhi5, a common cause for not catching an exception is that you have missed to add an `await` to your async call.

E.g., in the example below the exception will never be caught because Dart will spin off a new async context and immediately continue running your code after the insert.

```dart
try {
  MyModel.insert(model);
} catch (e) {
  // Will never be caught.
}
```

**Comment by Sandyhi5** [comment]
Future<bool> addResultList(Session session) async {
    String? strData = await readFile(session, jsonFileResults);

    session.log('addResultList: File string read len: ${strData?.length}');
    try {
      final jsonResponse = json.decode(strData!);

      SpResultT20Analyzed result;
      List<SpResultT20Analyzed> results = <SpResultT20Analyzed>[];

      for (int i = 0; i < jsonResponse.length; i++) {
        result = SpResultT20Analyzed.fromJson(jsonResponse[i]! as Map<String, dynamic>);

        results.add(result);
      `}`
      **await** SpResultT20Analyzed.db.insert(session, results);
      return true;
    } catch (e) {
      session.log('Exception caught: addResultList: ${e.toString()}');
    }
    return false;
  }

**Comment by Sandyhi5** [comment]
It's respolved now after adding "await" as marked above in asterisls
Can close now
Thanks

**Comment by Levi-Lesches** [comment]
Hi I don't think this is resolved: 

```dart
class ApiRoute extends WidgetRoute {
  @override
  Future<WidgetJson> build(Session session, HttpRequest request) async {
      await session.db.transaction((transaction) async {
        final user = User(username: "myName", id: 1);   // <-- this should trigger an error
        try {
          await User.db.insertRow(session, user, transaction: transaction);
        } on DatabaseException catch (error) {
          print("DB error");
        }
      });
    } on DatabaseException {
      print("DB error!");
    }

  // ...
}
```

This still manages to cause uncaught exceptions in `serverpod: 2.9.1`. Is it because it's in a Route on the relic server?

**EDIT** Never mind, it was a) not a `DatabaseException`, and b) console logging was enabled, so even when I did catch the error, it still got printed to the console.
