### ISSUE TITLE
Deploying to aws shows 502 bad gateway

### ISSUE THREAD

**Issue by husain-nahar** [serverpod/serverpod#2620]
**Describe the bug**
while deploying to aws:
when DART SDK version is 3.1.0 and serverpod version is 2.0.0.
everything works fine and api.<domain name> shows ok.

But if the DART SDK version becomes the latest(3.5.0) and serverpod is 2.0.2(Also the latest). I see the 502 Bad gateway.

Why is this so.
I Also have correct dart sdk version updated at aws linux machine.
This also doesn't help. [](https://github.com/serverpod/serverpod/discussions/445)

**Comment by hidayet-poscu** [comment]
502 Bad Gateway
I am faced with the same problem. Even though the installation was very difficult, I did it.
![image](https://github.com/user-attachments/assets/bb45e954-0200-4156-afa5-d113e0f9794b)

**Comment by hidayet-poscu** [comment]
aws 
[ec2-user@ip-10-0-6-131 ~]$ dart --version
**Dart SDK version: 3.5.0** (stable) (Tue Jul 30 02:17:59 2024 -0700) on "linux_x64"
[ec2-user@ip-10-0-6-131 ~]$    

vscode
hidayet@192 terraform % dart --version
**Dart SDK version: 3.5.0** (stable) (Tue Jul 30 02:17:59 2024 -0700) on "macos_arm64"
  Flutter 3.24.0 
 serverpod: 2.0.2

conclusion:  502 Bad Gateway

please help

**Comment by husain-nahar** [comment]
I made changes as stated in other issues before merging. But this is still showing 502 bad gateway. I made dart version to 3.5.3 and serverpod to 2.1.4. Also the dart version on ec2 is also 3.5.3. Please help me with detailed reply on how to fix this. As my whole project is stucked.
