### ISSUE TITLE
Protocol::getClassNameForObject is missing delegate to Serverpod protocol file.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2657]
**Describe the bug**
In the project generated protocols files `getClassNameForObject` method, we never check if the class name can be retrieved from the Serverpod generated protocol file.

This makes it impossible to serialize Serverpod defined models from a project.

**To Reproduce**
1. Create an instance of a Serverpod defined model, for example `CluserServerInfo('Hello world');`.
2. Try to Serialize it using a project-generated protocol file `Protocol().`
3. Observe exception

```dart
import 'package:serverpod/protocol.dart' as serverpod;
import 'package:serverpod_test_server/src/generated/protocol.dart';
import 'package:test/test.dart';

void main() {
  test(
      'Given a Serverpod defined model when encoding it with type then it is encoded',
      () {
    var protocol = Protocol();
    var serverpodDefinedModel =
        serverpod.ClusterServerInfo(serverId: 'Hello World');
    var encoded = protocol.encodeWithType(serverpodDefinedModel);

    expect(encoded, isA<String>());
  });
}

```

**Expected behavior**
Serialization of Serverpod defined models should be possible when encoding with type.

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ 2.0.2.
 - _Library version:_ 2.0.2.

**Comment by KristijanZic** [comment]
I still have this error on the Serverpod version: 2.1.0-beta.2
