### ISSUE TITLE
WASM support for serverpod_auth_email_flutter and serverpod_auth_shared_flutter

### ISSUE THREAD

**Issue by develocode777** [serverpod/serverpod#2662]
App doesn't compile to wasm using the packages `serverpod_auth_email_flutter` and `serverpod_auth_shared_flutter`. Please add support for these packages.

**Comment by SandPod** [comment]
Hey @develocode777!

Which version of Serverpod and the Serverpod CLI are you using?
WASM is currently only supported in the `2.1.0` beta that we are preparing for release.

**Comment by develocode777** [comment]
Hello @SandPod,

It's alright then, I'll use the beta version.

Thanks!
