### ISSUE TITLE
Can't find ')' to match '('.

### ISSUE THREAD

**Issue by donywan** [serverpod/serverpod#2682]
**Describe the bug**
```
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/endpoint_dispatch.dart:133:51: Error: Can't find ')' to match '('.
      var authFailed = await canUserAccessEndpoint(
                                                  ^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart:75:72: Error: Can't find ')' to match '('.
          var authFailed = await EndpointDispatch.canUserAccessEndpoint(
                                                                       ^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart:146:68: Error: Can't find ')' to match '('.
      var authFailed = await EndpointDispatch.canUserAccessEndpoint(
                                                                   ^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart:161:68: Error: Can't find ')' to match '('.
      var authFailed = await EndpointDispatch.canUserAccessEndpoint(
                                                                   ^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart:214:66: Error: Can't find ')' to match '('.
    var authFailed = await EndpointDispatch.canUserAccessEndpoint(
                                                                 ^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/endpoint_dispatch.dart:133:51: Error: Too few positional arguments: 3 required, 2 given.
      var authFailed = await canUserAccessEndpoint(
                                                  ^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/endpoint_dispatch.dart:183:46: Context: Found this candidate, but the arguments don't match.
  static Future<ResultAuthenticationFailed?> canUserAccessEndpoint(
                                             ^^^^^^^^^^^^^^^^^^^^^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart:75:72: Error: Too few positional arguments: 3 required, 2 given.
          var authFailed = await EndpointDispatch.canUserAccessEndpoint(
                                                                       ^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/endpoint_dispatch.dart:183:46: Context: Found this candidate, but the arguments don't match.
  static Future<ResultAuthenticationFailed?> canUserAccessEndpoint(
                                             ^^^^^^^^^^^^^^^^^^^^^
/d:/pub_cache/hosted/pub.flutter-io.cn/serverpod-2.1.0-beta.2/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart:146:68: Error: Too few positional arguments: 3 required, 2 given.
      var authFailed = await EndpointDispatch.canUserAccessEndpoint(
```

**To Reproduce**
1. upgrade serverpod version
2. start `server`

**Expected behavior**

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ Serverpod version: 2.1.0-beta.2
 - _Library version:_ 2.1.0-beta.2

**Platform information**
`server`

**Additional context**

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by SandPod** [comment]
Hey @donywan 👋 

Could you try to remove the dart cache and pull down the dependencies again?
Also, just to be sure, have you made any manual modifications to your cached version of Serverpod?

**Comment by donywan** [comment]
> Could you try to remove the dart cache and pull down the dependencies again?
Yes,I cleared the cache, but I couldn't figure out what the problem was, so I rolled back to 2.0.2.
> Also, just to be sure, have you made any manual modifications to your cached version of Serverpod?
No,I re-executed the `dart pub get` command.

I think it has something to do with the following command
> Try `dart pub outdated` for more information.

**Comment by SandPod** [comment]
Do you get this issue if you create a new project?
When upgrading, did you remember to update all dependencies towards Serverpod to use the same version?

My hunch tells me that if this was an issue in the version of Serverpod that we released, all our users would see this and we would catch it directly.

**Comment by donywan** [comment]
> Do you get this issue if you create a new project? When upgrading, did you remember to update all dependencies towards Serverpod to use the same version?
> 
> My hunch tells me that if this was an issue in the version of Serverpod that we released, all our users would see this and we would catch it directly.

There is no error, this may be a problem with the environment in my computer.
