### ISSUE TITLE
Add comparisons to ColumnSerializable (enum)

### ISSUE THREAD

**Issue by juanaguss** [serverpod/serverpod#269]
We have a class `Fund` were one of its fields is `purpose`, which is an enum of six options. When I ask the server for the list of every fund of any particular purpose, at the time of writing the query we get several errors regarding the comparison of the `enum`. 

So when looking at the code, I find that there is no support for comparisons with enums, which would be really nice to have.

To conclude, I'm leaving an alternative to do this in case someone is wondering how to do that.
```
/// Enums for [Purpose] values.
enum Purpose {
  /// The purpose is to save money for somethingA.
  somethingA,

  /// The purpose is to save money for a somethingB.
  somethingB,

  /// The purpose is to save money for somethingC.
  somethingC,

  /// The purpose is to save money for any reason.
  other
}

/// extension on [Fund] to add custom methods
extension FundEnum on Fund {
  /// This method returns a [Purpose] from a string, and if the string
  /// is not a valid [Purpose] returns null.
  Purpose? purposeFromString(String value) {
    return Purpose.values.firstWhereOrNull((e) => e.toString() == value);
  }

  /// This getter return the [Purpose] of the goal.
  Purpose get purposeEnum {
    return purposeFromString(purpose)!;
  }
```

**Comment by Isakdl** [comment]
Closing this as this as enum are support as of 1.2 in queries.

See: https://docs.serverpod.dev/concepts/database/filter#equals and https://docs.serverpod.dev/concepts/database/filter#in-set
