### ISSUE TITLE
In the module client template, the main file is incorrectly called `module.dart`

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#2702]
When creating a new module using:

```bash
serverpod create --template module my_module
```

The main exported file in the client is incorrectly named `lib/module.dart`. It would be much better if it was named by the client package, e.g. `lib/my_module_client.dart`.

The `my_module_server` package is correct, so it should probably be an easy fix. 🙂

**Comment by muhib349** [comment]
I'm on it.
