### ISSUE TITLE
serverpod_auth lacks an method for letting a user change its full name

### ISSUE THREAD

**Issue by dannejosefsson** [serverpod/serverpod#2723]
`UserInfo` has the fullName instance property, but there is no method of change it in the current version of `serverpod_auth`.

**Describe the solution you'd like**
I would like to have an endpoint method named `changeFullName` in `auth.user` that can be used, like the existing `changeUserName`.

**Describe alternatives you've considered**
I haven't really considered any other options.

**Additional context**
`UserSettingsConfig` has flags `UserName` and `FullName`, but I cannot see that these are looked at in `serverpod_auth`. Shouldn't they actually be in use?

**Comment by dannejosefsson** [comment]
Related PR: [#2724](https://github.com/serverpod/serverpod/pull/2724).

**Comment by daniel-webstep** [comment]
@SandPod, any take on the question I had under *Additional context* regarding the use of `UserSettingsConfig`?

**Comment by SandPod** [comment]
@daniel-webstep, Just some minor fixes for the tests and we are ready for merge 👍

**Comment by daniel-webstep** [comment]
I think I wasn't clear regarding the intention with the last message. I saw that there is a class called `UserSettingsConfig` that defines whether the user should be allowed to change its `userName` or `fullName`. But from what I could see, the methods that alter `userName` doesn't take this into account. So I didn't implement it for `fullName` either.

So the question is: Should this class affect the endpoint for updating `fullName` and `userName` (and perhaps other fields, cannot recall which options there were)?

**Comment by SandPod** [comment]
I believe this is actually a bug and filed an issue for it here: https://github.com/serverpod/serverpod/issues/2746

@dannejosefsson / @daniel-webstep - Would you be up for fixing this issue as well?

**Comment by dannejosefsson** [comment]
I can definitely scope it at least.
