### ISSUE TITLE
Throw `ExitException` in `Serverpod.start` instead of exiting process

### ISSUE THREAD

**Issue by hampuslavin** [serverpod/serverpod#2725]
**Is your feature request related to a problem? Please describe.**
To enable the new Serverpod test helpers to run Serverpod in `test` mode, it needs to gracefully be able to handle start-up failures without exiting the process (which would exit the test runner altogether).

An `ExitException` should be thrown instead so that the caller can decide what to do with the failure.

**Comment by SandPod** [comment]
To not make this a breaking change, I would suggest that this behavior is toggleable using an argument passed to `start`. We already use a similar pattern for `shutdown` where the process exits if the flag is set to true (which is the default behavior from legacy reasons).
