### ISSUE TITLE
"Bad state: Redis needs to be enabled to use this method" Error on SessionManager.signOut()

### ISSUE THREAD

**Issue by Choolabo** [serverpod/serverpod#2730]
**Describe the bug**
Since the update to 2.1.0 i recognized an issue, when i want to logout an User.

**To Reproduce**
1. Go to 'Sign in a user with the SessionManager'
2. Click on 'Signout with the SessionManager.signOut() Method'
4. See error:
`CALL: serverpod_auth.status.signOut duration: 8ms numQueries: 1 authenticatedUser: 1
Bad state: Redis needs to be enabled to use this method
0      MessageCentral.postMessage (package:serverpod/src/server/message_central.dart:52:9)
1      MessageCentralAccess.authenticationRevoked (package:serverpod/src/server/session.dart:639:43)
2      UserAuthentication.signOutUser (package:serverpod_auth_server/src/business/user_authentication.dart:51:10)
<asynchronous suspension>
3      StatusEndpoint.signOut (package:serverpod_auth_server/src/endpoints/status_endpoint.dart:21:5)
<asynchronous suspension>
4      Server._handleUriCall (package:serverpod/src/server/server.dart:494:20)
<asynchronous suspension>
5      Server._handleRequest (package:serverpod/src/server/server.dart:293:18)
<asynchronous suspension>
6      Server._handleRequestWithErrorBoundary (package:serverpod/src/server/server.dart:182:5)
<asynchronous suspension>`

**Expected behavior**
Don´t get this Exception. 

**Screenshots**

**Serverpod versions**
 -  _CLI Version: 2.1.0
 - _Library version: 2.1.0

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**
I think the problem is in the session.dart on line 642. Here it call postMessage with the fixed variable global = true. As i can read in the Documentation, this should cause the error. I am new as dev and i think anyone else can evaluate it better than me.

![Bildschirmfoto 2024-09-10 um 13 27 17](https://github.com/user-attachments/assets/cba920d5-8040-4fad-b754-54878a8312ba)
![Bildschirmfoto 2024-09-10 um 13 27 28](https://github.com/user-attachments/assets/d67570a7-af5a-4830-b7b8-fb6e74bdc771)

**Comment by Code-Remote** [comment]
I've upgraded CLI and all serverpod packages to 2.1.1 .  but still get the same error when trying to log out. 

```
I/flutter ( 7521): Failed call: serverpod_auth.status.signOut
I/flutter ( 7521): ServerpodClientException: Internal server error, statusCode = 500
```

Server logs
```
CALL: serverpod_auth.status.signOut duration: 9ms numQueries: 1 authenticatedUser: 3
Bad state: Redis needs to be enabled to use this method
#0      MessageCentral.postMessage (package:serverpod/src/server/message_central.dart:52:9)
#1      MessageCentralAccess.authenticationRevoked (package:serverpod/src/server/session.dart:639:43)
#2      UserAuthentication.signOutUser (package:serverpod_auth_server/src/business/user_authentication.dart:51:10)
<asynchronous suspension>
#3      StatusEndpoint.signOut (package:serverpod_auth_server/src/endpoints/status_endpoint.dart:21:5)
<asynchronous suspension>
#4      Server._handleUriCall (package:serverpod/src/server/server.dart:494:20)
<asynchronous suspension>
#5      Server._handleRequest (package:serverpod/src/server/server.dart:293:18)
<asynchronous suspension>
#6      Server._handleRequestWithErrorBoundary (package:serverpod/src/server/server.dart:182:5)
<asynchronous suspension>
```
