### ISSUE TITLE
Sign in with email (auth module) shows numeric keyboard, but requires text input

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#2735]
Haven't verified myself, but got a bug report that sign in with email shows a numeric keyboard for entering the authentication code, but the code has letter too. So, it's impossible to enter the code from the keyboard.

Not sure which platforms are affected.

**Comment by klkucaj** [comment]
@vlidholt i think this is fixed by @BenAuerDev https://github.com/serverpod/serverpod/pull/2455

**Comment by SandPod** [comment]
Closing as resolved.
