### ISSUE TITLE
Optional named parameter with default value is incorrectly interpreted as `required`

### ISSUE THREAD

**Issue by hampuslavin** [serverpod/serverpod#2788]
**Describe the bug**
Optional named parameters with a default value are incorrectly interpreted as `required`. Take this example:
```dart
Future<String?> echoOptionalNamedArgWithDefault(
  Session session, {
  String string = 'default',
}) async {
  return string;
}
```
This generates the following client incorrect signature:
```dart
_i2.Future<String?> echoOptionalNamedArgWithDefault(
          {required String string}) =>
```

**Solution** 
The problem lies in the `_isRequired` helper here:

https://github.com/serverpod/serverpod/blob/97d72a2ac377cc81a82a2e9f2ef6a82717283e12/tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_parameter_analyzer.dart#L112-L128

 It only checks for `nullabilitySuffix` but not for the presence of a default assignment.

This also requires the following issue to be fixed: https://github.com/serverpod/serverpod/issues/2787

**Comment by SandPod** [comment]
Closing as duplicate of: https://github.com/serverpod/serverpod/issues/584
