### ISSUE TITLE
Proper Documentation

### ISSUE THREAD

**Issue by agarwalrohit2503** [serverpod/serverpod#279]
Need a proper documentation for how to call endpoints from any application not created in flutter 
Right now i have cracked it as calling as a POST Request with having method name in the body but need to know whether this is 
the proper way or not?

**Comment by vlidholt** [comment]
The future plan for this is to provide code generation for languages other than Dart, but documentation would be nice also obviously. What is your use case?

**Comment by agarwalrohit2503** [comment]
My use case is basically to understand how to handle the requests in any app apart from flutter 
Like how to handle authentication, streams, file handling and all.

**Comment by vlidholt** [comment]
The focus for the 1.0 release this fall is making Serverpod really great for Flutter. After that, we may start looking at other platforms too.

**Comment by abcnow** [comment]
I wonder if there is any documentation related to proper folder architecture for a Production App? What would be the best strategy here? How would you handle those 3 created parts during this stage?

**Comment by vlidholt** [comment]
@abcnow if you use `serverpod create mypod`, `mypod` should be the root of the Git repository. Then all the deployment scripts etc will work.
