### ISSUE TITLE
MethodStreamManager: Type Mismatch in onTimeout callback for closeAllStreams() Method

### ISSUE THREAD

**Issue by KristijanZic** [serverpod/serverpod#2804]
**Describe the bug**
When a connection with a stream that has a controller defined in the endpoint gets cut, the closing errors out instead of being handled gracefully causing all the cancel or addWillCloseListener not to run. Specifically, the error is:

```sh
2024-10-02 13:15:35.798186Z Internal server error. Zoned exception.
type '() => void' is not a subtype of type '(() => Future<Null>?)?' of 'onTimeout'
#0      Future.timeout (dart:async/future_impl.dart:925:54)
#1      MethodStreamManager.closeAllStreams.<anonymous closure> (package:serverpod/src/server/websocket_request_handlers/helpers/method_stream_manager.dart:169:38)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:39:18)
#7      MethodStreamManager.closeAllStreams (package:serverpod/src/server/websocket_request_handlers/helpers/method_stream_manager.dart:175:23)
#8      MethodWebsocketRequestHandler.handleWebsocket (package:serverpod/src/server/websocket_request_handlers/method_websocket_request_handler.dart:89:33)
<asynchronous suspension>
```

**To Reproduce**
To reproduce the behavior create the following endpoint, listen to it on from the app and then quit the app.
```dart
class PokemonStreamEndpoint extends Endpoint {
  // ensure that the user is logged in (serverpod functionality)
  @override
  bool get requireLogin => true;

  // Stream Methods
  final pokemonStreamController = StreamController<PokemonDTO?>.broadcast(
    onCancel: () {
      print(" CANCELLING POKEMON STREAM");
    },
    onListen: () {
      print("LISTENING TO POKEMON STREAM");
    },
  );

  Stream<PokemonDTO?> pokemonStream(Session session) {
    return pokemonStreamController.stream;
  }
}
```

**Expected behavior**
The code should execute without a type mismatch, allowing the `onTimeout` function to run without causing an error.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Serverpod versions**
- _CLI Version:_ [2.1.3]

**Additional context**
This error is related to differences between `void` and `Future<Null>`, possibly due to a mismatch in Dart SDK expectations vs Serverpod implementation.

**Comment by t-kietzmann** [comment]
Any plans for shipping a hotfix for this?

As long as the PR is not released, all close-listener streams will not work if a broadcast stream is involved
