### ISSUE TITLE
Better type checks when parsing protocol yaml files

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#282]
Currently, the types in the yaml files are not properly checked. Adding a check would make it easier for new users to understand why things may not be working.

**Comment by II11II** [comment]
Hi @vlidholt 
What is the benefit of using yaml files to generate dart classes?
Is not it better to generate code depending on class that programmer creates?

**Comment by vlidholt** [comment]
The main benefit is that it's easy to also add other information in the yaml-files such as database indexes or information about data that shouldn't be stored in the database (e.g the api or database scope on variables).

**Comment by II11II** [comment]
Question out of my curiosity, does it have any disadvantages? if so, do not outweigh the disadvantages over the advantages?

**Comment by vlidholt** [comment]
No real disadvantages. Less code. The only thing is that you will need to separate the data from your logic.

**Comment by wstrange** [comment]
I had pretty much the same question here: https://github.com/serverpod/serverpod/discussions/626#discussioncomment-5387079

**Comment by vikas-flutter** [comment]
https://pub.dev/packages/checked_yaml can be used for type checks in yaml. But i am all in for dart classes for the db entities like suggested in https://github.com/serverpod/serverpod/discussions/626#discussioncomment-5387079
