### ISSUE TITLE
Error while trying to upload file

### ISSUE THREAD

**Issue by justasher** [serverpod/serverpod#2833]
When I tried to upload a file using Serverpod i got an error: ServerpodClientException: Internal server error, statusCode = 500

Here is my example code::
```
Future<String?> uploadFile(File file, String filePath) async {
  try {
    final uploadDescription = await client.files.getUploadDescription(filePath);
    
    if (uploadDescription != null) {
      final uploader = FileUploader(uploadDescription);
      final fileStream = file.openRead();
      final fileLength = await file.length();
      
      await uploader.upload(fileStream, fileLength);
      
      // Check upload success and get file URL
      if (await client.files.verifyUpload(filePath)) {
        return await client.files.getFileUrl(filePath);
      }
    }
    return null;
  } catch (e) {
    log("Upload file error: $e");
    rethrow;
  } finally {
    await fileStream.cancel(); 
  }
}
```

1- Call the function with an appropriate file and path.
2- Observe the error message that appears.

Expected behavior:
The file should be uploaded successfully, and the function should return the URL of the uploaded file.

**Comment by SandPod** [comment]
Hey @justasher!

How big is the file your are trying to upload? 
If the file is big you might need to configure the maxRequestSize configuration option listed in the documentation here: https://docs.serverpod.dev/concepts/configuration

If that does not solve your issue, could you please post the error logs along with the stacktrace?

**Comment by justasher** [comment]
> Hey @justasher!
> 
> How big is the file your are trying to upload? If the file is big you might need to configure the maxRequestSize configuration option listed in the documentation here: https://docs.serverpod.dev/concepts/configuration
> 
> If that does not solve your issue, could you please post the error logs along with the stacktrace?

Hello, thank you for your help, it helped me solve my problem
