### ISSUE TITLE
verifyDirectFileUpload always returns false

### ISSUE THREAD

**Issue by justasher** [serverpod/serverpod#2841]
After the file is uploaded I tried to check that the upload is complete but it always returns false. I checked if my files were present in the serverpod_cloud_storage_direct_upload table and then retrieved a file path and retested with it but it still returns false

```
Future<bool> verifyUpload(Session session, String path) async {
  return await session.storage.verifyDirectFileUpload(
    storageId: 'public',
    path: path,
  );
}
```

**Comment by hampuslavin** [comment]
Hi @justasher! 
Thanks for the report! 

This is tracked in an existing issue: https://github.com/serverpod/serverpod/issues/2517
And there is a PR in progress to fix it here: https://github.com/serverpod/serverpod/pull/2745
