### ISSUE TITLE
Chat Module BROKEN in Serverpod 2.1.4

### ISSUE THREAD

**Issue by darko-bacic** [serverpod/serverpod#2856]
Hi, dear Serverpod developers, I want to say again how much I love your work and to keep it up!

**Describe the bug**
I'm building an app that uses the chat module. I was on server pod version 2.1.1 and saw that there was a new release, so I decided to update to 2.1.4. Oh man, what a costly mistake. I lost at least 3-4 hours trying to figure out what the problem was on my side, the local setup, or whatever it could be. 

Then after coming to some sense, I started to debug your code and saw where the error happened. After some recent updates on how you handle web sockets, you broke the connection process, and the chat module is useless.

The breaking change would be here (getConnectorByName):

![Screenshot 2024-10-11 at 19 23 16](https://github.com/user-attachments/assets/3fed7e16-f24d-4cfc-9a40-f5be7ab8c93c)

In the EndpointWebsocketRequestHandler.handleWebsocket() method, you are passing in the wrong EndpointDispatch to the _callStreamOpened() for modules. It should be **module** in line 38 and not the _endpointDispatch_ from my own server code.

<img width="970" alt="Screenshot 2024-10-12 at 14 49 20" src="https://github.com/user-attachments/assets/fdcaa6a7-3b2f-416c-8cfa-dd9e185938a2">

I would love to see a quick fix and some tests to cover the actual opening and communication with the streams since this bug will also break any other modules that some developers have built that utilize streams.

**To Reproduce**
1. Download chat example
2. Run the app
3. Try to send a message
4. See the error in serverpod server and in app

**Expected behavior**
The socket should be opened but it's not because it can't find the chat endpoint from the serverpod_chat module

**Screenshots**
Screenshot are attached above, and also one more here to see the server log.

<img width="1288" alt="Screenshot 2024-10-12 at 15 01 19" src="https://github.com/user-attachments/assets/09ed9fc1-c277-457a-8cca-8facb3304e36">

**Serverpod versions**
 -  _CLI Version: Serverpod version: 2.1.4
 - _Library version: 2.1.4 for each package

**Platform information**
MacBook Air M3, Sequoia

Flutter doctor:
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.94.2)

**Additional context**
None

**Comment by SandPod** [comment]
Thanks for the detailed report @darko-bacic! 

We will make sure to fast-track this fix along with test that validate this is not broken again.
