### ISSUE TITLE
Future Calls

### ISSUE THREAD

**Issue by agarwalrohit2503** [serverpod/serverpod#286]
### Discussed in https://github.com/serverpod/serverpod/discussions/285

<div type='discussions-op-text'>

<sup>Originally posted by **agarwalrohit2503** September 12, 2022</sup>
The given function is not defined and if not then how to do the future calls
<img width="441" alt="Screenshot 2022-09-12 at 4 39 17 PM" src="https://user-images.githubusercontent.com/33911927/189639164-d1fe1314-8e35-45dd-8110-f117a275138f.png">
</div>

So there is an error in the auto generated comment
it says call using session.server.futureCallWithDelay

![](https://user-images.githubusercontent.com/33911927/189642088-cad1c4f4-e30d-4bfe-842a-9f455ea74def.png)

/lib/src/future_calls/example_future_call.dart file which gets autogenerated

If possible can i contribute to fix that?

**Comment by vlidholt** [comment]
Yeah, feel free to submit a pull request! :)

**Comment by vlidholt** [comment]
Merged your PR :)
