### ISSUE TITLE
Error message for mismatch between database and project is incorrect

### ISSUE THREAD

**Issue by hampuslavin** [serverpod/serverpod#2879]
**Describe the bug**
Error message for mismatch between database and project is incorrect. 

**To Reproduce**
1. Create a new model
2. Don't run `serverpod generate`
3. Create a migration and apply it
4. Observe error

```bash
➜  <project_name>_server: ✗ dart bin/apply_migrations.dart             
SERVERPOD version: 2.1.5, dart: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64", time: 2024-10-17 12:59:19.871134Z
mode: development, role: maintenance, logging: normal, serverId: default
Applied database migration:
 - 20241017125808036
WARNING: The database does not match the target database:
 - Table "<table_name>" is not like the target database:
 - Missing Index "<unique_idx>".
```

**Expected behavior**
- The warning should be in the other direction. The index _does exist_ in the database but not in the project.
- A hint to run `serverpod generate` is probably appropriate

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_ 2.1.5
 - _Library version:_ 2.1.5

**Comment by vanlooverenkoen** [comment]
Thanks @hampuslavin indeed a hint to run `serverpod generate` again would have saved me some time

**Comment by klkucaj** [comment]
@hampuslavin I followed all the steps to reproduce the issue but was unable to replicate it. I’m closing this PR for now. If the issue resurfaces later, we can reopen it.
