### ISSUE TITLE
"muti-user": is it wanted?

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#2884]
https://github.com/serverpod/serverpod/blob/bee2cfe19bac000f3f09517d4a66b439f83e8cc3/templates/serverpod_templates/projectname_server_upgrade/deploy/aws/scripts/install_dependencies#L36

Seems a pretty important typo

**Comment by SandPod** [comment]
This typo also exists in the documentation and should be fixed there simultaneously.
