### ISSUE TITLE
Support transaction savepoint and rollbacks

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2938]
**Is your feature request related to a problem? Please describe.**
Database transactions support adding and releasing savepoints and rolling back to these savepoints.

Savepoint documentation for postgres here: https://www.postgresql.org/docs/current/sql-savepoint.html
Release savepoint documentation for postgres here: https://www.postgresql.org/docs/current/sql-release-savepoint.html
Rollback documentation for postgres here: https://www.postgresql.org/docs/current/sql-rollback-to.html

**Describe the solution you'd like**
Serverpod should provide a typed interface for adding savepoints and rolling back during a transaction.

**Comment by hampuslavin** [comment]
Releasing save points should probably also be part of this task: https://www.postgresql.org/docs/current/sql-release-savepoint.html

**Comment by SandPod** [comment]
> Releasing save points should probably also be part of this task: https://www.postgresql.org/docs/current/sql-release-savepoint.html

Good point, updated the issue!
