### ISSUE TITLE
Geospatial Queries like the ones in MongoDB

### ISSUE THREAD

**Issue by Shiba-Kar** [serverpod/serverpod#2946]
https://www.mongodb.com/docs/manual/geospatial-queries/#geospatial-queries

**Comment by binemmanuel** [comment]
I used Firebase for this one my app, if only Serverpod had support for it

**Comment by SandPod** [comment]
This is a duplicate of the issue tracked here, closing as duplicate: https://github.com/serverpod/serverpod/issues/2439

This is something we will add support for in the future.
