### ISSUE TITLE
Quick opening and closing of multiple streams from stream endpoint methods fails

### ISSUE THREAD

**Issue by christerswahn** [serverpod/serverpod#2952]
**Describe the bug**
Quick opening and closing of multiple streams from stream endpoint methods fails with `Unhandled exception: Method stream WebSocket connection closed`.

**To Reproduce**

Assuming there is a stream endpoint method `laika.exercise.pump()`, this client code causes the stream failure:

```
  final pumps = <Stream<String>>[];
  for (int i = 0; i < 10; i++) {
    pumps.add(laika.exercise.pump());
  }
  for (final pump in pumps) {
    await for (final str in pump) {
      print(str);
    }
  }
```

An alternative reproduction, creating multiple streams quickly while keeping them open (just pausing them):

```
  final pumps = <Stream<String>>[];
  for (int i = 0; i < load; i++) {
    pumps.add(laika.exercise.pump());
    // For comparison, when instead creating the following local stream, it works:
    // pumps.add(Stream.fromIterable(List.generate(
    //   pumpLength,
    //   (final i) => '$i',
    // )));
  }
  for (final pump in pumps) {
    StreamSubscription<String>? sub;
    var count = 0;
    sub = pump.listen(
      (final String str) {
        print(str);
        if (++count >= 2 && sub != null) {
          sub.pause();
        }
      },
    );
  }
```

**Expected behavior**

The streams should succeed normally. Clients should be able to open and close multiple streams in quick succession.

**Serverpod versions**

Serverpod version: 2.2.0-beta.1

**Platform information**

MacOS, bash, simple CLI client towards Serverpod server.

**Comment by hampuslavin** [comment]
Could possibly be related to this previous issue that I created: #2818
