### ISSUE TITLE
User table name

### ISSUE THREAD

**Issue by g123k** [serverpod/serverpod#298]
Hello,

In Postgres, the `user` table name [is reserved](https://stackoverflow.com/questions/22256124/cannot-create-a-database-table-named-user-in-postgresql), but it's still possible to use it. The only change to make is to wrap the table name between quotation marks:

From: 
```
CREATE TABLE user
```

To: 
```
CREATE TABLE "user"
```

And this should be done for all queries to the database.

**Comment by vlidholt** [comment]
Thanks for the report, will try to fix! It may affect other code too though.

**Comment by II11II** [comment]
@vlidholt @g123k it is fixed in the scope of #384 pr

**Comment by vlidholt** [comment]
Thanks, closing this one.
