### ISSUE TITLE
errors running serverpod generate using v2.2.0

### ISSUE THREAD

**Issue by starklord** [serverpod/serverpod#2990]
Hi, while updating serverpod from 2.1.5 to 2.2.0
there is a problem when running "serverpod generate"
the file lib/src/generated/endpoints.dart
create contraslashes instead slasche for the import routes. For example:
import '..\endpoints\branch_service.dart' as _i2;
import '..\endpoints\enterprise_service.dart' as _i3;
import '..\endpoints\finance\cash_service.dart' as _i4;
import '..\endpoints\hr\employee_service.dart' as _i5;

that gives me the error: "Target of URI doesn´t exists"

so i am changing manually to this:

import '../endpoints/branch_service.dart' as _i2;
import '../endpoints/enterprise_service.dart' as _i3;
import '../endpoints/finance/cash_service.dart' as _i4;
import '../endpoints/hr/employee_service.dart' as _i5;

and everythigs seems running ok. But while its a generated file i shouldnt do this change manually.

My Operating System is Windows 11, using VSCode

**Comment by SandPod** [comment]
Thank you for the report!

We will create a fix for this ASAP!
