### ISSUE TITLE
Serverpod command failing to download templates

### ISSUE THREAD

**Issue by craiglabenz** [serverpod/serverpod#300]
I am connected to the internet and just installed Serverpod, which I presume guarantees that I'm using the latest version.

Any troubleshooting tips?

```
$ serverpod
Downloading templates for version 0.9.12
Failed to download templates.
Could not download the required resources for Serverpod. Make sure that you are connected to the internet and that you are using the latest version of Serverpod.
```

**Comment by vlidholt** [comment]
Will have this fixed tomorrow!

**Comment by vlidholt** [comment]
New version released. pub.dev had changed the address for where packages are archived.
