### ISSUE TITLE
built-in support for offline-first projects: record/table/global stamps, merging, syncing

### ISSUE THREAD

**Issue by macMikey** [serverpod/serverpod#3009]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
* every mobile app we have written assumes that the network connection will be intermittent. that means that each client has its own sqlite instance, followed by syncing with the server.
* obviously, some operations must be done, live, and rejected, if not
* to facilitate this, we have implemented record stamps, table stamps, and global stamps on our databases. when the mobe has comms with the server, syncing and merging occurs.
* serverpod supporting + automating this process would be a great 

**Describe alternatives you've considered**
implementing these features, ourselves.

**Additional context**

**Comment by SandPod** [comment]
Hey @macMikey!

This is a feature we are really enthusiastic about and have on our long-term roadmap. It is quite a big feature to build that will take some careful consideration to integrate in an intuitive way.

But if everything goes as planned, this should be part of the Serverpod framework in the future.

We already have a couple of other issues that track somewhat related features: https://github.com/serverpod/serverpod/issues/2258, https://github.com/serverpod/serverpod/issues/1719

Also worth mentioning this discussion: https://github.com/serverpod/serverpod/discussions/2084

Do you think this feature is represented in the other issues or should we track this separately here?

**Comment by macMikey** [comment]
oh, look, crdt.
never mind, closing this issue.
