### ISSUE TITLE
Serverpod create should check which version of Flutter is installed.

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#304]
It looks like if an older version of Flutter is installed, Serverpod will just fail to work, but without any good warnings.

**Comment by SandPod** [comment]
We now display errors if any issue would occur when running `flutter create`.

If Serverpod is not compatible with the version of Flutter installed then normal Dart errors will be displayed.

This should be enough to help users understand if an incompatible version of flutter is installed.
Please feel free to reopen @vlidholt if that is not the case.
