### ISSUE TITLE
Serialization Issue with Set<int> Parameters in Serverpod Endpoints

### ISSUE THREAD

**Issue by justasher** [serverpod/serverpod#3041]
**Describe the bug**
When using a Set<int> as a parameter in a Serverpod endpoint method, an error occurs when the Flutter client tries to call the method. The error message is:
Converting object to an encodable object failed: _Set len:0.

The issue resolves when the parameter is changed to List<int> instead of Set<int>.

**To Reproduce**
1- Create a Serverpod endpoint with a method that accepts a Set<int> parameter, for example:

```
class MyEndpoint extends Endpoint {
  Future<List<Object>> getMyObjects(Session session, Set<int> ids) async {
    return await Object.db.find(session, where: (t) => t.id.notInSet(ids), limit: 10);
  }
}
```

2- Call the endpoint method from a Flutter app:

```
Future<List<Object>> getObjects(Set<int> ids) async {
  return await client.objects.getMyObjects(ids);
}
```

3- Observe the error in the Flutter app:

```
Converting object to an encodable object failed: _Set len:0.
```

**Expected behavior**
The Set<int> parameter should be correctly serialized and deserialized between the Flutter client and Serverpod without throwing an error.

**Serverpod versions**
 -  _CLI Version: 2.2.1
 - _Library version: 2.2.1

**Platform information**
iOS 18.1 simulator

**Comment by SandPod** [comment]
Hey @justasher!

The `Set` type is not yet supported by the framework as an endpoint parameter.

The supported endpoint parameter types are listed here: https://docs.serverpod.dev/concepts/working-with-endpoints#passing-parameters

There already exists an issue to track this here https://github.com/serverpod/serverpod/issues/1784 and here https://github.com/serverpod/serverpod/issues/1915.

Closing this as duplicate.
