### ISSUE TITLE
Generate enums instead of classes for enums specified by the protocol

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#307]
Currently, enums specified in the protocol are generated as classes.

In my opinion it is more elegant and user/developer friendly to generate dart enums instead.

**Comment by vlidholt** [comment]
That would indeed be preferable, the problem is how the serialization currently works and how the values are stored in the database. It's possible that it can be fixed in a future version.

**Comment by fischerscode** [comment]
Apart from the mentioned edge case, the implementation in #308 should be compatible.
