### ISSUE TITLE
Signup using phone number instead of email

### ISSUE THREAD

**Issue by mozexty** [serverpod/serverpod#315]
How to implement signup using phone number and OTP instead of email/password ?

**Comment by vlidholt** [comment]
Right now, you would need to do this solution yourself. It would be pretty easy to base it on the email solution. It is a planned future feature though.

Another option can be to use the Firebase login, which supports phone numbers.

**Comment by GautamSharma05** [comment]
I want to work on that issue can you assign me this label, so I can start work on this issue @vlidholt

**Comment by Faizan-Pasha** [comment]
@GautamSharma05 Have you done it?

**Comment by GautamSharma05** [comment]
Not yet @Faizan-Pasha

**Comment by Faizan-Pasha** [comment]
@GautamSharma05 No worries. I did it #1362.

**Comment by SandPod** [comment]
New Issue created for this here: https://github.com/serverpod/serverpod/issues/2050

Closing this issue as it will be tracked there.
