### ISSUE TITLE
add video tutorial

### ISSUE THREAD

**Issue by alikaptanoglu** [serverpod/serverpod#324]
add video tutorial

**Comment by vlidholt** [comment]
Video tutorials are coming with the 1.0 release.

CodeX has done three tutorials on Serverpod so far: https://www.youtube.com/watch?v=3Q2vKGacfh0

**Comment by abcnow** [comment]
I have watched some of the video tutorials.. @vlidholt can we just get something practical in there like a chat app and a newsapp?
