### ISSUE TITLE
Serverpod cannot be used in Dart+HTML (webdev)

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#329]
I have been trying to do my portfolio with serverpod using Dart and HTML. And I ran into some issue which is almost this https://github.com/dart-lang/build/issues/2719. When I check the client code, I found it uses `dart:io` import. Where it doesn't support where we use `dart:html`. `io` is being used for [SecurityContext](https://api.flutter.dev/flutter/dart-io/SecurityContext-class.html).

Any alternate for this?

**Comment by yahu1031** [comment]
Serverpod works with HTML when we comment out `SecurityContext` and remove `dart:io` from the client code, which is not supposed to be edited.

## Changes I have done in order to make it work
```diff
/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: public_member_api_docs
// ignore_for_file: unused_import
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: depend_on_referenced_packages


--// import 'dart:io';
++// import 'dart:io';
import 'dart:typed_data' as typed_data;

import 'package:serverpod_client/serverpod_client.dart';

...

class Client extends ServerpodClient {
  late final _EndpointExample example;

  Client(String host,
      {
--    SecurityContext? context,
++    // SecurityContext? context,
      ServerpodClientErrorCallback? errorHandler,
      AuthenticationKeyManager? authenticationKeyManager})
      : super(host, Protocol.instance,
--          // context: context,
++          // context: context,
            errorHandler: errorHandler,
            authenticationKeyManager: authenticationKeyManager) {
    example = _EndpointExample(this);
  }

  @override
  Map<String, EndpointRef> get endpointRefLookup => {
        'example': example,
      };

  @override
  Map<String, ModuleEndpointCaller> get moduleLookup => {};
}
```

## Results
With default generated client code
<img width="1440" alt="Screenshot 2022-11-16 at 1 57 30 AM" src="https://user-images.githubusercontent.com/35523357/202018740-bdba90ac-2bf4-45ef-ae78-d4945b899308.png">

With modified client code
<img width="1440" alt="Screenshot 2022-11-16 at 1 58 52 AM" src="https://user-images.githubusercontent.com/35523357/202018964-98fce486-ad35-4737-a5d2-11af03b31de8.png">

`web/main.dart`

```dart
import 'dart:html';

import 'package:portfolio_client/portfolio_client.dart';

Client client = Client(
  'http://localhost:8080/',
);
void main() {
  print('object');
  client.example.hello('Minnu').then((response) {
    querySelector('#output')?.text = response;
  });
}
```

Screen recording
<video src="https://user-images.githubusercontent.com/35523357/202021858-d1c6d073-1ed3-43ca-a552-4118bde33c1d.mov" >

**Comment by vlidholt** [comment]
Tested new project on Flutter web and it works.

**Comment by yahu1031** [comment]
@vlidholt no no Not in flutter web. Dart web (Dart + HTML + CSS) I meant.

**Comment by yahu1031** [comment]
@vlidholt Reopen this, as we have discussed, I will be sharing all the recordings to reproduce this.

**Comment by yahu1031** [comment]
`client.dart` - `import 'dart:io' as _i3;` this will result in not letting the HTML+Dart code not to run due to `dart:html` import in website.

NOTE: This is not related to flutter. Pure Dart.

**Comment by yahu1031** [comment]
https://github.com/serverpod/serverpod/blob/67433c273db740ad1d1f4d9d31fbe304c77ca0f1/tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart#L608-L610

This will give a fix if we do this in generator

```diff
Parameter((p) => p
  ..name = 'context'
  ..named = true
  ..type = TypeReference((t) => t
--    ..symbol = 'SecurityContext'
++    ..symbol = 'dynamic')),
--    ..url = 'dart:io'
--    ..isNullable = true)),
```
