### ISSUE TITLE
Usage of `dart:mirrors` prevents compiling server ahead of time

### ISSUE THREAD

**Issue by tp** [serverpod/serverpod#33]
The import of `dart:mirrors` prevents the static compilation of the server (with `dart compile exe bin/main.dart`).

https://github.com/serverpod/serverpod/blob/78086b22bda9f966c040020f0447355291ad4a71/packages/serverpod/lib/src/database/table.dart#L1

Instead of using reflection here, it seems very possible to fix this in code generation and implement `void setColumn(String columnName, dynamic value)` for each `TableRow` subtype with a `switch` assigning to the local field.

**Comment by vlidholt** [comment]
Fixed
