### ISSUE TITLE
Need support for adding folder under protocol folder in XXXX_server for model generation

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#330]
While developing an application, We use a lot of models, and having all of them in one folder doesn't look organized.

EG:
This is what we have
```
protocol
   |-- auth_req.yaml
   |-- auth_res.yaml
   |-- some_other.yaml
```

This is what I ask for

```
protocol
   |-- auth
   |    |----- res.yaml
   |    |----- req.yaml
   |
   |
   |-- some_other.yaml
```

```
generated
   |-- auth
   |    |----- res.dart
   |    |----- req.dart
   |
   |
   |-- endpoints.dart
   |-- protocol.dart
   |-- some_other.dart
```

What happens if we continue with what we have then there will be a lot of files in a single folder and get confused and project structuring will be easy as also refactoring.

**Comment by vlidholt** [comment]
You aren't really supposed to touch the generated code. Can you describe what use case this enables other than just neatness?

**Comment by yahu1031** [comment]
@vlidholt Yes, just an organized project, instead of searching for a file in a huge generated list of files it is much easier to check out. LMK if there is any kind of complexity...

**Comment by AndryHTC** [comment]
@vlidholt in #331 this seems ready! 😄
