### ISSUE TITLE
Problem running 'dart pub global activate serverpod_cli' install serverpod

### ISSUE THREAD

**Issue by julianoventola** [serverpod/serverpod#342]
I just ran the command to activate it and got the following:
![image](https://user-images.githubusercontent.com/28475558/197847236-9cf978d7-ce47-4581-b968-e92b5458bb16.png)
![image](https://user-images.githubusercontent.com/28475558/197847319-572add09-368c-4697-9713-9ea66cf4154f.png)
![image](https://user-images.githubusercontent.com/28475558/197847380-d4be70ea-0259-4586-9137-bccc17a283aa.png)

Can you help me understand please?

**Comment by julianoventola** [comment]
I tried again 2h later and it worked 😃

**Comment by vlidholt** [comment]
Looks like this may have been an issue with the dart/pub tooling. Glad it works now!
