### ISSUE TITLE
Update macos/Runner/DebugProfile.entitlements for generated flutter MacOS projects

### ISSUE THREAD

**Issue by mirozahorak** [serverpod/serverpod#358]
without following line generated project does not have rights for network access on MacOS app.
<key>com.apple.security.network.client</key>
<true/>

**Comment by vlidholt** [comment]
It would be great to find a way to automatically set that up when creating the project. The problem right now is that the project setup is using `flutter create` to setup the MacOS part of the project.

**Comment by SandPod** [comment]
This is now solved when creating a new project: https://github.com/serverpod/serverpod/pull/2209
