### ISSUE TITLE
Make sure documentation is up-to-date

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#36]
Check all documentation:
- [x] Getting started
- [ ] Chat module
- [x] Auth module
- [x] Adding modules
- [x] Authentication
- [x] Streaming
- [x] Cache
- [x] Database

**Comment by MarkOSullivan94** [comment]
@vlidholt I'm guessing this is out of date as latest version of Serverpod which I'm using is `0.9.5`?

**Comment by vlidholt** [comment]
Updated docs are here: https://docs.serverpod.dev Docs are compatible with 0.9.5 with some minor changes.
