### ISSUE TITLE
[constraint] cannot override error response [4**-5**] 

### ISSUE THREAD

**Issue by II11II** [serverpod/serverpod#369]
To send an informative error response to the client, it is needed to allow override the error status code and its response

Actual behavior: Allow overriding error response [4**-5**] 
Non-informative:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/45257709/201527346-58880784-637b-4ff0-84d4-3c4f7823dc18.png">

Expected behavior: Allow overriding error response [4**-5**]

**Comment by vlidholt** [comment]
Passing information like this to the client can be a security concern as you generally want to reveal as little information as possible to the client. The (very soon) coming Serverpod companion app will help you pinpoint these issues by searching for log ids.
