### ISSUE TITLE
Update and simplify examples

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#389]
Make sure all examples are working with new serialization.

- [x] Authentication
- [x] Chat (create a new project for the chat)
- [x] Pixorama (also fix possible caching issues)

**Comment by II11II** [comment]
@vlidholt It is better to fill the docs
Currently, docs do not have full information

**Comment by II11II** [comment]
@vlidholt 
I think the doc should answer the below questions

how does the serverpod auth work under the hood?( what tables are created? When does serverpod get user info from firebase? Does serverpod synchronise with firebase automatically or per user request?
What are endpoints of serverpod auth?
)

How to check requests using postman or other clients?

**Comment by II11II** [comment]
I know some of them have already been answered on github discussion.
But it is better to have the answers in the docs

**Comment by II11II** [comment]
FYI:
While you are updating the docs, kindly request to update the link in the docs and maybe leave the some comments 

https://github.com/serverpod/serverpod/issues/350#issuecomment-1306862643

**Comment by AndryHTC** [comment]
I think the docs that are included in this version, are just a quick start: they do not explain everything a developer needs to know to confidently feel the framework as a completely manageable solution.

Right at the beginning, the serialization part is missing in how can you manually deserialize an object. Should be used the Protocol class? Why?
Or should be used directly the `SerializableObject `with his method `.toJson`? And if so, what is the `SerializationManager`, and how can be passed as a parameter?

Our team have lost a few hours just to understand how to transform a basic JSON into a protocol's generated object, and even now we're not sure that we should deserialize as we've found with a deep dive into the implementation.

The concept behind Serverpod is awesome, and so should be the documentation. The best part of Flutter is the simplicity/discoverability/transparency of both code APIs and documentation around it. If Serverpod aims to be the Flutter for servers, there should be a more _Flutterish_ approach in the APIs/documentation: do not make the stupid proof, just make them enjoyable even for who want more.

**Comment by vlidholt** [comment]
Thanks for the feedback @AndryHTC, we are usually very fast at replying to messages here or on the discussion board if you run into any issues. I've been on vacation for the past week, so that's why the response has been somewhat slow.

As for the deserialization, typically Serverpod will handle this automatically unless you have some very special use case? Can you describe a bit more what that is you want to do?

**Comment by AndryHTC** [comment]
> Thanks for the feedback @AndryHTC, we are usually very fast at replying to messages here or on the discussion board if you run into any issues. I've been on vacation for the past week, so that's why the response has been somewhat slow.

Sure, I appreciate your efforts

> As for the deserialization, typically Serverpod will handle this automatically unless you have some very special use case? Can you describe a bit more about what that is you want to do?

Just a quick example, I'm using a PlanetScale DB as Write Model and Firestore as a read one. How should I pass between the server and clients the data? Now it's possible even with custom classes, but when I started with Serverpod there wasn't this option, and I also opted for the protocols as in the future the serialization/transmission/deserialization could largely be optimized.

So, how can I manually deserialize a JSON (Map) into a Serverpod-generated protocol from a query done in another DB or retrieved by another way that does not consider the native Postgres one?

**Comment by AndryHTC** [comment]
#515
