### ISSUE TITLE
2022-11-23 11:15:42.212015Z Failed to connect to database. PostgreSQLSeverity.error 42P01: relation "serverpod_runtime_settings" does not exist

### ISSUE THREAD

**Issue by Shubhamdsingh** [serverpod/serverpod#407]
SERVERPOD version: 0.9.19 mode: development time: 2022-11-23 11:15:41.387691Z
2022-11-23 11:15:42.212015Z Failed to connect to database.
PostgreSQLSeverity.error 42P01: relation "serverpod_runtime_settings" does not exist
package:postgres/src/connection.dart 513:18 _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 474:7 _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart 542:22 _PostgreSQLExecutionContextMixin.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 769:23 _PgExecutionContextWrapper.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 695:27 _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 768:12 _PgExecutionContextWrapper.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 631:16 PgPool.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 332:22 PgPool.run..
package:postgres_pool/postgres_pool.dart 431:27 PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 403:14 PgPool._withConnection.
package:executor/src/executor_impl.dart 61:19 _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 171:20 DatabaseConnection.find
package:serverpod/src/database/database_connection.dart 199:18 DatabaseConnection.findSingleRow
package:serverpod/src/database/database.dart 86:12 Database.findSingleRow
package:serverpod/src/server/serverpod.dart 312:13 Serverpod.start.
package:serverpod/src/server/serverpod.dart 301:5 Serverpod.start
package:serverpod_demo_server/server.dart 30:3 run
===== asynchronous gap ===========================
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 171:20 DatabaseConnection.find
package:serverpod/src/database/database_connection.dart 199:18 DatabaseConnection.findSingleRow
package:serverpod/src/database/database.dart 86:12 Database.findSingleRow
package:serverpod/src/server/serverpod.dart 312:13 Serverpod.start.
package:serverpod/src/server/serverpod.dart 301:5 Serverpod.start
package:serverpod_demo_server/server.dart 30:3 run

2022-11-23 11:15:43.849357Z Internal server error. Failed to load method lookup.
PostgreSQLSeverity.error 42P01: relation "serverpod_method" does not exist
package:postgres/src/connection.dart 513:18 _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 474:7 _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart 542:22 _PostgreSQLExecutionContextMixin.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 769:23 _PgExecutionContextWrapper.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 695:27 _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 768:12 _PgExecutionContextWrapper.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 631:16 PgPool.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 332:22 PgPool.run..
package:postgres_pool/postgres_pool.dart 431:27 PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 403:14 PgPool._withConnection.
package:executor/src/executor_impl.dart 61:19 _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 171:20 DatabaseConnection.find
package:serverpod/src/database/database_connection.dart 199:18 DatabaseConnection.findSingleRow
package:serverpod/src/database/database.dart 86:12 Database.findSingleRow
package:serverpod/src/server/method_lookup.dart 47:26 MethodLookup._attemptLoad
package:serverpod/src/server/method_lookup.dart 30:7 MethodLookup.load
package:serverpod/src/server/serverpod.dart 327:9 Serverpod.start.
package:serverpod/src/server/serverpod.dart 301:5 Serverpod.start
package:serverpod_demo_server/server.dart 30:3 run
===== asynchronous gap ===========================
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 171:20 DatabaseConnection.find
package:serverpod/src/database/database_connection.dart 199:18 DatabaseConnection.findSingleRow
package:serverpod/src/database/database.dart 86:12 Database.findSingleRow
package:serverpod/src/server/method_lookup.dart 47:26 MethodLookup._attemptLoad
package:serverpod/src/server/method_lookup.dart 30:7 MethodLookup.load
package:serverpod/src/server/serverpod.dart 327:9 Serverpod.start.
package:serverpod/src/server/serverpod.dart 301:5 Serverpod.start
package:serverpod_demo_server/server.dart 30:3 run

Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082
2022-11-23 11:15:44.190060Z Internal server error. Failed to connect to database in future call manager.
PostgreSQLSeverity.error 42P01: relation "serverpod_future_call" does not exist
package:postgres/src/connection.dart 513:18 _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 474:7 _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart 542:22 _PostgreSQLExecutionContextMixin.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 769:23 _PgExecutionContextWrapper.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 695:27 _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 768:12 _PgExecutionContextWrapper.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 631:16 PgPool.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 332:22 PgPool.run..
package:postgres_pool/postgres_pool.dart 431:27 PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 403:14 PgPool._withConnection.
package:executor/src/executor_impl.dart 61:19 _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 456:20 DatabaseConnection.deleteAndReturn
package:serverpod/src/database/database.dart 166:12 Database.deleteAndReturn
package:serverpod/src/server/future_call_manager.dart 99:18 FutureCallManager._checkQueue
===== asynchronous gap ===========================
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 456:20 DatabaseConnection.deleteAndReturn
package:serverpod/src/database/database.dart 166:12 Database.deleteAndReturn
package:serverpod/src/server/future_call_manager.dart 99:18 FutureCallManager._checkQueue

Local stacktrace:
#0 FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:136:36)

2022-11-23 11:15:49.445007Z Internal server error. Failed to connect to database in future call manager.
PostgreSQLSeverity.error 42P01: relation "serverpod_future_call" does not exist
package:postgres/src/connection.dart 513:18 _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 474:7 _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart 542:22 _PostgreSQLExecutionContextMixin.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 769:23 _PgExecutionContextWrapper.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 695:27 _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 768:12 _PgExecutionContextWrapper.mappedResultsQuery
package:postgres_pool/postgres_pool.dart 631:16 PgPool.mappedResultsQuery.
package:postgres_pool/postgres_pool.dart 332:22 PgPool.run..
package:postgres_pool/postgres_pool.dart 431:27 PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 403:14 PgPool._withConnection.
package:executor/src/executor_impl.dart 61:19 _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 456:20 DatabaseConnection.deleteAndReturn
package:serverpod/src/database/database.dart 166:12 Database.deleteAndReturn
package:serverpod/src/server/future_call_manager.dart 99:18 FutureCallManager._checkQueue
===== asynchronous gap ===========================
package:postgres_pool/postgres_pool.dart 331:18 PgPool.run.
package:retry/retry.dart 131:16 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14 PgPool.run
package:serverpod/src/database/database_connection.dart 456:20 DatabaseConnection.deleteAndReturn
package:serverpod/src/database/database.dart 166:12 Database.deleteAndReturn
package:serverpod/src/server/future_call_manager.dart 99:18 FutureCallManager._checkQueue

Local stacktrace:
#0 FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:136:36)

@yahu1031 @II11II @vlidholt getting same error

**Comment by yahu1031** [comment]
What did it say when you run the [`tables.pgsql`](https://raw.githubusercontent.com/serverpod/serverpod/main/packages/serverpod/generated/tables.pgsql) script in your DB?

And also check this out once #122

**Comment by Shubhamdsingh** [comment]
Iam running the dart bin/main.dart and it showing above things @yahu1031

**Comment by Shubhamdsingh** [comment]
i actually cloned this project this from my friend's branch and running it @yahu1031

**Comment by yahu1031** [comment]
Yeah I understand, refer to what I have mentioned.
