### ISSUE TITLE
[constraint][enhancement] Dependency Injection

### ISSUE THREAD

**Issue by II11II** [serverpod/serverpod#419]
### OS : Mac OS

Dependency injection(DI) is providing the objects that an object needs (its dependencies) instead of having it construct them itself.
It's more clear and correct way to pass  implementation by constructors(usually) or by other way.

### The problem:

1. It is not clear how to pass dependency to Enpdoint classes. (To couple software modules loosely)
 f.e. **api client** which does request to other services or **other database** implementation. 
2. It is not clear how to apply ```factory pattern``` to `Serverpod` classes(f.e. `Enpdoint class`). (To be able to test or easily change implementation depeneding on flavour)

**Comment by SandPod** [comment]
I agree with the principle of this issue, but it is hard to understand what action is required to complete it.

I'll close this issue as we now provide a test framework to validate endpoints and their behavior.

@II11II - Please feel free to reopen this request with a more detailed clarification around where you would like to see dependency injection introduction.

**Comment by obiwanzenobi** [comment]
@II11II You can try our di library for serverpod: https://pub.dev/packages/launchpad/versions/0.0.4-rc.4
