### ISSUE TITLE
Update file_picker dependency - serverpod_auth_shared_flutter

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#421]
If someone is using a dependency that uses an updated version of `ffi` ("UPDATED"... it's from 6 months ago), he cannot use auth modules.
[serverpod_auth_shared_flutter/pubspec.yaml](https://github.com/serverpod/serverpod/tree/main/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml) depends on a very outdated version of the file_picker

```
Running "flutter pub get" in project_flutter...                  
Because serverpod_auth_firebase_flutter >=0.9.20 depends on serverpod_auth_shared_flutter ^0.9.20 which depends on file_picker ^4.1.6, serverpod_auth_firebase_flutter >=0.9.20 requires file_picker ^4.1.6.
And because file_picker ^4.0.0 depends on ffi ^1.1.2, serverpod_auth_firebase_flutter >=0.9.20 requires ffi ^1.1.2.
And because package_info_plus 3.0.2 depends on ffi ^2.0.1 and no versions of package_info_plus match >3.0.2 <4.0.0, serverpod_auth_firebase_flutter >=0.9.20 is incompatible with package_info_plus ^3.0.2.
So, because project_flutter depends on both package_info_plus ^3.0.2 and serverpod_auth_firebase_flutter ^0.9.20, version solving failed.
pub get failed (1; So, because project_flutter depends on both package_info_plus ^3.0.2 and serverpod_auth_firebase_flutter ^0.9.20, version solving failed.)
```

**Comment by yahu1031** [comment]
How about overriding then for time being till we get next version

**Comment by AndryHTC** [comment]
> How about overriding then for time being till we get next version

Obviosly. I reported it because I've seen the last dependencies upgrade #386 it's about 10 days ago: I thought you missed them :)

**Comment by vlidholt** [comment]
Fixed.
