### ISSUE TITLE
How to clean after a failed serverpod create attempt ?

### ISSUE THREAD

**Issue by mozexty** [serverpod/serverpod#425]
I had faced this many times.
1- `serverpod create mypod` failed, due to some error. Usually due to netstat being absent
2- I remove the mypod folder.
3- I use `docker-compose down` to stop the containers
4- I (in some cases) use `docker rm` to remove the containers
5- I fix the error (install netstat if needed)
6- `serverpod create mypod` again
7- `docker-compose up --build --detach`
8- `dart bin/main.dart` Then I get **Failed to connect to database.
PostgreSQLSeverity.fatal 28P01: password authentication failed for user "postgres"**
9- If I do `serverpod create mypod2` it works.

How to solve this issue in step 8 ?

**Comment by yahu1031** [comment]
Yes, that is because the volumes that are being used by the same name already exist. You need to clean the volumes too. @mozexty

**Comment by yahu1031** [comment]
There may be some other reasons too. But in your case, This is the case as I mentioned.

**Comment by mozexty** [comment]
Thank you @yahu1031.
I removed the volumes and it worked.
