### ISSUE TITLE
Generated file is changing and showing error  when i run watch command  in my server project 

### ISSUE THREAD

**Issue by Shubhamdsingh** [serverpod/serverpod#428]
/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: public_member_api_docs
// ignore_for_file: implementation_imports

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod/serverpod.dart' as _i1;
import 'protocol.dart' as _i2;

class AuthModel extends _i1.SerializableEntity {
  AuthModel({
    required this.status,
    required this.statusCode,
    required this.message,
    this.data,
  });

  factory AuthModel.fromJson(
    Map<String, dynamic> jsonSerialization,
    _i1.SerializationManager serializationManager,
  ) {
    return AuthModel(
      status:
          serializationManager.deserialize<bool>(jsonSerialization['status']),
      statusCode: serializationManager
          .deserialize<int>(jsonSerialization['statusCode']),
      message: serializationManager
          .deserialize<String>(jsonSerialization['message']),
      data: serializationManager
          .deserialize<_i2.User?>(jsonSerialization['data']),
    );
  }

  bool status;

  int statusCode;

  String message;

  _i2.User? data;

  @override
  Map<String, dynamic> toJson() {
    return {
      'status': status,
      'statusCode': statusCode,
      'message': message,
      'data': data,
    };
  }

  @override
  Map<String, dynamic> allToJson() {
    return {
      'status': status,
      'statusCode': statusCode,
      'message': message,
      'data': data,
    };
  }
}
@vlidholt @yahu1031

**Comment by yahu1031** [comment]
Please use this model to show code in GitHub tickets 😄 
\```dart
YOUR CODE
\```

Okie, So what was the error you get? Please mention the error too.

**Comment by Shubhamdsingh** [comment]
Error

Missing concrete implementations of 'SerializableEntity.serialize' and 'getter SerializableEntity.className'.
Try implementing the missing methods, or make the class abstract.dart[non_abstract_class_inherits_abstract_member](https://dart.dev/diagnostics/non_abstract_class_inherits_abstract_member)

@yahu1031

**Comment by yahu1031** [comment]
Which file is this? Custom model?

**Comment by yahu1031** [comment]
I got the same data but no error
```dart
/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: public_member_api_docs
// ignore_for_file: implementation_imports

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod/serverpod.dart' as _i1;
import 'protocol.dart' as _i2;

class AuthModel extends _i1.SerializableEntity {
  AuthModel({
    required this.status,
    required this.statusCode,
    required this.message,
    required this.data,
  });

  factory AuthModel.fromJson(
    Map<String, dynamic> jsonSerialization,
    _i1.SerializationManager serializationManager,
  ) {
    return AuthModel(
      status:
          serializationManager.deserialize<bool>(jsonSerialization['status']),
      statusCode: serializationManager
          .deserialize<int>(jsonSerialization['statusCode']),
      message: serializationManager
          .deserialize<String>(jsonSerialization['message']),
      data:
          serializationManager.deserialize<_i2.User>(jsonSerialization['data']),
    );
  }

  bool status;

  int statusCode;

  String message;

  _i2.User data;

  @override
  Map<String, dynamic> toJson() {
    return {
      'status': status,
      'statusCode': statusCode,
      'message': message,
      'data': data,
    };
  }

  @override
  Map<String, dynamic> allToJson() {
    return {
      'status': status,
      'statusCode': statusCode,
      'message': message,
      'data': data,
    };
  }
}
```

**Comment by Shubhamdsingh** [comment]
No it is a file from generated folder which automatically creates a file for our protocols folder file when we run watch command in our terminal

**Comment by Shubhamdsingh** [comment]
class: AuthModel
fields:
    status: bool
    statusCode: int
    message: String
    data: User?

**Comment by yahu1031** [comment]
@Shubhamdsingh Resolved?
