### ISSUE TITLE
No deserialization found for type `RuntimeSettings`

### ISSUE THREAD

**Issue by Shubhamdsingh** [serverpod/serverpod#432]
Shubhams-MacBook-Air:serverpod_demo_server shubhamsingh$ dart bin/main.dart
SERVERPOD version: 0.9.20 mode: development time: 2022-12-06 05:25:55.398510Z
2022-12-06 05:25:56.127243Z Failed to connect to database.
FormatException: No deserialization found for type RuntimeSettings
#0      SerializationManager.deserialize (package:serverpod_serialization/src/serialization.dart:73:5)
#1      Protocol.deserialize (package:serverpod_demo_server/src/generated/protocol.dart:80:18)
#2      DatabaseConnection._formatTableRow (package:serverpod/src/database/database_connection.dart:239:45)
#3      DatabaseConnection.find (package:serverpod/src/database/database_connection.dart:178:18)
<asynchronous suspension>
#4      DatabaseConnection.findSingleRow (package:serverpod/src/database/database_connection.dart:199:18)
<asynchronous suspension>
#5      Database.findSingleRow (package:serverpod/src/database/database.dart:86:12)
<asynchronous suspension>
#6      Serverpod.start.<anonymous closure> (package:serverpod/src/server/serverpod.dart:310:13)
<asynchronous suspension>
#7      Serverpod.start (package:serverpod/src/server/serverpod.dart:299:5)
<asynchronous suspension>
#8      run (package:serverpod_demo_server/server.dart:30:3)
<asynchronous suspension>

@yahu1031  @filonov @aldychris @tp @II11II @vlidholt

**Comment by yahu1031** [comment]
Similar issue to #426

**Comment by yahu1031** [comment]
Can you explain to us what function/method you called?

**Comment by yahu1031** [comment]
@Shubhamdsingh Please edit the title as 
No deserialization found for type \`RuntimeSettings\`

**Comment by Shubhamdsingh** [comment]
I am running my server project and its showing the above error
COMMAND
dart bin/main.dart

**Comment by yahu1031** [comment]
@Shubhamdsingh What is in here `serverpod_demo_server/server.dart` line 30

**Comment by Shubhamdsingh** [comment]
import 'package:serverpod/serverpod.dart';

import 'package:serverpod_demo_server/src/web/routes/root.dart';

import 'src/generated/protocol.dart';
import 'src/generated/endpoints.dart';

// This is the starting point of your Serverpod server. In most cases, you will
// only need to make additions to this file if you add future calls,  are
// configuring Relic (Serverpod's web-server), or need custom setup work.

void run(List<String> args) async {
  // Initialize Serverpod and connect it with your generated code.
  final pod = Serverpod(
    args,
    Protocol(),
    Endpoints(),
  );

  // If you are using any future calls, they need to be registered here.
  // pod.registerFutureCall(ExampleFutureCall(), 'exampleFutureCall');

  // Setup a default page at the web root.
  pod.webServer.addRoute(RouteRoot(), '/');
  // Serve all files in the /static directory.
  pod.webServer
      .addRoute(RouteStaticDirectory(serverDirectory: 'static'), '/static/*');

  // Start the server.
  await pod.start();
}

@yahu1031  this the code of  'serverpod_demo_server/server.dart'  file

**Comment by Shubhamdsingh** [comment]
@yahu1031  can u help me in this its urgent

**Comment by Shubhamdsingh** [comment]
@yahu1031  can tell me solution here only ?

**Comment by Shubhamdsingh** [comment]
1) I had created a project 
2) Started docker in background
3) In Server project i created protocols file and created endpoints with  'serverpod generate --watch ' running in terminal
4) Then i started postgres and redis with command  'docker-compose up --build --detach'
4) After that i runned my server project with command  'dart bin/main.dart'

@yahu1031

**Comment by yahu1031** [comment]
okie... sounds smooth. can you please check if the DB has all the tables?

**Comment by Shubhamdsingh** [comment]
@yahu1031  yes DB has all tables

**Comment by yahu1031** [comment]
Okie can you restart the system and try again?

**Comment by suhaelfarouk** [comment]
just clear the serverpod_runtime_settings table and restart the server and you are good to go.

**Comment by yahu1031** [comment]
this may work. Try it.

**Comment by Shubhamdsingh** [comment]
Thanks it works @yahu1031  @suhaelfarouk
