### ISSUE TITLE
Check that naming of a new project is valid

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#440]
There should be a check that the provided project name for `serverpod create` is valid lowecase and snakecase.

**Comment by yahu1031** [comment]
@vlidholt Ideally, the name validation was handled by flutter itself. But before doing it, then we need one. I can add that.

**Comment by Crazycoder122** [comment]
Maybe I would Like to contribute to this issue and start my Open Source Framework journey with Dart and Flutter with this one..

**Comment by yahu1031** [comment]
Okie go on, Good luck buddy @Crazycoder122

**Comment by Crazycoder122** [comment]
Did it and made a PR :)

**Comment by SandPod** [comment]
When creating the project a check for this now exists: https://github.com/serverpod/serverpod/blob/2865fdcce43dfcdd2ef0eeb40b982608bb1033bb/tools/serverpod_cli/lib/src/create/create.dart#L50
