### ISSUE TITLE
setup-tables: 9: netstat: not found Waiting for Postgres...

### ISSUE THREAD

**Issue by kutucobain** [serverpod/serverpod#447]
when create project always stuck in :+1: 
"setup-tables: 9: netstat: not found
Waiting for Postgres...

I'm use ubuntu

**Comment by yahu1031** [comment]
@kutucobain I'm aware of this issue, The is coming up. Meanwhile please follow this. https://github.com/serverpod/serverpod/issues/420#issuecomment-1332415970

**Comment by yahu1031** [comment]
You must be in the server folder of your project. and if it has the `setup-tables` file then edit in it and run that file, else create one and copy the content and change the required values such as `DB_PASSWORD`, `projectname` and try again.

**Comment by SandPod** [comment]
Now that creating database tables are not part of creating a project this issue can be closed.
