### ISSUE TITLE
ByteData values in generated serializable objects are inserted into the database incorrectly.

### ISSUE THREAD

**Issue by kralverde** [serverpod/serverpod#466]
When serializing a ByteData object to the database it encodes the actual "decode('xxxxx=', 'base64')" string as bytes. (e.g. `\x226465636f64652827414141414141414141414141414141414141414141414141414141414141414141514141414141414141413d272c2027626173653634272922` in the database)

Modifying https://github.com/serverpod/serverpod/blob/e1775f871c4ee02f82998b053131f7f6217f71f2/packages/serverpod/lib/src/database/value_encoder.dart#L10 to

```
String convert(value, {bool escapeStrings = true}) {
    print(value);
    if (value is ByteData || value is DateTime) {
      return convert(SerializationManager.encode(value),
          escapeStrings: escapeStrings);
    } else if (value is String &&
        value.startsWith('"decode(\'') &&
        value.endsWith('\', \'base64\')"')) {
      // TODO:
      // This is a bit of a hack to get ByteData working. Strings that starts
      // with `convert('` and ends with `', 'base64') will be incorrectly
      // encoded to base64. Best would be to find a better way to detect when we
      // are trying to store a ByteData.
      print('decode check');
      return value.substring(1, value.length - 1);
```

had it working again, probably because the encoded string is passed up to the super method which then treats it as a normal string, but the overridden method also treats it incorrectly as-is. I am unsure how my hotfix would affect other serializations.

**Comment by kralverde** [comment]
Note this also breaks the deserialization of these items from the database: as the value is essentially junk data without another level of parsing

**Comment by kralverde** [comment]
Also wondering why it is encoded in base64 rather than '\x' + hex encoding, which might make it simpler. Is that to decrease the actual size of the query?

**Comment by vlidholt** [comment]
@kralverde Fixed, this was a regression that happened when reworking the serialization layer. Added a test to make sure it works correctly and that it doesn't get broken again.

As I understand it base64 is more efficient than the hex encoding. However, it would be even more efficient to send the data as raw bytes. Hope to support that sometime in the future, but it's not highest on the priority list.
