### ISSUE TITLE
[Help]Need A demo project for Authentication , also i prefer all of aws services , so in this case i need all related stuff even in development mode

### ISSUE THREAD

**Issue by manishgautammg3994** [serverpod/serverpod#467]
As I found serverpod interesting but still i am facing some issues like authentication, s3 storage bucket, as in this case we have to configure the credentials, it will be better if you can provide us more Serverpod Example as you have provided like Chat ,Pixnorma

**Comment by vlidholt** [comment]
Working on the authentication example as we speak! :)

**Comment by manishgautammg3994** [comment]
*THANKS* , waiting curiously hope You will help me everytime , also I want to upload some Serverpod related Videos On my [Youtube Channel Antinna](https://youtube.com/@antinna) , Hope you will permit me to Do so </br> ``` <Reason for asking Permission:- BSD 3-Clause "New" or "Revised" License> ```

**Comment by vlidholt** [comment]
Added much improved docs for the authentication. It will be released in the next few days. A preview can be found here:
https://github.com/serverpod/serverpod_docs/blob/main/docs/04-concepts/07-authentication.md

@manishgautammg3994 I would love to see some Serverpod videos on your channel! Please let me know if you do so I can share here and in our social media. :)
