### ISSUE TITLE
Support nested mapping for `protocol/*.yaml` files

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#477]
`protocol/*.yaml` file doesn't support nested mapping. This could be a good enhancement to implement. So the object can be defined in one file itself. EG: #476

**Comment by SandPod** [comment]
Serverpod now supports nested map structure in the YAML files: https://github.com/serverpod/serverpod/blob/2865fdcce43dfcdd2ef0eeb40b982608bb1033bb/tests/serverpod_test_server/lib/src/models/types_map.spy.yaml#L29
