### ISSUE TITLE
Memory bloat/leak on sessions marked as non-logging

### ISSUE THREAD

**Issue by kralverde** [serverpod/serverpod#506]
Scenario: an internal session that exists for the duration of the server execution

Logs are always cached in the `SessionLogEntryCache` for internal sessions even if `enableLogging` is false. e.g:
https://github.com/serverpod/serverpod/blob/3f74c7508fff9ab37ef2a3b52de98bd456e1f6a3/packages/serverpod/lib/src/server/session.dart#L196

as they always fail this check https://github.com/serverpod/serverpod/blob/3f74c7508fff9ab37ef2a3b52de98bd456e1f6a3/packages/serverpod/lib/src/server/log_manager.dart#L157

Because of this the internal session gets bloated with stuff that can't get gc'd

Sessions with `enableLogging` set to false should not have stuff added to `SessionLogEntryCache` since it is only used in
https://github.com/serverpod/serverpod/blob/3f74c7508fff9ab37ef2a3b52de98bd456e1f6a3/packages/serverpod/lib/src/server/log_manager.dart#L308
which fast fails if `enableLogging` is false

**Comment by vlidholt** [comment]
Well spotted. I'll make sure this gets fixed!

**Comment by vlidholt** [comment]
I had a chance to look more closely at this. The sessions are meant to be used more momentarily. So, it's not recommended to setup a session when you start the server and use that throughout the duration of the server's life time.

Instead, create a new session for a particular task. This will also work better with the logging system. I will add some more documentation around this as it is not clear.
