### ISSUE TITLE
 serverpod_auth_google: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

### ISSUE THREAD

**Issue by Shubhamdsingh** [serverpod/serverpod#513]
serverpod_auth_google: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

getting this error when try to google sign in in serverpod project

@yahu1031 @vlidholt @II11II

**Comment by yahu1031** [comment]
@Shubhamdsingh Thanks for the issues. But This is not very specific to serverpod. It is an issue with the `google_sign_in` plugin. You are missing some configs. Please try googling the issue before you create a ticket here. This will help you in exploring things and learn new things. Cause in the GitHub tickets you won't be getting any explanations ideally. They will be fixed and merged. So you don't know why.

> **NOTE:** Please don't tag anyone.
