### ISSUE TITLE
Serverpod should use the default Postgres port or allow a `--postgresPort` flag when creating

### ISSUE THREAD

**Issue by TylerSustare** [serverpod/serverpod#523]
My previous issue was closed without a resolution. https://github.com/serverpod/serverpod/issues/517
I'm assuming it was a breakdown in communication because I was forced to use the `-f` flag.

## As a user of Serverpod, I want to use the default postgres port `5432`.
At the very least I should be able to pass a custom `--postgresPort` option to the cli when creating a new serverpod app.

## I'm blocked on using or contributing to serverpod until this is resolved.
See my previous issue for detail on why I can't run `serverpod create project`

```
$ serverpod create superduper
There are some issues with your setup that will prevent your Serverpod project from running out of the box and
without further configuration. You can still create this project by passing -f to "serverpod create" and
manually configure your Serverpod.

One or more network ports Serverpod want to use are not available. The most likely reason is that you have
another Serverpod project running, but it can also be another service.

Ports in use:
 • 8090: PostgreSQL server
```
When trying to identify the problem
```
$ sudo lsof -i :8090
Password:
COMMAND PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
launchd   1 root   11u  IPv4 0xb8c5c6c13b9d1987      0t0  TCP localhost:8090 (LISTEN)
```

**Comment by vlidholt** [comment]
It was moved to a discussion, as it was more of a question. But this is a great feature request, I'll try to make sure it gets done in the future.
