### ISSUE TITLE
type 'Null' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by alizera** [serverpod/serverpod#536]
I have a table called `city` that has `id`, `a1`, and `a2` columns, I want to do a `union all` query and get the sum of the particularly same rows, this is my endpoint:

```
  Future<List<List<dynamic>>> fetchMatchedCity(Session session) async {
    session.log("querying match...");
    final start = DateTime.now().millisecond;

    final result = await session.db.query(""" select id1, id2, sum(score) from (
	    select t1.id as id1 , t2.id as id2, 1 as score from city as t1, city as t2 where t1.a1 = t2.a1 and t1.id <> t2.id union all
        select t1.id as id1 , t2.id as id2, 1 as score from city as t1, city as t2 where t1.a2 = t2.a2 and t1.id <> t2.id
    ) as final
    where id1 > id2
    group by (id1, id2) order by sum(score) desc  """);

    return result;
  }
```

in `main.dart`:
```
....
onPressed: () async {
  await client.city.fetchMatchedCity();
}
```
I removed the usage of the result of `await client.city.fetchMatchedCity();` due to reduce the risk of errors! but I still get following error:

```
flutter: FormatException: No deserialization found for type dynamic
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: No deserialization found for type dynamic
#0      SerializationManager.deserialize (package:serverpod_serialization/src/serialization.dart:73:5)
#1      Protocol.deserialize (package:hlafit_client/src/protocol/protocol.dart:107:18)
#2      Protocol.deserialize.<anonymous closure> (package:hlafit_client/src/protocol/protocol.dart:96:40)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:51:28)
```

P.S: Query is working on db management applications like postico.

**Comment by yahu1031** [comment]
Similar/duplicates of #426 #432

**Comment by alizera** [comment]
@yahu1031 I don't understand these issues' points, https://github.com/serverpod/serverpod/issues/432#issuecomment-1339478060 didn't work for me, and https://github.com/serverpod/serverpod/issues/426 needs PR I think. So there is no fix for this issue now and I have to wait for the PR, am I right? Thanks, @yahu1031 for answering.

**Comment by yahu1031** [comment]
You can do one thing. Place a debugger there and see what is the data you get and runtime type. As the issue states it  is null, we need a deserializer for Null data type too. Check if you have that in serverpod deserialize package. I will update it once I check. @alizera

**Comment by vlidholt** [comment]
It's currently not supported to return `dynamic` objects from Serverpod. You will need to specify a serializable type (the ones you create in the yaml-files). It's possible we can add support for this in the future.

**Comment by alizera** [comment]
If I get your points and example project correctly:
1- I created a new module called `serverpod_test_shared` (actually copied it from the example project)
2- Add `serverpod_flutter: ^0.9.21` into this modules dependencies
3- Modify the `FreezedCustomClass` that already exists in this shared module
4- Run `flutter pub get` and run the `build_runner` to generate the `freezed` class of  `FreezedCustomClass`
5- Modify my endpoint:
```
 Future<List<FreezedCustomClass>> fetchMatchedCity(Session session) async {
    session.log("querying match...");
    final start = DateTime.now().millisecond;

    final result = await session.db.query(""" select id1, id2, sum(score) from (
	    select t1.id as id1 , t2.id as id2, 1 as score from city as t1, city as t2 where t1.a1 = t2.a1 and t1.id <> t2.id union all
        select t1.id as id1 , t2.id as id2, 1 as score from city as t1, city as t2 where t1.a2 = t2.a2 and t1.id <> t2.id
    ) as final
    where id1 > id2
    group by (id1, id2) order by sum(score) desc  """);

    return result as List<FreezedCustomClass>;
  }
```
6- Call it from my app and now a new error happens: 
```
flutter: Failed call: city.fetchMatchedCity
flutter: ServerpodClientException: Internal server error. Call log id: 172, statusCode = 500
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ServerpodClientException: Internal server error. Call log id: 172, statusCode = 500
#0      ServerpodClient.callServerEndpoint (package:serverpod_client/src/serverpod_client_io.dart:83:9)
<asynchronous suspension>
#1      HomePage.build.<anonymous closure> (package:hlafit/pages/home_page.dart:60:19)
<asynchronous suspension>
```

My query is working properly on my SQL app. Can you please help me for this? Or fix me if I'm wrong? Thanks guys for your awesome job and support ❤️

**Comment by yahu1031** [comment]
I didn't get exactly that `point 2`, but to check what the error is, please head over to the logs table in the DB and check for the `ID-172` 👉🏻 `Call log id: 172, statusCode = 500` as it mentioned. @alizera

**Comment by yahu1031** [comment]
Check with this please, 
```console
type '_PostgreSQLResult' is not a subtype of type 'List<FreezedCustomClass>' in type cast
```

**Comment by alizera** [comment]
@yahu1031 I understood the error, but I don't know how to fix it. At the end line of my endpoint method, I cast it to `List<FreezedCustomClass>` that may cause the error, but before it, it was `List<List<dynamic>>` that didn't work either.
Can you please help me to fix it? I think I'm mixing something stupidly easy.

**Comment by yahu1031** [comment]
@alizera type casting won't work all the time cause the API endpoint query is not returning the `FreezedCustomClass`, It returns `List<List<dynamic>>`. `List<List>` cannot be typecasted as custom models/Objects. Hope this will clear your doubt.

> I think I'm missing something stupidly easy.

Not actually cause many will get into issues at this point by directly typecasting the response. (Even I do sometimes 🤣)

**Comment by alizera** [comment]
Dear @yahu1031, I know what you're saying but I don't know what to do about my issue!!
Please look at my first comment, I was using `List<List<dynamic>>` as the return type of the method and I was getting `deserialization` error!

I think I can't get the idea behind serialization (I've read its [documentation](https://docs.serverpod.dev/concepts/serialization) twice and yet... I don't get it).

Finally, you can see my whole code and database and query and the result of the query (that consists of 2 int and one double columns), can you give me a straightforward solution, please? 🥺

Thank you again.

**Comment by yahu1031** [comment]
@alizera I can actually help you. 
> I was getting a `deserialization` error!

IS because it was getting null at that time. But later it was having the result(non-null value) but is not castable. That was the issue you get. Can you post the result here? Or you can contact me in twitter/linkedin

**Comment by SandPod** [comment]
We have not revisited this in a while, Is this still an issue or can we close this? There has been som major work regarding serialization and database communication to stabilize the interface.
