### ISSUE TITLE
Serverpod auth example client can't reach server

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#544]
Please see discussion thread in https://github.com/serverpod/serverpod/discussions/541 , but I will copy the important information here.

I copied code from `serverpod/examples/auth_example/auth_example_flutter/` to my own Flutter project. This project was able to successfully connect to the serverpod server in its module before I added this code.

However, the auth code does not seem to be able to contact the server. It seems to be using the wrong port (56888, not 8080):

```
I/flutter ( 4355): Failed call: serverpod_auth.google.authenticateWithServerAuthCode
I/flutter ( 4355): SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 56888
I/flutter ( 4355): serverpod_auth_google: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 56888
I/flutter ( 4355): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
I/flutter ( 4355): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1827:26)
I/flutter ( 4355): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
I/flutter ( 4355): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2048:22)
I/flutter ( 4355): #4      Socket.startConnect (dart:io/socket.dart:759:21)
I/flutter ( 4355): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2453:20)
I/flutter ( 4355): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867:12)
I/flutter ( 4355): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2872:12)
I/flutter ( 4355): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2727:12)
I/flutter ( 4355): #9      _HttpClient.postUrl (dart:_http/http_impl.dart:2601:49)
I/flutter ( 4355): #10     ServerpodClient.callServerEndpoint
package:serverpod_client/src/serverpod_client_io.dart:71
I/flutter ( 4355): <asynchronous suspension>
I/flutter ( 4355): #11     signInWithGoogle
package:serverpod_auth_google_flutter/src/auth.dart:70
I/flutter ( 4355): <asynchronous suspension>
```

The correct URL `http://localhost:8080/serverpod_auth.google` is being fetched by `serverpod_client_io.dart:71` as:

```
      var request = await _httpClient.postUrl(url);
```

However this throws an exception stating the wrong port number:

```
address: _InternetAddress (InternetAddress('127.0.0.1', IPv4))
message: "Connection refused"
osError: OSError (OS Error: Connection refused, errno = 111)
port: 55074
hashCode: 721684399
runtimeType: Type (SocketException)
```

The endpoint `serverpod_auth.google` is in fact being correctly registered in the server -- in `mypod_server/lib/src/generated/endpoints.dart` I see:

```
import 'package:serverpod_auth_server/module.dart' as _i3;
// ...
    modules['serverpod_auth'] = _i3.Endpoints()..initializeEndpoints(server);
```

If I visit `http://localhost:8080/serverpod_auth.google` in a web browser, I get a 400 error, so at least it's not giving `Connection refused`.

I have stepped through the code in the debugger to the extent that I could, and I can't see any reason this should be failing, so I suspect there may be some sort of bug here that I triggered.

**Comment by lukehutch** [comment]
Update: maybe this is a Dart framework bug. The following code in `main()` triggers the same issue:

```
  final socket = await Socket.connect('localhost', 8080);
  print('Connected to: ${socket.remoteAddress.address}:${socket.remotePort}');
```

```
E/flutter (30451): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 50730
E/flutter (30451): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
E/flutter (30451): #1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:948:12)
E/flutter (30451): #2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1815:26)
E/flutter (30451): #3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
E/flutter (30451): #4      Socket._connect (dart:io-patch/socket_patch.dart:2038:22)
E/flutter (30451): #5      Socket.connect (dart:io/socket.dart:743:21)
E/flutter (30451): #6      main
```

However, connecting to the server using `telnet localhost 8080` works fine.

**Comment by lukehutch** [comment]
OK, the problem was that on the Android emulator, `10.0.2.2` is the address of the host machine, not `localhost`.

https://developer.android.com/studio/run/emulator-networking

So I guess the only "solution" needed here is that in the docs for `ServerPod`, the example code that uses `localhost:8080` for setting up the client should have a note that says

> (use `10.0.2.2:8080` to connect to the server running on the host machine, if the client is running in the Android emulator)

**Comment by lukehutch** [comment]
Also, maybe the constructor for `Client` should determine what platform the Flutter code is running on, and auto-translate `localhost` into `10.0.2.2` if it's the Android emulator?

**Comment by lukehutch** [comment]
It looks like the iOS emulator uses the network of the host machine, so Android is the only platform that needs special case handling.

https://stackoverflow.com/questions/6077888/how-do-i-access-the-host-machine-itself-from-the-iphone-simulator

**Comment by lukehutch** [comment]
Actually this is not just a client documentation issue. The server generates profile image URLs using `localhost` too.

```
════════ Exception caught by image resource service ════════════════════════════
The following _ClientSocketException was thrown resolving an image codec:
Connection refused

When the exception was thrown, this was the stack
Image provider: CachedNetworkImageProvider("http://localhost:8080/serverpod_cloud_storage?method=file&path=serverpod%2Fuser_images%2F1-1.jpg", scale: 1.0) 
 Image key: CachedNetworkImageProvider("http://localhost:8080/serverpod_cloud_storage?method=file&path=serverpod%2Fuser_images%2F1-1.jpg", scale: 1.0): CachedNetworkImageProvider("http://localhost:8080/serverpod_cloud_storage?method=file&path=serverpod%2Fuser_images%2F1-1.jpg", scale: 1.0)
```

**Comment by deladourig** [comment]
Same issue for me, I was running my app on an IOS device from my Mac
`SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = localhost, port = 63136`

I followed [this steps](https://ymoondhra.medium.com/how-to-run-localhost-on-your-iphone-4110a54d1896), and could interact with the server on my device by using Internet Sharing. Also needed to update `publicHost` from _config/development.yaml_ in Serverpod project to my computer name so I can access images database. A bit restrictive but it does the job

If anyone has a better solution, please let me know

**Comment by Bierbuddy** [comment]
I still have the same issue. I don't know how to solve it

**Comment by lukehutch** [comment]
@Bierbuddy which part? I think I saw a change a few months ago where `10.0.2.2` is now the default host for Android apps -- if it's not, and you're using the Android emulator, you need to set that. Also you need to set up the files in `config/`, e.g. `config/development.yaml`.
