### ISSUE TITLE
Wrong imports when using sub folders in the protocol directory

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#545]
#449 Added support for sub folders in the protocol directory.

For me (Windows) the imports and exports in generated files are not correct.
I'll provide a PR.

**Comment by AndryHTC** [comment]
Is this fix included in the 1.0.0? I cannot track it because there aren't any releases in the Repository and the last tag was 0.9.19

**Comment by vlidholt** [comment]
This should be in 1.0.0. We should add a test for it to make sure that it works.

**Comment by AmoonPod** [comment]
> 

Yes, cause I don't think it's working even in 1.0.0. The generated files inside folders gives an import error on 'protocol.dart'.
This doesn't happens in every generated .dart file of the subfolder, but only in some of them. (I didn't find any relation between the files that gives the error.)

**Comment by fischerscode** [comment]
@AmoonPod I'd be great if you could provide an example, that doesn't work. Since for me everything seemed to work for now. Otherwise I'll experiment (probably) tomorrow.

**Comment by fischerscode** [comment]
@AmoonPod If you have a case similar to the example provided in #622, #624 should fix your problem. 

If you're not using generated types as generics in subdirectories, it would be great if you could provide me additional information about your use-case.

*(In case it's something you don't want to share with the public, you can also contact me using [e-mail](https://github.com/fischerscode))*
