### ISSUE TITLE
Waiting for Postgres

### ISSUE THREAD

**Issue by Saleque474** [serverpod/serverpod#551]
Starting docker
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
/usr/bin/netstat
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...
Waiting for Postgres...

![image](https://user-images.githubusercontent.com/56844858/211402565-4692df5e-a82d-4b5c-89f0-82d64bbc7218.png)

I have docker installed on my pc:
![image](https://user-images.githubusercontent.com/56844858/211402703-4fdf392d-1cca-444a-bfaa-c18c62f8dab9.png)

So how to fix the problem.

**Comment by Saleque474** [comment]
the problem was related to my docker. Docker needed superuser on linux. After fixing the issue of super user the problem gone.
I have uninstall docker and reinstall docker-desktop. after that the problem gone

**Comment by yahu1031** [comment]
@Saleque474 There was a similar ticket raised #420. This may also help you. And please close the ticket if it was solved.

**Comment by Saleque474** [comment]
Problem fix after reintalling docker. And give docker access  without superuser.

**Comment by yahu1031** [comment]
Please close the ticket @Saleque474
