### ISSUE TITLE
`serverpod generate` needs to merge in generated pgsql files from dependencies

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#553]
When I run `serverpod generate`, it produces the database table creation commands in `mypod_server/generated/tables.pgsql` and `generated/tables-serverpod.pgsql`.

However even if the project has a dependency, e.g. on `serverpod_auth_server-0.9.21`, then `serverpod generate` does not merge the contents of `serverpod_auth_server-0.9.21/generated/tables.pgsql` into `mypod_server/generated/tables.pgsql`.

This means that to properly set up the database to work with all the tables required by any dependency, I have to go hunt down every single `pgsql` file of any (transitive) dependency, and manually set up the required tables.

Shouldn't all the database setup SQL code for all transitive dependencies be automatically merged into one file?

**Comment by yahu1031** [comment]
@lukehutch Thanks for bringing up this, Even I thought of raising a similar issue but got diverted by some other things. But you see `serverpod_auth_server` tables need to be run once while you configuring the auth module, then later everything will be handled from the server level. I don't think it is a huge task but still a task every time. @vlidholt Needs to be considered may be.

**Comment by vlidholt** [comment]
This will be addressed in 1.1

**Comment by lukehutch** [comment]
I wonder if it would be possible to integrate some sort of schema diff functionality into Serverpod too, which would compare the new schema to the existing one in the database, and would generate only the commands needed to morph the current database into the new one:

https://www.pgadmin.org/docs/pgadmin4/6.18/schema_diff.html

**Comment by vlidholt** [comment]
@lukehutch, the diff is what we are building for 1.1. :)

**Comment by SandPod** [comment]
With the introduction of database migrations this workflow has now been replaced: https://github.com/orgs/serverpod/projects/4?pane=issue&itemId=26435351

**Comment by SandPod** [comment]
We now do merge them all schema changes into a single SQL that is applied to the database.

**Comment by lukehutch** [comment]
Which single file is it though? So you're saying after a `docker compose down - v`, when I run `docker compose up`, all sql files will now be installed automatically? 

Is the migration part fully documented yet (the mechanism of action as well as the command to use)?

**Comment by SandPod** [comment]
Yes, once you have done the docker restart as you described, all tables will be created as part of applying the migrations, including all of the dependencies that you might have.

You can find the documentation under the `next` version under concepts/database/migrations, but here is a direct link: https://docs.serverpod.dev/next/concepts/database/migrations#apply-migrations.

Check out this section to get a better understanding of what migration file is applied when: https://docs.serverpod.dev/next/concepts/database/migrations#migrations-directory-structure

**Comment by SandPod** [comment]
For completeness this guide that explains how to become compatible with the new migration system with an old system can also be linked: https://docs.serverpod.dev/next/upgrading/upgrade-to-one-point-two#initialize-migration-system

**Comment by SandPod** [comment]
I'll answer in the other thread! :)
