### ISSUE TITLE
 Internal server error. Failed to connect to database in future call manager. PostgreSQLSeverity.fatal 28P01: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Saleque474** [serverpod/serverpod#555]
I have composed server with 

     docker-compose up --build --detach

after that I have run 

     dart bin/main.dart

But the problem is 

![image](https://user-images.githubusercontent.com/56844858/211439332-ea0bbb5e-1f70-4c7f-8a3e-cd014895a214.png)
how to fix it?

**Comment by yahu1031** [comment]
@Saleque474 Try removing any previous volumes from docker that aren't being used.

**Comment by Saleque474** [comment]
> @Saleque474 Try removing any previous volumes from docker that aren't being used. Other ref #121

all volumes of docker are removed. Still causing same problem

**Comment by yahu1031** [comment]
In between these commands, you need to create tables. Was that done? @Saleque474

**Comment by Saleque474** [comment]
![image](https://user-images.githubusercontent.com/56844858/211549002-3533dd67-3985-4349-853c-b4e1fdf794ca.png)
problem is in authentication.
I have used password from 
   config/passwords.yaml
and database from
    config/development.yaml
![image](https://user-images.githubusercontent.com/56844858/211549450-8fe6cbb9-f568-4514-b0a6-e871fee168dc.png)

![image](https://user-images.githubusercontent.com/56844858/211549557-02ffa854-c6b0-454e-b651-f53dea49158c.png)

if authentication fails , then what is the password?

**Comment by Saleque474** [comment]
and tried also this
![image](https://user-images.githubusercontent.com/56844858/211550011-3501a672-b7e7-42a9-ad99-209da291df68.png)

**Comment by yahu1031** [comment]
@Saleque474 Cross-check the `docker-compose.yaml` and the `password.yaml` files have same password for the database

**Comment by Saleque474** [comment]
![image](https://user-images.githubusercontent.com/56844858/211720727-90ef275b-fe9e-4835-ad25-d84d6e355120.png)
After coping the whole script and paste it on database command and running the command to generate database table . It worked. But the question is why the tables are not automatic created?
![image](https://user-images.githubusercontent.com/56844858/211720937-5616c98e-f73d-404e-997c-9ae0c2cf9cb3.png)

**Comment by Saleque474** [comment]
![image](https://user-images.githubusercontent.com/56844858/211721228-129445d3-08bd-4c9d-be92-d03615833e21.png)
Serverpod runned after the creation of the table. But why it is not automatic creating?
any way . It is great news for me that finally the serverpod is running.

**Comment by yahu1031** [comment]
@Saleque474 Do you see `setup-tables` in the server folder?

**Comment by yahu1031** [comment]
Could you please log your system/os details here? I will be following up on this.

**Comment by Saleque474** [comment]
![image](https://user-images.githubusercontent.com/56844858/212469773-14678261-e8ff-4387-a259-7de23f8183e9.png)
my os.
![image](https://user-images.githubusercontent.com/56844858/212469839-fa41fa99-d88f-4811-a3a3-eeaab22f536c.png)

**Comment by Frank1016** [comment]
I also met this similar password authentication failed for postgres database error, after deleting a previous serverpod project.

**Comment by Frank1016** [comment]
> 
I deleted unused volumes in Docker before re-creating a new serverpod project, then the issue disappeared!

**Comment by yahu1031** [comment]
@Frank1016 Try host: `localhost` and check.

**Comment by Frank1016** [comment]
> @Frank1016 If this issue solved, please close the ticket as `solved`.

Sorry, it's not me who opened the issue, and I don't know how to close this ticket.

**Comment by Saleque474** [comment]
In this case , I am not using docker anymore. I have created a database in postgreSQL . and pass the credential under config/development.yaml and config/password.yaml . After that have generated my database tables using tables-serverpod.pgsql. 
That solve my problem .
I am using ubuntu 20.04 where docker host is not getting.

**Comment by Saleque474** [comment]
I have discuss the solution above .
The problem is related to docker only.

**Comment by naranbat7** [comment]
1. Clear all docker containers and volumes
2. Re create serverpod project
These steps helped me for this issue.

**Comment by ramyak-mehra** [comment]
> * Clear all docker containers and volumes
> * Re create serverpod project
>   These steps helped me for this issue.

what if I want to keep the other docker containers and volumes for other projects

**Comment by MarkOSullivan94** [comment]
@naranbat7 this isn't ideal when you're already making use of Docker for other projects

I'm having the same issue

```
SERVERPOD version: 1.1.0, dart: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_arm64", time: 2023-05-01 21:20:24.870997Z
mode: development, role: monolith, logging: normal, serverId: default
Failed to connect to the database. Retrying in 10 seconds. PostgreSQLSeverity.fatal 28P01: password authentication failed for user "postgres" 
Database configuration:
database host: localhost
database port: 8090
database name: testing
database user: postgres
database require SSL: false
database unix socket: false
database pass: ********
```

**Comment by raghav042** [comment]
You have to manually setup tables by running tables.cmd command: posted solution and video link on stackoverflow : https://stackoverflow.com/a/77252351/14360762

**Comment by yahu1031** [comment]
Can you share verbose logs? @namtrungle20

**Comment by rammesaran** [comment]
If anyone facing this issue. please check your Postgres password is same as password.yamal. 
![Screenshot2024_02_27_235536](https://github.com/serverpod/serverpod/assets/45402258/4e80f019-f4e2-4d08-9b2d-7d9837624d70)
![Screenshot2024_02_27_235552](https://github.com/serverpod/serverpod/assets/45402258/738b4200-d4e4-40fd-8572-fb6d4d391d07)
