### ISSUE TITLE
[Enhancement] - Reduce utilisation of child process spawns

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#557]
## Is your feature request related to a problem? Please describe. ##
It is ideally not a problem but this will be like reinventing the wheel.

## Describe the solution you'd like ##
Instead, to delete files/dir, try utilizing `Directory/File.delete()/deleteSync()`. So we can reduce a known child process spawn.

## Additional context ##
Can be found in deleting `setup-tables` deletion feature.

**Comment by SandPod** [comment]
No child processes are spawned when creating new project anymore so I think it is safe to close this issue.
