### ISSUE TITLE
docker-compose is now docker compose in linux

### ISSUE THREAD

**Issue by j-albr16** [serverpod/serverpod#560]
Most scripts use docker-compose instead of docker compose. For example "setup-tables" uses

`docker-compose up -d`

I am on linux and the docker-compose cli was included in the docker cli.

You can now call

`docker compose up -d`

[see in docker docs](https://docs.docker.com/compose/cli-command-compatibility/)

The result is that all the scripts like "setup-tables" are failing

**Comment by j-albr16** [comment]
as workaround i did the following:

```
echo "docker compose $@" > /usr/bin/docker-compose
chmod +x /usr/bin/docker-compose
```

**Comment by yahu1031** [comment]
@j-albr16 Could you please share us your sys info.

**Comment by j-albr16** [comment]
@yahu1031 

Pop!_OS 22.04 LTS
64-bit

CPU: AMD® Ryzen 5 3600 6-core processor × 12 
Graphics: NVIDIA Corporation TU116 [GeForce GTX 1650]

**Comment by yahu1031** [comment]
@vlidholt This is not a bug, But this is going to be a deprecation. The old systems/Old versions of docker can still use `docker-compose` and new versions will slowly remove this command. Right now the current docker version will support both commands. Please add an enhancement label to this.
