### ISSUE TITLE
I cant create serverpod project

### ISSUE THREAD

**Issue by nopxjs** [serverpod/serverpod#586]
**I cant create serverpod project its says:**
One or more network ports Serverpod want to use are not available. The most likely reason is that you have another
Serverpod project running, but it can also be another service.

**But im not running any other server**

**Comment by nopxjs** [comment]
and docker is running

**Comment by yahu1031** [comment]
Hey @nopxjs

> One or more network ports Serverpod want to use are not available. The most likely reason is that you have another
Serverpod project running, but it can also be another service.

Nothing to do with serverpod. Check if `8080`, `8081`, `8082`, `8090` are free

**Comment by nopxjs** [comment]
how to change port?

**Comment by yahu1031** [comment]
currently we don't have custom ports, so please stop the services and try again.

**Comment by nopxjs** [comment]
i have another question, how to do ForeignKey in models

**Comment by hortigado** [comment]
only stop the app that use el port 8090
