### ISSUE TITLE
i cant run the server

### ISSUE THREAD

**Issue by nopxjs** [serverpod/serverpod#590]
**i cant run the server, im getting this error (iam on windows):**
package:serverpod/src/server/future_call_manager.dart 100:18    FutureCallManager._checkQueue

Local stacktrace:
#0      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:136:36)
<asynchronous suspension>

**Comment by yahu1031** [comment]
Hey @nopxjs again, Please make sure you have generated tables in the database, such that the logs/calls will be logged in the dedicated serverpod tables. Also please make sure to check out the previously closed issues to get solutions.

**Comment by nopxjs** [comment]
i did serverpod generate --watch

**Comment by yahu1031** [comment]
Did you run the `*_server/generated/tables-serverpod.pgsql` in the database?

**Comment by nopxjs** [comment]
no how to run it there

**Comment by yahu1031** [comment]
Use any db connection app/postico(recommend) ans connect to the server and run the query. And now stop the server and run the server again. It will work. Ideally you don't need to do it. What os are you using? And what serverpod version are you using?

**Comment by nopxjs** [comment]
windows and last serverpod version,

**Comment by yahu1031** [comment]
okie then, follow the above steps.

**Comment by nopxjs** [comment]
hey @yahu1031 how to run the command, where in database, i installed DBeaver and i added my database

**Comment by yahu1031** [comment]
@nopxjs Not pretty good with it, check it out [here](https://dbeaver.com/docs/wiki/SQL-Execution/)
