### ISSUE TITLE
[feature_request] make serverpod podman friendly

### ISSUE THREAD

**Issue by iapicca** [serverpod/serverpod#592]
### Description

[podman](https://podman.io/) is an **open source** **_daemonless_** container engine alternative to `docker`
it would be nice if `serverpod` would be less opinionated on what container engine I'm running 
and allow me to try `serverpod` w/o getting married to docker

**Comment by yahu1031** [comment]
@iapicca Actually, You can give it a shot of creating that feature and raise a PR. 😄

**Comment by yahu1031** [comment]
@iapicca It does work with podman as you suggest but needs a few configs for it.

**Comment by yahu1031** [comment]
<img width="1440" alt="Screenshot 2023-01-31 at 1 28 11 AM" src="https://user-images.githubusercontent.com/35523357/215582294-9d3e1142-b984-4b63-8b71-1a70ec7e795d.png">

@iapicca Result with podman

**Comment by iapicca** [comment]
@yahu1031 
what's the configuration of your podman machine?

I get the following using the same machine I use for [minikube](minikube.sigs.k8s.io)
```
➜  serverpod serverpod create server_test
There are some issues with your setup that will prevent your Serverpod project from running out of the box and without further configuration. You can still create this project by passing -f to "serverpod create" and
manually configure your Serverpod.

You do not have Docker installed or it is not running. Serverpod uses Docker to run Postgres and Redis. It's recommended that you install Docker Desktop from https://www.docker.com/get-started but you can also install and
configure Postgres and Redis manually and run this command with the -f flag added.
➜  serverpod podman machine info
Host:
  Arch: arm64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: /var/folders/p9/m6wv1ql505109hc1gv2d1rx40000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/yakforward/.config/containers/podman/machine/qemu
  MachineImageDir: /Users/yakforward/.local/share/containers/podman/machine/qemu
  MachineState: Running
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.3.1
  Built: 1668026638
  BuiltTime: Wed Nov  9 22:43:58 2022
  GitCommit: ""
  GoVersion: go1.18.8
  Os: darwin
  OsArch: darwin/arm64
  Version: 4.3.1
```

**Comment by yahu1031** [comment]
@iapicca There is a small trick you can do. Write an alias in the `.zshrc` or `.bashrc` (which ever you work on) and try again. Check it out here https://podman.io/whatis.html

**Comment by yahu1031** [comment]
<img width="949" alt="Screenshot 2023-01-31 at 1 48 35 AM" src="https://user-images.githubusercontent.com/35523357/215586025-6adbc4ec-e578-4167-b756-a51a3474b69d.png">
Also supports health. 😄

**Comment by SandPod** [comment]
The `serverpod create` command no longer requires Docker to run.

Was that the only issue encountered when running podman? If so we could probably close this issue now.

**Comment by SandPod** [comment]
I'll close this request as Serverpod no longer has a hard requirement on Docker.
