### ISSUE TITLE
Getting "union_set not found" error when i run server

### ISSUE THREAD

**Issue by nopxjs** [serverpod/serverpod#599]
**im getting this error when i run main.dart:**

../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/collection.dart:22:1: Error: Error when reading '../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/union_set.dart': The system cannot find the file specified.

export 'src/union_set.dart';
^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/union_set_controller.dart:5:8: Error: Error when reading '../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/union_set.dart': The system cannot find the file specified.

import 'union_set.dart';
       ^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/unmodifiable_wrappers.dart:5:8: Error: Error when reading '../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/empty_unmodifiable_set.dart': The file or directory is corrupted and unreadable.

import 'empty_unmodifiable_set.dart';
       ^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/union_set_controller.dart:26:9: Error: Type 'UnionSet' not found.
  final UnionSet<E> set;
        ^^^^^^^^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/unmodifiable_wrappers.dart:114:47: Error: Couldn't find constructor 'EmptyUnmodifiableSet'.
  const factory UnmodifiableSetView.empty() = EmptyUnmodifiableSet<E>;
                                              ^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/unmodifiable_wrappers.dart:114:47: Error: Redirection constructor target not found: 'EmptyUnmodifiableSet'
  const factory UnmodifiableSetView.empty() = EmptyUnmodifiableSet<E>;
                                              ^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/union_set_controller.dart:26:9: Error: 'UnionSet' isn't a type.
  final UnionSet<E> set;
        ^^^^^^^^
../../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/collection-1.17.1/lib/src/union_set_controller.dart:40:15: Error: Method not found: 'UnionSet'.
      : set = UnionSet<E>(_sets, disjoint: disjoint);

**Comment by vlidholt** [comment]
Can you provide mer information about which version of Flutter and Dart you are using and on which platform?

**Comment by nopxjs** [comment]
Dart SDK version: 2.19.0, 
Flutter 3.7.0
i'm using visual studio on windows
