### ISSUE TITLE
[Enhancement] Make listening on port as hyperlink 

### ISSUE THREAD

**Issue by shan-shaji** [serverpod/serverpod#607]
**Is your feature request related to a problem? Please describe.**
After starting the serverpod project we will get certain console outputs.

**Describe the solution you'd like**
 It would be nice if the console outputs like for the server we could change the output 
from "listening to port 8080" -> server running on localhost:8080"

**Describe alternatives you've considered**
We can use this [approach](https://github.com/felangel/mason/blob/master/packages/mason_logger/lib/src/link.dart) to build hyperlinks.

**Additional context**

<img width="469" alt="Screenshot 2023-02-03 at 1 11 28 AM" src="https://user-images.githubusercontent.com/42430941/216434274-81c82a23-124a-4218-a315-7f9a9f03d2f8.png">

**Comment by shan-shaji** [comment]
@vlidholt i can add this change if no one is working on this.

**Comment by vlidholt** [comment]
Hm, I'm not sure this is a good idea. What would you use in production? The server itself is listening on a specific port, but another port may be used by a load balancer, making the link incorrect. I think I would prefer to leave this as is to avoid any confusion.
