### ISSUE TITLE
Use pub_updator for serverpod_cli

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#611]
### Discussed in https://github.com/serverpod/serverpod/discussions/606

<div type='discussions-op-text'>

<sup>Originally posted by **shan-shaji** February  2, 2023</sup>
https://pub.dev/packages/pub_updater

I believe it would be nice to give the developers a prompt to update the package if a new version of the package is updated in pub.dev. </div>

**Comment by damienissa** [comment]
@vlidholt  Hi. I made a possible solution for it. Without adding additional lib [pub_updater](https://pub.dev/packages/pub_updater)
I have added only one pub [Logger](https://pub.dev/packages/logger). But it can be easily replaced by making an in-house print.
The current output result is:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/17296142/216725455-7f11de30-62d2-4988-b7e8-7082dcdb0af8.png">

Please feel free to propose any changes!

**Comment by vlidholt** [comment]
Perhaps copy the style of Flutter to make it feel more familiar.

```
┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
```

The update instructions are a bit more involved with Serverpod as you will need to add the new version to:
1. The tooling, update by running `dart pub global activate serverpod_cli`
2. Add the new version to your server, client, and flutter packages.

**Comment by damienissa** [comment]
@vlidholt Hello. Thanks for the update. this message style can be printed without an additional lib. I can create a PR with these changes if you approve the text.

```
┌───────────────────────────────────────────────────────────────────────────────────────┐
│ A new version of Serverpod is available!                                              │
│                                                                                       │
│ To update to the latest version, run "dart pub global activate serverpod_cli".        │
│ Also, do not forget to update packages in your server, client, and flutter projects.  │
└───────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by vlidholt** [comment]
Looking good.

**Comment by SandPod** [comment]
Hey @damienissa!
Starting from your commits I'll push this over the finish line.

Might postpone some of the nice error messaging and do that as part issue #1042. Then we can do an overhaul on all messaging and logging for the Cli.
