### ISSUE TITLE
Failed to connect to database ( in windows) while starting the server

### ISSUE THREAD

**Issue by Apoorva554** [serverpod/serverpod#613]
**Describe the bug**
Receiving failed to connect to database when ran dart bin/main.dart.

**To Reproduce**
1. ran 'docker-compose up --build --detach'
2. when  'dart bin/main.dart'
3. See error

**Expected behavior**
The server needs to run

**Screenshots**
![ss1](https://user-images.githubusercontent.com/119829200/216745563-4d33bf5b-7e6b-47de-b393-19c95c6fa05b.png)

**Serverpod versions**
 -  _CLI Version:_ 1.0.0
 - _Library version:_ 1.0.0

**Platform information**
On which platforms do you experience the issue - Windows

**Comment by shan-shaji** [comment]
@Apoorva554 Please make sure docker is running

**Comment by yahu1031** [comment]
@Apoorva554  When you run the docker, connect to the database and create the required tables and then run the server.

**Comment by easy-Coder** [comment]
I also face this same problem, using 'setup_tables.cmd' won't connect to the database

**Comment by Apoorva554** [comment]
> @Apoorva554 When you run the docker, connect to the database and create the required tables and then run the server.

cool thanks a lot .Worked fine. Is it the same method when we deployed to aws ?

**Comment by yahu1031** [comment]
> > @Apoorva554 When you run the docker, connect to the database and create the required tables and then run the server.
> 
> cool thanks a lot .Worked fine. Is it the same method when we deployed to aws ?
> 
> Boz when deploying to aws i get api url as 502 bad request 

 Yes this is one of the reasons
