### ISSUE TITLE
Exclude a "folder" or some files from being generated to the "_client" side

### ISSUE THREAD

**Issue by klkucaj** [serverpod/serverpod#621]
Hi, first of all congratulations for this amazing server you guys built.

My question is: can I exclude some files or a folder not to be generated on the "_client" module ?

What I want is to exclude all the models that are database entities/tables from being generated to "_client" module and maybe use DTOs.

Basically all database models I want them to be generated only on "_server" part and not in "_client" part, and then DTOs to be generated in both parts.

**Comment by vlidholt** [comment]
I'm adding this to the roadmap!

**Comment by fischerscode** [comment]
@klkucaj Would #625 (see the example) satisfy your requirements?

**Comment by klkucaj** [comment]
> @klkucaj Would #625 (see the example) satisfy your requirements?

@fischerscode that is perfect, thank you!
