### ISSUE TITLE
PostgreSQLSeverity.error 42601: syntax error at or near `*`

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#627]
## Describe the bug ##
UserData model

```yaml
class: UserData

table: user
fields:
  user: module:auth:UserInfo
  email: String
  uid: String
  points: int
  communities: List<Community>
```

> Inserting the data from code

```dart
// Tried this
await session.db.insert<UserData>(userData)

// Tried this
await UserData.insert(session, userData);
```

But not sure why my code throws error - `PostgreSQLSeverity.error 42601: syntax error at or near "user"`

Traces
```console
package:postgres/src/connection.dart 513:18                     _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 474:7                      _PostgreSQLExecutionContextMixin.query
package:postgres_pool/postgres_pool.dart 750:23                 _PgExecutionContextWrapper.query.<fn>
package:postgres_pool/postgres_pool.dart 695:27                 _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 749:12                 _PgExecutionContextWrapper.query
package:postgres_pool/postgres_pool.dart 585:16                 PgPool.query.<fn>
package:postgres_pool/postgres_pool.dart 332:22                 PgPool.run.<fn>.<fn>
package:postgres_pool/postgres_pool.dart 431:27                 PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 403:14                 PgPool._withConnection.<fn>
package:executor/src/executor_impl.dart 61:19                   _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 331:18                 PgPool.run.<fn>
package:retry/retry.dart 131:16                                 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14                 PgPool.run
package:serverpod/src/database/database_connection.dart 363:11  DatabaseConnection.insert
package:serverpod/src/database/database.dart 137:5              Database.insert
package:fluttermeetups_server/src/endpoints/auth.dart 47:7      AuthEndPoint.createUser
package:serverpod/src/server/endpoint_dispatch.dart 111:20      EndpointDispatch.handleUriCall
package:serverpod/src/server/server.dart 224:18                 Server._handleRequest
===== asynchronous gap ===========================
package:postgres_pool/postgres_pool.dart 331:18                 PgPool.run.<fn>
package:retry/retry.dart 131:16                                 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 329:14                 PgPool.run
package:serverpod/src/database/database_connection.dart 363:11  DatabaseConnection.insert
package:serverpod/src/database/database.dart 137:5              Database.insert
package:fluttermeetups_server/src/endpoints/auth.dart 47:7      AuthEndPoint.createUser
package:serverpod/src/server/endpoint_dispatch.dart 111:20      EndpointDispatch.handleUriCall
package:serverpod/src/server/server.dart 224:18                 Server._handleRequest
```

---

This is my case, When I debug and I stopped at `$HOME/.pub-cache/hosted/pub.dev/serverpod-1.0.0/lib/src/database/database_connection.dart 377`

This is my Query`(formatted for git preview)`
```pgsql
INSERT INTO user ("user", "email", "uid", "points", "communities") VALUES 
('{"id":1,"userIdentifier":"hi2minnu@gmail.com","userName":"Minnu","fullName":"Minnu","email":"hi2minnu@gmail.com",
"created":"2023-02-06T19:43:41.082894Z",
"imageUrl":"https://storage.flutterfinder.in/serverpod/user_images/1-1.jpg","scopeNames":[],"blocked":false}', 
'hi2minnu@gmail.com', '3f5731b8-99d5-4cca-a337-6df3a9c8e90e', 0, '[]') RETURNING id
```

This runs in postico SQL query(With small changes)
```pgsql
INSERT INTO "public"."user" ("user", "email", "uid", "points", "communities") VALUES 
('{"id":1,"userIdentifier":"hi2minnu@gmail.com","userName":"Minnu","fullName":"Minnu","email":"hi2minnu@gmail.com",
"created":"2023-02-06T19:43:41.082894Z",
"imageUrl":"https://storage.flutterfinder.in/serverpod/user_images/1-1.jpg","scopeNames":[],"blocked":false}', 
'hi2minnu@gmail.com', '3f5731b8-99d5-4cca-a337-6df3a9c8e90e', 0, '[]') RETURNING id
```

- Returns Id 1

---

## Serverpod versions ##
 -  _CLI Version:_ v1.0.0
 - _Library version:_ v1.0.0

## Platform information ##
Mac OS M1 - 2020 (13.1 (22C65))

## Additional Context ##
Expecting that was because my table name and the column name were same. But ideally that must not give error.

**Comment by Apoorva554** [comment]
I’m dealing with the same issue.

**User model**

`class: User
table: user
fields: 
  uid: String
  name: String
  mobile: int
  email: String
  dateofbirth: String
  weight: String
  height: String
  gender: String
  subcription: bool
  updateon: DateTime`

Error in db - `PostgreSQLSeverity.error 42601: syntax error at or near "user" `

**Stack Traces**
`package:postgres/src/connection.dart 513:18                     _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart 474:7                      _PostgreSQLExecutionContextMixin.query
package:postgres_pool/postgres_pool.dart 801:23                 _PgExecutionContextWrapper.query.<fn>
package:postgres_pool/postgres_pool.dart 746:27                 _PgExecutionContextWrapper._run
package:postgres_pool/postgres_pool.dart 800:12                 _PgExecutionContextWrapper.query
package:postgres_pool/postgres_pool.dart 615:16                 PgPool.query.<fn>
package:postgres_pool/postgres_pool.dart 352:22                 PgPool.run.<fn>.<fn>
package:postgres_pool/postgres_pool.dart 451:27                 PgPool._useOrCreate
package:postgres_pool/postgres_pool.dart 423:14                 PgPool._withConnection.<fn>
package:executor/src/executor_impl.dart 61:19                   _Executor.scheduleTask
package:postgres_pool/postgres_pool.dart 351:18                 PgPool.run.<fn>
package:retry/retry.dart 131:16                                 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 349:14                 PgPool.run
package:serverpod/src/database/database_connection.dart 363:11  DatabaseConnection.insert
package:serverpod/src/database/database.dart 137:5              Database.insert
package:backend_server/src/endpoints/user_endpoint.dart 13:5    UserEndpoint.addUser
package:serverpod/src/server/endpoint_dispatch.dart 111:20      EndpointDispatch.handleUriCall
package:serverpod/src/server/server.dart 224:18                 Server._handleRequest
===== asynchronous gap ===========================
package:postgres_pool/postgres_pool.dart 351:18                 PgPool.run.<fn>
package:retry/retry.dart 131:16                                 RetryOptions.retry
package:postgres_pool/postgres_pool.dart 349:14                 PgPool.run
package:serverpod/src/database/database_connection.dart 363:11  DatabaseConnection.insert
package:serverpod/src/database/database.dart 137:5              Database.insert
package:backend_server/src/endpoints/user_endpoint.dart 13:5    UserEndpoint.addUser
package:serverpod/src/server/endpoint_dispatch.dart 111:20      EndpointDispatch.handleUriCall
package:serverpod/src/server/server.dart 224:18                 Server._handleRequest`

**Comment by fleeser** [comment]
Here to confirm that this error is thrown when the table and column names do match like @yahu1031 expected.

**Comment by Apoorva554** [comment]
Yep

**Comment by Apoorva554** [comment]
Any update !

**Comment by SandPod** [comment]
I think this was an issue because we did not escape the table name when querying from Serverpod. And since `user` has a specific meaning in Postgres it couldn't resolve the query.

This should be fixed now as we have added escapes around all tables used in queries.

We ran into a similar issue with using `order` as an entity name in our integration tests, but that works as expected now.

Will close this issue assuming it works as expected in with latest main.
Feel free to reopen if the issue still remians.
