### ISSUE TITLE
Add support for UUID

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#635]
It would be nice to be able to use UUID types with the database.

**Comment by fischerscode** [comment]
Would the UUID be a `String` at the dart side?

**Comment by fischerscode** [comment]
Related to #351

**Comment by fischerscode** [comment]
Just thought about this, and it is not trivial, since we don't have a dedicated dart type representing an uuid. I think wit would be best, if the developer would specify `_uuid` as the type in the yaml file. With a bit of reworking, we could then support uuids.
