### ISSUE TITLE
Tag `release-1.0.0` is missing

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#648]
**Describe the bug**
There is no tag `release-1.0.0`. Is this intended?

**To Reproduce**
1. Go to https://github.com/serverpod/serverpod/tree/release-1.0.0
2. See 404

**Expected behavior**
I think the release 1.0.0 should have a tag.

**Screenshots**
N/A

**Serverpod versions**
N/A

**Platform information**
N/A

**Additional context**
*none*

**Comment by vlidholt** [comment]
Will fix this!

**Comment by vlidholt** [comment]
Fixed
