### ISSUE TITLE
There should be more detailed documents

### ISSUE THREAD

**Issue by jijkbird** [serverpod/serverpod#659]
1. The document points out that there is a built-in user management module, but I don't know how to implement the custom login method, including the additional fields of the user module.

2. Is it possible to realize the data cache function of the client in the future, preferentially read local data and update it remotely and asynchronously.

3. How to use uuid as the default id field

4. I like this project very much, but I look forward to more functions.

**Comment by vlidholt** [comment]
This has been quite thoroughly fleshed out in our documentation now, so I'm closing this.
