### ISSUE TITLE
Move key-token to header instead of body

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#663]
**Is your feature request related to a problem? Please describe.**
As discussed here #657 it may be better to pass the key token for signed in users in the header instead of a URL query parameter.

**Additional context**
This is not a large security risk as the URL isn't typically visible or stored in history or cache. It's possible both a query parameter and header can be used simultaneously, making this change backwards compatible.

**Comment by damienissa** [comment]
@vlidholt Hi. Can I commit to it?

**Comment by vlidholt** [comment]
@damienissa Yes, as long as it is backwards compatible, this would be a great addition! :)

**Comment by wstrange** [comment]
Proxies and/or load balancers might log the URL. This isn't hair on fire, but it probably should be addressed in the next release.

**Comment by vlidholt** [comment]
Good point @wstrange

**Comment by yahu1031** [comment]
@davideroffo Currently, I'm able to pass the token in headers. When you consume in the server part, we need to use the session.

sample code
```dart
Future<CustomUserObject> getUserInfo(Session session, String id) async {
  if (session is MethodCallSession) {
    if(session.httpRequest.headers.value('Authorization') == null) {
      throw UserException(
        message: UserExceptionCode.unauthorized.message,
        code: UserExceptionCode.unauthorized.code,
      );
    }
  }
  // ... YOUR CODE ... //
}
```

> Correct me if I'm doing something wrong/ not exactly correct.

CC: @vlidholt

**Comment by perumalrollfi** [comment]
How do we add the header parameter in serverpod flutter app while calling the endpoint? We would like to add JWT token received while login for signed in users in header to authenticate on server side similar what is mentioned above.

**Comment by fstof** [comment]
> 

I would also like to know what the client (flutter) side code looks like to send the header. I'm not finding anything related in the docs

**Comment by vlidholt** [comment]
@fstof, adding custom headers would be a nice feature.

**Comment by fstof** [comment]
> @fstof, adding custom headers would be a nice feature.

@vlidholt I have a PR I'm just cleaning up if you don't mind...

I'm thinking similar to `AuthenticationKeyManager` we can add a "headerManager" that can be passed in on client creation

```dart
Client(
  'http://localhost:8080/',
  headerManager: CustomHeaderManager(),
)
```
... and the abstract class...
```dart
abstract class HeaderManager {
  Future<Map<String, String>?> get();
}
```

**Comment by fstof** [comment]
So any takers on #1298 @vlidholt , @Isakdl ? 

Not exactly sure what the issue is on the web implementation of my PR
Would really appreciate some input here

**Comment by vlidholt** [comment]
Sorry for the delay here. Will take a look shortly!

**Comment by lukehutch** [comment]
Related to JWT support requests: #1698, #1720.

**Comment by fstof** [comment]
> Related to JWT support requests: #1698, #1720.

Not exactly... those refer to the format of the auth key. Here the issue is the location of the token. IE Header vs Body
using "Authorization" header is standard practice and would be ideal

**Comment by lukehutch** [comment]
@fstof Right, but what I'm saying is that the token itself should be a JWT. Yes, it should be stored in a header.
