### ISSUE TITLE
How to customize login

### ISSUE THREAD

**Issue by jijkbird** [serverpod/serverpod#672]
I get the key from the server through the following code

`Future<String?> login(Session session) async {
    AuthKey authKey = await session.auth.signInUser(156156, "auto");
    print(authKey);
    return authKey.key;
  }`

How to use the returned data to log in on the client

**Comment by jijkbird** [comment]
I tried this, but the server did not show me to log in.

` await client.authenticationKeyManager!.put(token);`

**Comment by yahu1031** [comment]
What is `key` in `authKey` and what does `put()` do? (If it is custom function).

**Comment by jijkbird** [comment]
I want to log in to the account on the client, and the server can obtain the authentication information
@yahu1031

**Comment by jijkbird** [comment]
我想自己实现自定义登录方式，服务器派发了key给客户端，我在客户端该以什么样的形式去保存这个key，并且是客户端的状态变更为已登录？
@yahu1031

**Comment by yahu1031** [comment]
理想情况下，您不需要这样做。 因为会话管理器会注意用户是否登录，即使您关闭应用程序并重新打开也是如此。@jijkbird

**Comment by jijkbird** [comment]
我在服务端使用以下语句进行登录
await session.auth.signInUser(156156, "auto");
但是我在客户端该怎么做才能实现登录状态，如果我在客户端不做任何操作的话，获取到的
print(await session.auth.authenticatedUserId);
这个将等于null.
包括以下代码也等于false
sessionManager.addListener(() {
      print(sessionManager.isSignedIn);
    });

似乎会话管理器并没有注意到用户已经登录了
@yahu1031

**Comment by jijkbird** [comment]
帮帮我，因为我这里没有办法使用邮件、苹果、谷歌或者其他登录方式

**Comment by yahu1031** [comment]
Any error or something? And what are you expecting to happen?

**Comment by jijkbird** [comment]
https://lure-plus.oss-cn-chengdu.aliyuncs.com/lureplus.zip

这个是我的代码

我希望能获取到登录状态

**Comment by jijkbird** [comment]
![2023-02-18_07-13](https://user-images.githubusercontent.com/20245625/219814742-7db62c76-3bad-41eb-9d04-a6204780e48e.png)

@yahu1031

**Comment by jijkbird** [comment]
我先暂时用邮箱登录好了
