### ISSUE TITLE
Generator creates wrong path for endpoint 

### ISSUE THREAD

**Issue by ivanesi** [serverpod/serverpod#675]
**Describe the bug**
If endpoint is in subfolder, generator creates wrong path for it.

**To Reproduce**
1. Create enpoint in `lib/src/endpoints/sub_folder/my_endpoint.dart`
2. Run `serverpod generate`
3. See imports in `lib/src/generated/endpoints.dart`.
4. See error: `Target of URI doesn't exist: '../endpoints/my_endpoint.dart'.`

**Expected behavior**
Correct import path: `../endpoints/sub_folder/my_endpoint.dart`

**Serverpod versions**
 -  _CLI Version:_ Serverpod version: 1.0.1
 - _Library version:_ serverpod: ^1.0.1

**Comment by yahu1031** [comment]
CC: @fischerscode I think you know where is the issue.

**Comment by fischerscode** [comment]
Sub folders are currently not supported for endpoints.

Maybe I find some time to add this tomorrow.

**Comment by fischerscode** [comment]
@vlidholt I'm currently having a look at this. Should it be possible to have two endpoints with the same name in different directories? (Then the sub folder would have to be a part of the generated name.) I think it'd be better if endpoint names have to be unique.

**Comment by vlidholt** [comment]
Good question. At least for now endpoint names need to be unique. Changing this would require some pretty big changes in how you reference the endpoints from the client.

**Comment by fischerscode** [comment]
It would be possible to name it "$subDirectory$endpointName" or similar. But we'd have to decide it now, since changing it later would be a breaking change. (The name is used in the server - client communication)

**Comment by vlidholt** [comment]
For version 1.x let's stick with unique endpoint names.
