### ISSUE TITLE
Dead Code: `ResultStatusCode` is never used

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#687]
**Describe the bug**
I've just browsed through the code due to #680 and it seems like I've found some dead code.

Since `ResultStatusCode` is never extended and never created in [here](https://github.com/serverpod/serverpod/blob/07d99a5341ad32897f2371cf6fb220fc425bdfd4/packages/serverpod/lib/src/server/endpoint_dispatch.dart#L52-L134) and therefore never there content of [`result`](https://github.com/serverpod/serverpod/blob/07d99a5341ad32897f2371cf6fb220fc425bdfd4/packages/serverpod/lib/src/server/server.dart#L224). So the the class definition and the related if statement is dead code.

https://github.com/serverpod/serverpod/blob/07d99a5341ad32897f2371cf6fb220fc425bdfd4/packages/serverpod/lib/src/server/endpoint_dispatch.dart#L295-L307

https://github.com/serverpod/serverpod/blob/07d99a5341ad32897f2371cf6fb220fc425bdfd4/packages/serverpod/lib/src/server/server.dart#L248-L251

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Serverpod versions**
 -  _CLI Version:_ 1.0.1
 - _Library version:_ 1.0.1

**Platform information**
N/A

**Additional context**
Test coverage might be useful to detect something like this.

**Comment by vlidholt** [comment]
This should probably be removed.

**Comment by SandPod** [comment]
This class is used now so I will close this issue: https://github.com/serverpod/serverpod/blob/ba8d1f6b9b7a2c584a02d19ad49aeefdb06282f6/packages/serverpod/lib/src/server/server.dart#L472
