### ISSUE TITLE
Support non-future functions in server calls.

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#696]
## Is your feature request related to a problem? Please describe.
I have a function that returns a list of strings (manipulation happening in the function) which is not a future block.

## Describe the solution you'd like
The server must also support non-future functions to be supported for client code generation.

**Comment by vlidholt** [comment]
But the call to the server takes time, therefore it needs to return a Future. On the server side, even if the server is returning a Future, the call will return immediately if you return a value (you still need to declare the method async).
