### ISSUE TITLE
Return Modified Data

### ISSUE THREAD

**Issue by Aboidrees** [serverpod/serverpod#699]
**Is your feature request related to a problem? Please describe.**
I have an Endpoint that should return the object after update or insert, for example if the user created a new product I should return the row he entered to the frontend, and I don't want to do that in two cycle.

**Describe the solution you'd like**
make an alternate functions with insert and update that return what is inserted.
Instead of:
```
Future<void> insert(...)
Future<bool> update(...)
```

let's make new ones:
```
Future<Model?> insertAndReturn(...)
Future<Model?> updateAndReturn(...)
```

If we can return the modified data with good performance, it would be nice. For example, we can do that from the database itself by using [`RETURNING`](https://www.postgresql.org/docs/current/dml-returning.html) if it's not bad for performance.

**Describe alternatives you've considered**
I am currently using the modified inserted by the user for the update function, and two cycles for the Insert function, which is very tedious to handle for each case :rofl: .

**Comment by vlidholt** [comment]
If the insert or update method returns without an exception, you have the latest version of the row and can safely return it to the client. No need to fetch it again.

```dart
// Create and insert object
MyObject object = MyObject(...);
await MyObject.insert(object);

// We will only reach here if the object was successfully inserted
return object;
```
