### ISSUE TITLE
Error on deployment to aws 

### ISSUE THREAD

**Issue by sandeepdevacc** [serverpod/serverpod#700]
@![image](https://user-images.githubusercontent.com/118791435/222050344-ec552b67-e72b-49e4-b675-b34af5dc3a31.png)
Hi,
 I'm trying to deploy my infra to AWS I have done all the necessary prerequisites in config.auto.fvars file and had run 
 terraform init 
 terraform apply 

 after some time I got the above error please help me with the same.
@vlidholt @II11II @yahu1031 @fischerscode

**Comment by yahu1031** [comment]
Check if you are using root user or Im user in aws account.

**Comment by yahu1031** [comment]
No you need to use root user

**Comment by sandeepdevacc** [comment]
> No you need to use root user. Is it your first time running terraform?

Yes.
Are there any changes other than config.auto.fvars ??
@yahu1031

**Comment by yahu1031** [comment]
@sandeepdevacc From the error it looks like, you are not the root user...

**Comment by yahu1031** [comment]
@sandeepdevacc Check if anything happened in the aws console. And can you please make sure that you have logged into the AWS console as `ROOT USER` and not `IAM USER`.

**Comment by sandeepdevacc** [comment]
@yahu1031  
I have created one IAM User and try to deploy the same hope all things go well.

**Comment by yahu1031** [comment]
No, It should be `ROOT USER` only. `IAM USER` doesn't have access to do it.

**Comment by yahu1031** [comment]
![Screenshot 2023-03-01 at 6 06 53 PM](https://user-images.githubusercontent.com/35523357/222141295-d4eb767c-58f2-457d-9f35-8d655ffd41d0.png)
I tried to ask Chat GPT about the issue. I got this answer(May not be super accurate, but the info is almost near to the issue).

**Comment by sandeepdevacc** [comment]
@yahu1031  
Good news got success to terraform apply command 
Now, I'm trying to Deploy through Github but In Action >Deploy to aws is not visible 
![image](https://user-images.githubusercontent.com/118791435/222144795-c23031d4-9e25-4824-8ca8-3af2850215b1.png)

**Comment by yahu1031** [comment]
reload it and check if the yml file exists.

**Comment by sandeepdevacc** [comment]
@yahu1031  
No there is no yml file

**Comment by yahu1031** [comment]
Then push it.

**Comment by sandeepdevacc** [comment]
@yahu1031  
I have pushed the code on the main branch still the .github folder is not generated.
Please help me with the same.

**Comment by sandeepdevacc** [comment]
@yahu1031 fyr
![Screenshot 2023-03-01 at 10 32 07 PM](https://user-images.githubusercontent.com/118791435/222210170-4d5f4474-21a9-4f56-9140-6372f622676a.png)

**Comment by yahu1031** [comment]
Ha, you are missing that file

**Comment by sandeepdevacc** [comment]
yes, how can I generate it?

**Comment by yahu1031** [comment]
Try `serverpod create .` in the same folder.

**Comment by sandeepdevacc** [comment]
> Try `serverpod create .` in the same folder. If it doesn't work, write things manually. But there must be a way.

Yes, it's not working.
If you have any reference code??

**Comment by sandeepdevacc** [comment]
@yahu1031  
Hi,
I was trying to run the working and the below error occurred please help me with the same.
![image](https://user-images.githubusercontent.com/118791435/222336670-6f846669-c699-43a3-953c-027b6e83815a.png)

**Comment by yahu1031** [comment]
check the action logs.

**Comment by sandeepdevacc** [comment]
![image](https://user-images.githubusercontent.com/118791435/222344369-552d1ee8-7791-4ab2-a71c-24f9470e5a72.png)

@yahu1031  
but I have main.dart file.

**Comment by yahu1031** [comment]
can you share github repo?

**Comment by sandeepdevacc** [comment]
Its private repo

**Comment by yahu1031** [comment]
screenshot the repo please

**Comment by sandeepdevacc** [comment]
![image](https://user-images.githubusercontent.com/118791435/222352412-3e25b678-ef39-45e7-b652-4c36d4bc6682.png)

**Comment by yahu1031** [comment]
Can you share the work flow please.

**Comment by sandeepdevacc** [comment]
Update 
Got the success on deployment
![image](https://user-images.githubusercontent.com/118791435/222359637-d1d8554a-2c95-4fd4-a381-f7d914162f59.png)

![image](https://user-images.githubusercontent.com/118791435/222359558-c3a52bc4-3d99-443c-b339-6188f9c1aec6.png)

But when I run the app then the below error occurred 
![image](https://user-images.githubusercontent.com/118791435/222359924-787f432f-c7b1-41e3-9e94-74686b574d31.png)

**Comment by yahu1031** [comment]
`https`

**Comment by sandeepdevacc** [comment]
> And why did you deploy it to examplepod.com?

No, I did it on my domain only
![image](https://user-images.githubusercontent.com/118791435/222377412-243fdb15-69d0-4f13-986f-0178f2f471ab.png)

**Comment by yahu1031** [comment]
Check the domains correctly, Cause it redirects me here `
http://app.examplepod.com/`

**Comment by sandeepdevacc** [comment]
@yahu1031  
![image](https://user-images.githubusercontent.com/118791435/222416998-a2751801-9a68-4fe5-8887-5a0fd33347ec.png)

**Comment by yahu1031** [comment]
Generate tables in production db.
