### ISSUE TITLE
Protection against snooping with mitmproxy/wireshark

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#702]
Most client/server architectures are vulnerable to man-in-the-middle attacks, which allow snooping, cookie stealing, replay attacks, etc., even if the client and server communicate using TLS.

This is very easy to set up using mitmproxy and wireshark. This was famously used by a number of people to figure out the Tinder API, automate large-scale exfiltration of data, automate large numbers of profile swipes, etc. (in fact I did this myself at one point, for a couple of different dating apps...).

One way around this is via certificate pinning, but more elaborate client/server protocols can be used to cryptographically prove whether there is a "man in the middle" changing the SSL certificate.

What sort of measures can Serverpod put in place to protect against MITM attacks?

**Comment by lukehutch** [comment]
The way it works is MITMProxy intercepts all traffic as a proxy (you have to modify OS proxy settings to pull this off, so it's not a 3rd party attack vector, it just allows you to reverse engineer the server protocol, then mess with the server programmatically).

MITMProxy used to use a self-signed certificate, but I assume now it uses a Letsencerypt certificate. It then initiates a regular TLS connection to the server.

Checking whether the signing authority is trusted isn't enough, since a valid certificate can be obtained for free from Letsencerypt.

What you really need is to be able to verify is that the certificate received by the client is the same as the certificate sent by the server. And the server needs to be the party that verifies this.

Basically what I'm requesting is something like Firebase App Check, but for Serverpod:

https://firebase.google.com/docs/app-check

**Comment by lukehutch** [comment]
(To answer your question: yes, I stole my own cookie using MITMProxy's built-in certificate, then I watched several requests using Wireshark to understand the JSON-RPC schemata, then I used the cookie to pull all the data from the server by simply using curl/wget and a bash script, which was made a lot easier because the engineers had used consecutive integers for user ids.)

**Comment by fischerscode** [comment]
I see, so you need too access to the attacked device.

To be honest, I think once an attacker has root access to the client, there will always be a way to spoof the communication.

Do you know how such a validation would work? If the client has to send something to the server, the attacker could just modify the message, right? And it's not obvious to me how there could be any secure key exchange.

**Comment by lukehutch** [comment]
Correct, for a sufficiently determined attacker, all prevention measures could be circumvented... Heck, they could just decompile your app, look at and modify your code, and/or steal your app secret keys.

The trick is making it exponentially harder to do anything like that. MITMProxy is so easy it requires little investment. Anything more complicated requires a huge investment of time, and a lot of specialized knowledge.

App Check agrees: "App Check relies on the strength of its attestation providers to determine app or device authenticity. It prevents some, but not all, abuse vectors directed towards your backends. Using App Check does not guarantee the elimination of all abuse, but by integrating with App Check, you are taking an important step towards abuse protection for your backend resources."

**Comment by lukehutch** [comment]
.... and so yes, if you have some sort of attestation protocol built in, a sufficiently determined attacker could spoof the protocol responses to trick the server into trusting the proxy. But that is simply a level of complexity that very few people would be willing to go to -- and any hacker that is this determined will always find a way anyway.

**Comment by fischerscode** [comment]
I think should be possible (and not too hard) to start a webserver at the client (native only) that forwards the traffic to the server through a pre-shared public key (shipped with the app). The Serverpod client could just connect to that local webserver.

For an attacker, this should almost be impossible to bypass. The attacker would have to change the public key, that is baked into the app.

**Comment by lukehutch** [comment]
What about something even simpler: just have the client libraries check the key obtained from the remote server against a copy shipped with the app. This is known as certificate pinning. (I don't know why having a local forwarding server would help.) However certificate pinning is not ideal with Letsencrypt certs, because they are short-lived.

**Comment by lukehutch** [comment]
Actually on that note, does Serverpod implement ACME (the Letsencrypt cert provisioning protocol)?

**Comment by fischerscode** [comment]
> I don't know why having a local forwarding server would help

The Local forwarding server would encrypt the message on top of http/https. It would be a solution/package that could be used on for every http api. And in case the user has to use a proxy, due to a restricted network, it would still work.

In case you don't want to allow proxies at all, it might be the easiest to [disallow them](https://api.dart.dev/stable/2.19.2/dart-io/HttpClient-class.html#turning-proxies-on-and-off). This however might need some changes to the Serverpod package.

> Actually on that note, does Serverpod implement ACME (the Letsencrypt cert provisioning protocol)?

Serverpod does not support acme (like most web servers). You could acquire a certificate and add the [`HTTPS certificate to your load balancer`](https://docs.serverpod.dev/deployments/general#running-a-cluster-of-servers).

**Comment by lukehutch** [comment]
> In case you don't want to allow proxies at all, it might be the easiest to [disallow them](https://api.dart.dev/stable/2.19.2/dart-io/HttpClient-class.html#turning-proxies-on-and-off). This however might need some changes to the Serverpod package.

You can still install a MitM proxy on a network gateway...

Here is an approach to certificate pinning:

https://dwirandyh.medium.com/securing-your-flutter-app-by-adding-ssl-pinning-474722e38518

And there is a Flutter library that might be even better:

https://pub.dev/packages/http_certificate_pinning

**Comment by SandPod** [comment]
If I understand the final request after your discussion, this would be to support certificate pinning.

This can already be achieved in the client by providing a `SecurityContext` when the client is initialized.
On the server, this will be possible to configure once this issue is resolved: https://github.com/serverpod/serverpod/issues/2964

@lukehutch - Can we close this issue as a duplicate of the mentioned issue above?

**Comment by lukehutch** [comment]
Possibly, but I'm so far out of the think-space of this right now that I couldn't hazard a guess as to whether that issue resolves what I was looking for.

**Comment by SandPod** [comment]
No problem.

Then I will close this as a duplicate and if it comes up again we can reopen it.
