### ISSUE TITLE
Not clear how to use orderBy in find() method

### ISSUE THREAD

**Issue by wstrange** [serverpod/serverpod#726]
It is not clear how to use `orderBy` in the find method:

```dart
`Event.find(session,
        where: (event) => event.sectionId.equals(sectionId), orderBy: ???? );
```

The where parameter provides an `Expression` in the closure that can reference the column names.  

I'd expect orderBy to have a similar closure, or to provide some other means of getting the Column expression. 

I think this works:

```
    var sc = EventTable().startTime; // get column for orderBy=

```

But it feels kludgy

**Comment by hortigado** [comment]
`  return await UserServer.find(session,orderBy: ColumnDateTime("dateTime"),orderDescending: false);`
I have not used it yet but I understand that it is used like this

**Comment by vlidholt** [comment]
This should be added to the documentation if it isn't already.

```dart
Event.find(
  session,
  where: (event) => event.sectionId.equals(sectionId),
  orderBy: Event.t.id,
);
```

The `Event.t` object will be a representation of your table, and have a field for each column.

**Comment by vlidholt** [comment]
Added docs here: https://github.com/serverpod/serverpod_docs/commit/c4334ead9ed266d88c428f51f33370f1a83b7c54
Will be updated with the 1.1 release.

**Comment by dongri727** [comment]
Please tell me 
How do I write the orderBy to refer to the year Field and then, if it is the same year, to refer to the month and day Field in the same table ?

**Comment by vlidholt** [comment]
@dongri727 if you use a DateTime, it will be sorted by date (including year, month, and day) or am I missing something?

There is also a `orderByList` property if you need to order by multiple columns.

**Comment by dongri727** [comment]
@vlidholt Thanks for the answer. Since I am dealing with historical events, like 13.8 billion years ago, or 772 BC... I didn't think I could use DateTime. Anyway how do I describe the orderByList in my endpoint ?
