### ISSUE TITLE
More flexible query to find Users

### ISSUE THREAD

**Issue by wstrange** [serverpod/serverpod#730]
Another minor, but useful feature request:

The `Users` object has `findUserbyEmail`, `findUserById`, and `findUserByIdentifier`

What I'm looking for is the ability to find users via a flexible query (find via email like `foo@bar.com`, fullName starts with `Bert`, etc.) 

This can be done via raw SQL, but having support for a generic `find` would be super helpful.

**Comment by hortigado** [comment]
it exist.
 Users.findSingleRow(session,where: (p0) => p0.email.equals(email));

**Comment by wstrange** [comment]
@hortigado That query is an exact match in SQL?

Take a look at the postgres docs for LIKE and ILIKE queries.  For example, I want to search for all users from `acme.com` domain.

**Comment by hortigado** [comment]
and to all users
`Users.find(session);`

**Comment by wstrange** [comment]
OK, I completely missed the `like` expression!  Yes - this works!

```dart
    return UserInfo.find(session, where: (x) => (x.email.ilike(qq)) | (x.fullName.ilike(qq)));

```

(Remember to include wildcards in the query where appropriate)
