### ISSUE TITLE
Customizable text to SignInWithGoogleButton

### ISSUE THREAD

**Issue by hortigado** [serverpod/serverpod#731]
Hi can you add text variable to the SignInWithGoogleButton. Thanks
'
` label: text!=null?text: Text('Sign in with Google'),
`
Also the same for SignInWithFirebaseButton
Also signInWithFirebase needed SignInScreen variables as headerBuilder for can custom the Login Page

**Comment by vlidholt** [comment]
This would be a nice addition. In the meantime, the code for the `SignInWithGoogleButton` is very short. You can just copy the code and make the button look like anything you want!

Here is the code:
https://github.com/serverpod/serverpod/blob/main/modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/signin_button.dart

**Comment by hortigado** [comment]
Yeah mate, I finally implemented the flutterfire login screen and button myself for more control. Greetings
`   return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.only(
            left: 16.0,
            right: 16.0,
            bottom: 20.0,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Row(),
              Expanded(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Flexible(
                      flex: 1,
                      child: Image.asset(
                        'assets/images/intro/feeding.png',
                        height: size.height * .2,
                      ),
                    ),
                    SizedBox(height: 20),
                    Text(
                      'Bienvenido',
                      style: TextStyle(
                        fontSize: 40,
                      ),
                    ),
                    Text(
                      'Ingresa con tu cuenta',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: size.width * .07,
                      ),
                    ),
                    SizedBox(
                      height: size.height * .08,
                    ),
                    FutureBuilder(
                      future:
                          Authentication.initializeFirebase(context: context),
                      builder: (context, snapshot) {
                        if (snapshot.hasError) {
                          return Text('Error al iniciar Firebase');
                        } else if (snapshot.connectionState ==
                            ConnectionState.done) {
                          return GoogleSignInButtoCustom();
                        }
                        return CircularProgressIndicator(
                          color: Colors.grey.shade900,
                          valueColor: AlwaysStoppedAnimation<Color>(
                            Colors.black,
                          ),
                        );
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );`
```
  static Future<FirebaseApp> initializeFirebase({
    required BuildContext context,
  }) async {
    FirebaseApp firebaseApp = await Firebase.initializeApp();

    User? user = FirebaseAuth.instance.currentUser;

    if (user != null) {
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(
          builder: (context) => Menu(),
        ),
      );
    }

    return firebaseApp;
  }

  static Future<User?> signInWithGoogle({required BuildContext context}) async {
    FirebaseAuth auth = FirebaseAuth.instance;
    User? user;

    if (kIsWeb) {
      GoogleAuthProvider authProvider = GoogleAuthProvider();

      try {
        final UserCredential userCredential =
            await auth.signInWithPopup(authProvider);

        user = userCredential.user;
      } catch (e) {
        print(e);
      }
    } else {
      final GoogleSignIn googleSignIn = GoogleSignIn();

      final GoogleSignInAccount? googleSignInAccount =
          await googleSignIn.signIn();

      if (googleSignInAccount != null) {
        final GoogleSignInAuthentication googleSignInAuthentication =
            await googleSignInAccount.authentication;

        final AuthCredential credential = GoogleAuthProvider.credential(
          accessToken: googleSignInAuthentication.accessToken,
          idToken: googleSignInAuthentication.idToken,
        );

        try {
          final UserCredential userCredential =
              await auth.signInWithCredential(credential);
          user = userCredential.user;

          final userget = await client.userServer.getUser(user!.uid.toString());
          if (userget == null) {
            client.userServer.create(UserServer(
                uid: user.uid,
                name: user.displayName.toString(),
                email: user.email.toString(),
                photo: user.photoURL.toString()));
          }
        } on FirebaseAuthException catch (e) {
          if (e.code == 'account-exists-with-different-credential') {
            ScaffoldMessenger.of(context).showSnackBar(
              Authentication.customSnackBar(
                content:
                    'The account already exists with a different credential',
              ),
            );
          } else if (e.code == 'invalid-credential') {
            ScaffoldMessenger.of(context).showSnackBar(
              Authentication.customSnackBar(
                content:
                    'Error occurred while accessing credentials. Try again.',
              ),
            );
          }
        } catch (e) {
          ScaffoldMessenger.of(context).showSnackBar(
            Authentication.customSnackBar(
              content: 'Error occurred using Google Sign In. Try again.',
            ),
          );
        }
      }
    }

    return user;
  }
```
