### ISSUE TITLE
Please update version dependencies for serverpod_auth

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#732]
**Describe the bug**

Can the dependencies of the `serverpod_auth` libraries please be updated? They are quite out of date.

If I use in my dependencies

```
  serverpod_auth_google_flutter: ^1.0.1
  serverpod_auth_apple_flutter: ^1.0.1
  image: ^4.0.15 
```

I get

```
Because serverpod_auth_shared_flutter >=0.9.20 depends on image ^3.2.2 and myapp_flutter depends on image ^4.0.15, serverpod_auth_shared_flutter >=0.9.20 is forbidden.
So, because myapp_flutter depends on serverpod_auth_shared_flutter ^1.0.1, version solving failed.
```

Furthermore when building the Android app I get:

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':sign_in_with_apple' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

`serverpod_auth_apple_flutter` depends on `sign_in_with_apple 3.3.0`, but `4.3.0` is available.

I tried overriding these versions using

```
dependency_overrides:
  image: ^4.0.15
  sign_in_with_apple: ^4.3.0
```

However bumping the `image` dependency to 4.x breaks one line in serverpod_auth_shared_flutter:

```
: Error: Too many positional arguments: 1 allowed, but 2 found.
image_uploader.dart:47
Try removing the extra positional arguments.
      image = img.copyResizeCropSquare(image, imageSize);
                                      ^
```

I submitted a PR to fix these, see below.

**Serverpod versions**
 -  _CLI Version:_ 1.0.1
 - _Library version:_ 1.0.1

**Platform information**
Linux

**Comment by vlidholt** [comment]
This needs to be fixed
