### ISSUE TITLE
example error on Windows: SocketException: The remote computer refused the network connection.

### ISSUE THREAD

**Issue by siuvoniazzi** [serverpod/serverpod#733]
**Describe the bug**
Running the example on windows throws SocketException when "Send to Server" button is clicked.
![image](https://user-images.githubusercontent.com/9570323/224530125-9726c393-7a90-4244-a2db-3eeda11d816a.png)

**To Reproduce**
1. Install serverpod as described in "Get Started"
2. Try Serverpod Example App (type name "test" and hit "Send to Server" Button) on device windows
3. Error message appears

**Expected behavior**
- no error message
- Hello test

**Screenshots**
![image](https://user-images.githubusercontent.com/9570323/224530284-81c01490-d8e3-498a-a59e-145be79c4c42.png)

**Serverpod versions**
 -  _CLI Version: Serverpod version: 1.0.1
 - _Library version: serverpod_flutter: ^1.0.1

**Platform information**
Windows 11

**Additional context**
On web the error message is slightly different
![image](https://user-images.githubusercontent.com/9570323/224530502-1a9d1120-0239-45ed-b026-37faad7ce2fb.png)

**Comment by siuvoniazzi** [comment]
I understand Windows is still not officially supported, so you can close this issue if you want.

Just in case it is of some help, here are some other issues that stood out running through the default setup on Windows:

- failed to get console mode for stdin: The handle is invalid.
![image](https://user-images.githubusercontent.com/9570323/224533127-54c80f41-933b-4ed4-80e3-dab48d99c8e0.png)

- 3 containers
![image](https://user-images.githubusercontent.com/9570323/224533211-54dd23f2-667c-4428-8e92-7f30962faadd.png)

**Comment by hortigado** [comment]
In android you mus use 
```
client = Client(
    'http://10.0.2.2:8080/',
    authenticationKeyManager: FlutterAuthenticationKeyManager(),
  )..connectivityMonitor = FlutterConnectivityMonitor();

```

**Comment by hortigado** [comment]
Also you made this step?
![image](https://user-images.githubusercontent.com/42924254/224744943-abd8c8dd-a157-46ec-91a5-10eda99fc5ed.png)

**Comment by siuvoniazzi** [comment]
Thanks for your reply @hortigado. I'm trying to make a web app, so no Android specific issue. Anyways, your screen shot made me check everything, I deleted one of the postgres containers and tried the app again this morning and now it works.  I'm not sure what did it because I could swear I did exactly this at least one more time already.  aight, I'm closing this. Thanks for the help
