### ISSUE TITLE
Meaningful error messages for endpoints returning boolean

### ISSUE THREAD

**Issue by mikepyts** [serverpod/serverpod#742]
**Describe the bug**
Any endpoint that returns a boolean should return a meaningful message about the error instead, a good example of this could be `createAccountRequest` endpoint which will return `false` if you try to create an account with the same data as the existing account, so end user will be not able to identify the root cause of the issue

**To Reproduce**
1. Create a user account
2. Try to create a user account with the same data again

**Expected behavior**
A clear and concise description of the error returned from the endpoint

**Screenshots**
![image](https://user-images.githubusercontent.com/26088845/224673795-83266762-a574-4f82-8575-bf6701279e43.png)

**Serverpod versions**
1.0.0

**Platform information**
Any

**Comment by hortigado** [comment]
Friend, to you can watch the error you have that run withc  it the command serverpod.
`--watch`

**Comment by wstrange** [comment]
@hortigado I appreciate you are trying to be helpful, but you need to read these issues more carefully before responding. 

This issue is about returning more information to the client so it can present a more meaningful message to the end user.

**Comment by hortigado** [comment]
oh i dont watch that for final user. for it can you first made a consult if the consult return a user not insert the new user.

**Comment by hortigado** [comment]
for example for firebase auth
```
  final UserCredential userCredential =
              await auth.signInWithCredential(credential);
          user = userCredential.user;
          print(user!.uid.toString());

          final userget= await client.userServer.getUser(user!.uid.toString());
if(userget==null){
            client.userServer.create(UserServer(uid: user.uid,name: user.displayName.toString(), email: user.email.toString(), photo: user.photoURL.toString()));

}
```

**Comment by vlidholt** [comment]
@mikepyts We are solving this in Serverpod 1.1 with exceptions you can throw on the server and catch on the client. The exceptions can contain extra information about the error too.

**Comment by vlidholt** [comment]
@wstrange while exceptions are a bit more expensive compared to returning a value, someone made a test and throwing a million exceptions took about 400ms, so I wouldn't think that is an issue compared to the cost of doing i/o etc.

https://stackoverflow.com/questions/62957269/what-is-the-performance-cost-of-throwing-an-exception-in-dart

**Comment by andyhorn** [comment]
@vlidholt I think this should be re-opened.

I'm using Serverpod 1.2 and I haven't been able to find a way to return any kind of error when using `createAccountRequest` with an email that is already taken. I haven't found anything in the auth module's `AuthConfig` that allows me to hook into the create account flow to verify whether the email is taken and return an error - so I'm stuck on the client with just a "something went wrong" and no way to indicate what happened.
