### ISSUE TITLE
Feature: copyWith() method for entities

### ISSUE THREAD

**Issue by wstrange** [serverpod/serverpod#748]
A minor feature request for quality of life:   Generate a `copyWith` method on entities.  Makes it easy to clone objects. 

Lateral thought: Generate models using freezed as the base. Provides copyWith, immutability, and json serialization.

**Comment by vlidholt** [comment]
This is a feature we should add.

For reference, Serverpod is compatible with Freezed if you prefer that for your serialization. More info here:
https://docs.serverpod.dev/concepts/serialization#custom-serializable-objects

**Comment by wstrange** [comment]
WDYT about using Freezed as the base for generated models? You'd get `copyWIth` for "free".   It might be a breaking change though...

**Comment by pro100andrey** [comment]
To generate copyWith, hashCode and == operator, user should be run serverpod generate --client-data-class

**Comment by vlidholt** [comment]
There is a good starting point for doing this here:
https://github.com/serverpod/serverpod/pull/976

**Comment by jason-downs** [comment]
> 

The problem with using the Custom Serializable Objects approach is that in that case it can't be connected to the database. Or am I missing something? As far as I can tell only with the classes defined in yaml can they be used in the postgres tables.

So it seems currenlty my dilemma is I can either have classes that are equatable via freezed/equatable etc, or I can have them compatible with the built-in database, but not both. I'm trying to move a pre-existing large flutter project over to serverpod and this is basically a blocker for me until fixed, becuase I'm heavily dependent on classes being equatable (via Equatable package) for unit tests and some business logic that would be hard to change.

I hope this can be dealt with soon as I don't know what to do for now except being super-hacky and adding Equatable to the classes in the generated code after each `serverpod generate` which obviously is not workable long-term.
