### ISSUE TITLE
Errors building serverpod from source

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#749]
When I try to build serverpod from source in VSCode, right after git clone, I see:

(1) `templates/pubspecs/tools/serverpod_cli/bin/generated/version.dart`:

```
Undefined name 'PRODUCTION_MODE'.
```

(2) `templates/pubspecs/tools/serverpod_cli/pubspec.yaml`:

```
[templates/pubspecs/tools/serverpod_cli] dart pub get
Error on line 4, column 5 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
4 │ name: serverpod_cli
  │     ^
  ╵
exit code 65

--

[templates/pubspecs/tools/serverpod_cli] dart pub get
Error on line 4, column 5 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
4 │ name: serverpod_cli
  │     ^
  ╵
exit code 65
```

**Comment by hortigado** [comment]
Maybe you didn't edit the `yaml `file for the client folder because it should be ` serverpod_client` in the name

**Comment by lukehutch** [comment]
I'm using what is checked into git, without modification. Why wouldn't it build out of the box?

**Comment by vlidholt** [comment]
Serverpod contains a number of packages that you can (potentially) build individually. It looks like you are analyzing files in the templates directory, and they aren't meant to be analyzed before being applied to the real yaml files used by the individual packages.

**Comment by lukehutch** [comment]
All I'm doing is loading the entire serverpod git repo into VS Code, and then accepting its requests to run `pub get`.

What's the right way to set up VS Code with serverpod?

**Comment by vlidholt** [comment]
I see, I usually just open up the different packages individually. But we should probably add some analyzer files that ignores the directories that shouldn't be checked.

**Comment by lukehutch** [comment]
Hey, I'm still running into these two issues. It would be nice to be able to load the whole `serverpod` repo into VS Code, and not have it complain about errors.

Also, the docs need to contain instructions about how to build the different modules. Any protocol modifications to `serverpod_auth` require running `serverpod generate` inside `serverpod_auth_server`, for example. And in several places there is a `generated/protocol.yaml`, but running `serverpod generate` in some of those directories reports an error. One of them even causes `serverpod_cli` to lock up.

**Comment by vlidholt** [comment]
You can re-run all the required `serverpod generate` commands in for all of serverpod by running the `util/generate_all` script. It is also run in the tests on Github.
