### ISSUE TITLE
User ids should be `bigint`, not `int`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#767]
**Is your feature request related to a problem? Please describe.**

User ids are currently of Postgres `int` type (int32). They really should be of `bigint` type (int64).

If a server runs for long enough, with hundreds of millions of users who may delete and recreate accounts at will, it's only a matter of time before `int`-typed user ids wrap around and become negative.

**Describe the solution you'd like**

The user id column should be created as `bigint`.

Dart ints have 53 bits of reliable precision. Changing the user id type from `int` to `bigint` for the creation of new ids would (presumably) not require any changes to existing codebases.

**Comment by fischerscode** [comment]
> Dart ints have 53 bits of reliable precision.

Only on web, as far as I know. However, the id could be constrained to that size in the database.

**Comment by gintominto5329** [comment]
And this limitation of dart-web, of 32-bit `int`s, is until dart-to-wasm is released, scheduled for dart-3

**Comment by lukehutch** [comment]
Not true... if you just want to use ints or do basic arithmetic, you're limited to 53 bits on dart-web, and 64 bits on other platforms. You're limited to 32 bits on all platforms only if you use Boolean bitwise operations.

**Comment by andriyndev** [comment]
What about giving user possibility to choose which type to use for the id field? Because in some cases `bigint` may be too big.

**Comment by SandPod** [comment]
After this PR https://github.com/serverpod/serverpod/pull/1194, this should be solved since we now use bigint by default for all integers stored in the Database.
