### ISSUE TITLE
Serverpod tests sometimes fail

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#773]
**Describe the bug**
Sometimes the `tests_single_server` tests fail. [example](https://github.com/serverpod/serverpod/actions/runs/4491639572/jobs/7900382427). I assume it's some kind of race condition.

**To Reproduce**
N/A

**Expected behavior**
Tests should be deterministic.

**Screenshots**
N/A

**Serverpod versions**
N/A

**Platform information**
N/A

**Additional context**
N/A

**Comment by 10422001** [comment]
Hello to all! My first comment here.
I was trying to find the issue / reproduce it. But I couldn't do that. 
Here are the failed actions I could find with similar tests failing over the last week, so the next person has an easier overview

Logging Logging in stream (over the last week)
(test/service_protocol_test.dart 289:7 --> Expected: <12> Actual: <11>)
( test/service_protocol_test.dart 292:7 -- >Expected: <11> Actual: <10>)
https://github.com/serverpod/serverpod/actions/runs/4491639572/jobs/7900382427
https://github.com/serverpod/serverpod/actions/runs/4512965831/jobs/7947134058
https://github.com/serverpod/serverpod/actions/runs/4480665083/jobs/7876286041
https://github.com/serverpod/serverpod/actions/runs/4480267691/jobs/7875334287
https://github.com/serverpod/serverpod/actions/runs/4479032416/jobs/7872525739

(3 days ago but also similar to find 2 weeks ago, not sure if these are also connected to this issue)
Database desired definition indexes
(test/service_protocol_test.dart 399:9 --> Expected: hash Actual: brin)
https://github.com/serverpod/serverpod/actions/runs/4479032416/jobs/7872525739
https://github.com/serverpod/serverpod/actions/runs/4479059556/jobs/7872581781

(Sorry, If the comment in not necessary or in the wrong spot)

**Comment by fischerscode** [comment]
With #778 there might be a fix now. Please report it here if the 'Logging in stream' test fails in a PR that has this change already applied.

**Comment by vlidholt** [comment]
I think that the reason the test failed is that the logs are stored asynchronously. When you write a log entry on the server, it does so in a future that may not have returned before the call has finished. If the tests run slow, perhaps the write hasn't finished before we are doing a read to check if the logs have been written.

**Comment by 10422001** [comment]
I think I might have found a way. It is not perfect.
```dart
// This test failed some times due to some kind of race condition.
// Idealy we would not use a hard coded delay here.
// Ticket: https://github.com/serverpod/serverpod/issues/773
for (var i = 0; i < 10; i += 1) {
  if (client.streamingConnectionStatus != StreamingConnectionStatus.connected) {
    await Future.delayed(const Duration(milliseconds: 300));
  }
}
// import 'package:serverpod_service_client/src/protocol/session_log_result.dart' as _i4;
_i4.SessionLogResult logResult = await serviceClient.insights.getSessionLog(1, null);
for (var i = 0; i < 10; i += 1) {
    if (logResult.sessionLog[0].logs.length != 12) {
      await Future.delayed(const Duration(milliseconds: 1000));
      logResult = await serviceClient.insights.getSessionLog(1, null);
  }
}

// await Future.delayed(const Duration(seconds: 5));

// var logResult = await serviceClient.insights.getSessionLog(1, null);
expect(logResult.sessionLog.length, equals(1));
expect(logResult.sessionLog[0].sessionLogEntry.isOpen, equals(true));
// We should have logged one entry when opening the stream and 11 when
// sending messages.
expect(logResult.sessionLog[0].logs.length, equals(12));

```
First, we check if the connection is open. (Could add:  if else break) If not we recheck with delay.
Then we check for the logResult.sessionLog[0].logs.length is full / 12. 
Here I am not sure which logResult would be the best and if there are some background-tasks 
that might forbid calling the log more often.
I also tried Future.sync, Future.microtask and more, but couldn't find a working solution.
