### ISSUE TITLE
Test serverpod_cli, esp. generation.

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#777]
**Is your feature request related to a problem? Please describe.**
Edge cases of `serverpod_cli` should be tested, esp. with `serverpod generate`.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
- failing generation
- generation with deleted `generated` folder
- continuous generation

**Comment by Isakdl** [comment]
We now have way more than 1000 tests on the CLI covering the mentioned topics.
