### ISSUE TITLE
Use `CommandRunner` to struture commands in `serverpod_cli`

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#783]
**Is your feature request related to a problem? Please describe.**
Make the commands / the structure of `serverpod_cli` easier to read.

**Describe the solution you'd like**
Use `CommandRunner` to struture commands in `serverpod_cli`.

**Describe alternatives you've considered**

**Additional context**
[docs](https://pub.dev/packages/args#dispatching-commands)

**Comment by SandPod** [comment]
This has now been implemented: https://github.com/serverpod/serverpod/blob/ba8d1f6b9b7a2c584a02d19ad49aeefdb06282f6/tools/serverpod_cli/bin/serverpod_cli.dart#L62-L79
