### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#8]
Plug-in for editors to display errors in yaml-files and continuously generating code.

**Comment by yahu1031** [comment]
@vlidholt  released vscode extension

**Comment by vlidholt** [comment]
We saw it. :) The part that we've written is the code analyzer for the yaml-files, we will have a second look at your stuff to see if we can use it for starting/stopping the server!

**Comment by Isakdl** [comment]
Official vscode extension available here: https://marketplace.visualstudio.com/items?itemName=serverpod.serverpod
