### ISSUE TITLE
Drop `int? id` field for non-persisted classes

### ISSUE THREAD

**Issue by tp** [serverpod/serverpod#81]
We have some entities which are not persisted to the DB but which nonetheless contain the optional `id` field.

This often gets confusing, as e.g. an `UpdateUserMessage` would look like this:

```
class UpdateUserMessage {
  int? id;
  String name;
  int userId;
}
```

Then one has to be very careful to read from the `userId` in these cases instead of the usual `id` field for most entities.

I don't think having these `id` fields by default serves any purpose by default, and removing it would exclude a type of bug.

**Comment by vlidholt** [comment]
Fixed
