### ISSUE TITLE
Missing contribution setup info in the documents

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#830]
> If you run the local version of the serverpod command line interface you will need to set the SERVERPOD_HOME environment variable. It should point to your cloned serverpod repository.

This part should specify clearly that it is the root of the mono repo that should be targeted.

It would also be nice to include the fact that you may need to update the version of the all serverpod dependencies if you create a new project with the dev version of the cli tool. I.E. if the latest version is not yet published, you should use the local path in your projects.

**Comment by vlidholt** [comment]
Fixed
