### ISSUE TITLE
Allow connection timeout to be configured

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#837]
**Is your feature request related to a problem? Please describe.**

`serverpod_client_io.dart` configures `_httpClient.connectionTimeout = const Duration(seconds: 20);`.

This timeout should be configurable. (I would like to set it to 10 seconds or something).

**Describe the solution you'd like**

`ServerpodClient`'s constructor needs to accept a `Duration` as an optional parameter that overrides the default timeout.

**Comment by SandPod** [comment]
This is now configurable through the `Client` constructor with the `connectionTimeout` argument.
