### ISSUE TITLE
Permissions in Flutter macOS app template — SocketException: Connection failed

### ISSUE THREAD

**Issue by filonov** [serverpod/serverpod#84]
`SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = localhost, port = 8080
`

Need to add client permissions in _macos/Runner/DebugProfile.entitlements_ and _macos/Runner/Release.entitlements_

`<key>com.apple.security.network.client</key>
 <true/>`

**Comment by Story5** [comment]
It's not work for me
