### ISSUE TITLE
Insights app shows some error on Log settings.

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#846]
**Describe the bug**

**To Reproduce**
1. Installed the app
2. Open the App
3. Click on `Log Settings`

**Screenshots**
<img width="1002" alt="Screenshot 2023-04-26 at 1 07 44 AM" src="https://user-images.githubusercontent.com/35523357/234384824-a1f8a5ba-9e6d-4b9b-92e4-1732a77983b7.png">

**Serverpod versions**
 -  _CLI Version:_ 1.1.0
 - _Library version:_ 1.1.0

**Platform information**
`sw_vers`
```console
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F5037d
```

**Comment by vlidholt** [comment]
There should be better error messages here for sure!

**Comment by SandPod** [comment]
@yahu1031 - Could you validate that this is still an issue?

With the latest version of insights, an error message is displayed in log settings if no project is connected for example.

Closing this as resolved but please open it again if the problem persists.

**Comment by yahu1031** [comment]
Yes seems fixed.
