### ISSUE TITLE
Unable to connect PostgreSQL sever

### ISSUE THREAD

**Issue by MrShakila** [serverpod/serverpod#852]
I am getting this error when i try to deploy the sever pod sever 

`Failed to connect to the database. Retrying in 10 seconds. PostgreSQLSeverity.fatal 28P01: password authentication failed for user "postgres" `

![Screenshot 2023-04-28 at 17 04 51](https://user-images.githubusercontent.com/90470539/235137219-34583d2a-220f-45cd-b010-f75b70a2497c.png)

Flutter Doctor Results

![Screenshot 2023-04-28 at 17 06 44](https://user-images.githubusercontent.com/90470539/235137557-dd8415e1-f271-486c-b249-e04e44e339a1.png)

**Comment by avatarnguyen** [comment]
I had a similiar case where my password is not correct. maybe double check your `passwords.yaml` credential with your `development.yaml` passwords for the database

**Comment by yahu1031** [comment]
@MrShakila Duplicate #555
