### ISSUE TITLE
Please add instructions to the documentation to create the tables for authentication.

### ISSUE THREAD

**Issue by masudataichi** [serverpod/serverpod#857]
**Describe the bug**
There is no explanation about how to create tables for authentication such as `serverpod_user_info`.

**To Reproduce**
1. Add `serverpod_auth_server` to the server.
2. Set up as described in [the documentation](https://docs.serverpod.dev/concepts/authentication#app-setup).
3. Try login
4. I got `PostgreSQLSeverity.error 42P01: relation "serverpod_user_info" does not exist `

**Serverpod versions**
 -  _CLI Version:_ 1.1.0
 - _Library version:_  1.1.0

**Platform information**
macOS 13.3.1

**Comment by yahu1031** [comment]
CC: @vlidholt Actually yes. Adding [auth tables in the modules](https://docs.serverpod.dev/concepts/modules#database-setup) may not be appropriate. This can go under authentication part.

**Comment by vlidholt** [comment]
We are working on improving the documentation for the modules and hope to have that updated in the next few weeks. You can find instructions for adding a module and its tables here:
https://docs.serverpod.dev/concepts/modules
