### ISSUE TITLE
Newly created project has empty tables.pgsql file

### ISSUE THREAD

**Issue by MarkOSullivan94** [serverpod/serverpod#861]
**Describe the bug**

After I generated a new serverpod project, I noticed that there's an empty pgsql file.

**To Reproduce**
1. Ensure serverpod_cli has been installed
2. `serverpod create myserver`
3. Find the file within `myserver_server/generated` directory 

**Expected behavior**

There should be no empty file generated.

**Screenshots**

<img width="1728" alt="Screenshot 2023-05-01 at 23 37 00" src="https://user-images.githubusercontent.com/6950843/235567694-38eb6ef9-dbd7-407d-a642-4a5d892fc98e.png">

**Serverpod versions**
 -  _CLI Version:_ 1.1.0
 - _Library version:_ 1.1.0

**Comment by yahu1031** [comment]
@MarkOSullivan94 Yes, this will be generated when you have some models and the model has some table.

**Comment by vlidholt** [comment]
Correct, this is where the sql code for any tables you add will end up.

**Comment by MarkOSullivan94** [comment]
@vlidholt could we get a comment added to this file for when it's empty with that info?

**Comment by vlidholt** [comment]
This is being completely reworked for Serverpod 1.2.

**Comment by MarkOSullivan94** [comment]
Any estimation on 1.2 release date @vlidholt?

**Comment by vlidholt** [comment]
Sometime this fall. 🤞 It's a pretty substantial update, both when it comes to Serverpod itself and the tooling around it.
