### ISSUE TITLE
Serialization Issues

### ISSUE THREAD

**Issue by Dokotela** [serverpod/serverpod#873]
**Describe the bug**
I'm having trouble using the serialization process for serverpod. Here's the repo if you'd like to take a look: https://github.com/fhir-fli/fhirpod. All of my classes are freezed, and I've adjusted all of the fromJson to include the serializationManagers. That has no errors. When I try to generate code, if I remove json_serializable from the pubspec and all of the part 'file.g.dart'; code, then it generates fine. However, it doesn't generate the toJson() files that are required. 

However, when I do include the json_serializable to generate the toJson() methods, I get this error message:
```
[SEVERE] json_serializable on lib/r4/resource_types/financial/general/general.dart:

Expecting a `fromJson` constructor with exactly one positional parameter. The only extra parameters allowed are functions of the form `T Function(Object?) fromJsonT` where `T` is a type parameter of the target type.
package:fhir/r4/special_types/special_types.dart:483:16
```

I'm using   serverpod_serialization: ^1.1.0.

Just hoping someone else had a similar experience and had found a solution.

**Comment by Dokotela** [comment]
So I thought I'd update this. Since I couldn't get the above working, I've decided to try a different tack. Ideally it would just be generated from the classes I already have, but since I can't get that to work, I thought I'd try and pull the data from the class directly into the yaml file for generation. I'm still working out some of the details, but I think it general it's a possibility. I'll attach my script here in case anyone else wants to try and play with it:
```dart
import 'dart:io';

Future<void> main() async {
  final Directory dir = Directory('.');
  final List<String> fileList = await dir
      .list(recursive: true)
      .map((FileSystemEntity event) => event.path)
      .toList();
  for (final String file in fileList) {
    if (file.contains('.dart') &&
        !file.contains('.g.') &&
        !file.contains('freezed') &&
        !file.contains('enum')) {
      final String fileString = await File(file).readAsString();
      final List<String> stringList = fileString.split('\n');
      String yaml = '';
      bool isClass = false;
      String className = '';
      for (final String line in stringList) {
        if (isClass) {
          if (line.trim().startsWith('///')) {
          } else if (line.endsWith(',')) {
            final List<String> splitLine = line.split(' ');
            yaml += '  ';
            yaml += splitLine.last.replaceAll(',', '');
            yaml += ': ';
            yaml += splitLine[splitLine.length - 2];
            yaml += '\n';
          } else if (line.contains('}) = _')) {
            isClass = false;
            await File('serverpod/${className.toLowerCase()}.yaml')
                .writeAsString(yaml);
            yaml = '';
          }
        }
        if (line.contains('factory') && line.contains('({')) {
          isClass = true;
          className = line.replaceAll('factory ', '').replaceAll('({', '');
          yaml += 'class: $className\n';
          yaml += 'fields: \n';
        }
      }
    }
  }
}
```

**Comment by Dokotela** [comment]
So some progress today, albeit with a different direction. Or at least, a workaround. First step is to generate all of your code as usual using freezed and jsonserializable. Then, add in the SerializationManager as an optional, positional parameter (this way it doesn't interfere if you call fromJson from any other methods or functions). I did a regex lookup and replace in VSCode. End result looks like this:
```dart
// ignore_for_file: invalid_annotation_target
// ignore_for_file: sort_unnamed_constructors_first
// ignore_for_file: sort_constructors_first
// ignore_for_file: avoid_unused_constructor_parameters

// Dart imports:
import 'dart:convert';

// Package imports:
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:serverpod_serialization/serverpod_serialization.dart';
import 'package:yaml/yaml.dart';

// Project imports:
import '../../r5.dart';

part 'element.freezed.dart';
part 'element.g.dart';

@freezed
class Element with _$Element {
  Element._();
  factory Element({
    @JsonKey(name: 'id') FhirId? fhirId,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    @JsonKey(name: 'fhir_comments') List<String>? fhirComments,
  }) = _Element;

  factory Element.fromJson(
    Map<String, dynamic> json, [
    SerializationManager? serializationManager,
  ]) =>
      _$ElementFromJson(json);
  }
}
```
Again, you can't regenerate your code at this point, it will throw an error. But, you can generate serverpod data. In your ```serverpod_server/config/generator.yaml``` file, you can add this class in like this:
```yaml
type: server

client_package_path: ../fhirpod_client

extraClasses:
  - package:fhir/r5.dart:Element
```
Then run ```serverpod generate``` and it will generate the protocol.dart file for the serializationManager, using your class. Next step is to figure out how to generate table data.

**Comment by SandPod** [comment]
The serialization manager is no longer present in the fromJson and toJson interfaces, please have a look at the updated documentation for serialization with freezed classes: https://docs.serverpod.dev/concepts/serialization#custom-class-with-freezed

Closing this issue, but please let me know if you encounter any other issues.
