### ISSUE TITLE
Stuck in "Setting up default database tables in directory"

### ISSUE THREAD

**Issue by ambanikousik** [serverpod/serverpod#88]
Hi, I can't create serverpod project, it seems to generate the flutter directory fine, but it get stucked at this point:
Setting up default database tables in /directory...
And I don't see any error message either.

**Comment by vlidholt** [comment]
Hi! Any chance you can do a `flutter doctor` and paste the output here?

**Comment by ambanikousik** [comment]
### flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

### serverpod create squadhead
Creating project squadhead...
  /Users/kousikambani/Development/tools/squadhead/squadhead_servergenerated/tables-serverpod.pgsql
  /Users/kousikambani/Development/tools/squadhead/squadhead_servergenerated/protocol.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_servergenerated/tables.pgsql
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverdocker-compose.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverbin/main.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverCHANGELOG.md
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverconfig/generator.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverconfig/staging.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverconfig/production.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverconfig/development.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverconfig/passwords.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverREADME.md
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverpubspec.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serversetup-tables
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverlib/server.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverlib/src/generated/endpoints.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverlib/src/generated/protocol.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverlib/src/generated/example_class.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverlib/src/endpoints/example_endpoint.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverlib/src/future_calls/example_future_call.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_serverlib/src/protocol/example_class.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_serveranalysis_options.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_servergitignore
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientCHANGELOG.md
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientREADME.md
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientpubspec.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientlib/PROJECTNAME_client.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientlib/src/protocol/client.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientlib/src/protocol/protocol.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientlib/src/protocol/example_class.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientanalysis_options.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_clientgitignore
  /Users/kousikambani/Development/tools/squadhead/squadhead_fluttertest/widget_test.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_flutterREADME.md
  /Users/kousikambani/Development/tools/squadhead/squadhead_flutterpubspec.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_flutterlib/main.dart
  /Users/kousikambani/Development/tools/squadhead/squadhead_flutteranalysis_options.yaml
  /Users/kousikambani/Development/tools/squadhead/squadhead_fluttergitignore
Running `dart pub get` in /Users/kousikambani/Development/tools/squadhead/squadhead_server
Resolving dependencies...
+ args 2.3.0
+ async 2.8.2
+ buffer 1.1.1
+ charcode 1.3.1
+ collection 1.15.0
+ crypto 3.0.1
+ executor 2.2.2
+ http 0.13.4
+ http_parser 4.0.0
+ lints 1.0.1
+ meta 1.7.0
+ path 1.8.1
+ pedantic 1.11.1
+ postgres 2.4.3
+ redis 2.2.0
+ retry 3.1.0
+ sasl_scram 0.1.0
+ saslprep 1.0.2
+ serverpod 0.9.4
+ serverpod_client 0.9.4
+ serverpod_postgres_pool 2.1.1
+ serverpod_serialization 0.9.4
+ serverpod_service_client 0.9.4
+ serverpod_shared 0.9.4
+ source_span 1.8.2
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ unorm_dart 0.2.0
+ web_socket_channel 2.1.0
+ yaml 3.1.0
Changed 33 dependencies!

Running `dart pub get` in /Users/kousikambani/Development/tools/squadhead/squadhead_client
Resolving dependencies...
+ async 2.8.2
+ charcode 1.3.1
+ collection 1.15.0
+ crypto 3.0.1
+ http 0.13.4
+ http_parser 4.0.0
+ meta 1.7.0
+ path 1.8.1
+ serverpod_client 0.9.4
+ serverpod_serialization 0.9.4
+ source_span 1.8.2
+ stream_channel 2.1.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ web_socket_channel 2.1.0
+ yaml 3.1.0
Changed 17 dependencies!

Running `flutter create` in /Users/kousikambani/Development/tools/squadhead/squadhead_flutter
Recreating project ....
  windows/runner/flutter_window.cpp (created)
  windows/runner/utils.h (created)
  windows/runner/utils.cpp (created)
  windows/runner/runner.exe.manifest (created)
  windows/runner/CMakeLists.txt (created)
  windows/runner/win32_window.h (created)
  windows/runner/Runner.rc (created)
  windows/runner/win32_window.cpp (created)
  windows/runner/resources/app_icon.ico (created)
  windows/runner/main.cpp (created)
  windows/runner/resource.h (created)
  windows/runner/flutter_window.h (created)
  windows/flutter/CMakeLists.txt (created)
  windows/.gitignore (created)
  windows/CMakeLists.txt (created)
  ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  ios/Runner/Info.plist (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  ios/Runner/Base.lproj/Main.storyboard (created)
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  ios/Flutter/Debug.xcconfig (created)
  ios/Flutter/Release.xcconfig (created)
  ios/Flutter/AppFrameworkInfo.plist (created)
  ios/.gitignore (created)
  squadhead_flutter.iml (created)
  web/favicon.png (created)
  web/index.html (created)
  web/manifest.json (created)
  web/icons/Icon-maskable-512.png (created)
  web/icons/Icon-192.png (created)
  web/icons/Icon-maskable-192.png (created)
  web/icons/Icon-512.png (created)
  .metadata (created)
  android/app/src/profile/AndroidManifest.xml (created)
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  android/app/src/main/res/drawable/launch_background.xml (created)
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  android/app/src/main/res/values-night/styles.xml (created)
  android/app/src/main/res/values/styles.xml (created)
  android/app/src/main/res/drawable-v21/launch_background.xml (created)
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  android/app/src/main/AndroidManifest.xml (created)
  android/app/src/debug/AndroidManifest.xml (created)
  android/gradle/wrapper/gradle-wrapper.properties (created)
  android/gradle.properties (created)
  android/.gitignore (created)
  android/settings.gradle (created)
  android/app/build.gradle (created)
  android/app/src/main/kotlin/com/example/squadhead_flutter/MainActivity.kt (created)
  android/build.gradle (created)
  android/squadhead_flutter_android.iml (created)
  ios/Runner/Runner-Bridging-Header.h (created)
  ios/Runner/AppDelegate.swift (created)
  ios/Runner.xcodeproj/project.pbxproj (created)
  .idea/runConfigurations/main_dart.xml (created)
  .idea/libraries/Dart_SDK.xml (created)
  .idea/libraries/KotlinJavaRuntime.xml (created)
  .idea/modules.xml (created)
  .idea/workspace.xml (created)
Running "flutter pub get" in squadhead_flutter...                2,495ms
Wrote 90 files.

All done!
In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.


Setting up default database tables in /Users/kousikambani/Development/tools/squadhead/squadhead_server

**Comment by ambanikousik** [comment]
Hi I was managed to solve the issue, 
I had to keep docker open , So I guess it should be written in the doc.

**Comment by vlidholt** [comment]
Great! I will add that to the dock, thanks for letting me know!
