### ISSUE TITLE
Give a warning if serverpod dependencies have different versions when running serverpod commands

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#889]
Since all serverpod packages should always use the same version we should give a warning if we find a diff between serverpod versions in all the pubspec files when running a serverpod cli command.

For example:

```bash 
$ serverpod generate

WARNING: Mismatching versions between serverpod_auth and serverpod in pubspec (<path/to/pubspec>) may lead to problems. Make sure all your serverpod packages are using the same version.
```

**Comment by SandPod** [comment]
Solved by: https://github.com/serverpod/serverpod/pull/1051
