### ISSUE TITLE
I am not able create other project cause 8080: Serverpod API already in use 

### ISSUE THREAD

**Issue by shiwam77** [serverpod/serverpod#890]
D:\>serverpod create hotelmanagement
WARNING! Windows is not officially supported yet. Things may or may not work as expected.

There are some issues with your setup that will prevent your Serverpod project from running out of the box and without
further configuration. You can still create this project by passing -f to "serverpod create" and manually configure your
Serverpod.

One or more network ports Serverpod want to use are not available. The most likely reason is that you have another
Serverpod project running, but it can also be another service.

Ports in use:
 • 8080: Serverpod API

**Comment by Isakdl** [comment]
You have another serverpod server running, stop that server first and you should be able to create the project. 

You can also run the command with -f to force create the project anyway. I.E. `serverpod create -f hotelmanagement`.

If you want to run two projects at the same time you will have to configure the ports used for your server, you can change the server side configuration inside `your_project_server/config/development.yaml`. 

Then make sure to use the correct port in your client as well!
