### ISSUE TITLE
serverpod generate command is not generating necessary class 

### ISSUE THREAD

**Issue by shiwam77** [serverpod/serverpod#894]
![Screenshot (43)](https://user-images.githubusercontent.com/42408353/236975385-684a7600-4da5-43d1-904a-b7906d5bafdc.png)
 
 One question From when server pod will be fully supported in the window

**Comment by fleeser** [comment]
Please add some more information about what exactly the problem is. I don't see any red lines or something similar in your IDE.

**Comment by shiwam77** [comment]
class DummyEndpoint extends Endpoint {
  // You create methods in your endpoint which are accessible from the client by
  // creating a public method with `Session` as its first parameter. Supported
  // parameter types are `bool`, `int`, `double`, `String`, `DateTime`, and any
  // objects that are generated from your `protocol` directory. The methods
  // should return a typed future; the same types as for the parameters are
  // supported. The `session` object provides access to the database, logging,
  // passwords, and information about the request being made to the server.
  Future<String> dummyFunction(Session session, String name) async {
    return 'Hello $name';
  }
}


After that I am running the command  
serverpod generate
response Is : WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Done.
But not able to call this function in flutter app & demo ExampleEndpoint is working though
