### ISSUE TITLE
i cant create sserverpod app

### ISSUE THREAD

**Issue by nopxjs** [serverpod/serverpod#895]
ProcessException: No such file or directory
  Command: dart pub get
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      CommandLineTools.dartPubGet (package:serverpod_cli/src/util/command_line_tools.dart:13:26)
#4      performCreate (package:serverpod_cli/src/create/create.dart:296:22)
<asynchronous suspension>
#5      _main (file:///home/omar/.pub-cache/hosted/pub.dev/serverpod_cli-1.1.0/bin/serverpod_cli.dart:201:9)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///home/omar/.pub-cache/hosted/pub.dev/serverpod_cli-1.1.0/bin/serverpod_cli.dart:36:9)
<asynchronous suspension>
#7      main (file:///home/omar/.pub-cache/hosted/pub.dev/serverpod_cli-1.1.0/bin/serverpod_cli.dart:33:3)
<asynchronous suspension>

**Comment by fleeser** [comment]
Please add some more information about what you are trying to achieve and in which directory you executed the command `dart pub get`.

The title states that you are having problems creating a serverpod project, but the command is for fetching all the packages. 

For now, I think you're just in the wrong directory. Please `cd` into the server project and execute the command. Whenever trying to `pub get` there should be a pubspec.yaml file in that directory.
