### ISSUE TITLE
Auth and Deployment documentation

### ISSUE THREAD

**Issue by ambanikousik** [serverpod/serverpod#90]
Hi, I've recently discovered this amazing project and instantly became a fan of it. I really appreciate for creating serverpod, I believe this will open a whole new world for the Dart lovers like me. Now, I know you guys are currently working on the documentation and without that I really can't  utilize all the magic hidden inside serverpor. 

Now, what I really want to know is, 
1) How can I deploy my serverpod server app to DigitalOcean dropplet or EC2, 
2) How can I connect to external postgresql db,
3) How do I write complex logic/query.
4) How to implement auth and token handling.

Thanks, I guess these are really needed for someone to get started with SERVERPOD.

**Comment by vlidholt** [comment]
Thanks for the feedback! Much improved documentation is in the works, I'll leave this ticket open until we've covered the topics that you mention.

**Comment by EwigSol** [comment]
any update on this so far guys we are planing to work on a development project using serverpod and want to be sure that we can run this on lightsail or may be ec2
kindly reply

**Comment by vlidholt** [comment]
I've been running it on ec2 and that is no problems. Documentation has been updated and can be found here: https://docs.serverpod.dev Closing this ticket now.
