### ISSUE TITLE
Can we use server pod  end points in Kotlin / swift or with other client side libraries like Dio in flutter 

### ISSUE THREAD

**Issue by sadaqatdev** [serverpod/serverpod#902]
Thanks for developing great server side frame work using dart

can we use server pod  end points in Kotlin / swift or with other client side libraries like Dio in flutter

**Comment by Isakdl** [comment]
In theory, you can, serverpod is built around regular rest requests using POST that sends the data in the body. You can in other words construct your own requests and send them to the server using any language you prefer. However, this is not something we officially have support for, meaning you will have to look at the code and figure out the endpoint/parameters you need to send. 

We have discussed creating support for other clients in the future by building code generators for multiple languages that would enable you to get an SDK out of the box. With that said this is something we would look at a bit further down the road.

**Comment by sadaqatdev** [comment]
Thanks
