### ISSUE TITLE
Need better database instructions

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#907]
**Is your feature request related to a problem? Please describe.**

The Serverpod instructions do not spell out any of the following:

* How to work with `psql` or similar to view the Serverpod tables (e.g., get the hostname, port number, username, and password from `generated/`)
* How to create the Flutter app database after the Postgres docker image is built (the docker build command only adds the `postgres` database)
* How to execute the `.pgsql` files in the Postgres database instance, to create the tables and indices (these can't be run until the app database is created)
  * Some required tables aren't in the `.pgsql` files, such as `serverpod_user_info` -- how are these supposed to be created?
* How to shut down the Postgres and Redis instances if needed
* How to update the SQL tables if your schemata change
* How to blow away the database if you want a fresh start (by stopping the Docker instances, and removing them, then recreating)

**Describe the solution you'd like**

The docs need a lot more detail

**Comment by yahu1031** [comment]
Check it out [here](https://docs.serverpod.dev/concepts/modules#database-setup). But yeah I do upvote for better docs. @lukehutch

**Comment by MarkOSullivan94** [comment]
+1 from me

There's no info on whether or not we need to manually run the pgsql scripts or if this is done automatically, feel this should be important information to include

**Comment by yahu1031** [comment]
Just FYI, Yes sometimes we need to run the script manually for the first time. I will check with the current code and update it if it still fails.

**Comment by SandPod** [comment]
Small update here, there are still improvements need to be made to the documentation to cover all requested points.

But with the introduction of the new migration system we have improved the documentation around how to set up you database schema and apply changes to the database: https://docs.serverpod.dev/next/concepts/database/migrations

**Comment by Isakdl** [comment]
All points here is covered in the new documentation, from the new migration system to database configuration and docker instructions (https://docs.serverpod.dev/next/concepts/database/connection)
