### ISSUE TITLE
Serverpod version: 1.1.0 - Serializable exceptions is not catch in client side

### ISSUE THREAD

**Issue by pro100andrey** [serverpod/serverpod#913]
**Describe the bug**
Serializable exceptions not catch in client side .

All steps are taken from the documentation  [exceptions](https://docs.serverpod.dev/concepts/exceptions)

**To Reproduce**

1. Create 'not_found.yaml' file in protocol folder:

```yaml
exception: NotFound
fields:
  postId: int
  errorMessage: String
```
  
2. Run `serverpod generate`
3. Implement throw `NotFound` in server side:
<img width="700" alt="Screenshot 2023-05-14 at 20 37 38" src="https://github.com/serverpod/serverpod/assets/46396672/71a32435-ef28-4d53-8444-71b22c736344">

4. Call `test` method in client Side:
<img width="581" alt="Screenshot 2023-05-14 at 20 40 37" src="https://github.com/serverpod/serverpod/assets/46396672/0a4fd88c-b914-4095-bf9a-c53918831bc5">

5. Result:
"ServerpodException: Internal server error"

Thanks!

**Comment by Isakdl** [comment]
Indeed, this looks like a bug, not sure why this happens right now. Seems to be something wrong with the code generation. We will take a look at this soon.

Out of curiosity any reason for duplicating the auth module rather than using the one hosted on pub.dev?

**Comment by pro100andrey** [comment]
Hi @Isakdl, Thanks for response!
> Out of curiosity any reason for duplicating the auth module rather than using the one hosted on pub.dev?

Simply put, I prefer to have full control over all the code in my project. By duplicating the auth module, I have the flexibility to customize and modify it according to my specific requirements. Although there may be an existing auth module available on pub.dev, using my own duplicate version gives me the freedom to make changes and enhancements as needed without relying on external dependencies. It allows me to have a deeper understanding of the authentication logic and maintain full control over the codebase

:)

Thanks!

**Comment by Isakdl** [comment]
This bug is fixed with https://github.com/serverpod/serverpod/pull/935

For the next version 1.1.1 this issue should be fixed.

**Comment by pro100andrey** [comment]
@Isakdl Thanks!!!
