### ISSUE TITLE
Signin with Apple platformsupport web/android

### ISSUE THREAD

**Issue by Isakdl** [serverpod/serverpod#914]
Signin with Apple works nicely for ios. But to have fullsupport on web and android the backend need to handle a callback URL from apple. Today we have not implemented this functionality.

Example endpoint, taken from [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple) package example server.
```javascript
// The callback route used for Android, which will send the callback parameters from Apple into the Android app.
// This is done using a deeplink, which will cause the Chrome Custom Tab to be dismissed and providing the parameters from Apple back to the app.
app.post("/callbacks/sign_in_with_apple", (request, response) => {
  const redirect = `intent://callback?${new URLSearchParams(
    request.body
  ).toString()}#Intent;package=${
    process.env.ANDROID_PACKAGE_IDENTIFIER
  };scheme=signinwithapple;end`;

  console.log(`Redirecting to ${redirect}`);

  response.redirect(307, redirect);
});
```
[Full code](https://glitch.com/edit/#!/flutter-sign-in-with-apple-example?path=server.js%3A22%3A0)

For web support we also have to expose the webAuthenticationOptions config object on the client. As this is needed to launch the sign in popup.

```dart
 var credential = await SignInWithApple.getAppleIDCredential(
      webAuthenticationOptions: WebAuthenticationOptions(
        clientId: 'com.example',
        redirectUri: Uri.https('example.com/callback/apple_sign_in_web'),
      ),
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
    );
```

More info here:
https://pub.dev/packages/sign_in_with_apple

**Comment by a1exhedb** [comment]
Did you manage to get Apple login working on Android?

**Comment by FantaMagier** [comment]
Any news on this Issue :D
