### ISSUE TITLE
Serverpod stuck after running 'dart bin/main.dart'

### ISSUE THREAD

**Issue by AmoonPod** [serverpod/serverpod#915]
**Serverpod stuck after running `dart bin/main.dart`**

Before migrating to Dart 3, Serverpod used to retrieve the following console output:
`
SERVERPOD version: 1.1.0, mode: development, time: 2022-09-12 17:22:02.825468Z
Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082
` 

After migrating to Dart 3, it only retrieves me: 
`SERVERPOD version: 1.1.0, dart: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "macos_arm64", time: 2023-05-16 07:07:22.758779Z
mode: development, role: monolith, logging: normal, serverId: default`

but it actually never starts.

I don't know how to fix this.

**Comment by Isakdl** [comment]
Have you tested to create a clean project? If not please do so, if it doesn't work please let me know. If it works I would take a look at the dependencies and other potentially blocking code in the main method.

**Comment by AndryHTC** [comment]
> Have you tested to create a clean project? If not please do so, if it doesn't work please let me know. If it works I would take a look at the dependencies and other potentially blocking code in the main method.

Could be anything related to Dart 3 as intended in this comment https://github.com/serverpod/serverpod/issues/906#issuecomment-1546112935?

**Comment by AmoonPod** [comment]
> Have you tested to create a clean project? If not please do so, if it doesn't work please let me know. If it works I would take a look at the dependencies and other potentially blocking code in the main method.

Hi. Yeah, I've tested by creating a new empty Serverpod project and it actually works fine, even with new Dart 3 version.
I still can't understand what's the problem. I've tried running serverpod from the branch that there is actually in production, so it's a branch where any change has been made since the deploy. But it still doesn't work.

**Comment by Isakdl** [comment]
Are you using any dependencies that might cause the error? That does not support Dart 3? 

Hard to tell without more code to look at.

**Comment by yahu1031** [comment]
There could be one package that causes this issue. Not a pretty rememberable package, LMC when I have time. I faced this issue a few time ago.

**Comment by AmoonPod** [comment]
Hello again. Apparently, I made a mistake. For some reason, the `await pod.start()` in the `server.dart` file has been removed, preventing Serverpod to run properly. 
After including it, everything started working again.

**Comment by vlidholt** [comment]
Glad you sorted it out. :)
