### ISSUE TITLE
Generate Custom Serializable Tables

### ISSUE THREAD

**Issue by Dokotela** [serverpod/serverpod#917]
**Is your feature request related to a problem? Please describe.**
My work involves a large number of Freezed classes (> 800). I'd like to be able to serialize this data and generate the code for Tables.

**Describe the solution you'd like**
To run ```serverpod generate``` and have it not just generate SerializedEntity classes but TableRow classes too.

**Describe alternatives you've considered**
It has taken me a while to actually implement code generation for my serialized classes. Currently what I've had to do is generate everything, then afterwards, do a Search/Replace in VS Code for each .FromJson() method, exchanging it from:
```dart
  factory Element.fromJson(Map<String, dynamic> json) => _$ElementFromJson(json);
```
to
```dart
factory Element.fromJson(
    Map<String, dynamic> json, [
    SerializationManager serializationManager,
    ]) => _$ElementFromJson(json);
```
Not ideal (because I can't re-generate my code), but it otherwise works. I'm then able to generate serverpod code using ```serverpod generate```. However, it only generates code for my classes as a SerializedEntity. There's no documentation on how to generate code for the classes that I want to extend TableRow and generate that code (including for Postgresql).

**Comment by vlidholt** [comment]
This is not something we are currently supporting, but we are considering adding annotations in Dart for serialization and database connectivity in future versions of Serverpod. I understan how this can be very useful.

**Comment by SandPod** [comment]
@Dokotela - The `serializationManager` is no longer a required argument when working with serialization of other classes.

Does that resolve this issue?

Please check the updated documentation here: https://docs.serverpod.dev/concepts/serialization#custom-class-with-freezed

I'll close this issue, but please open it again if it is unresolved.
