### ISSUE TITLE
Flutter 3.10 because iOS Impeller 

### ISSUE THREAD

**Issue by applegold** [serverpod/serverpod#918]
Can we upgrade the template to Flutter 3.10 

By default, all apps built for iOS with Flutter 3.10 use Impeller. These iOS apps will have less jank and better consistent performance.

**Comment by yahu1031** [comment]
I don't think, we specifically need to do this, cause as of the serverpod templates are not having anything to change in code level to support 3.10

**Comment by vlidholt** [comment]
We will do this update pretty soon!

**Comment by Isakdl** [comment]
The templates only have a minimum required flutter version, you should be able to run any flutter version above this.

We have just updated all the templates to allow dart version < 4.0.0 and flutter version >= 3.7.0
