### ISSUE TITLE
[feat] Model relationships 

### ISSUE THREAD

**Issue by egyleader** [serverpod/serverpod#926]
What about model & database relationships ? 

 for example a `User` should `have many` `Post`'s but  the `Post` belongs to only one `User` .

this should be reflected to the database migration as well as the model creation process & support for code generation

**Comment by rectrick** [comment]
This feature must be implemented as soon as possible, as it is one of the most important things for project management

**Comment by Isakdl** [comment]
This is now supported on the main branch
