### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by fleeser** [serverpod/serverpod#957]
### Discussed in https://github.com/serverpod/serverpod/discussions/956

<div type='discussions-op-text'>

<sup>Originally posted by **fleeser** May 27, 2023</sup>
I am trying to get the server up and running on AWS for two days now, but get a **502 Bad Gateway** when trying to access `api.app.example.app`. 

The terraform scripts seem to work since they run successfully. 

**Background Info**:
- I am using a subdomain `app.example.app` as the base domain. The generated subdomains then would be e.g. `api.app.example.app`.
- I am using the `eu-central-1` region besides the required `us-east-1` region.

I am able to connect to the database via tools like pgAdmin. When trying to access all the other subdomains via the Browser, the **502 Bad Gateway** response code gets returned.

I also found this discussion: [Discussion](https://github.com/serverpod/serverpod/discussions/445), but I don't think that a wrong Dart version is causing this error since I already replaced all the SDK versions in all files by nearly every possible version out there.

I tried creating a complete new Serverpod project, so that the Dart SDK versions are the default ones and the same error appears.</div>

**Comment by sroepges** [comment]
Answered in #956.
