### ISSUE TITLE
Have serverpod generate --watch show timestamps

### ISSUE THREAD

**Issue by dirkschut** [serverpod/serverpod#971]
**Is your feature request related to a problem? Please describe.**
It would be nice to know if the latest `File changed` output from the `serverpod generate --watch` command is from just now, or a while ago.

**Describe the solution you'd like**
Print a simple timestamp before the `File Changed` output.

**Describe alternatives you've considered**
Trusting the system...

**Additional context**
This is of course not a major feature and I don't expect it to get any real priority, or even be implemented at all. But at the same time, it is something that can probably be implemented in a couple of minutes. Might be a good issue to flag for a new to the project developer to tackle.

**Comment by BenAuerDev** [comment]
Hey Guys, 

May I pick this one up? :) 

I investigated the code and added a log.info() statement within the WatchEvent loop. And ended up with this:

![logs](https://github.com/serverpod/serverpod/assets/136239531/7f4a7f9c-2daa-4cc2-aaea-1123aed9a83e)

But before making a PR I wanted to ask:

- should it be on it's own line like in the screenshot or in the same line as 'File changed'
- what would be the preferred/most beneficial formatting of the timestamp?
- should it contain the year? 

Any other suggestions are of course welcome too :)
