### ISSUE TITLE
Docs need to specify that server address `localhost` should be `10.0.2.2` if client running on Android

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#979]
**Is your feature request related to a problem? Please describe.**

If you are running your Serverpod server on your local machine, and the client is running in the Android emulator, then you have to use `10.0.2.2:8080` for the server address, *not* `localhost:8080`. The IP address `10.0.2.2` is the host machine IP address.

It took me forever to figure this out when I was first working with Serverpod. I couldn't figure out why I couldn't connect to the server from my Android app, when I could connect just fine from my commandline.

I just ran into it again in a more frustrating way. This one took me several days to figure out. When calling `getUploadDescription` to upload a file, the returned URL contains `localhost:8080` by default, and the host name is sourced from the server's `config/development.yaml` file, as `publicHost: localhost`. This needs to also be changed to `publicHost: 10.0.2.2`.

I could not for the life of me figure out why my client could connect to the server just fine (because of the first of the two changes given above), but could not upload files, failing with `Connection refused` (because the second of the above two changes was also needed).

**Describe the solution you'd like**

Please describe in the docs how to set up the Android emulator to do local development, detailing *both* of the above changes that are required. You will save some people a lot of time.

**Comment by Isakdl** [comment]
Agreed, will be fixed in the next update of the docs!

This also does apply if you are running on a physical device, but then you need to use your local IP and be on the same network.

**Comment by vlidholt** [comment]
We have also fixed this in the template for new projects in Serverpod 1.2.
