### ISSUE TITLE
setup-tables hangs

### ISSUE THREAD

**Issue by udiedrichsen** [serverpod/serverpod#99]
I ran setup-tables, but this script didn't finish. I have a Mac Book ProMax M1 with a fresh docker installation.
Flutter & dart are up2date on stable branch.

I waited for more than 30 minutes. I assumee this should not take very long.

--
-- Class RuntimeSettings as table serverpod_runtime_settings
--

CREATE TABLE serverpod_runtime_settings (
  "id" serial,
  "logSettings" json NOT NULL,

**Comment by vlidholt** [comment]
Did you use the `serverpod create` command to setup your project and did that complete without an error? `setup-tables` isn't meant to be run manually and should be deleted at the end of the process of creating a new project.

**Comment by udiedrichsen** [comment]
Ok, was my fault. 

On my first try with serverpod create my_pod my Docker was not up and running.

Now its works good, thanks for the fast response.
