### ISSUE TITLE
`serverpod generate` does not regenerate `my_server/generated/tables-serverpod.sql`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#991]
**Describe the bug**

I upgraded Serverpod from 1.0.1 to 1.1.1, and even after doing `docker down -v ; docker up --build --detach` and then running the `pgsql` scripts to recreate my databases, I got:

```
WARNING: The database does not match the target database:
 - Table "serverpod_health_connection_info" is not like the target database.
 - Table "serverpod_health_metric" is not like the target database.
 ```

The reason is that columns were added to these databases recently.

Running `serverpod generate` in my server project does not fix the problem. The file `my_server/generated/tables-serverpod.pgsql` are not updated to represent the new tables contained in the Serverpod project.

Instead, you have to run the script at `templates/serverpod_templates/projectname_server/generated/tables-serverpod.pgsql`.

Since another script, `serverpod/modules/serverpod_auth/serverpod_auth_server/generated/tables.pgsql`, also has to be manually run when setting up a new database, probably `my_server/generated/tables-serverpod.pgsql` should not actually be included in the new project template, because it will become outdated on any significant Serverpod upgrade.

**Comment by SandPod** [comment]
This is now fixed as part of the new migration system. When this warning happens (after generating the project) you can simply create a new migration.

**Comment by Isakdl** [comment]
If you didn't see my other comment, you have the project migration guide for 1.2 here: 
https://docs.serverpod.dev/next/upgrading/upgrade-to-one-point-two

And migration documentation here:
https://docs.serverpod.dev/next/concepts/database/migrations

**Comment by jblankenship5** [comment]
According to the [1.2 docs](https://docs.serverpod.dev/deployments/deploying-to-gce-terraform#:~:text=Once%20connected%2C%20run%20the%20database%20queries%20found%20in%20generated/tables%2Dserverpod.pgsql%20and%20in%20generated/tables.pgsql.%20When%20you%20have%20added%20the%20tables%20for%20the%20database%2C%20Serverpod%20should%20be%20able%20to%20start.%20However%2C%20it%20could%20take%20an%20hour%20before%20the%20correct%20SSL%20certificates%20are%20created%20and%20validated.) on deploying using google cloud, I should run sql queries from generated/tables-serverpod.pgsql and generated/tables.pgsql. I dont see a file named tables-serverpod.pgsql. and tables.pgsql mentions that it is deprecated and shouldn't be used. How do i generate the tables in my production DB?
